### ISSUE TITLE
Problems when two different users are logged in

### ISSUE THREAD

**Issue by tomas-knap** [mff-uk/odcs#1006]
To reproduce: 
- open dbpedia pipeline as admin
- open a new tab, load GUI
- log as a different user in that second tab, go to pipelines table
- switch back to the previous tab (where admin is logged in)

Then error occured: 

![screen shot 2014-01-01 at 5 21 36 pm](https://f.cloud.github.com/assets/3014917/1829807/1523ac12-7301-11e3-9593-bb6facf5b9fa.png)

```
2014-01-01 17:21:45,907 [http-bio-8080-exec-75] ERROR cz.cuni.mff.xrg.odcs.frontend.AppEntry - Uncaught exception
virtuoso.jdbc4.VirtuosoException: SR133: Can not set NULL to not nullable column 'DB.ODCS.PPL_OPEN_EVENT.user_id'
    at virtuoso.jdbc4.VirtuosoResultSet.process_result(Unknown Source) ~[virtjdbc-4.1.jar:na]
    at virtuoso.jdbc4.VirtuosoResultSet.getMoreResults(Unknown Source) ~[virtjdbc-4.1.jar:na]
    at virtuoso.jdbc4.VirtuosoPreparedStatement.sendQuery(Unknown Source) ~[virtjdbc-4.1.jar:na]
    at virtuoso.jdbc4.VirtuosoPreparedStatement.executeUpdate(Unknown Source) ~[virtjdbc-4.1.jar:na]
    at org.apache.commons.dbcp.DelegatingPreparedStatement.executeUpdate(DelegatingPreparedStatement.java:105) ~[commons-dbcp-1.4.jar:1.4]
    at org.apache.commons.dbcp.DelegatingPreparedStatement.executeUpdate(DelegatingPreparedStatement.java:105) ~[commons-dbcp-1.4.jar:1.4]
    at org.eclipse.persistence.internal.databaseaccess.DatabaseAccessor.executeDirectNoSelect(DatabaseAccessor.java:890) ~[eclipselink-2.5.1.jar:2.5.1.v20130918-f2b9fc5]
    at org.eclipse.persistence.internal.databaseaccess.DatabaseAccessor.executeNoSelect(DatabaseAccessor.java:962) ~[eclipselink-2.5.1.jar:2.5.1.v20130918-f2b9fc5]
    at org.eclipse.persistence.internal.databaseaccess.DatabaseAccessor.basicExecuteCall(DatabaseAccessor.java:631) ~[eclipselink-2.5.1.jar:2.5.1.v20130918-f2b9fc5]
    at org.eclipse.persistence.internal.databaseaccess.DatabaseAccessor.executeCall(DatabaseAccessor.java:558) ~[eclipselink-2.5.1.jar:2.5.1.v20130918-f2b9fc5]
    at org.eclipse.persistence.internal.sessions.AbstractSession.basicExecuteCall(AbstractSession.java:1991) ~[eclipselink-2.5.1.jar:2.5.1.v20130918-f2b9fc5]
    at org.eclipse.persistence.sessions.server.ClientSession.executeCall(ClientSession.java:298) ~[eclipselink-2.5.1.jar:2.5.1.v20130918-f2b9fc5]
    at org.eclipse.persistence.internal.queries.DatasourceCallQueryMechanism.executeCall(DatasourceCallQueryMechanism.java:242) ~[eclipselink-2.5.1.jar:2.5.1.v20130918-f2b9fc5]
    at org.eclipse.persistence.internal.queries.DatasourceCallQueryMechanism.executeCall(DatasourceCallQueryMechanism.java:228) ~[eclipselink-2.5.1.jar:2.5.1.v20130918-f2b9fc5]
    at org.eclipse.persistence.internal.queries.DatasourceCallQueryMechanism.insertObject(DatasourceCallQueryMechanism.java:377) ~[eclipselink-2.5.1.jar:2.5.1.v20130918-f2b9fc5]
    at org.eclipse.persistence.internal.queries.StatementQueryMechanism.insertObject(StatementQueryMechanism.java:165) ~[eclipselink-2.5.1.jar:2.5.1.v20130918-f2b9fc5]
    at org.eclipse.persistence.internal.queries.StatementQueryMechanism.insertObject(StatementQueryMechanism.java:180) ~[eclipselink-2.5.1.jar:2.5.1.v20130918-f2b9fc5]
    at org.eclipse.persistence.internal.queries.DatabaseQueryMechanism.insertObjectForWrite(DatabaseQueryMechanism.java:489) ~[eclipselink-2.5.1.jar:2.5.1.v20130918-f2b9fc5]
    at org.eclipse.persistence.queries.InsertObjectQuery.executeCommit(InsertObjectQuery.java:80) ~[eclipselink-2.5.1.jar:2.5.1.v20130918-f2b9fc5]
    at org.eclipse.persistence.queries.InsertObjectQuery.executeCommitWithChangeSet(InsertObjectQuery.java:90) ~[eclipselink-2.5.1.jar:2.5.1.v20130918-f2b9fc5]
    at org.eclipse.persistence.internal.queries.DatabaseQueryMechanism.executeWriteWithChangeSet(DatabaseQueryMechanism.java:301) ~[eclipselink-2.5.1.jar:2.5.1.v20130918-f2b9fc5]
    at org.eclipse.persistence.queries.WriteObjectQuery.executeDatabaseQuery(WriteObjectQuery.java:58) ~[eclipselink-2.5.1.jar:2.5.1.v20130918-f2b9fc5]
    at org.eclipse.persistence.queries.DatabaseQuery.execute(DatabaseQuery.java:899) ~[eclipselink-2.5.1.jar:2.5.1.v20130918-f2b9fc5]
    at org.eclipse.persistence.queries.DatabaseQuery.executeInUnitOfWork(DatabaseQuery.java:798) ~[eclipselink-2.5.1.jar:2.5.1.v20130918-f2b9fc5]
    at org.eclipse.persistence.queries.ObjectLevelModifyQuery.executeInUnitOfWorkObjectLevelModifyQuery(ObjectLevelModifyQuery.java:108) ~[eclipselink-2.5.1.jar:2.5.1.v20130918-f2b9fc5]
    at org.eclipse.persistence.queries.ObjectLevelModifyQuery.executeInUnitOfWork(ObjectLevelModifyQuery.java:85) ~[eclipselink-2.5.1.jar:2.5.1.v20130918-f2b9fc5]
    at org.eclipse.persistence.internal.sessions.UnitOfWorkImpl.internalExecuteQuery(UnitOfWorkImpl.java:2896) ~[eclipselink-2.5.1.jar:2.5.1.v20130918-f2b9fc5]
    at org.eclipse.persistence.internal.sessions.AbstractSession.executeQuery(AbstractSession.java:1793) ~[eclipselink-2.5.1.jar:2.5.1.v20130918-f2b9fc5]
    at org.eclipse.persistence.internal.sessions.AbstractSession.executeQuery(AbstractSession.java:1775) ~[eclipselink-2.5.1.jar:2.5.1.v20130918-f2b9fc5]
    at org.eclipse.persistence.internal.sessions.AbstractSession.executeQuery(AbstractSession.java:1726) ~[eclipselink-2.5.1.jar:2.5.1.v20130918-f2b9fc5]
    at org.eclipse.persistence.internal.sessions.CommitManager.commitNewObjectsForClassWithChangeSet(CommitManager.java:226) ~[eclipselink-2.5.1.jar:2.5.1.v20130918-f2b9fc5]
    at org.eclipse.persistence.internal.sessions.CommitManager.commitAllObjectsWithChangeSet(CommitManager.java:125) ~[eclipselink-2.5.1.jar:2.5.1.v20130918-f2b9fc5]
    at org.eclipse.persistence.internal.sessions.AbstractSession.writeAllObjectsWithChangeSet(AbstractSession.java:4196) ~[eclipselink-2.5.1.jar:2.5.1.v20130918-f2b9fc5]
    at org.eclipse.persistence.internal.sessions.UnitOfWorkImpl.commitToDatabase(UnitOfWorkImpl.java:1441) ~[eclipselink-2.5.1.jar:2.5.1.v20130918-f2b9fc5]
    at org.eclipse.persistence.internal.sessions.UnitOfWorkImpl.commitToDatabaseWithChangeSet(UnitOfWorkImpl.java:1531) ~[eclipselink-2.5.1.jar:2.5.1.v20130918-f2b9fc5]
    at org.eclipse.persistence.internal.sessions.RepeatableWriteUnitOfWork.commitRootUnitOfWork(RepeatableWriteUnitOfWork.java:277) ~[eclipselink-2.5.1.jar:2.5.1.v20130918-f2b9fc5]
    at org.eclipse.persistence.internal.sessions.UnitOfWorkImpl.commitAndResume(UnitOfWorkImpl.java:1169) ~[eclipselink-2.5.1.jar:2.5.1.v20130918-f2b9fc5]
    at org.eclipse.persistence.internal.jpa.transaction.EntityTransactionImpl.commit(EntityTransactionImpl.java:132) ~[eclipselink-2.5.1.jar:2.5.1.v20130918-f2b9fc5]
    at org.springframework.orm.jpa.JpaTransactionManager.doCommit(JpaTransactionManager.java:512) ~[spring-orm-3.1.2.RELEASE.jar:3.1.2.RELEASE]
    at org.springframework.transaction.support.AbstractPlatformTransactionManager.processCommit(AbstractPlatformTransactionManager.java:754) ~[spring-tx-3.1.2.RELEASE.jar:3.1.2.RELEASE]
    at org.springframework.transaction.support.AbstractPlatformTransactionManager.commit(AbstractPlatformTransactionManager.java:723) ~[spring-tx-3.1.2.RELEASE.jar:3.1.2.RELEASE]
    at org.springframework.transaction.interceptor.TransactionAspectSupport.commitTransactionAfterReturning(TransactionAspectSupport.java:394) ~[spring-tx-3.1.2.RELEASE.jar:3.1.2.RELEASE]
    at org.springframework.transaction.interceptor.TransactionInterceptor.invoke(TransactionInterceptor.java:120) ~[spring-tx-3.1.2.RELEASE.jar:3.1.2.RELEASE]
    at org.springframework.aop.framework.ReflectiveMethodInvocation.proceed(ReflectiveMethodInvocation.java:172) ~[spring-aop-3.0.7.RELEASE.jar:3.0.7.RELEASE]
    at org.springframework.aop.framework.JdkDynamicAopProxy.invoke(JdkDynamicAopProxy.java:202) ~[spring-aop-3.0.7.RELEASE.jar:3.0.7.RELEASE]
    at com.sun.proxy.$Proxy338.createOpenEvent(Unknown Source) ~[na:na]
    at cz.cuni.mff.xrg.odcs.frontend.gui.views.PipelineEdit$1.refresh(PipelineEdit.java:163) ~[PipelineEdit$1.class:na]
    at com.github.wolfie.refresher.Refresher.fireRefreshEvents(Refresher.java:72) ~[refresher-1.2.1.7.jar:1.2.1.7]
    at com.github.wolfie.refresher.Refresher.access$1(Refresher.java:70) ~[refresher-1.2.1.7.jar:1.2.1.7]
    at com.github.wolfie.refresher.Refresher$1.refresh(Refresher.java:35) ~[refresher-1.2.1.7.jar:1.2.1.7]
    at sun.reflect.GeneratedMethodAccessor442.invoke(Unknown Source) ~[na:na]
    at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43) ~[na:1.7.0_40]
    at java.lang.reflect.Method.invoke(Method.java:606) ~[na:1.7.0_40]
    at com.vaadin.server.ServerRpcManager.applyInvocation(ServerRpcManager.java:168) ~[vaadin-server-7.1.8.jar:7.1.8]
    at com.vaadin.server.ServerRpcManager.applyInvocation(ServerRpcManager.java:118) ~[vaadin-server-7.1.8.jar:7.1.8]
    at com.vaadin.server.communication.ServerRpcHandler.handleBurst(ServerRpcHandler.java:207) [vaadin-server-7.1.8.jar:7.1.8]
    at com.vaadin.server.communication.ServerRpcHandler.handleRpc(ServerRpcHandler.java:111) [vaadin-server-7.1.8.jar:7.1.8]
    at com.vaadin.server.communication.UidlRequestHandler.synchronizedHandleRequest(UidlRequestHandler.java:91) [vaadin-server-7.1.8.jar:7.1.8]
    at com.vaadin.server.SynchronizedRequestHandler.handleRequest(SynchronizedRequestHandler.java:37) [vaadin-server-7.1.8.jar:7.1.8]
    at com.vaadin.server.VaadinService.handleRequest(VaadinService.java:1371) [vaadin-server-7.1.8.jar:7.1.8]
    at com.vaadin.server.VaadinServlet.service(VaadinServlet.java:238) [vaadin-server-7.1.8.jar:7.1.8]
    at cz.cuni.mff.xrg.odcs.frontend.IntlibApplicationServlet.service(IntlibApplicationServlet.java:67) [IntlibApplicationServlet.class:na]
    at javax.servlet.http.HttpServlet.service(HttpServlet.java:728) [servlet-api.jar:na]
    at org.apache.catalina.core.ApplicationFilterChain.internalDoFilter(ApplicationFilterChain.java:305) [catalina.jar:7.0.33]
    at org.apache.catalina.core.ApplicationFilterChain.doFilter(ApplicationFilterChain.java:210) [catalina.jar:7.0.33]
    at org.apache.catalina.core.StandardWrapperValve.invoke(StandardWrapperValve.java:222) [catalina.jar:7.0.33]
    at org.apache.catalina.core.StandardContextValve.invoke(StandardContextValve.java:123) [catalina.jar:7.0.33]
    at org.apache.catalina.authenticator.AuthenticatorBase.invoke(AuthenticatorBase.java:472) [catalina.jar:7.0.33]
    at org.apache.catalina.core.StandardHostValve.invoke(StandardHostValve.java:171) [catalina.jar:7.0.33]
    at org.apache.catalina.valves.ErrorReportValve.invoke(ErrorReportValve.java:99) [catalina.jar:7.0.33]
    at org.apache.catalina.valves.AccessLogValve.invoke(AccessLogValve.java:931) [catalina.jar:7.0.33]
    at org.apache.catalina.core.StandardEngineValve.invoke(StandardEngineValve.java:118) [catalina.jar:7.0.33]
    at org.apache.catalina.connector.CoyoteAdapter.service(CoyoteAdapter.java:407) [catalina.jar:7.0.33]
    at org.apache.coyote.http11.AbstractHttp11Processor.process(AbstractHttp11Processor.java:1004) [tomcat-coyote.jar:7.0.33]
    at org.apache.coyote.AbstractProtocol$AbstractConnectionHandler.process(AbstractProtocol.java:589) [tomcat-coyote.jar:7.0.33]
    at org.apache.tomcat.util.net.JIoEndpoint$SocketProcessor.run(JIoEndpoint.java:312) [tomcat-coyote.jar:7.0.33]
    at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1145) [na:1.7.0_40]
    at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:615) [na:1.7.0_40]
    at java.lang.Thread.run(Thread.java:724) [na:1.7.0_40]
2014-01-01 17:21:46,075 [http-bio-8080-exec-85] DEBUG org.eclipse.persistence.logging.sql - 2014-01-01 17:21:46.075--ServerSession(695455970)--Connection(52311168)--Thread(Thread[http-bio-8080-exec-85,5,main])--SELECT CASE  WHEN (MAX(t_last_change) > ?) THEN CAST(? AS INTEGER) ELSE CAST(? AS INTEGER) END FROM exec_pipeline
```

**Comment by tomas-knap** [comment]
It behaves really strange when two different users are logged in in two different tabs. The second user overrides the first one.

**Comment by tomas-knap** [comment]
And the it is really confusing.

**Comment by janvojt** [comment]
> It behaves really strange when two different users are logged in in two different tabs. The second user overrides the first one. 

This is expected. User session is shared among all tabs (session id is saved in a cookie).

**Comment by tomas-knap** [comment]
I understand that. But still if I open the pipeline detail X as one user, then open a different tab, log as a different user, open pipeline list. Then, if I return back to X, I may edit the pipeline, but it cannot be saved, which is confusing: 

![screen shot 2014-01-03 at 4 05 25 pm](https://f.cloud.github.com/assets/3014917/1839959/c62ec0e0-7488-11e3-9e78-f1f98d369f98.png)

**Comment by janvojt** [comment]
Well, it would be pretty standard if we were not updating open-pipeline status. This is actually a more common pattern. For example you could be editing DPU configuration after logout, and you also would not be able to save it.
1. We could solve this globally by adding a heartbeat request every few seconds and check whether user is still logged in. If not redirect to login screen.
2. We could use request registering pipeline-open event, and redirect to login screen if user was logged out. This would solve the problem only for this screen.
3. We could just ignore this scenario. It would be quite stupid to manually log out and then expect to save a pipeline. On the other hand in case of long inactivity, the same thing could happen after session timeout.

What do you suggest? Maybe discuss at the meeting?

**Comment by tomas-knap** [comment]
Ok, let's discuss on the meeting
