### ISSUE TITLE
Pipeline finished but at the end, there was an error

### ISSUE THREAD

**Issue by tomas-knap** [mff-uk/odcs#1019]
java.lang.IllegalArgumentException You have attempted to set a value of type class cz.cuni.mff.xrg.odcs.commons.app.pipeline.Pipeline for parameter pipeline with expected type of class java.lang.Long from query string SELECT s FROM Schedule s JOIN s.afterPipelines p WHERE p.id = :pipeline AND s.type = :type AND s.enabled = :enabled. at 

![screen shot 2014-01-03 at 11 09 12 pm](https://f.cloud.github.com/assets/3014917/1842825/d9f429a4-74c3-11e3-9149-24651163c151.png)

Strange is that after finishing the pipeline, it starts to reconnect (see the figure above). Why? @janvojt please answer
Also please @janvojt check the behavior. It seems that there is a problem with Long type. 

@skodape please also discuss, if it is in your part

Could be similar as #1016 
Could be related to #1017

**Comment by tomas-knap** [comment]
See ODCS, pipeline exec no. 164

**Comment by tomas-knap** [comment]
using localRDF for storing intermediate results

**Comment by janvojt** [comment]
Stack trace:

```
java.lang.IllegalArgumentException You have attempted to set a value of type class cz.cuni.mff.xrg.odcs.commons.app.pipeline.Pipeline for parameter pipeline with expected type of class java.lang.Long from query string SELECT s FROM Schedule s JOIN s.afterPipelines p WHERE p.id = :pipeline AND s.type = :type AND s.enabled = :enabled.
 at org.eclipse.persistence.internal.jpa.QueryImpl.setParameterInternal(QueryImpl.java:933)
 at org.eclipse.persistence.internal.jpa.EJBQueryImpl.setParameter(EJBQueryImpl.java:593)
 at cz.cuni.mff.xrg.odcs.commons.app.scheduling.DbScheduleImpl.getFollowers(DbScheduleImpl.java:50)
 at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
 at sun.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:57)
 at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
 at java.lang.reflect.Method.invoke(Method.java:606)
 at org.springframework.aop.support.AopUtils.invokeJoinpointUsingReflection(AopUtils.java:319)
 at org.springframework.aop.framework.ReflectiveMethodInvocation.invokeJoinpoint(ReflectiveMethodInvocation.java:183)
 at org.springframework.aop.framework.ReflectiveMethodInvocation.proceed(ReflectiveMethodInvocation.java:150)
 at org.springframework.transaction.interceptor.TransactionInterceptor.invoke(TransactionInterceptor.java:110)
 at org.springframework.aop.framework.ReflectiveMethodInvocation.proceed(ReflectiveMethodInvocation.java:172)
 at org.springframework.aop.framework.JdkDynamicAopProxy.invoke(JdkDynamicAopProxy.java:202)
 at com.sun.proxy.$Proxy33.getFollowers(Unknown Source)
 at cz.cuni.mff.xrg.odcs.commons.app.facade.ScheduleFacadeImpl.executeFollowers(ScheduleFacadeImpl.java:200)
 at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
 at sun.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:57)
 at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
 at java.lang.reflect.Method.invoke(Method.java:606)
 at org.springframework.aop.support.AopUtils.invokeJoinpointUsingReflection(AopUtils.java:319)
 at org.springframework.aop.framework.ReflectiveMethodInvocation.invokeJoinpoint(ReflectiveMethodInvocation.java:183)
 at org.springframework.aop.framework.ReflectiveMethodInvocation.proceed(ReflectiveMethodInvocation.java:150)
 at org.springframework.transaction.interceptor.TransactionInterceptor.invoke(TransactionInterceptor.java:110)
 at org.springframework.aop.framework.ReflectiveMethodInvocation.proceed(ReflectiveMethodInvocation.java:172)
 at org.springframework.aop.aspectj.MethodInvocationProceedingJoinPoint.proceed(MethodInvocationProceedingJoinPoint.java:80)
 at cz.cuni.mff.xrg.odcs.backend.facade.DatabaseReconnectAspect.failureTolerant(DatabaseReconnectAspect.java:103)
 at sun.reflect.GeneratedMethodAccessor16.invoke(Unknown Source)
 at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
 at java.lang.reflect.Method.invoke(Method.java:606)
 at org.springframework.aop.aspectj.AbstractAspectJAdvice.invokeAdviceMethodWithGivenArgs(AbstractAspectJAdvice.java:621)
 at org.springframework.aop.aspectj.AbstractAspectJAdvice.invokeAdviceMethod(AbstractAspectJAdvice.java:610)
 at org.springframework.aop.aspectj.AspectJAroundAdvice.invoke(AspectJAroundAdvice.java:65)
 at org.springframework.aop.framework.ReflectiveMethodInvocation.proceed(ReflectiveMethodInvocation.java:172)
 at org.springframework.aop.interceptor.ExposeInvocationInterceptor.invoke(ExposeInvocationInterceptor.java:90)
 at org.springframework.aop.framework.ReflectiveMethodInvocation.proceed(ReflectiveMethodInvocation.java:172)
 at org.springframework.aop.framework.JdkDynamicAopProxy.invoke(JdkDynamicAopProxy.java:202)
 at com.sun.proxy.$Proxy35.executeFollowers(Unknown Source)
 at cz.cuni.mff.xrg.odcs.backend.scheduling.Scheduler.onPipelineFinished(Scheduler.java:58)
 at cz.cuni.mff.xrg.odcs.backend.scheduling.Scheduler.onApplicationEvent(Scheduler.java:99)
 at org.springframework.context.event.SimpleApplicationEventMulticaster.multicastEvent(SimpleApplicationEventMulticaster.java:97)
 at org.springframework.context.support.AbstractApplicationContext.publishEvent(AbstractApplicationContext.java:324)
 at cz.cuni.mff.xrg.odcs.backend.execution.pipeline.Executor.run(Executor.java:433)
 at java.util.concurrent.Executors$RunnableAdapter.call(Executors.java:471)
 at java.util.concurrent.FutureTask.run(FutureTask.java:262)
 at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1145)
 at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:615)
 at java.lang.Thread.run(Thread.java:724) 
```

**Comment by janvojt** [comment]
Error was introduced in commit 6435eef47f7f9a499fe640a29619efc721e0851a. It is fixed now.

**Comment by tomas-knap** [comment]
Thanks, also for the test.
