### ISSUE TITLE
File extractor dialog

### ISSUE THREAD

**Issue by tomesj** [mff-uk/odcs#104]
When I choose value"Upload file", then I choose a file and give save dialog,  then I can not open the dialog for this DPU again. 

In other cases (file, directory, http) it is OK (a can save and then open dialog).

**Comment by kukharm** [comment]
Hi, Jiri, I suppose that this is because the field textFieldPath for "Upload file" is read only and in setConfiguration its necessary for case extractType == FileExtractType.UPLOAD_FILE to set

 textFieldPath.setReadOnly(false); // allow value settings
 textFieldPath.setValue(conf.Path); // set value
 textFieldPath.setReadOnly(true); // forbid

I was put this settings when I prepared the dialogue but in the last version i don't see this changes... Now I can't check this my supposition because I have global problem with File extractor dialogue it falls with exception when i select  File extractor in the DPUtree.

июл 14, 2013 5:05:13 PM com.vaadin.server.DefaultErrorHandler doDefault
SEVERE: 
com.vaadin.event.ListenerMethod$MethodException: Invocation of method itemClick in cz.cuni.xrg.intlib.frontend.gui.views.DPU$4 failed.
    at com.vaadin.event.ListenerMethod.receiveEvent(ListenerMethod.java:528)
    at com.vaadin.event.EventRouter.fireEvent(EventRouter.java:167)
    at com.vaadin.server.AbstractClientConnector.fireEvent(AbstractClientConnector.java:968)
    at com.vaadin.ui.Tree.changeVariables(Tree.java:470)
    at com.vaadin.server.communication.ServerRpcHandler.changeVariables(ServerRpcHandler.java:403)
    at com.vaadin.server.communication.ServerRpcHandler.handleBurst(ServerRpcHandler.java:228)
    at com.vaadin.server.communication.ServerRpcHandler.handleRpc(ServerRpcHandler.java:111)
    at com.vaadin.server.communication.PushHandler$2.run(PushHandler.java:158)
    at com.vaadin.server.communication.PushHandler.callWithUi(PushHandler.java:289)
    at com.vaadin.server.communication.PushHandler.onRequest(PushHandler.java:308)
    at org.atmosphere.cpr.AsynchronousProcessor.action(AsynchronousProcessor.java:259)
    at org.atmosphere.cpr.AsynchronousProcessor.suspended(AsynchronousProcessor.java:166)
    at org.atmosphere.container.TomcatWebSocketUtil.doService(TomcatWebSocketUtil.java:137)
    at org.atmosphere.container.Tomcat7AsyncSupportWithWebSocket.service(Tomcat7AsyncSupportWithWebSocket.java:59)
    at org.atmosphere.cpr.AtmosphereFramework.doCometSupport(AtmosphereFramework.java:1448)
    at org.atmosphere.websocket.DefaultWebSocketProcessor.dispatch(DefaultWebSocketProcessor.java:219)
    at org.atmosphere.websocket.DefaultWebSocketProcessor$2.run(DefaultWebSocketProcessor.java:183)
    at org.atmosphere.util.VoidExecutorService.execute(VoidExecutorService.java:101)
    at org.atmosphere.websocket.DefaultWebSocketProcessor.dispatch(DefaultWebSocketProcessor.java:178)
    at org.atmosphere.websocket.DefaultWebSocketProcessor.invokeWebSocketProtocol(DefaultWebSocketProcessor.java:167)
    at org.atmosphere.container.TomcatWebSocketHandler.onTextMessage(TomcatWebSocketHandler.java:92)
    at org.apache.catalina.websocket.MessageInbound.onTextData(MessageInbound.java:74)
    at org.apache.catalina.websocket.StreamInbound.doOnTextData(StreamInbound.java:186)
    at org.apache.catalina.websocket.StreamInbound.onData(StreamInbound.java:134)
    at org.apache.coyote.http11.upgrade.UpgradeProcessor.upgradeDispatch(UpgradeProcessor.java:83)
    at org.apache.coyote.AbstractProtocol$AbstractConnectionHandler.process(AbstractProtocol.java:587)
    at org.apache.tomcat.util.net.JIoEndpoint$SocketProcessor.run(JIoEndpoint.java:310)
    at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1110)
    at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:603)
    at java.lang.Thread.run(Thread.java:722)
Caused by: com.thoughtworks.xstream.converters.reflection.AbstractReflectionConverter$UnknownFieldException: No such field cz.cuni.mff.xrg.intlib.extractor.file.FileExtractorConfig.PathType
---- Debugging information ----
field               : PathType
class               : cz.cuni.mff.xrg.intlib.extractor.file.FileExtractorConfig
required-type       : cz.cuni.mff.xrg.intlib.extractor.file.FileExtractorConfig
converter-type      : com.thoughtworks.xstream.converters.reflection.ReflectionConverter
path                : /cz.cuni.mff.xrg.intlib.extractor.file.FileExtractorConfig/PathType
line number         : 5

## version             : null

```
at com.thoughtworks.xstream.converters.reflection.AbstractReflectionConverter.determineType(AbstractReflectionConverter.java:453)
at com.thoughtworks.xstream.converters.reflection.AbstractReflectionConverter.doUnmarshal(AbstractReflectionConverter.java:294)
at com.thoughtworks.xstream.converters.reflection.AbstractReflectionConverter.unmarshal(AbstractReflectionConverter.java:234)
at com.thoughtworks.xstream.core.TreeUnmarshaller.convert(TreeUnmarshaller.java:72)
at com.thoughtworks.xstream.core.AbstractReferenceUnmarshaller.convert(AbstractReferenceUnmarshaller.java:65)
at com.thoughtworks.xstream.core.TreeUnmarshaller.convertAnother(TreeUnmarshaller.java:66)
at com.thoughtworks.xstream.core.TreeUnmarshaller.convertAnother(TreeUnmarshaller.java:50)
at com.thoughtworks.xstream.core.TreeUnmarshaller.start(TreeUnmarshaller.java:134)
at com.thoughtworks.xstream.core.AbstractTreeMarshallingStrategy.unmarshal(AbstractTreeMarshallingStrategy.java:32)
at com.thoughtworks.xstream.XStream.unmarshal(XStream.java:1058)
at com.thoughtworks.xstream.XStream.unmarshal(XStream.java:1030)
at com.thoughtworks.xstream.XStream$2.readFromStream(XStream.java:1723)
at com.thoughtworks.xstream.core.util.CustomObjectInputStream.readObjectOverride(CustomObjectInputStream.java:104)
at java.io.ObjectInputStream.readObject(ObjectInputStream.java:363)
at cz.cuni.xrg.intlib.commons.app.dpu.DPURecord.getConf(DPURecord.java:180)
at cz.cuni.xrg.intlib.frontend.auxiliaries.dpu.DPURecordWrap.loadConfigIntoDialog(DPURecordWrap.java:102)
at cz.cuni.xrg.intlib.frontend.auxiliaries.dpu.DPURecordWrap.getDialog(DPURecordWrap.java:55)
at cz.cuni.xrg.intlib.frontend.auxiliaries.dpu.DPUTemplateWrap.getDialog(DPUTemplateWrap.java:13)
at cz.cuni.xrg.intlib.frontend.gui.views.DPU.buildDPUDetailLayout(DPU.java:324)
at cz.cuni.xrg.intlib.frontend.gui.views.DPU.access$500(DPU.java:69)
at cz.cuni.xrg.intlib.frontend.gui.views.DPU$4.itemClick(DPU.java:252)
at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
at sun.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:57)
at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
at java.lang.reflect.Method.invoke(Method.java:601)
at com.vaadin.event.ListenerMethod.receiveEvent(ListenerMethod.java:508)
... 29 more
```

**Comment by tomesj** [comment]
Peter recently changed configuration setting, try to clean your database and put schema and data again. If it is not solve your problem, write email to Peter.

**Comment by skodapetr** [comment]
Hi, yes I do .. Maria know about it .. and I'm afraid it's not this case. In the stack trace is:
 com.thoughtworks.xstream.XStream$2.readFromStream(XStream.java:1723)
the XStream takes care about configuration serialisation. If the configuration class is changed and there is previously serialised configuration in database it produce this exception.

**Comment by tomesj** [comment]
Thank you, Maria for given hint :-) The problem is solved:-)
