### ISSUE TITLE
Null pointer exception in AppEntry

### ISSUE THREAD

**Issue by tomesj** [mff-uk/odcs#1051]
When I clicked on DEBUG button I get

![image](https://f.cloud.github.com/assets/3481055/1870379/a4a4d91c-7886-11e3-85e3-da0dc4250a16.png)

Tomcat log says:

7:58:45.283 [catalina-exec-10] ERROR c.c.m.x.o.f.AppEntry - Uncaught exception
java.lang.NullPointerException: null
    at cz.cuni.mff.xrg.odcs.frontend.gui.components.DataUnitSelector.refreshDpuSelector(DataUnitSelector.java:221) ~[DataUnitSelector.class:na]
    at cz.cuni.mff.xrg.odcs.frontend.gui.components.DataUnitSelector.buildDpuSelector(DataUnitSelector.java:156) ~[DataUnitSelector.class:na]
    at cz.cuni.mff.xrg.odcs.frontend.gui.components.DataUnitSelector.buildMainLayout(DataUnitSelector.java:54) ~[DataUnitSelector.class:na]
    at cz.cuni.mff.xrg.odcs.frontend.gui.components.DataUnitSelector.<init>(DataUnitSelector.java:45) ~[DataUnitSelector.class:na]
    at cz.cuni.mff.xrg.odcs.frontend.gui.components.RDFQueryView.<init>(RDFQueryView.java:87) ~[RDFQueryView.class:na]
    at cz.cuni.mff.xrg.odcs.frontend.gui.components.DebuggingView.buildMainLayout(DebuggingView.java:208) ~[DebuggingView.class:na]
    at cz.cuni.mff.xrg.odcs.frontend.gui.components.DebuggingView.initialize(DebuggingView.java:136) ~[DebuggingView.class:na]
    at cz.cuni.mff.xrg.odcs.frontend.gui.views.executionlist.ExecutionListViewImpl.buildDebugView(ExecutionListViewImpl.java:344) ~[ExecutionListViewImpl.class:na]
    at cz.cuni.mff.xrg.odcs.frontend.gui.views.executionlist.ExecutionListViewImpl.buildExecutionDetail(ExecutionListViewImpl.java:297) ~[ExecutionListViewImpl.class:na]
    at cz.cuni.mff.xrg.odcs.frontend.gui.views.executionlist.ExecutionListViewImpl.showExecutionDetail(ExecutionListViewImpl.java:95) ~[ExecutionListViewImpl.class:na]
    at cz.cuni.mff.xrg.odcs.frontend.gui.views.executionlist.ExecutionListPresenterImpl.showDebugEventHandler(ExecutionListPresenterImpl.java:171) ~[ExecutionListPresenterImpl.class:na]
    at cz.cuni.mff.xrg.odcs.frontend.gui.views.executionlist.ExecutionListViewImpl$7.action(ExecutionListViewImpl.java:240) ~[ExecutionListViewImpl$7.class:na]
    at cz.cuni.mff.xrg.odcs.frontend.gui.tables.ActionColumnGenerator$Action.buttonClick(ActionColumnGenerator.java:32) ~[ActionColumnGenerator$Action.class:na]
    at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method) ~[na:1.7.0_21]
    at sun.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:57) ~[na:1.7.0_21]
    at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43) ~[na:1.7.0_21]
    at java.lang.reflect.Method.invoke(Method.java:601) ~[na:1.7.0_21]
    at com.vaadin.event.ListenerMethod.receiveEvent(ListenerMethod.java:508) ~[vaadin-server-7.1.8.jar:7.1.8]
    at com.vaadin.event.EventRouter.fireEvent(EventRouter.java:167) ~[vaadin-server-7.1.8.jar:7.1.8]
    at com.vaadin.server.AbstractClientConnector.fireEvent(AbstractClientConnector.java:969) ~[vaadin-server-7.1.8.jar:7.1.8]
    at com.vaadin.ui.Button.fireClick(Button.java:368) ~[vaadin-server-7.1.8.jar:7.1.8]
    at com.vaadin.ui.Button$1.click(Button.java:57) ~[vaadin-server-7.1.8.jar:7.1.8]
    at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method) ~[na:1.7.0_21]
    at sun.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:57) ~[na:1.7.0_21]
    at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43) ~[na:1.7.0_21]
    at java.lang.reflect.Method.invoke(Method.java:601) ~[na:1.7.0_21]
    at com.vaadin.server.ServerRpcManager.applyInvocation(ServerRpcManager.java:168) ~[vaadin-server-7.1.8.jar:7.1.8]
    at com.vaadin.server.ServerRpcManager.applyInvocation(ServerRpcManager.java:118) ~[vaadin-server-7.1.8.jar:7.1.8]
    at com.vaadin.server.communication.ServerRpcHandler.handleBurst(ServerRpcHandler.java:207) [vaadin-server-7.1.8.jar:7.1.8]
    at com.vaadin.server.communication.ServerRpcHandler.handleRpc(ServerRpcHandler.java:111) [vaadin-server-7.1.8.jar:7.1.8]
    at com.vaadin.server.communication.UidlRequestHandler.synchronizedHandleRequest(UidlRequestHandler.java:91) [vaadin-server-7.1.8.jar:7.1.8]
    at com.vaadin.server.SynchronizedRequestHandler.handleRequest(SynchronizedRequestHandler.java:37) [vaadin-server-7.1.8.jar:7.1.8]
    at com.vaadin.server.VaadinService.handleRequest(VaadinService.java:1371) [vaadin-server-7.1.8.jar:7.1.8]
    at com.vaadin.server.VaadinServlet.service(VaadinServlet.java:238) [vaadin-server-7.1.8.jar:7.1.8]
    at cz.cuni.mff.xrg.odcs.frontend.IntlibApplicationServlet.service(IntlibApplicationServlet.java:67) [IntlibApplicationServlet.class:na]
    at javax.servlet.http.HttpServlet.service(HttpServlet.java:728) [servlet-api.jar:na]
    at org.apache.catalina.core.ApplicationFilterChain.internalDoFilter(ApplicationFilterChain.java:305) [catalina.jar:7.0.42]
    at org.apache.catalina.core.ApplicationFilterChain.doFilter(ApplicationFilterChain.java:210) [catalina.jar:7.0.42]
    at org.apache.catalina.core.StandardWrapperValve.invoke(StandardWrapperValve.java:222) [catalina.jar:7.0.42]
    at org.apache.catalina.core.StandardContextValve.invoke(StandardContextValve.java:123) [catalina.jar:7.0.42]
    at org.apache.catalina.authenticator.AuthenticatorBase.invoke(AuthenticatorBase.java:502) [catalina.jar:7.0.42]
    at org.apache.catalina.core.StandardHostValve.invoke(StandardHostValve.java:171) [catalina.jar:7.0.42]
    at org.apache.catalina.valves.ErrorReportValve.invoke(ErrorReportValve.java:99) [catalina.jar:7.0.42]
    at org.apache.catalina.valves.AccessLogValve.invoke(AccessLogValve.java:953) [catalina.jar:7.0.42]
    at org.apache.catalina.core.StandardEngineValve.invoke(StandardEngineValve.java:118) [catalina.jar:7.0.42]
    at org.apache.catalina.connector.CoyoteAdapter.service(CoyoteAdapter.java:408) [catalina.jar:7.0.42]
    at org.apache.coyote.http11.AbstractHttp11Processor.process(AbstractHttp11Processor.java:1023) [tomcat-coyote.jar:7.0.42]
    at org.apache.coyote.AbstractProtocol$AbstractConnectionHandler.process(AbstractProtocol.java:589) [tomcat-coyote.jar:7.0.42]
    at org.apache.tomcat.util.net.AprEndpoint$SocketProcessor.run(AprEndpoint.java:1852) [tomcat-coyote.jar:7.0.42]
    at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1145) [na:1.7.0_21]
    at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:615) [na:1.7.0_21]
    at java.lang.Thread.run(Thread.java:722) [na:1.7.0_21]

**Comment by bogo777** [comment]
Should be solved by same commit as #1053.

**Comment by tomas-knap** [comment]
Please test

**Comment by tomesj** [comment]
It´s OK now :-)
