### ISSUE TITLE
Cannot open pipeline execution detail.

### ISSUE THREAD

**Issue by janvojt** [mff-uk/odcs#1052]
Reproduced on commit 4c17574197762ff465e3a61a801fa123afd47a19. When clicking on a running pipeline (launched by scheduler) I could not open detail and the following error popped out:

![screenshot from 2014-01-08 21 17 45](https://f.cloud.github.com/assets/2247062/1872268/18a2d7f8-78a3-11e3-8015-ebaa260d89b1.png)

I am not sure who to assign, but Petr might know why DataUnitGraph is null...

Stacktrace:

```
21:14:45.170 [http-bio-8089-exec-27] ERROR c.c.m.x.o.f.AppEntry - Uncaught exception
java.lang.NullPointerException: null
        at cz.cuni.mff.xrg.odcs.frontend.gui.components.DataUnitSelector.refreshDpuSelector(DataUnitSelector.java:221) ~[DataUnitSelector.class:na]
        at cz.cuni.mff.xrg.odcs.frontend.gui.components.DataUnitSelector.buildDpuSelector(DataUnitSelector.java:156) ~[DataUnitSelector.class:na]
        at cz.cuni.mff.xrg.odcs.frontend.gui.components.DataUnitSelector.buildMainLayout(DataUnitSelector.java:54) ~[DataUnitSelector.class:na]
        at cz.cuni.mff.xrg.odcs.frontend.gui.components.DataUnitSelector.<init>(DataUnitSelector.java:45) ~[DataUnitSelector.class:na]
        at cz.cuni.mff.xrg.odcs.frontend.gui.components.RDFQueryView.<init>(RDFQueryView.java:87) ~[RDFQueryView.class:na]
        at cz.cuni.mff.xrg.odcs.frontend.gui.components.DebuggingView.buildMainLayout(DebuggingView.java:208) ~[DebuggingView.class:na]
        at cz.cuni.mff.xrg.odcs.frontend.gui.components.DebuggingView.initialize(DebuggingView.java:136) ~[DebuggingView.class:na]
        at cz.cuni.mff.xrg.odcs.frontend.gui.views.executionlist.ExecutionListViewImpl.buildDebugView(ExecutionListViewImpl.java:344) ~[ExecutionListViewImpl.class:na]
        at cz.cuni.mff.xrg.odcs.frontend.gui.views.executionlist.ExecutionListViewImpl.buildExecutionDetail(ExecutionListViewImpl.java:297) ~[ExecutionListViewImpl.class:na]
        at cz.cuni.mff.xrg.odcs.frontend.gui.views.executionlist.ExecutionListViewImpl.showExecutionDetail(ExecutionListViewImpl.java:95) ~[ExecutionListViewImpl.class:na]
        at cz.cuni.mff.xrg.odcs.frontend.gui.views.executionlist.ExecutionListPresenterImpl.showDebugEventHandler(ExecutionListPresenterImpl.java:171) ~[ExecutionListPresenterImpl.class:na]
        at cz.cuni.mff.xrg.odcs.frontend.gui.views.executionlist.ExecutionListViewImpl$15.itemClick(ExecutionListViewImpl.java:431) ~[ExecutionListViewImpl$15.class:na]
        at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method) ~[na:1.7.0_45]
        at sun.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:57) ~[na:1.7.0_45]
        at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43) ~[na:1.7.0_45]
        at java.lang.reflect.Method.invoke(Method.java:606) ~[na:1.7.0_45]
        at com.vaadin.event.ListenerMethod.receiveEvent(ListenerMethod.java:508) ~[vaadin-server-7.1.8.jar:7.1.8]
        at com.vaadin.event.EventRouter.fireEvent(EventRouter.java:167) ~[vaadin-server-7.1.8.jar:7.1.8]
        at com.vaadin.server.AbstractClientConnector.fireEvent(AbstractClientConnector.java:969) ~[vaadin-server-7.1.8.jar:7.1.8]
        at com.vaadin.ui.CustomTable.handleClickEvent(CustomTable.java:3035) ~[filteringtable-0.9.0.v7.jar:7.1.8]
        at com.vaadin.ui.CustomTable.changeVariables(CustomTable.java:2830) ~[filteringtable-0.9.0.v7.jar:7.1.8]
        at com.vaadin.server.communication.ServerRpcHandler.changeVariables(ServerRpcHandler.java:396) [vaadin-server-7.1.8.jar:7.1.8]
        at com.vaadin.server.communication.ServerRpcHandler.handleBurst(ServerRpcHandler.java:221) [vaadin-server-7.1.8.jar:7.1.8]
        at com.vaadin.server.communication.ServerRpcHandler.handleRpc(ServerRpcHandler.java:111) [vaadin-server-7.1.8.jar:7.1.8]
        at com.vaadin.server.communication.UidlRequestHandler.synchronizedHandleRequest(UidlRequestHandler.java:91) [vaadin-server-7.1.8.jar:7.1.8]
        at com.vaadin.server.SynchronizedRequestHandler.handleRequest(SynchronizedRequestHandler.java:37) [vaadin-server-7.1.8.jar:7.1.8]
        at com.vaadin.server.VaadinService.handleRequest(VaadinService.java:1371) [vaadin-server-7.1.8.jar:7.1.8]
        at com.vaadin.server.VaadinServlet.service(VaadinServlet.java:238) [vaadin-server-7.1.8.jar:7.1.8]
        at cz.cuni.mff.xrg.odcs.frontend.IntlibApplicationServlet.service(IntlibApplicationServlet.java:67) [IntlibApplicationServlet.class:na]
        at javax.servlet.http.HttpServlet.service(HttpServlet.java:728) [servlet-api.jar:na]
        at org.apache.catalina.core.ApplicationFilterChain.internalDoFilter(ApplicationFilterChain.java:305) [catalina.jar:7.0.37]
        at org.apache.catalina.core.ApplicationFilterChain.doFilter(ApplicationFilterChain.java:210) [catalina.jar:7.0.37]
        at org.apache.catalina.core.StandardWrapperValve.invoke(StandardWrapperValve.java:222) [catalina.jar:7.0.37]
        at org.apache.catalina.core.StandardContextValve.invoke(StandardContextValve.java:123) [catalina.jar:7.0.37]
        at org.apache.catalina.authenticator.AuthenticatorBase.invoke(AuthenticatorBase.java:472) [catalina.jar:7.0.37]
        at org.apache.catalina.core.StandardHostValve.invoke(StandardHostValve.java:171) [catalina.jar:7.0.37]
        at org.apache.catalina.valves.ErrorReportValve.invoke(ErrorReportValve.java:99) [catalina.jar:7.0.37]
        at org.apache.catalina.valves.AccessLogValve.invoke(AccessLogValve.java:936) [catalina.jar:7.0.37]
        at org.apache.catalina.core.StandardEngineValve.invoke(StandardEngineValve.java:118) [catalina.jar:7.0.37]
        at org.apache.catalina.connector.CoyoteAdapter.service(CoyoteAdapter.java:407) [catalina.jar:7.0.37]
        at org.apache.coyote.http11.AbstractHttp11Processor.process(AbstractHttp11Processor.java:1004) [tomcat-coyote.jar:7.0.37]
        at org.apache.coyote.AbstractProtocol$AbstractConnectionHandler.process(AbstractProtocol.java:589) [tomcat-coyote.jar:7.0.37]
        at org.apache.tomcat.util.net.JIoEndpoint$SocketProcessor.run(JIoEndpoint.java:312) [tomcat-coyote.jar:7.0.37]
        at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1145) [na:1.7.0_45]
        at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:615) [na:1.7.0_45]
        at java.lang.Thread.run(Thread.java:744) [na:1.7.0_45]
```

**Comment by skodapetr** [comment]
Looks like this has been solved in #1053, so closing.
