### ISSUE TITLE
Malformed input around byte

### ISSUE THREAD

**Issue by tomesj** [mff-uk/odcs#1059]
When I make copy of pipeline contains XSLT DPU, click on edit, I get:

![image](https://f.cloud.github.com/assets/3481055/1891427/10c446de-7a3d-11e3-9729-217a4becb74d.png)

**Comment by tomesj** [comment]
```
ERROR c.c.m.x.o.f.AppEntry - Uncaught exception
virtuoso.jdbc4.VirtuosoException: Virtuoso Communications Link Failure (timeout) : malformed input around byte 3688
    at virtuoso.jdbc4.VirtuosoFuture.nextResult(Unknown Source) ~[virtjdbc-4.1.jar:na]
    at virtuoso.jdbc4.VirtuosoBlob.getBytes(Unknown Source) ~[virtjdbc-4.1.jar:na]
    at org.eclipse.persistence.internal.helper.ConversionManager.convertObjectToByteArray(ConversionManager.java:325) ~[commons-app-1.0.0.jar:na]
    at org.eclipse.persistence.internal.helper.ConversionManager.convertObject(ConversionManager.java:136) ~[commons-app-1.0.0.jar:na]
    at org.eclipse.persistence.internal.databaseaccess.DatasourcePlatform.convertObject(DatasourcePlatform.java:179) ~[commons-app-1.0.0.jar:na]
    at org.eclipse.persistence.internal.databaseaccess.DatabaseAccessor.getObject(DatabaseAccessor.java:1306) ~[commons-app-1.0.0.jar:na]
    at org.eclipse.persistence.internal.databaseaccess.DatabaseAccessor.fetchRow(DatabaseAccessor.java:1075) ~[commons-app-1.0.0.jar:na]
    at org.eclipse.persistence.internal.databaseaccess.DatabaseAccessor.processResultSet(DatabaseAccessor.java:742) ~[commons-app-1.0.0.jar:na]
    at org.eclipse.persistence.internal.databaseaccess.DatabaseAccessor.basicExecuteCall(DatabaseAccessor.java:655) ~[commons-app-1.0.0.jar:na]
    at org.eclipse.persistence.internal.databaseaccess.DatabaseAccessor.executeCall(DatabaseAccessor.java:558) ~[commons-app-1.0.0.jar:na]
    at org.eclipse.persistence.internal.sessions.AbstractSession.basicExecuteCall(AbstractSession.java:1991) ~[commons-app-1.0.0.jar:na]
    at org.eclipse.persistence.sessions.server.ServerSession.executeCall(ServerSession.java:570) ~[commons-app-1.0.0.jar:na]
    at org.eclipse.persistence.sessions.server.ClientSession.executeCall(ClientSession.java:250) ~[commons-app-1.0.0.jar:na]
    at org.eclipse.persistence.internal.queries.DatasourceCallQueryMechanism.executeCall(DatasourceCallQueryMechanism.java:242) ~[commons-app-1.0.0.jar:na]
    at org.eclipse.persistence.internal.queries.DatasourceCallQueryMechanism.executeCall(DatasourceCallQueryMechanism.java:228) ~[commons-app-1.0.0.jar:na]
    at org.eclipse.persistence.internal.queries.DatasourceCallQueryMechanism.selectOneRow(DatasourceCallQueryMechanism.java:714) ~[commons-app-1.0.0.jar:na]
    at org.eclipse.persistence.internal.queries.ExpressionQueryMechanism.selectOneRowFromTable(ExpressionQueryMechanism.java:2801) ~[commons-app-1.0.0.jar:na]
    at org.eclipse.persistence.internal.queries.ExpressionQueryMechanism.selectOneRow(ExpressionQueryMechanism.java:2754) ~[commons-app-1.0.0.jar:na]
    at org.eclipse.persistence.queries.ReadObjectQuery.executeObjectLevelReadQuery(ReadObjectQuery.java:545) ~[commons-app-1.0.0.jar:na]
    at org.eclipse.persistence.queries.ObjectLevelReadQuery.executeDatabaseQuery(ObjectLevelReadQuery.java:1168) ~[commons-app-1.0.0.jar:na]
    at org.eclipse.persistence.queries.DatabaseQuery.execute(DatabaseQuery.java:899) ~[commons-app-1.0.0.jar:na]
    at org.eclipse.persistence.queries.ObjectLevelReadQuery.execute(ObjectLevelReadQuery.java:1127) ~[commons-app-1.0.0.jar:na]
    at org.eclipse.persistence.queries.ReadObjectQuery.execute(ReadObjectQuery.java:431) ~[commons-app-1.0.0.jar:na]
    at org.eclipse.persistence.queries.ObjectLevelReadQuery.executeInUnitOfWork(ObjectLevelReadQuery.java:1215) ~[commons-app-1.0.0.jar:na]
    at org.eclipse.persistence.internal.sessions.UnitOfWorkImpl.internalExecuteQuery(UnitOfWorkImpl.java:2896) ~[commons-app-1.0.0.jar:na]
    at org.eclipse.persistence.internal.sessions.AbstractSession.executeQuery(AbstractSession.java:1793) ~[commons-app-1.0.0.jar:na]
    at org.eclipse.persistence.internal.sessions.AbstractSession.executeQuery(AbstractSession.java:1775) ~[commons-app-1.0.0.jar:na]
    at org.eclipse.persistence.internal.indirection.QueryBasedValueHolder.instantiate(QueryBasedValueHolder.java:129) ~[commons-app-1.0.0.jar:na]
    at org.eclipse.persistence.internal.indirection.QueryBasedValueHolder.instantiate(QueryBasedValueHolder.java:116) ~[commons-app-1.0.0.jar:na]
    at org.eclipse.persistence.internal.indirection.DatabaseValueHolder.getValue(DatabaseValueHolder.java:89) ~[commons-app-1.0.0.jar:na]
    at org.eclipse.persistence.internal.indirection.UnitOfWorkValueHolder.instantiateImpl(UnitOfWorkValueHolder.java:173) ~[commons-app-1.0.0.jar:na]
    at org.eclipse.persistence.internal.indirection.UnitOfWorkValueHolder.instantiate(UnitOfWorkValueHolder.java:234) ~[commons-app-1.0.0.jar:na]
    at org.eclipse.persistence.internal.indirection.DatabaseValueHolder.getValue(DatabaseValueHolder.java:89) ~[commons-app-1.0.0.jar:na]
    at org.eclipse.persistence.internal.indirection.BasicIndirectionPolicy.getRealAttributeValueFromObject(BasicIndirectionPolicy.java:280) ~[commons-app-1.0.0.jar:na]
    at org.eclipse.persistence.internal.indirection.WeavedObjectBasicIndirectionPolicy.getRealAttributeValueFromObject(WeavedObjectBasicIndirectionPolicy.java:73) ~[commons-app-1.0.0.jar:na]
    at org.eclipse.persistence.mappings.ObjectReferenceMapping.cascadePerformRemoveIfRequired(ObjectReferenceMapping.java:879) ~[commons-app-1.0.0.jar:na]
    at org.eclipse.persistence.mappings.ObjectReferenceMapping.cascadePerformRemoveIfRequired(ObjectReferenceMapping.java:859) ~[commons-app-1.0.0.jar:na]
    at org.eclipse.persistence.internal.descriptors.ObjectBuilder.cascadePerformRemove(ObjectBuilder.java:2434) ~[commons-app-1.0.0.jar:na]
    at org.eclipse.persistence.internal.sessions.UnitOfWorkImpl.performRemove(UnitOfWorkImpl.java:3594) ~[commons-app-1.0.0.jar:na]
    at org.eclipse.persistence.mappings.CollectionMapping.cascadePerformRemoveIfRequired(CollectionMapping.java:372) ~[commons-app-1.0.0.jar:na]
    at org.eclipse.persistence.internal.descriptors.ObjectBuilder.cascadePerformRemove(ObjectBuilder.java:2434) ~[commons-app-1.0.0.jar:na]
    at org.eclipse.persistence.internal.sessions.UnitOfWorkImpl.performRemove(UnitOfWorkImpl.java:3594) ~[commons-app-1.0.0.jar:na]
    at org.eclipse.persistence.mappings.ObjectReferenceMapping.cascadePerformRemoveIfRequired(ObjectReferenceMapping.java:886) ~[commons-app-1.0.0.jar:na]
    at org.eclipse.persistence.mappings.ObjectReferenceMapping.cascadePerformRemoveIfRequired(ObjectReferenceMapping.java:859) ~[commons-app-1.0.0.jar:na]
    at org.eclipse.persistence.internal.descriptors.ObjectBuilder.cascadePerformRemove(ObjectBuilder.java:2434) ~[commons-app-1.0.0.jar:na]
    at org.eclipse.persistence.internal.sessions.UnitOfWorkImpl.performRemove(UnitOfWorkImpl.java:3594) ~[commons-app-1.0.0.jar:na]
    at org.eclipse.persistence.internal.jpa.EntityManagerImpl.remove(EntityManagerImpl.java:563) ~[commons-app-1.0.0.jar:na]
    at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method) ~[na:1.7.0_21]
    at sun.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:57) ~[na:1.7.0_21]
    at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43) ~[na:1.7.0_21]
    at java.lang.reflect.Method.invoke(Method.java:601) ~[na:1.7.0_21]
    at org.springframework.orm.jpa.SharedEntityManagerCreator$SharedEntityManagerInvocationHandler.invoke(SharedEntityManagerCreator.java:240) ~[spring-orm-3.1.2.RELEASE.jar:3.1.2.RELEASE]
    at com.sun.proxy.$Proxy26.remove(Unknown Source) ~[na:na]
    at cz.cuni.mff.xrg.odcs.commons.app.dao.db.DbAccessBase.delete(DbAccessBase.java:39) ~[commons-app-1.0.0.jar:na]
    at cz.cuni.mff.xrg.odcs.commons.app.facade.PipelineFacadeImpl.delete(PipelineFacadeImpl.java:176) ~[commons-app-1.0.0.jar:na]
    at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method) ~[na:1.7.0_21]
    at sun.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:57) ~[na:1.7.0_21]
    at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43) ~[na:1.7.0_21]
    at java.lang.reflect.Method.invoke(Method.java:601) ~[na:1.7.0_21]
    at org.springframework.aop.support.AopUtils.invokeJoinpointUsingReflection(AopUtils.java:309) ~[spring-aop-3.0.7.RELEASE.jar:3.0.7.RELEASE]
    at org.springframework.aop.framework.ReflectiveMethodInvocation.invokeJoinpoint(ReflectiveMethodInvocation.java:183) ~[spring-aop-3.0.7.RELEASE.jar:3.0.7.RELEASE]
    at org.springframework.aop.framework.ReflectiveMethodInvocation.proceed(ReflectiveMethodInvocation.java:150) ~[spring-aop-3.0.7.RELEASE.jar:3.0.7.RELEASE]
    at org.springframework.security.access.intercept.aopalliance.MethodSecurityInterceptor.invoke(MethodSecurityInterceptor.java:64) ~[spring-security-core-3.1.4.RELEASE.jar:3.1.4.RELEASE]
    at org.springframework.aop.framework.ReflectiveMethodInvocation.proceed(ReflectiveMethodInvocation.java:172) ~[spring-aop-3.0.7.RELEASE.jar:3.0.7.RELEASE]
    at org.springframework.aop.framework.JdkDynamicAopProxy.invoke(JdkDynamicAopProxy.java:202) ~[spring-aop-3.0.7.RELEASE.jar:3.0.7.RELEASE]
    at com.sun.proxy.$Proxy32.delete(Unknown Source) ~[na:na]
    at cz.cuni.mff.xrg.odcs.frontend.gui.views.pipelinelist.PipelineListPresenterImpl$2.onClose(PipelineListPresenterImpl.java:187) ~[PipelineListPresenterImpl$2.class:na]
    at org.vaadin.dialogs.DefaultConfirmDialogFactory$2.buttonClick(DefaultConfirmDialogFactory.java:145) ~[confirmdialog-2.0.4.jar:2.0.4]
    at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method) ~[na:1.7.0_21]
    at sun.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:57) ~[na:1.7.0_21]
    at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43) ~[na:1.7.0_21]
    at java.lang.reflect.Method.invoke(Method.java:601) ~[na:1.7.0_21]
    at com.vaadin.event.ListenerMethod.receiveEvent(ListenerMethod.java:508) ~[vaadin-server-7.1.8.jar:7.1.8]
    at com.vaadin.event.EventRouter.fireEvent(EventRouter.java:167) ~[vaadin-server-7.1.8.jar:7.1.8]
    at com.vaadin.server.AbstractClientConnector.fireEvent(AbstractClientConnector.java:969) ~[vaadin-server-7.1.8.jar:7.1.8]
    at com.vaadin.ui.Button.fireClick(Button.java:368) ~[vaadin-server-7.1.8.jar:7.1.8]
    at com.vaadin.ui.Button$1.click(Button.java:57) ~[vaadin-server-7.1.8.jar:7.1.8]
    at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method) ~[na:1.7.0_21]
    at sun.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:57) ~[na:1.7.0_21]
    at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43) ~[na:1.7.0_21]
    at java.lang.reflect.Method.invoke(Method.java:601) ~[na:1.7.0_21]
    at com.vaadin.server.ServerRpcManager.applyInvocation(ServerRpcManager.java:168) ~[vaadin-server-7.1.8.jar:7.1.8]
    at com.vaadin.server.ServerRpcManager.applyInvocation(ServerRpcManager.java:118) ~[vaadin-server-7.1.8.jar:7.1.8]
    at com.vaadin.server.communication.ServerRpcHandler.handleBurst(ServerRpcHandler.java:207) [vaadin-server-7.1.8.jar:7.1.8]
    at com.vaadin.server.communication.ServerRpcHandler.handleRpc(ServerRpcHandler.java:111) [vaadin-server-7.1.8.jar:7.1.8]
    at com.vaadin.server.communication.UidlRequestHandler.synchronizedHandleRequest(UidlRequestHandler.java:91) [vaadin-server-7.1.8.jar:7.1.8]
    at com.vaadin.server.SynchronizedRequestHandler.handleRequest(SynchronizedRequestHandler.java:37) [vaadin-server-7.1.8.jar:7.1.8]
    at com.vaadin.server.VaadinService.handleRequest(VaadinService.java:1371) [vaadin-server-7.1.8.jar:7.1.8]
    at com.vaadin.server.VaadinServlet.service(VaadinServlet.java:238) [vaadin-server-7.1.8.jar:7.1.8]
    at cz.cuni.mff.xrg.odcs.frontend.IntlibApplicationServlet.service(IntlibApplicationServlet.java:67) [IntlibApplicationServlet.class:na]
    at javax.servlet.http.HttpServlet.service(HttpServlet.java:728) [servlet-api.jar:na]
    at org.apache.catalina.core.ApplicationFilterChain.internalDoFilter(ApplicationFilterChain.java:305) [catalina.jar:7.0.42]
    at org.apache.catalina.core.ApplicationFilterChain.doFilter(ApplicationFilterChain.java:210) [catalina.jar:7.0.42]
    at org.apache.catalina.core.StandardWrapperValve.invoke(StandardWrapperValve.java:222) [catalina.jar:7.0.42]
    at org.apache.catalina.core.StandardContextValve.invoke(StandardContextValve.java:123) [catalina.jar:7.0.42]
    at org.apache.catalina.authenticator.AuthenticatorBase.invoke(AuthenticatorBase.java:502) [catalina.jar:7.0.42]
    at org.apache.catalina.core.StandardHostValve.invoke(StandardHostValve.java:171) [catalina.jar:7.0.42]
    at org.apache.catalina.valves.ErrorReportValve.invoke(ErrorReportValve.java:99) [catalina.jar:7.0.42]
    at org.apache.catalina.valves.AccessLogValve.invoke(AccessLogValve.java:953) [catalina.jar:7.0.42]
    at org.apache.catalina.core.StandardEngineValve.invoke(StandardEngineValve.java:118) [catalina.jar:7.0.42]
    at org.apache.catalina.connector.CoyoteAdapter.service(CoyoteAdapter.java:408) [catalina.jar:7.0.42]
    at org.apache.coyote.http11.AbstractHttp11Processor.process(AbstractHttp11Processor.java:1023) [tomcat-coyote.jar:7.0.42]
    at org.apache.coyote.AbstractProtocol$AbstractConnectionHandler.process(AbstractProtocol.java:589) [tomcat-coyote.jar:7.0.42]
    at org.apache.tomcat.util.net.AprEndpoint$SocketProcessor.run(AprEndpoint.java:1852) [tomcat-coyote.jar:7.0.42]
    at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1145) [na:1.7.0_21]
    at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:615) [na:1.7.0_21]
    at java.lang.Thread.run(Thread.java:722) [na:1.7.0_21]
```

**Comment by janvojt** [comment]
Is your relational database schema updated? Column `configuration` in tables `DPU_INSTANCE` and `DPU_TEMPLATE` should be of type "LONG **N**VARCHAR".

**Comment by tomesj** [comment]
It´s OK now :-)
