### ISSUE TITLE
Uncaught exception in GUI

### ISSUE THREAD

**Issue by tomas-knap** [mff-uk/odcs#1078]
I click on DPU template record, got: 

![screen shot 2014-01-19 at 4 46 44 pm](https://f.cloud.github.com/assets/3014917/1949787/1f5348ea-8121-11e3-8175-05d3f1a3cdfd.png)

014-01-19 16:47:11,849 [http-bio-8080-exec-572] DEBUG org.eclipse.persistence.logging.sql - 2014-01-19 16:47:11.849--ServerSession(1888330474)--Connection(198346175)--SELECT ID, full_name, u_password, table_rows, USERNAME, email_id FROM usr_user WHERE (ID = ?)
    bind => [1]
2014-01-19 16:47:11,852 [http-bio-8080-exec-572] ERROR cz.cuni.mff.xrg.odcs.frontend.AppEntry - Uncaught exception
java.lang.NullPointerException: null
    at cz.cuni.mff.xrg.odcs.frontend.gui.views.dpu.DPUPresenterImpl.getPipelinesForDpu(DPUPresenterImpl.java:202) ~[DPUPresenterImpl.class:na]
    at cz.cuni.mff.xrg.odcs.frontend.gui.views.dpu.DPUPresenterImpl.getTableData(DPUPresenterImpl.java:291) ~[DPUPresenterImpl.class:na]
    at cz.cuni.mff.xrg.odcs.frontend.gui.views.dpu.DPUViewImpl.buildVerticalLayoutInstances(DPUViewImpl.java:775) ~[DPUViewImpl.class:na]
    at cz.cuni.mff.xrg.odcs.frontend.gui.views.dpu.DPUViewImpl.buildDPUDetailLayout(DPUViewImpl.java:306) ~[DPUViewImpl.class:na]
    at cz.cuni.mff.xrg.odcs.frontend.gui.views.dpu.DPUViewImpl.selectNewDPU(DPUViewImpl.java:745) ~[DPUViewImpl.class:na]
    at cz.cuni.mff.xrg.odcs.frontend.gui.views.dpu.DPUPresenterImpl$1.onClose(DPUPresenterImpl.java:260) ~[DPUPresenterImpl$1.class:na]
    at org.vaadin.dialogs.DefaultConfirmDialogFactory$2.buttonClick(DefaultConfirmDialogFactory.java:145) ~[confirmdialog-2.0.4.jar:2.0.4]
    at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method) ~[na:1.7.0_40]
    at sun.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:57) ~[na:1.7.0_40]
    at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43) ~[na:1.7.0_40]
    at java.lang.reflect.Method.invoke(Method.java:606) ~[na:1.7.0_40]
    at com.vaadin.event.ListenerMethod.receiveEvent(ListenerMethod.java:508) ~[vaadin-server-7.1.8.jar:7.1.8]
    at com.vaadin.event.EventRouter.fireEvent(EventRouter.java:167) ~[vaadin-server-7.1.8.jar:7.1.8]
    at com.vaadin.server.AbstractClientConnector.fireEvent(AbstractClientConnector.java:969) ~[vaadin-server-7.1.8.jar:7.1.8]
    at com.vaadin.ui.Button.fireClick(Button.java:368) ~[vaadin-server-7.1.8.jar:7.1.8]
    at com.vaadin.ui.Button$1.click(Button.java:57) ~[vaadin-server-7.1.8.jar:7.1.8]
    at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method) ~[na:1.7.0_40]
    at sun.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:57) ~[na:1.7.0_40]
    at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43) ~[na:1.7.0_40]
    at java.lang.reflect.Method.invoke(Method.java:606) ~[na:1.7.0_40]
    at com.vaadin.server.ServerRpcManager.applyInvocation(ServerRpcManager.java:168) ~[vaadin-server-7.1.8.jar:7.1.8]
    at com.vaadin.server.ServerRpcManager.applyInvocation(ServerRpcManager.java:118) ~[vaadin-server-7.1.8.jar:7.1.8]
    at com.vaadin.server.communication.ServerRpcHandler.handleBurst(ServerRpcHandler.java:207) [vaadin-server-7.1.8.jar:7.1.8]
    at com.vaadin.server.communication.ServerRpcHandler.handleRpc(ServerRpcHandler.java:111) [vaadin-server-7.1.8.jar:7.1.8]
    at com.vaadin.server.communication.UidlRequestHandler.synchronizedHandleRequest(UidlRequestHandler.java:91) [vaadin-server-7.1.8.jar:7.1.8]
    at com.vaadin.server.SynchronizedRequestHandler.handleRequest(SynchronizedRequestHandler.java:37) [vaadin-server-7.1.8.jar:7.1.8]
    at com.vaadin.server.VaadinService.handleRequest(VaadinService.java:1371) [vaadin-server-7.1.8.jar:7.1.8]
    at com.vaadin.server.VaadinServlet.service(VaadinServlet.java:238) [vaadin-server-7.1.8.jar:7.1.8]
    at cz.cuni.mff.xrg.odcs.frontend.ODCSApplicationServlet.service(ODCSApplicationServlet.java:67) [ODCSApplicationServlet.class:na]
    at javax.servlet.http.HttpServlet.service(HttpServlet.java:728) [servlet-api.jar:na]
    at org.apache.catalina.core.ApplicationFilterChain.internalDoFilter(ApplicationFilterChain.java:305) [catalina.jar:7.0.33]
    at org.apache.catalina.core.ApplicationFilterChain.doFilter(ApplicationFilterChain.java:210) [catalina.jar:7.0.33]
    at org.apache.catalina.core.StandardWrapperValve.invoke(StandardWrapperValve.java:222) [catalina.jar:7.0.33]
    at org.apache.catalina.core.StandardContextValve.invoke(StandardContextValve.java:123) [catalina.jar:7.0.33]
    at org.apache.catalina.authenticator.AuthenticatorBase.invoke(AuthenticatorBase.java:472) [catalina.jar:7.0.33]
    at org.apache.catalina.core.StandardHostValve.invoke(StandardHostValve.java:171) [catalina.jar:7.0.33]
    at org.apache.catalina.valves.ErrorReportValve.invoke(ErrorReportValve.java:99) [catalina.jar:7.0.33]
    at org.apache.catalina.valves.AccessLogValve.invoke(AccessLogValve.java:931) [catalina.jar:7.0.33]
    at org.apache.catalina.core.StandardEngineValve.invoke(StandardEngineValve.java:118) [catalina.jar:7.0.33]
    at org.apache.catalina.connector.CoyoteAdapter.service(CoyoteAdapter.java:407) [catalina.jar:7.0.33]
    at org.apache.coyote.http11.AbstractHttp11Processor.process(AbstractHttp11Processor.java:1004) [tomcat-coyote.jar:7.0.33]
    at org.apache.coyote.AbstractProtocol$AbstractConnectionHandler.process(AbstractProtocol.java:589) [tomcat-coyote.jar:7.0.33]
    at org.apache.tomcat.util.net.JIoEndpoint$SocketProcessor.run(JIoEndpoint.java:312) [tomcat-coyote.jar:7.0.33]
    at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1145) [na:1.7.0_40]
    at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:615) [na:1.7.0_40]
    at java.lang.Thread.run(Thread.java:724) [na:1.7.0_40]

**Comment by tomas-knap** [comment]
@janvojt Maybe associates with your yesterday's commits

**Comment by tomas-knap** [comment]
Happens only for certain record - XSLT on ODCS-Test

**Comment by tomas-knap** [comment]
Please look on that, cannot replace XSLT easily thanks to that

**Comment by bogo777** [comment]
Should be fixed by 647b908d6f5c896b33f1f976f0311e4f17d37168 . Please update and retry.
