### ISSUE TITLE
Support for FileDataUnit in the frontend

### ISSUE THREAD

**Issue by tomas-knap** [mff-uk/odcs#1082]
Petr dodelal file data unit, tedy je mozne ukladat soubory jako vystup z dpu. S tim souvisi drobne upravy v gui: 

1) V Browse/Query, kdyz nekdo vybere jinou nez RDF DataUnit (tedy aktualne FileDataUnit): Tak to zobrazi misto:

![screen shot 2014-01-20 at 5 16 20 pm](https://f.cloud.github.com/assets/3014917/1955830/40e61bf4-81ee-11e3-885c-8f0b5064ee0e.png)

Proste jen: 
Browser not available. 

Tenhle text dej do vlastni komponenty, v budoucnu tam muze pribyt trebas tree view komponenta

2) On pipeline canvas, when pressing "Validate", melo by to zahlasit problem kdyz nesedi typy data units, tedy mapujes vystup rdf data unit na vstup file data unit napriklad. Jeste lepsi by bylo, kdyby v mapovacim dialogu pri mapovani data units vubec neslo namapovat data units odlisnych typu.

Souvisi s #1041

**Comment by bogo777** [comment]
1) Should be done, do we have some DPU with FileDataUnit input/output to test it?
2) I need some way to get the input/output type for data unit, ideally from DataUnitDescription. @skodape Can you provide this or guide me how to get it?

**Comment by skodapetr** [comment]
On DataUnitDescription is method getType .. it's string but basically it's just the name of the class serialized into the string. But has never been tested as has never been used. But I hope it will do the job.

**Comment by tomas-knap** [comment]
on ODCS-test, there is pipeline exec 247, uriGenerator has fileOutput for example.

**Comment by tomas-knap** [comment]
Ready for testing?

**Comment by bogo777** [comment]
Possibly yes, if it won't work, could you provide .jar of some DPU with FileDataUnit for testing on local?

**Comment by tomas-knap** [comment]
On ODCS-test, see first execution - Decisions form nsoud.cz - Batch. 

If I go to browse/query, select XSLT metadata, select file data unit. "No brose available", which is correct. Then I reselect data unit to rdfInput and: 

![screen shot 2014-01-31 at 12 17 39 pm](https://f.cloud.github.com/assets/3014917/2049914/d7e77e0c-8a69-11e3-913e-6e129b04ad1d.png)

2014-01-31 12:17:27,241 [http-bio-8080-exec-130] DEBUG c.c.m.x.o.f.g.v.e.ExecutionListPresenterImpl - ExecutionMonitor refreshed.
2014-01-31 12:17:30,534 [http-bio-8080-exec-130] DEBUG org.openrdf.sail.nativerdf.NativeStore - Initializing NativeStore...
2014-01-31 12:17:30,535 [http-bio-8080-exec-130] DEBUG org.openrdf.sail.nativerdf.NativeStore - Data dir is /usr/local/tomcat/apache-tomcat-7.0.33/temp/intlib-repo8612456298583761048/localRepository
2014-01-31 12:17:30,544 [http-bio-8080-exec-130] DEBUG org.openrdf.sail.nativerdf.TripleStore - No indexes specified, using default indexes: spoc,posc
2014-01-31 12:17:30,545 [http-bio-8080-exec-130] TRACE org.openrdf.sail.nativerdf.TripleStore - Initializing index 'spoc'...
2014-01-31 12:17:30,545 [http-bio-8080-exec-130] TRACE org.openrdf.sail.nativerdf.TripleStore - Initializing index 'posc'...
2014-01-31 12:17:30,545 [http-bio-8080-exec-130] DEBUG org.openrdf.sail.nativerdf.NativeStore - NativeStore initialized
2014-01-31 12:17:30,545 [http-bio-8080-exec-130] INFO  cz.cuni.mff.xrg.odcs.rdf.repositories.LocalRDFRepo - New local repository with data graph http://default successfully initialized.
2014-01-31 12:17:30,551 [http-bio-8080-exec-130] INFO  cz.cuni.mff.xrg.odcs.rdf.repositories.LocalRDFRepo - Releasing DPU LocalRdf: /usr/local/tomcat/apache-tomcat-7.0.33/temp/intlib-repo8612456298583761048
2014-01-31 12:17:30,551 [http-bio-8080-exec-130] INFO  cz.cuni.mff.xrg.odcs.rdf.repositories.LocalRDFRepo - Relelased LocalRdf: /usr/local/tomcat/apache-tomcat-7.0.33/temp/intlib-repo8612456298583761048
2014-01-31 12:17:30,552 [Thread-388] DEBUG org.openrdf.sail.nativerdf.NativeStore - Shutting down NativeStore...
2014-01-31 12:17:30,554 [Thread-388] DEBUG org.openrdf.sail.nativerdf.NativeStore - NativeStore shut down
2014-01-31 12:17:30,554 [Thread-388] DEBUG cz.cuni.mff.xrg.odcs.rdf.repositories.LocalRDFRepo - Repository with data graph http://default destroyed SUCCESSFUL.
2014-01-31 12:17:30,606 [http-bio-8080-exec-130] ERROR cz.cuni.mff.xrg.odcs.frontend.AppEntry - Uncaught exception
java.lang.NullPointerException: null
    at cz.cuni.mff.xrg.odcs.frontend.auxiliaries.RDFDataUnitHelper.getRepository(RDFDataUnitHelper.java:53) ~[RDFDataUnitHelper.class:na]
    at cz.cuni.mff.xrg.odcs.frontend.container.rdf.RDFQuery.<init>(RDFQuery.java:52) ~[RDFQuery.class:na]
    at cz.cuni.mff.xrg.odcs.frontend.container.rdf.RDFQueryFactory.constructQuery(RDFQueryFactory.java:19) ~[RDFQueryFactory.class:na]
    at org.vaadin.addons.lazyquerycontainer.LazyQueryView.getQuery(LazyQueryView.java:406) ~[vaadin-lazyquerycontainer-2.0.9.jar:2.0.9]
    at org.vaadin.addons.lazyquerycontainer.LazyQueryView.getQuerySize(LazyQueryView.java:392) ~[vaadin-lazyquerycontainer-2.0.9.jar:2.0.9]
    at org.vaadin.addons.lazyquerycontainer.LazyQueryView.size(LazyQueryView.java:219) ~[vaadin-lazyquerycontainer-2.0.9.jar:2.0.9]
    at org.vaadin.addons.lazyquerycontainer.LazyQueryContainer.size(LazyQueryContainer.java:183) ~[vaadin-lazyquerycontainer-2.0.9.jar:2.0.9]
    at cz.cuni.mff.xrg.odcs.frontend.gui.components.RDFQueryView.runQuery(RDFQueryView.java:367) ~[RDFQueryView.class:na]
    at cz.cuni.mff.xrg.odcs.frontend.gui.components.RDFQueryView.browseDataUnit(RDFQueryView.java:403) ~[RDFQueryView.class:na]
    at cz.cuni.mff.xrg.odcs.frontend.gui.components.Browse$1.componentEvent(Browse.java:33) ~[Browse$1.class:na]
    at cz.cuni.mff.xrg.odcs.frontend.gui.components.DataUnitSelector.fireEvent(DataUnitSelector.java:133) ~[DataUnitSelector.class:na]
    at cz.cuni.mff.xrg.odcs.frontend.gui.components.DataUnitSelector.access$400(DataUnitSelector.java:30) ~[DataUnitSelector.class:na]
    at cz.cuni.mff.xrg.odcs.frontend.gui.components.DataUnitSelector$4.buttonClick(DataUnitSelector.java:114) ~[DataUnitSelector$4.class:na]
    at sun.reflect.GeneratedMethodAccessor694.invoke(Unknown Source) ~[na:na]
    at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43) ~[na:1.7.0_40]
    at java.lang.reflect.Method.invoke(Method.java:606) ~[na:1.7.0_40]
    at com.vaadin.event.ListenerMethod.receiveEvent(ListenerMethod.java:508) ~[vaadin-server-7.1.10.jar:7.1.10]
    at com.vaadin.event.EventRouter.fireEvent(EventRouter.java:198) ~[vaadin-server-7.1.10.jar:7.1.10]
    at com.vaadin.event.EventRouter.fireEvent(EventRouter.java:161) ~[vaadin-server-7.1.10.jar:7.1.10]
    at com.vaadin.server.AbstractClientConnector.fireEvent(AbstractClientConnector.java:969) ~[vaadin-server-7.1.10.jar:7.1.10]
    at com.vaadin.ui.Button.fireClick(Button.java:368) ~[vaadin-server-7.1.10.jar:7.1.10]
    at com.vaadin.ui.Button$1.click(Button.java:57) ~[vaadin-server-7.1.10.jar:7.1.10]
    at sun.reflect.GeneratedMethodAccessor697.invoke(Unknown Source) ~[na:na]
    at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43) ~[na:1.7.0_40]
    at java.lang.reflect.Method.invoke(Method.java:606) ~[na:1.7.0_40]
    at com.vaadin.server.ServerRpcManager.applyInvocation(ServerRpcManager.java:168) ~[vaadin-server-7.1.10.jar:7.1.10]
    at com.vaadin.server.ServerRpcManager.applyInvocation(ServerRpcManager.java:118) ~[vaadin-server-7.1.10.jar:7.1.10]
    at com.vaadin.server.communication.ServerRpcHandler.handleBurst(ServerRpcHandler.java:207) [vaadin-server-7.1.10.jar:7.1.10]
    at com.vaadin.server.communication.ServerRpcHandler.handleRpc(ServerRpcHandler.java:111) [vaadin-server-7.1.10.jar:7.1.10]
    at com.vaadin.server.communication.UidlRequestHandler.synchronizedHandleRequest(UidlRequestHandler.java:91) [vaadin-server-7.1.10.jar:7.1.10]
    at com.vaadin.server.SynchronizedRequestHandler.handleRequest(SynchronizedRequestHandler.java:37) [vaadin-server-7.1.10.jar:7.1.10]
    at com.vaadin.server.VaadinService.handleRequest(VaadinService.java:1382) [vaadin-server-7.1.10.jar:7.1.10]
    at com.vaadin.server.VaadinServlet.service(VaadinServlet.java:238) [vaadin-server-7.1.10.jar:7.1.10]
    at cz.cuni.mff.xrg.odcs.frontend.ODCSApplicationServlet.service(ODCSApplicationServlet.java:67) [ODCSApplicationServlet.class:na]
    at javax.servlet.http.HttpServlet.service(HttpServlet.java:728) [servlet-api.jar:na]
    at org.apache.catalina.core.ApplicationFilterChain.internalDoFilter(ApplicationFilterChain.java:305) [catalina.jar:7.0.33]
    at org.apache.catalina.core.ApplicationFilterChain.doFilter(ApplicationFilterChain.java:210) [catalina.jar:7.0.33]
    at org.apache.catalina.core.StandardWrapperValve.invoke(StandardWrapperValve.java:222) [catalina.jar:7.0.33]
    at org.apache.catalina.core.StandardContextValve.invoke(StandardContextValve.java:123) [catalina.jar:7.0.33]
    at org.apache.catalina.authenticator.AuthenticatorBase.invoke(AuthenticatorBase.java:472) [catalina.jar:7.0.33]
    at org.apache.catalina.core.StandardHostValve.invoke(StandardHostValve.java:171) [catalina.jar:7.0.33]
    at org.apache.catalina.valves.ErrorReportValve.invoke(ErrorReportValve.java:99) [catalina.jar:7.0.33]
    at org.apache.catalina.valves.AccessLogValve.invoke(AccessLogValve.java:931) [catalina.jar:7.0.33]
    at org.apache.catalina.core.StandardEngineValve.invoke(StandardEngineValve.java:118) [catalina.jar:7.0.33]
    at org.apache.catalina.connector.CoyoteAdapter.service(CoyoteAdapter.java:407) [catalina.jar:7.0.33]
    at org.apache.coyote.http11.AbstractHttp11Processor.process(AbstractHttp11Processor.java:1004) [tomcat-coyote.jar:7.0.33]
    at org.apache.coyote.AbstractProtocol$AbstractConnectionHandler.process(AbstractProtocol.java:589) [tomcat-coyote.jar:7.0.33]
    at org.apache.tomcat.util.net.JIoEndpoint$SocketProcessor.run(JIoEndpoint.java:312) [tomcat-coyote.jar:7.0.33]
    at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1145) [na:1.7.0_40]
    at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:615) [na:1.7.0_40]
    at java.lang.Thread.run(Thread.java:724) [na:1.7.0_40]
2014-01-31 12:17:32,175 [http-bio-8080-exec-130] DEBUG org.eclipse.persistence.logging.sql - 2014-01-31 12:17:32.175--ServerSession(492669468)--Connection(1250254041)--SELECT CASE  WHEN (MAX(t_last_change) > ?) THEN CAST(? AS INTEGER) ELSE CAST(? AS INTEGER) END FROM exec_pipeline

**Comment by tomas-knap** [comment]
2) In the Edge detail dialog. When I am addimg a mapping to a list o mappings, if I try to map incompatible data units, it displays warning. Rather it should display an error and mapping of incompatible types cannot be added to the listbox of "available mappings"

**Comment by bogo777** [comment]
2) is done. Can you provide DPU with file data unit for testing the exception, at least on odcs-test, better directly as jar for me to test on local?

**Comment by tomas-knap** [comment]
Bohuslav, you can try Simple XSLT DPU, in repository
https://github.com/mff-uk/DPUs

**Comment by tomas-knap** [comment]
Does not work properly. It wrotes mapping cannot be created, but mapping is actually created (written in the lower textarea)

**Comment by bogo777** [comment]
Should be fixed by c66db2c48910543494c9b1ff83d0f1f26aa035be . I forgot to mention it in commit message.

**Comment by tomas-knap** [comment]
ok, diky
