### ISSUE TITLE
Problem when replacing DPU template while running

### ISSUE THREAD

**Issue by tomas-knap** [mff-uk/odcs#1121]
When trying to replace a DPU, following error occur: 

The replaced DPU was currently running. When trying second time when the DPU was not running it worked. But strange thing is that the DPU is running by backend, but was replaced in frontend. 

2014-01-27 18:44:46,476 [http-bio-8080-exec-73] DEBUG c.c.m.x.o.f.g.v.e.ExecutionListPresenterImpl - ExecutionMonitor refreshed.
2014-01-27 18:44:50,721 [http-bio-8080-exec-76] WARN  c.c.m.x.o.commons.app.module.DPUModuleManipulator - Failed to load bunle during replace.
cz.cuni.mff.xrg.odcs.commons.app.module.ModuleException: Failed to update bundle.
    at cz.cuni.mff.xrg.odcs.commons.app.module.osgi.OSGIModuleFacade.update(OSGIModuleFacade.java:203) ~[commons-app-1.0.0.jar:na]
    at cz.cuni.mff.xrg.odcs.commons.app.module.DPUModuleManipulator.replace(DPUModuleManipulator.java:310) ~[commons-app-1.0.0.jar:na]
    at cz.cuni.mff.xrg.odcs.frontend.gui.views.dpu.DPUPresenterImpl.copyToTarget(DPUPresenterImpl.java:233) [DPUPresenterImpl.class:na]
    at cz.cuni.mff.xrg.odcs.frontend.gui.views.dpu.DPUPresenterImpl.dpuUploaded(DPUPresenterImpl.java:213) [DPUPresenterImpl.class:na]
    at cz.cuni.mff.xrg.odcs.frontend.gui.views.dpu.DPUPresenterImpl.dpuUploadedEventHandler(DPUPresenterImpl.java:274) [DPUPresenterImpl.class:na]
    at cz.cuni.mff.xrg.odcs.frontend.gui.views.dpu.DPUViewImpl$15.uploadSucceeded(DPUViewImpl.java:625) [DPUViewImpl$15.class:na]
    at cz.cuni.mff.xrg.odcs.frontend.gui.AuthAwareUploadSucceededWrapper.uploadSucceeded(AuthAwareUploadSucceededWrapper.java:44) [AuthAwareUploadSucceededWrapper.class:na]
    at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method) ~[na:1.7.0_40]
    at sun.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:57) ~[na:1.7.0_40]
    at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43) ~[na:1.7.0_40]
    at java.lang.reflect.Method.invoke(Method.java:606) ~[na:1.7.0_40]
    at com.vaadin.event.ListenerMethod.receiveEvent(ListenerMethod.java:508) [vaadin-server-7.1.10.jar:7.1.10]
    at com.vaadin.event.EventRouter.fireEvent(EventRouter.java:198) [vaadin-server-7.1.10.jar:7.1.10]
    at com.vaadin.event.EventRouter.fireEvent(EventRouter.java:161) [vaadin-server-7.1.10.jar:7.1.10]
    at com.vaadin.server.AbstractClientConnector.fireEvent(AbstractClientConnector.java:969) [vaadin-server-7.1.10.jar:7.1.10]
    at com.vaadin.ui.Upload.fireUploadSuccess(Upload.java:802) [vaadin-server-7.1.10.jar:7.1.10]
    at com.vaadin.ui.Upload$1.streamingFinished(Upload.java:1060) [vaadin-server-7.1.10.jar:7.1.10]
    at com.vaadin.server.communication.FileUploadHandler.streamToReceiver(FileUploadHandler.java:567) [vaadin-server-7.1.10.jar:7.1.10]
    at com.vaadin.server.communication.FileUploadHandler.handleFileUploadValidationAndData(FileUploadHandler.java:432) [vaadin-server-7.1.10.jar:7.1.10]
    at com.vaadin.server.communication.FileUploadHandler.doHandleSimpleMultipartFileUpload(FileUploadHandler.java:395) [vaadin-server-7.1.10.jar:7.1.10]
    at com.vaadin.server.communication.FileUploadHandler.handleRequest(FileUploadHandler.java:280) [vaadin-server-7.1.10.jar:7.1.10]
    at com.vaadin.server.VaadinService.handleRequest(VaadinService.java:1382) [vaadin-server-7.1.10.jar:7.1.10]
    at com.vaadin.server.VaadinServlet.service(VaadinServlet.java:238) [vaadin-server-7.1.10.jar:7.1.10]
    at cz.cuni.mff.xrg.odcs.frontend.ODCSApplicationServlet.service(ODCSApplicationServlet.java:67) [ODCSApplicationServlet.class:na]
    at javax.servlet.http.HttpServlet.service(HttpServlet.java:728) [servlet-api.jar:na]
    at org.apache.catalina.core.ApplicationFilterChain.internalDoFilter(ApplicationFilterChain.java:305) [catalina.jar:7.0.33]
    at org.apache.catalina.core.ApplicationFilterChain.doFilter(ApplicationFilterChain.java:210) [catalina.jar:7.0.33]
    at org.apache.catalina.core.StandardWrapperValve.invoke(StandardWrapperValve.java:222) [catalina.jar:7.0.33]
    at org.apache.catalina.core.StandardContextValve.invoke(StandardContextValve.java:123) [catalina.jar:7.0.33]
    at org.apache.catalina.authenticator.AuthenticatorBase.invoke(AuthenticatorBase.java:472) [catalina.jar:7.0.33]
    at org.apache.catalina.core.StandardHostValve.invoke(StandardHostValve.java:171) [catalina.jar:7.0.33]
    at org.apache.catalina.valves.ErrorReportValve.invoke(ErrorReportValve.java:99) [catalina.jar:7.0.33]
    at org.apache.catalina.valves.AccessLogValve.invoke(AccessLogValve.java:931) [catalina.jar:7.0.33]
    at org.apache.catalina.core.StandardEngineValve.invoke(StandardEngineValve.java:118) [catalina.jar:7.0.33]
    at org.apache.catalina.connector.CoyoteAdapter.service(CoyoteAdapter.java:407) [catalina.jar:7.0.33]
    at org.apache.coyote.http11.AbstractHttp11Processor.process(AbstractHttp11Processor.java:1004) [tomcat-coyote.jar:7.0.33]
    at org.apache.coyote.AbstractProtocol$AbstractConnectionHandler.process(AbstractProtocol.java:589) [tomcat-coyote.jar:7.0.33]
    at org.apache.tomcat.util.net.JIoEndpoint$SocketProcessor.run(JIoEndpoint.java:310) [tomcat-coyote.jar:7.0.33]
    at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1145) [na:1.7.0_40]
    at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:615) [na:1.7.0_40]
    at java.lang.Thread.run(Thread.java:724) [na:1.7.0_40]
Caused by: org.eclipse.osgi.framework.internal.core.Framework$DuplicateBundleException: Bundle "cz.cuni.mff.xrg.odcs.Krovak" version "1.0.0" has already been installed from: file:////data/odcs/target/dpu/Krovak/Krovak-1.0.0.jar
    at org.eclipse.osgi.framework.internal.core.Framework.createAndVerifyBundle(Framework.java:722) ~[org.eclipse.osgi-3.9.0.v20130305-2200.jar:na]
    at org.eclipse.osgi.framework.internal.core.Framework.installWorkerPrivileged(Framework.java:942) ~[org.eclipse.osgi-3.9.0.v20130305-2200.jar:na]
    at org.eclipse.osgi.framework.internal.core.Framework$1.run(Framework.java:845) ~[org.eclipse.osgi-3.9.0.v20130305-2200.jar:na]
    at org.eclipse.osgi.framework.internal.core.Framework$1.run(Framework.java:1) ~[org.eclipse.osgi-3.9.0.v20130305-2200.jar:na]
    at java.security.AccessController.doPrivileged(Native Method) ~[na:1.7.0_40]
    at org.eclipse.osgi.framework.internal.core.Framework.installWorker(Framework.java:904) ~[org.eclipse.osgi-3.9.0.v20130305-2200.jar:na]
    at org.eclipse.osgi.framework.internal.core.Framework.installBundle(Framework.java:840) ~[org.eclipse.osgi-3.9.0.v20130305-2200.jar:na]
    at org.eclipse.osgi.framework.internal.core.BundleContextImpl.installBundle(BundleContextImpl.java:137) ~[org.eclipse.osgi-3.9.0.v20130305-2200.jar:na]
    at org.eclipse.osgi.framework.internal.core.BundleContextImpl.installBundle(BundleContextImpl.java:131) ~[org.eclipse.osgi-3.9.0.v20130305-2200.jar:na]
    at cz.cuni.mff.xrg.odcs.commons.app.module.osgi.BundleContainer.update(BundleContainer.java:223) ~[commons-app-1.0.0.jar:na]
    at cz.cuni.mff.xrg.odcs.commons.app.module.osgi.OSGIModuleFacade.update(OSGIModuleFacade.java:201) ~[commons-app-1.0.0.jar:na]
    ... 40 common frames omitted
2014-01-27 18:44:50,723 [http-bio-8080-exec-76] DEBUG org.eclipse.persistence.logging.sql - 2014-01-27 18:44:50.722--ServerSession(60407303)--Connection(1817827668)--SELECT ID, config_valid, description, jar_description, jar_directory, jar_name, name, configuration, visibility, TYPE, use_dpu_description, user_id, parent_id FROM dpu_template WHERE (ID = ?)

**Comment by skodapetr** [comment]
Is it replicable?

As it looks to me, the previous version DPU was not uninstalled properly (which is strange maybe more info is in log?). But I've tried replace of running DPU (to find out what happen) and it works fine. 

We can try to add more longs into this functionality.
