### ISSUE TITLE
Although there is an arrow on the canvas, the data unit might be missing

### ISSUE THREAD

**Issue by tomas-knap** [mff-uk/odcs#115]
Method:

RDFDataRepository repository = (RDFDataRepository) context.getInputs().get(0); 

may throw java.lang.IndexOutOfBoundsException when the DPU developer forgets to addOutputDataUnit() to his implementation of the previous DPU. 

Therefore, it may happen that there is edge on the canvas, but no data unit when executing the pipeline. I would expect that an edge - data flow on the canvas implies existence of data unit.

1: Validate button, which validates that DPUs implement proper data units to realize the data flow on the canvas. 

2?: Every edge on the canvas automatically yields in the data unit creation, because every arrow in the canvas is some data flow. So it should not happen that there is arrow on the canvas, but no data unit. Data unit which corresponds with the arrow on the canvas, should be created automatically. DPU developer can only specify which outputDataUnits (if there are more than one) receives which data. 

We should implement at least 1)

**Comment by tomas-knap** [comment]
Adjust the log message when certain data unit is missing (there should be input, but there is no input)

**Comment by tomas-knap** [comment]
Currently, it is thrown: 
Pipeline execution terminated because of: java.lang.IndexOutOfBoundsException: Index: 0, Size: 0
    at java.util.LinkedList.checkElementIndex(LinkedList.java:553)
    at java.util.LinkedList.get(LinkedList.java:474)
    at cz.cuni.mff.xrg.intlib.loader.file.FileLoader.load(FileLoader.java:42)
    at cz.cuni.xrg.intlib.backend.execution.PipelineWorker.runLoader(PipelineWorker.java:580)
    at cz.cuni.xrg.intlib.backend.execution.PipelineWorker.runNode(PipelineWorker.java:517)
    at cz.cuni.xrg.intlib.backend.execution.PipelineWorker.run(PipelineWorker.java:231)
    at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1145)
    at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:615)
    at java.lang.Thread.run(Thread.java:722)

It should be more user friendly

**Comment by tomas-knap** [comment]
Petre, can we close this issue?
