### ISSUE TITLE
Issue with logging when running on Windows in Eclipse when launching Backend

### ISSUE THREAD

**Issue by jakubklimek** [mff-uk/odcs#123]
This issue occurs when Kubo was trying to use Virtuoso other than default on localhost:1111. Maybe problem with hardcoded path to Virtuoso for storing logs? Or what do you think Petr?

17:12:43,892 |-WARN in ch.qos.logback.core.db.DriverManagerConnectionSource@42a4441e - Could not discover the dialect to use. virtuoso.jdbc4.VirtuosoException: Connection failed: Connection refused: connect
    at virtuoso.jdbc4.VirtuosoException: Connection failed: Connection refused: connect
    at  at virtuoso.jdbc4.VirtuosoConnection.connect(Unknown Source)
    at  at virtuoso.jdbc4.VirtuosoConnection.connect(Unknown Source)
    at  at virtuoso.jdbc4.VirtuosoConnection.<init>(Unknown Source)
    at  at virtuoso.jdbc4.Driver.connect(Unknown Source)
    at  at java.sql.DriverManager.getConnection(Unknown Source)
    at  at java.sql.DriverManager.getConnection(Unknown Source)
    at  at ch.qos.logback.core.db.DriverManagerConnectionSource.getConnection(DriverManagerConnectionSource.java:54)
    at  at ch.qos.logback.core.db.ConnectionSourceBase.discoverConnectionProperties(ConnectionSourceBase.java:48)
    at  at ch.qos.logback.core.db.DriverManagerConnectionSource.start(DriverManagerConnectionSource.java:38)
    at  at ch.qos.logback.core.joran.action.NestedComplexPropertyIA.end(NestedComplexPropertyIA.java:167)
    at  at ch.qos.logback.core.joran.spi.Interpreter.callEndAction(Interpreter.java:317)
    at  at ch.qos.logback.core.joran.spi.Interpreter.endElement(Interpreter.java:196)
    at  at ch.qos.logback.core.joran.spi.Interpreter.endElement(Interpreter.java:182)
    at  at ch.qos.logback.core.joran.spi.EventPlayer.play(EventPlayer.java:62)
    at  at ch.qos.logback.core.joran.GenericConfigurator.doConfigure(GenericConfigurator.java:149)
    at  at ch.qos.logback.core.joran.GenericConfigurator.doConfigure(GenericConfigurator.java:135)
    at  at ch.qos.logback.core.joran.GenericConfigurator.doConfigure(GenericConfigurator.java:99)
    at  at ch.qos.logback.core.joran.GenericConfigurator.doConfigure(GenericConfigurator.java:49)
    at  at ch.qos.logback.classic.util.ContextInitializer.configureByResource(ContextInitializer.java:75)
    at  at ch.qos.logback.classic.util.ContextInitializer.autoConfig(ContextInitializer.java:148)
    at  at org.slf4j.impl.StaticLoggerBinder.init(StaticLoggerBinder.java:85)
    at  at org.slf4j.impl.StaticLoggerBinder.<clinit>(StaticLoggerBinder.java:55)
    at  at org.slf4j.LoggerFactory.bind(LoggerFactory.java:128)
    at  at org.slf4j.LoggerFactory.performInitialization(LoggerFactory.java:107)
    at  at org.slf4j.LoggerFactory.getILoggerFactory(LoggerFactory.java:295)
    at  at org.slf4j.LoggerFactory.getLogger(LoggerFactory.java:269)
    at  at org.slf4j.LoggerFactory.getLogger(LoggerFactory.java:281)
    at  at cz.cuni.xrg.intlib.backend.AppEntry.<clinit>(AppEntry.java:42)

**Comment by tomas-knap** [comment]
Honzo, db connection for logging should be also taken from config.properties

**Comment by janvojt** [comment]
This has been fixed some time ago...closing.
