### ISSUE TITLE
Pre-executor fails

### ISSUE THREAD

**Issue by mingan** [mff-uk/odcs#1243]
Running/debugging demo DBPedia pipeline fails with

Time:Feb 21, 2014 1:06:44 PMLevel:ERRORSource:cz.cuni.mff.xrg.odcs.backend.dpu.event.DPUEventMessage:
Pre-executor 'cz.cuni.mff.xrg.odcs.backend.execution.dpu.impl.Configurator' failed for DPU 'SPARQL Extractor' with message: 'dpu.configure throws non ConfigException'

Stack trace:
java.lang.NoSuchMethodError cz.cuni.mff.xrg.odcs.commons.app.dpu.DPUInstanceRecord.getRawConf()[B at cz.cuni.mff.xrg.odcs.backend.execution.dpu.impl.Configurator.preAction(Configurator.java:71) at cz.cuni.mff.xrg.odcs.backend.execution.dpu.Executor.executePreExecutors(Executor.java:195) at cz.cuni.mff.xrg.odcs.backend.execution.dpu.Executor.execute(Executor.java:318) at cz.cuni.mff.xrg.odcs.backend.execution.dpu.Executor.run(Executor.java:441) at java.lang.Thread.run(Unknown Source)

Clean install from commit fc5fbf995b8e937bc0eb8c438d5aeef8cf097f6d, clean database populated from supplied SQL files, running Virtuoso 6.1.8.

**Comment by mingan** [comment]
Works fine with build from 616e41b4027e1a14bba82cbb9383f79691384b52
