### ISSUE TITLE
DPU Configuration - getConfiguration() is called when selecting DPU template, why?

### ISSUE THREAD

**Issue by jakubklimek** [mff-uk/odcs#1289]
on ODCS, In DPU Templates:
- On Metadata DPU config I click Save.
- I click on Buyer Profiles DPU
- Then, when I look in the frontend log, I see:
  <pre><code>
  java.lang.NumberFormatException: For input string: ""
      at java.lang.NumberFormatException.forInputString(NumberFormatException.java:65) ~[na:1.7.0_40]
      at java.lang.Integer.parseInt(Integer.java:504) ~[na:1.7.0_40]
      at java.lang.Integer.parseInt(Integer.java:527) ~[na:1.7.0_40]
      at cz.opendata.linked.ares.updates.ExtractorDialog.getConfiguration(ExtractorDialog.java:67) ~[na:na]
      at cz.opendata.linked.ares.updates.ExtractorDialog.getConfiguration(ExtractorDialog.java:14) ~[na:na]
      at cz.cuni.mff.xrg.odcs.commons.module.dialog.BaseConfigDialog.hasConfigChanged(BaseConfigDialog.java:131) ~[na:na]
      at cz.cuni.mff.xrg.odcs.frontend.gui.views.dpu.DPUViewImpl.isChanged(DPUViewImpl.java:698) [DPUViewImpl.class:na]
      at cz.cuni.mff.xrg.odcs.frontend.gui.views.dpu.DPUViewImpl$5.selectedTabChange(DPUViewImpl.java:278) [DPUViewImpl$5.class:na]
      at sun.reflect.GeneratedMethodAccessor507.invoke(Unknown Source) ~[na:na]
      at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43) ~[na:1.7.0_40]
      at java.lang.reflect.Method.invoke(Method.java:606) ~[na:1.7.0_40]
      at com.vaadin.event.ListenerMethod.receiveEvent(ListenerMethod.java:508) [vaadin-server-7.1.8.jar:7.1.8]
      at com.vaadin.event.EventRouter.fireEvent(EventRouter.java:167) [vaadin-server-7.1.8.jar:7.1.8]
      at com.vaadin.server.AbstractClientConnector.fireEvent(AbstractClientConnector.java:969) [vaadin-server-7.1.8.jar:7.1.8]
      at com.vaadin.ui.TabSheet.fireSelectedTabChange(TabSheet.java:837) [vaadin-server-7.1.8.jar:7.1.8]
      at com.vaadin.ui.TabSheet.addTab(TabSheet.java:312) [vaadin-server-7.1.8.jar:7.1.8]
      at com.vaadin.ui.TabSheet.addTab(TabSheet.java:271) [vaadin-server-7.1.8.jar:7.1.8]
      at com.vaadin.ui.TabSheet.addTab(TabSheet.java:247) [vaadin-server-7.1.8.jar:7.1.8]
      at cz.cuni.mff.xrg.odcs.frontend.gui.views.dpu.DPUViewImpl.buildDPUDetailLayout(DPUViewImpl.java:293) [DPUViewImpl.class:na]
      at cz.cuni.mff.xrg.odcs.frontend.gui.views.dpu.DPUViewImpl.selectNewDPU(DPUViewImpl.java:768) [DPUViewImpl.class:na]
      at cz.cuni.mff.xrg.odcs.frontend.gui.views.dpu.DPUPresenterImpl$1.onClose(DPUPresenterImpl.java:266) [DPUPresenterImpl$1.class:na]
      at org.vaadin.dialogs.DefaultConfirmDialogFactory$2.buttonClick(DefaultConfirmDialogFactory.java:145) [confirmdialog-2.0.4.jar:2.0.4]
      at sun.reflect.GeneratedMethodAccessor464.invoke(Unknown Source) ~[na:na]
      at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43) ~[na:1.7.0_40]
      at java.lang.reflect.Method.invoke(Method.java:606) ~[na:1.7.0_40]
      at com.vaadin.event.ListenerMethod.receiveEvent(ListenerMethod.java:508) [vaadin-server-7.1.8.jar:7.1.8]
      at com.vaadin.event.EventRouter.fireEvent(EventRouter.java:167) [vaadin-server-7.1.8.jar:7.1.8]
      at com.vaadin.server.AbstractClientConnector.fireEvent(AbstractClientConnector.java:969) [vaadin-server-7.1.8.jar:7.1.8]
      at com.vaadin.ui.Button.fireClick(Button.java:368) [vaadin-server-7.1.8.jar:7.1.8]
      at com.vaadin.ui.Button$1.click(Button.java:57) [vaadin-server-7.1.8.jar:7.1.8]
      at sun.reflect.GeneratedMethodAccessor467.invoke(Unknown Source) ~[na:na]
      at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43) ~[na:1.7.0_40]
      at java.lang.reflect.Method.invoke(Method.java:606) ~[na:1.7.0_40]
      at com.vaadin.server.ServerRpcManager.applyInvocation(ServerRpcManager.java:168) [vaadin-server-7.1.8.jar:7.1.8]
      at com.vaadin.server.ServerRpcManager.applyInvocation(ServerRpcManager.java:118) [vaadin-server-7.1.8.jar:7.1.8]
      at com.vaadin.server.communication.ServerRpcHandler.handleBurst(ServerRpcHandler.java:207) [vaadin-server-7.1.8.jar:7.1.8]
      at com.vaadin.server.communication.ServerRpcHandler.handleRpc(ServerRpcHandler.java:111) [vaadin-server-7.1.8.jar:7.1.8]
      at com.vaadin.server.communication.UidlRequestHandler.synchronizedHandleRequest(UidlRequestHandler.java:91) [vaadin-server-7.1.8.jar:7.1.8]
      at com.vaadin.server.SynchronizedRequestHandler.handleRequest(SynchronizedRequestHandler.java:37) [vaadin-server-7.1.8.jar:7.1.8]
      at com.vaadin.server.VaadinService.handleRequest(VaadinService.java:1371) [vaadin-server-7.1.8.jar:7.1.8]
      at com.vaadin.server.VaadinServlet.service(VaadinServlet.java:238) [vaadin-server-7.1.8.jar:7.1.8]
      at cz.cuni.mff.xrg.odcs.frontend.ODCSApplicationServlet.service(ODCSApplicationServlet.java:74) [ODCSApplicationServlet.class:na]
      at javax.servlet.http.HttpServlet.service(HttpServlet.java:728) [servlet-api.jar:na]
      at org.apache.catalina.core.ApplicationFilterChain.internalDoFilter(ApplicationFilterChain.java:305) [catalina.jar:7.0.33]
      at org.apache.catalina.core.ApplicationFilterChain.doFilter(ApplicationFilterChain.java:210) [catalina.jar:7.0.33]
      at org.apache.catalina.core.StandardWrapperValve.invoke(StandardWrapperValve.java:222) [catalina.jar:7.0.33]
      at org.apache.catalina.core.StandardContextValve.invoke(StandardContextValve.java:123) [catalina.jar:7.0.33]
      at org.apache.catalina.authenticator.AuthenticatorBase.invoke(AuthenticatorBase.java:472) [catalina.jar:7.0.33]
      at org.apache.catalina.core.StandardHostValve.invoke(StandardHostValve.java:171) [catalina.jar:7.0.33]
      at org.apache.catalina.valves.ErrorReportValve.invoke(ErrorReportValve.java:99) [catalina.jar:7.0.33]
      at org.apache.catalina.valves.AccessLogValve.invoke(AccessLogValve.java:931) [catalina.jar:7.0.33]
      at org.apache.catalina.core.StandardEngineValve.invoke(StandardEngineValve.java:118) [catalina.jar:7.0.33]
      at org.apache.catalina.connector.CoyoteAdapter.service(CoyoteAdapter.java:407) [catalina.jar:7.0.33]
      at org.apache.coyote.http11.AbstractHttp11Processor.process(AbstractHttp11Processor.java:1004) [tomcat-coyote.jar:7.0.33]
      at org.apache.coyote.AbstractProtocol$AbstractConnectionHandler.process(AbstractProtocol.java:589) [tomcat-coyote.jar:7.0.33]
      at org.apache.tomcat.util.net.JIoEndpoint$SocketProcessor.run(JIoEndpoint.java:312) [tomcat-coyote.jar:7.0.33]
      at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1145) [na:1.7.0_40]
      at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:615) [na:1.7.0_40]
      at java.lang.Thread.run(Thread.java:724) [na:1.7.0_40]
  </pre></code>
  and 
  <pre><code>
  java.lang.NumberFormatException: For input string: ""
      at java.lang.NumberFormatException.forInputString(NumberFormatException.java:65) ~[na:1.7.0_40]
      at java.lang.Integer.parseInt(Integer.java:504) ~[na:1.7.0_40]
      at java.lang.Integer.parseInt(Integer.java:527) ~[na:1.7.0_40]
      at cz.opendata.linked.buyer_profiles.ExtractorDialog.getConfiguration(ExtractorDialog.java:94) ~[na:na]
      at cz.opendata.linked.buyer_profiles.ExtractorDialog.getConfiguration(ExtractorDialog.java:16) ~[na:na]
      at cz.cuni.mff.xrg.odcs.commons.module.dialog.BaseConfigDialog.hasConfigChanged(BaseConfigDialog.java:131) ~[na:na]
      at cz.cuni.mff.xrg.odcs.frontend.gui.views.dpu.DPUViewImpl.isChanged(DPUViewImpl.java:698) [DPUViewImpl.class:na]
      at cz.cuni.mff.xrg.odcs.frontend.gui.views.dpu.DPUViewImpl$5.selectedTabChange(DPUViewImpl.java:278) [DPUViewImpl$5.class:na]
      at sun.reflect.GeneratedMethodAccessor507.invoke(Unknown Source) ~[na:na]
      at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43) ~[na:1.7.0_40]
      at java.lang.reflect.Method.invoke(Method.java:606) ~[na:1.7.0_40]
      at com.vaadin.event.ListenerMethod.receiveEvent(ListenerMethod.java:508) [vaadin-server-7.1.8.jar:7.1.8]
      at com.vaadin.event.EventRouter.fireEvent(EventRouter.java:167) [vaadin-server-7.1.8.jar:7.1.8]
      at com.vaadin.server.AbstractClientConnector.fireEvent(AbstractClientConnector.java:969) [vaadin-server-7.1.8.jar:7.1.8]
      at com.vaadin.ui.TabSheet.fireSelectedTabChange(TabSheet.java:837) [vaadin-server-7.1.8.jar:7.1.8]
      at com.vaadin.ui.TabSheet.addTab(TabSheet.java:312) [vaadin-server-7.1.8.jar:7.1.8]
      at com.vaadin.ui.TabSheet.addTab(TabSheet.java:271) [vaadin-server-7.1.8.jar:7.1.8]
      at com.vaadin.ui.TabSheet.addTab(TabSheet.java:247) [vaadin-server-7.1.8.jar:7.1.8]
      at cz.cuni.mff.xrg.odcs.frontend.gui.views.dpu.DPUViewImpl.buildDPUDetailLayout(DPUViewImpl.java:293) [DPUViewImpl.class:na]
      at cz.cuni.mff.xrg.odcs.frontend.gui.views.dpu.DPUViewImpl.selectNewDPU(DPUViewImpl.java:768) [DPUViewImpl.class:na]
      at cz.cuni.mff.xrg.odcs.frontend.gui.views.dpu.DPUPresenterImpl$1.onClose(DPUPresenterImpl.java:266) [DPUPresenterImpl$1.class:na]
      at org.vaadin.dialogs.DefaultConfirmDialogFactory$2.buttonClick(DefaultConfirmDialogFactory.java:145) [confirmdialog-2.0.4.jar:2.0.4]
      at sun.reflect.GeneratedMethodAccessor464.invoke(Unknown Source) ~[na:na]
      at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43) ~[na:1.7.0_40]
      at java.lang.reflect.Method.invoke(Method.java:606) ~[na:1.7.0_40]
      at com.vaadin.event.ListenerMethod.receiveEvent(ListenerMethod.java:508) [vaadin-server-7.1.8.jar:7.1.8]
      at com.vaadin.event.EventRouter.fireEvent(EventRouter.java:167) [vaadin-server-7.1.8.jar:7.1.8]
      at com.vaadin.server.AbstractClientConnector.fireEvent(AbstractClientConnector.java:969) [vaadin-server-7.1.8.jar:7.1.8]
      at com.vaadin.ui.Button.fireClick(Button.java:368) [vaadin-server-7.1.8.jar:7.1.8]
      at com.vaadin.ui.Button$1.click(Button.java:57) [vaadin-server-7.1.8.jar:7.1.8]
      at sun.reflect.GeneratedMethodAccessor467.invoke(Unknown Source) ~[na:na]
      at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43) ~[na:1.7.0_40]
      at java.lang.reflect.Method.invoke(Method.java:606) ~[na:1.7.0_40]
      at com.vaadin.server.ServerRpcManager.applyInvocation(ServerRpcManager.java:168) [vaadin-server-7.1.8.jar:7.1.8]
      at com.vaadin.server.ServerRpcManager.applyInvocation(ServerRpcManager.java:118) [vaadin-server-7.1.8.jar:7.1.8]
      at com.vaadin.server.communication.ServerRpcHandler.handleBurst(ServerRpcHandler.java:207) [vaadin-server-7.1.8.jar:7.1.8]
      at com.vaadin.server.communication.ServerRpcHandler.handleRpc(ServerRpcHandler.java:111) [vaadin-server-7.1.8.jar:7.1.8]
      at com.vaadin.server.communication.UidlRequestHandler.synchronizedHandleRequest(UidlRequestHandler.java:91) [vaadin-server-7.1.8.jar:7.1.8]
      at com.vaadin.server.SynchronizedRequestHandler.handleRequest(SynchronizedRequestHandler.java:37) [vaadin-server-7.1.8.jar:7.1.8]
      at com.vaadin.server.VaadinService.handleRequest(VaadinService.java:1371) [vaadin-server-7.1.8.jar:7.1.8]
      at com.vaadin.server.VaadinServlet.service(VaadinServlet.java:238) [vaadin-server-7.1.8.jar:7.1.8]
      at cz.cuni.mff.xrg.odcs.frontend.ODCSApplicationServlet.service(ODCSApplicationServlet.java:74) [ODCSApplicationServlet.class:na]
      at javax.servlet.http.HttpServlet.service(HttpServlet.java:728) [servlet-api.jar:na]
      at org.apache.catalina.core.ApplicationFilterChain.internalDoFilter(ApplicationFilterChain.java:305) [catalina.jar:7.0.33]
      at org.apache.catalina.core.ApplicationFilterChain.doFilter(ApplicationFilterChain.java:210) [catalina.jar:7.0.33]
      at org.apache.catalina.core.StandardWrapperValve.invoke(StandardWrapperValve.java:222) [catalina.jar:7.0.33]
      at org.apache.catalina.core.StandardContextValve.invoke(StandardContextValve.java:123) [catalina.jar:7.0.33]
      at org.apache.catalina.authenticator.AuthenticatorBase.invoke(AuthenticatorBase.java:472) [catalina.jar:7.0.33]
      at org.apache.catalina.core.StandardHostValve.invoke(StandardHostValve.java:171) [catalina.jar:7.0.33]
      at org.apache.catalina.valves.ErrorReportValve.invoke(ErrorReportValve.java:99) [catalina.jar:7.0.33]
      at org.apache.catalina.valves.AccessLogValve.invoke(AccessLogValve.java:931) [catalina.jar:7.0.33]
      at org.apache.catalina.core.StandardEngineValve.invoke(StandardEngineValve.java:118) [catalina.jar:7.0.33]
      at org.apache.catalina.connector.CoyoteAdapter.service(CoyoteAdapter.java:407) [catalina.jar:7.0.33]
      at org.apache.coyote.http11.AbstractHttp11Processor.process(AbstractHttp11Processor.java:1004) [tomcat-coyote.jar:7.0.33]
      at org.apache.coyote.AbstractProtocol$AbstractConnectionHandler.process(AbstractProtocol.java:589) [tomcat-coyote.jar:7.0.33]
      at org.apache.tomcat.util.net.JIoEndpoint$SocketProcessor.run(JIoEndpoint.java:312) [tomcat-coyote.jar:7.0.33]
      at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1145) [na:1.7.0_40]
      at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:615) [na:1.7.0_40]
      at java.lang.Thread.run(Thread.java:724) [na:1.7.0_40]
  </code></pre>

Notice that it accesses ARES Updates DPU!!

**Comment by tomas-knap** [comment]
When clicking on Ares Updates or Buyers' profile DPU template in the tree, the error above occurs. The error says that the configuration is taken from the dialog, but the dialog is not yes initialized, so when getting and parsing number from the field it throws an exception as above. That is probably the problem. 

Why is the method getConfiguration() called when clicking on the DPU template?

**Comment by skodapetr** [comment]
The problem is that Frontend set the DPU. This invokes the isChanged handler and this cause the call of ConfigDialog.isConfigChanged method and then  getConfiguration method,  before the frontend actually set the configuration. 

I add check which automatically return false as an answer for isConfigChanged , in case that the configuration has not been set yet.
