### ISSUE TITLE
Cannot browse RDF data unit

### ISSUE THREAD

**Issue by tomas-knap** [mff-uk/odcs#1325]
Problem when trying to browse RDF data unit!

See it on ODCS, exec 1090, reproduce according to image: 

![screen shot 2014-03-14 at 10 31 19 am](https://f.cloud.github.com/assets/3014917/2419344/badbb02c-ab5b-11e3-938a-48f816bd409d.png)

2014-03-14 10:30:12,968 [http-bio-8080-exec-587] ERROR c.c.m.x.o.frontend.auxiliaries.RDFDataUnitHelper - DPU info is null!
2014-03-14 10:30:12,972 [http-bio-8080-exec-587] ERROR cz.cuni.mff.xrg.odcs.frontend.AppEntry - Uncaught exception
java.lang.RuntimeException: Unable to load RDFDataUnit.
    at cz.cuni.mff.xrg.odcs.frontend.container.rdf.RDFQuery.size(RDFQuery.java:72) ~[RDFQuery.class:na]
    at org.vaadin.addons.lazyquerycontainer.LazyQueryView.getQuery(LazyQueryView.java:407) ~[vaadin-lazyquerycontainer-2.0.9.jar:2.0.9]
    at org.vaadin.addons.lazyquerycontainer.LazyQueryView.getQuerySize(LazyQueryView.java:392) ~[vaadin-lazyquerycontainer-2.0.9.jar:2.0.9]
    at org.vaadin.addons.lazyquerycontainer.LazyQueryView.size(LazyQueryView.java:219) ~[vaadin-lazyquerycontainer-2.0.9.jar:2.0.9]
    at org.vaadin.addons.lazyquerycontainer.LazyQueryContainer.size(LazyQueryContainer.java:183) ~[vaadin-lazyquerycontainer-2.0.9.jar:2.0.9]
    at cz.cuni.mff.xrg.odcs.frontend.gui.components.RDFQueryView.runQuery(RDFQueryView.java:369) ~[RDFQueryView.class:na]
    at cz.cuni.mff.xrg.odcs.frontend.gui.components.RDFQueryView.access$000(RDFQueryView.java:57) ~[RDFQueryView.class:na]
    at cz.cuni.mff.xrg.odcs.frontend.gui.components.RDFQueryView$1.buttonClick(RDFQueryView.java:106) ~[RDFQueryView$1.class:na]
    at sun.reflect.GeneratedMethodAccessor982.invoke(Unknown Source) ~[na:na]
    at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43) ~[na:1.7.0_40]
    at java.lang.reflect.Method.invoke(Method.java:606) ~[na:1.7.0_40]
    at com.vaadin.event.ListenerMethod.receiveEvent(ListenerMethod.java:508) ~[vaadin-server-7.1.8.jar:7.1.8]
    at com.vaadin.event.EventRouter.fireEvent(EventRouter.java:167) ~[vaadin-server-7.1.8.jar:7.1.8]
    at com.vaadin.server.AbstractClientConnector.fireEvent(AbstractClientConnector.java:969) ~[vaadin-server-7.1.8.jar:7.1.8]
    at com.vaadin.ui.Button.fireClick(Button.java:368) ~[vaadin-server-7.1.8.jar:7.1.8]
    at com.vaadin.ui.Button$1.click(Button.java:57) ~[vaadin-server-7.1.8.jar:7.1.8]
    at sun.reflect.GeneratedMethodAccessor993.invoke(Unknown Source) ~[na:na]
    at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43) ~[na:1.7.0_40]
    at java.lang.reflect.Method.invoke(Method.java:606) ~[na:1.7.0_40]
    at com.vaadin.server.ServerRpcManager.applyInvocation(ServerRpcManager.java:168) ~[vaadin-server-7.1.8.jar:7.1.8]
    at com.vaadin.server.ServerRpcManager.applyInvocation(ServerRpcManager.java:118) ~[vaadin-server-7.1.8.jar:7.1.8]
    at com.vaadin.server.communication.ServerRpcHandler.handleBurst(ServerRpcHandler.java:207) [vaadin-server-7.1.8.jar:7.1.8]
    at com.vaadin.server.communication.ServerRpcHandler.handleRpc(ServerRpcHandler.java:111) [vaadin-server-7.1.8.jar:7.1.8]
    at com.vaadin.server.communication.UidlRequestHandler.synchronizedHandleRequest(UidlRequestHandler.java:91) [vaadin-server-7.1.8.jar:7.1.8]
    at com.vaadin.server.SynchronizedRequestHandler.handleRequest(SynchronizedRequestHandler.java:37) [vaadin-server-7.1.8.jar:7.1.8]
    at com.vaadin.server.VaadinService.handleRequest(VaadinService.java:1371) [vaadin-server-7.1.8.jar:7.1.8]
    at com.vaadin.server.VaadinServlet.service(VaadinServlet.java:238) [vaadin-server-7.1.8.jar:7.1.8]
    at cz.cuni.mff.xrg.odcs.frontend.ODCSApplicationServlet.service(ODCSApplicationServlet.java:74) [ODCSApplicationServlet.class:na]
    at javax.servlet.http.HttpServlet.service(HttpServlet.java:728) [servlet-api.jar:na]
    at org.apache.catalina.core.ApplicationFilterChain.internalDoFilter(ApplicationFilterChain.java:305) [catalina.jar:7.0.33]
    at org.apache.catalina.core.ApplicationFilterChain.doFilter(ApplicationFilterChain.java:210) [catalina.jar:7.0.33]
    at org.apache.catalina.core.StandardWrapperValve.invoke(StandardWrapperValve.java:222) [catalina.jar:7.0.33]
    at org.apache.catalina.core.StandardContextValve.invoke(StandardContextValve.java:123) [catalina.jar:7.0.33]
    at org.apache.catalina.authenticator.AuthenticatorBase.invoke(AuthenticatorBase.java:472) [catalina.jar:7.0.33]
    at org.apache.catalina.core.StandardHostValve.invoke(StandardHostValve.java:171) [catalina.jar:7.0.33]
    at org.apache.catalina.valves.ErrorReportValve.invoke(ErrorReportValve.java:99) [catalina.jar:7.0.33]
    at org.apache.catalina.valves.AccessLogValve.invoke(AccessLogValve.java:931) [catalina.jar:7.0.33]
    at org.apache.catalina.core.StandardEngineValve.invoke(StandardEngineValve.java:118) [catalina.jar:7.0.33]
    at org.apache.catalina.connector.CoyoteAdapter.service(CoyoteAdapter.java:407) [catalina.jar:7.0.33]
    at org.apache.coyote.http11.AbstractHttp11Processor.process(AbstractHttp11Processor.java:1004) [tomcat-coyote.jar:7.0.33]
    at org.apache.coyote.AbstractProtocol$AbstractConnectionHandler.process(AbstractProtocol.java:589) [tomcat-coyote.jar:7.0.33]
    at org.apache.tomcat.util.net.JIoEndpoint$SocketProcessor.run(JIoEndpoint.java:310) [tomcat-coyote.jar:7.0.33]
    at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1145) [na:1.7.0_40]
    at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:615) [na:1.7.0_40]
    at java.lang.Thread.run(Thread.java:724) [na:1.7.0_40]
2014-03-14 10:30:14,590 [http-bio-8080-exec-605] DEBUG org.eclipse.persistence.logging.sql - 2014-03-14 10:30:14.589--ServerSession(1990490715)--Connection(1562381142)--SELECT MAX(t_last_change) FROM exec_pipeline

**Comment by tomas-knap** [comment]
I tried once again during the same session and it did not work. Then I tried to reload app, open the exec monitor again, open the detail and it was working properly

**Comment by skodapetr** [comment]
Can be cause by some cache? We may examine logs for mode info.
Better null pointer (invalid DPU info) handling is also a possibility here.

**Comment by ghost** [comment]
probably gone
