### ISSUE TITLE
 show log exception

### ISSUE THREAD

**Issue by kukharm** [mff-uk/odcs#138]
I get an exception after pushing the button "show log" in execution monitor

Jul 18, 2013 11:14:07 AM com.vaadin.server.DefaultErrorHandler doDefault
SEVERE: 
com.vaadin.server.ServerRpcManager$RpcInvocationException: Unable to invoke method click in com.vaadin.shared.ui.button.ButtonServerRpc
    at com.vaadin.server.ServerRpcManager.applyInvocation(ServerRpcManager.java:170)
    at com.vaadin.server.ServerRpcManager.applyInvocation(ServerRpcManager.java:118)
    at com.vaadin.server.communication.ServerRpcHandler.handleBurst(ServerRpcHandler.java:214)
    at com.vaadin.server.communication.ServerRpcHandler.handleRpc(ServerRpcHandler.java:111)
    at com.vaadin.server.communication.PushHandler$2.run(PushHandler.java:158)
    at com.vaadin.server.communication.PushHandler.callWithUi(PushHandler.java:289)
    at com.vaadin.server.communication.PushHandler.onRequest(PushHandler.java:308)
    at org.atmosphere.cpr.AsynchronousProcessor.action(AsynchronousProcessor.java:259)
    at org.atmosphere.cpr.AsynchronousProcessor.suspended(AsynchronousProcessor.java:166)
    at org.atmosphere.container.TomcatWebSocketUtil.doService(TomcatWebSocketUtil.java:137)
    at org.atmosphere.container.Tomcat7AsyncSupportWithWebSocket.service(Tomcat7AsyncSupportWithWebSocket.java:59)
    at org.atmosphere.cpr.AtmosphereFramework.doCometSupport(AtmosphereFramework.java:1448)
    at org.atmosphere.websocket.DefaultWebSocketProcessor.dispatch(DefaultWebSocketProcessor.java:219)
    at org.atmosphere.websocket.DefaultWebSocketProcessor$2.run(DefaultWebSocketProcessor.java:183)
    at org.atmosphere.util.VoidExecutorService.execute(VoidExecutorService.java:101)
    at org.atmosphere.websocket.DefaultWebSocketProcessor.dispatch(DefaultWebSocketProcessor.java:178)
    at org.atmosphere.websocket.DefaultWebSocketProcessor.invokeWebSocketProtocol(DefaultWebSocketProcessor.java:167)
    at org.atmosphere.container.TomcatWebSocketHandler.onTextMessage(TomcatWebSocketHandler.java:92)
    at org.apache.catalina.websocket.MessageInbound.onTextData(MessageInbound.java:74)
    at org.apache.catalina.websocket.StreamInbound.doOnTextData(StreamInbound.java:186)
    at org.apache.catalina.websocket.StreamInbound.onData(StreamInbound.java:134)
    at org.apache.coyote.http11.upgrade.UpgradeProcessor.upgradeDispatch(UpgradeProcessor.java:83)
    at org.apache.coyote.AbstractProtocol$AbstractConnectionHandler.process(AbstractProtocol.java:587)
    at org.apache.tomcat.util.net.JIoEndpoint$SocketProcessor.run(JIoEndpoint.java:310)
    at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1110)
    at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:603)
    at java.lang.Thread.run(Thread.java:722)
Caused by: java.lang.reflect.InvocationTargetException
    at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
    at sun.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:57)
    at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
    at java.lang.reflect.Method.invoke(Method.java:601)
    at com.vaadin.server.ServerRpcManager.applyInvocation(ServerRpcManager.java:168)
    ... 26 more
Caused by: com.vaadin.event.ListenerMethod$MethodException: Invocation of method buttonClick in cz.cuni.xrg.intlib.frontend.gui.views.ExecutionMonitor failed.
    at com.vaadin.event.ListenerMethod.receiveEvent(ListenerMethod.java:528)
    at com.vaadin.event.EventRouter.fireEvent(EventRouter.java:167)
    at com.vaadin.server.AbstractClientConnector.fireEvent(AbstractClientConnector.java:968)
    at com.vaadin.ui.Button.fireClick(Button.java:368)
    at com.vaadin.ui.Button$1.click(Button.java:57)
    ... 31 more
Caused by: java.lang.NullPointerException
    at cz.cuni.xrg.intlib.frontend.gui.components.DebuggingView.fillContent(DebuggingView.java:155)
    at cz.cuni.xrg.intlib.frontend.gui.components.DebuggingView.buildMainLayout(DebuggingView.java:119)
    at cz.cuni.xrg.intlib.frontend.gui.components.DebuggingView.<init>(DebuggingView.java:69)
    at cz.cuni.xrg.intlib.frontend.gui.views.ExecutionMonitor.buildlogLayout(ExecutionMonitor.java:464)
    at cz.cuni.xrg.intlib.frontend.gui.views.ExecutionMonitor.buttonClick(ExecutionMonitor.java:585)
    at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
    at sun.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:57)
    at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
    at java.lang.reflect.Method.invoke(Method.java:601)
    at com.vaadin.event.ListenerMethod.receiveEvent(ListenerMethod.java:508)
    ... 35 more

**Comment by tomas-knap** [comment]
Bohuslav, please check that, Maria cannot also finish #37 thanks to that.

**Comment by bogo777** [comment]
Is this still actual? I cannot reproduce it. If it is, could you post step by step how you got it?

**Comment by kukharm** [comment]
I run DBpedia pipeline, then go to execution monitor and push Show log button. After that I get exception. Also i get exception if pipeline was debugged (after push Debug data button in execution monitor)
