### ISSUE TITLE
Delete pipeline exception

### ISSUE THREAD

**Issue by kukharm** [mff-uk/odcs#151]
I deleted pipeline (used for that method .delete(pipeline) from PipelineFacade) then I had exception in Execution monitor (monitor contained the records about that pipeline before delete).

Jul 19, 2013 5:31:57 PM com.vaadin.server.DefaultErrorHandler doDefault
SEVERE: 
javax.persistence.EntityNotFoundException: Unable to find cz.cuni.xrg.intlib.commons.app.dpu.DPUInstanceRecord with id 1
    at org.hibernate.ejb.Ejb3Configuration$Ejb3EntityNotFoundDelegate.handleEntityNotFound(Ejb3Configuration.java:154)
    at org.hibernate.event.internal.DefaultLoadEventListener.load(DefaultLoadEventListener.java:210)
    at org.hibernate.event.internal.DefaultLoadEventListener.proxyOrLoad(DefaultLoadEventListener.java:251)
    at org.hibernate.event.internal.DefaultLoadEventListener.onLoad(DefaultLoadEventListener.java:148)
    at org.hibernate.internal.SessionImpl.fireLoad(SessionImpl.java:954)
    at org.hibernate.internal.SessionImpl.internalLoad(SessionImpl.java:903)
    at org.hibernate.type.EntityType.resolveIdentifier(EntityType.java:610)
    at org.hibernate.type.EntityType.resolve(EntityType.java:438)
    at org.hibernate.type.EntityType.nullSafeGet(EntityType.java:234)
    at org.hibernate.persister.collection.AbstractCollectionPersister.readIndex(AbstractCollectionPersister.java:764)
    at org.hibernate.collection.internal.PersistentMap.readFrom(PersistentMap.java:277)
    at org.hibernate.loader.Loader.readCollectionElement(Loader.java:1196)
    at org.hibernate.loader.Loader.readCollectionElements(Loader.java:800)
    at org.hibernate.loader.Loader.getRowFromResultSet(Loader.java:651)
    at org.hibernate.loader.Loader.doQuery(Loader.java:856)
    at org.hibernate.loader.Loader.doQueryAndInitializeNonLazyCollections(Loader.java:289)
    at org.hibernate.loader.Loader.doQueryAndInitializeNonLazyCollections(Loader.java:259)
    at org.hibernate.loader.Loader.loadEntity(Loader.java:2058)
    at org.hibernate.loader.entity.AbstractEntityLoader.load(AbstractEntityLoader.java:82)
    at org.hibernate.loader.entity.AbstractEntityLoader.load(AbstractEntityLoader.java:72)
    at org.hibernate.persister.entity.AbstractEntityPersister.load(AbstractEntityPersister.java:3697)
    at org.hibernate.event.internal.DefaultLoadEventListener.loadFromDatasource(DefaultLoadEventListener.java:439)
    at org.hibernate.event.internal.DefaultLoadEventListener.doLoad(DefaultLoadEventListener.java:420)
    at org.hibernate.event.internal.DefaultLoadEventListener.load(DefaultLoadEventListener.java:204)
    at org.hibernate.event.internal.DefaultLoadEventListener.proxyOrLoad(DefaultLoadEventListener.java:251)
    at org.hibernate.event.internal.DefaultLoadEventListener.onLoad(DefaultLoadEventListener.java:148)
    at org.hibernate.internal.SessionImpl.fireLoad(SessionImpl.java:954)
    at org.hibernate.internal.SessionImpl.internalLoad(SessionImpl.java:903)
    at org.hibernate.type.EntityType.resolveIdentifier(EntityType.java:610)
    at org.hibernate.type.EntityType.resolve(EntityType.java:438)
    at org.hibernate.engine.internal.TwoPhaseLoad.initializeEntity(TwoPhaseLoad.java:150)
    at org.hibernate.loader.Loader.initializeEntitiesAndCollections(Loader.java:1006)
    at org.hibernate.loader.Loader.doQuery(Loader.java:883)
    at org.hibernate.loader.Loader.doQueryAndInitializeNonLazyCollections(Loader.java:289)
    at org.hibernate.loader.Loader.doList(Loader.java:2463)
    at org.hibernate.loader.Loader.doList(Loader.java:2449)
    at org.hibernate.loader.Loader.listIgnoreQueryCache(Loader.java:2279)
    at org.hibernate.loader.Loader.list(Loader.java:2274)
    at org.hibernate.loader.hql.QueryLoader.list(QueryLoader.java:470)
    at org.hibernate.hql.internal.ast.QueryTranslatorImpl.list(QueryTranslatorImpl.java:355)
    at org.hibernate.engine.query.spi.HQLQueryPlan.performList(HQLQueryPlan.java:196)
    at org.hibernate.internal.SessionImpl.list(SessionImpl.java:1115)
    at org.hibernate.internal.QueryImpl.list(QueryImpl.java:101)
    at org.hibernate.ejb.QueryImpl.getResultList(QueryImpl.java:252)
    at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
    at sun.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:57)
    at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
    at java.lang.reflect.Method.invoke(Method.java:601)
    at org.springframework.orm.jpa.SharedEntityManagerCreator$DeferredQueryInvocationHandler.invoke(SharedEntityManagerCreator.java:310)
    at $Proxy37.getResultList(Unknown Source)
    at cz.cuni.xrg.intlib.commons.app.pipeline.PipelineFacade.getAllExecutions(PipelineFacade.java:124)
    at cz.cuni.xrg.intlib.commons.app.pipeline.PipelineFacade$$FastClassByCGLIB$$13bb3988.invoke(<generated>)
    at net.sf.cglib.proxy.MethodProxy.invoke(MethodProxy.java:204)
    at org.springframework.aop.framework.Cglib2AopProxy$DynamicAdvisedInterceptor.intercept(Cglib2AopProxy.java:618)
    at cz.cuni.xrg.intlib.commons.app.pipeline.PipelineFacade$$EnhancerByCGLIB$$26c16731.getAllExecutions(<generated>)
    at cz.cuni.xrg.intlib.frontend.gui.views.ExecutionMonitor.buildMainLayout(ExecutionMonitor.java:135)
    at cz.cuni.xrg.intlib.frontend.gui.views.ExecutionMonitor.enter(ExecutionMonitor.java:378)
    at com.vaadin.navigator.Navigator.navigateTo(Navigator.java:571)
    at com.vaadin.navigator.Navigator.navigateTo(Navigator.java:526)
    at cz.cuni.xrg.intlib.frontend.gui.MenuLayout$NavigateToCommand.menuSelected(MenuLayout.java:53)
    at com.vaadin.ui.MenuBar.changeVariables(MenuBar.java:178)
    at com.vaadin.server.communication.ServerRpcHandler.changeVariables(ServerRpcHandler.java:403)
    at com.vaadin.server.communication.ServerRpcHandler.handleBurst(ServerRpcHandler.java:228)
    at com.vaadin.server.communication.ServerRpcHandler.handleRpc(ServerRpcHandler.java:111)
    at com.vaadin.server.communication.PushHandler$2.run(PushHandler.java:158)
    at com.vaadin.server.communication.PushHandler.callWithUi(PushHandler.java:289)
    at com.vaadin.server.communication.PushHandler.onRequest(PushHandler.java:308)
    at org.atmosphere.cpr.AsynchronousProcessor.action(AsynchronousProcessor.java:259)
    at org.atmosphere.cpr.AsynchronousProcessor.suspended(AsynchronousProcessor.java:166)
    at org.atmosphere.container.TomcatWebSocketUtil.doService(TomcatWebSocketUtil.java:137)
    at org.atmosphere.container.Tomcat7AsyncSupportWithWebSocket.service(Tomcat7AsyncSupportWithWebSocket.java:59)
    at org.atmosphere.cpr.AtmosphereFramework.doCometSupport(AtmosphereFramework.java:1448)
    at org.atmosphere.websocket.DefaultWebSocketProcessor.dispatch(DefaultWebSocketProcessor.java:219)
    at org.atmosphere.websocket.DefaultWebSocketProcessor$2.run(DefaultWebSocketProcessor.java:183)
    at org.atmosphere.util.VoidExecutorService.execute(VoidExecutorService.java:101)
    at org.atmosphere.websocket.DefaultWebSocketProcessor.dispatch(DefaultWebSocketProcessor.java:178)
    at org.atmosphere.websocket.DefaultWebSocketProcessor.invokeWebSocketProtocol(DefaultWebSocketProcessor.java:167)
    at org.atmosphere.container.TomcatWebSocketHandler.onTextMessage(TomcatWebSocketHandler.java:92)
    at org.apache.catalina.websocket.MessageInbound.onTextData(MessageInbound.java:74)
    at org.apache.catalina.websocket.StreamInbound.doOnTextData(StreamInbound.java:186)
    at org.apache.catalina.websocket.StreamInbound.onData(StreamInbound.java:134)
    at org.apache.coyote.http11.upgrade.UpgradeProcessor.upgradeDispatch(UpgradeProcessor.java:83)
    at org.apache.coyote.AbstractProtocol$AbstractConnectionHandler.process(AbstractProtocol.java:587)
    at org.apache.tomcat.util.net.JIoEndpoint$SocketProcessor.run(JIoEndpoint.java:310)
    at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1110)
    at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:603)
    at java.lang.Thread.run(Thread.java:722)

**Comment by janvojt** [comment]
Resolved by commit 1fa68c4d in issue #152.

**Comment by kukharm** [comment]
If I delete pipeline witch have a scheduling rule, then after open Scheduler from the main menu i get exception

Jul 22, 2013 12:11:59 AM com.vaadin.server.DefaultErrorHandler doDefault
SEVERE: 
javax.persistence.EntityNotFoundException: Unable to find cz.cuni.xrg.intlib.commons.app.pipeline.Pipeline with id 1
    at org.hibernate.ejb.Ejb3Configuration$Ejb3EntityNotFoundDelegate.handleEntityNotFound(Ejb3Configuration.java:154)
    at org.hibernate.event.internal.DefaultLoadEventListener.load(DefaultLoadEventListener.java:210)
    at org.hibernate.event.internal.DefaultLoadEventListener.proxyOrLoad(DefaultLoadEventListener.java:251)
    at org.hibernate.event.internal.DefaultLoadEventListener.onLoad(DefaultLoadEventListener.java:148)
    at org.hibernate.internal.SessionImpl.fireLoad(SessionImpl.java:954)
    at org.hibernate.internal.SessionImpl.internalLoad(SessionImpl.java:903)
    at org.hibernate.type.EntityType.resolveIdentifier(EntityType.java:610)
    at org.hibernate.type.EntityType.resolve(EntityType.java:438)
    at org.hibernate.engine.internal.TwoPhaseLoad.initializeEntity(TwoPhaseLoad.java:150)
    at org.hibernate.loader.Loader.initializeEntitiesAndCollections(Loader.java:1006)
    at org.hibernate.loader.Loader.doQuery(Loader.java:883)
    at org.hibernate.loader.Loader.doQueryAndInitializeNonLazyCollections(Loader.java:289)
    at org.hibernate.loader.Loader.doList(Loader.java:2463)
    at org.hibernate.loader.Loader.doList(Loader.java:2449)
    at org.hibernate.loader.Loader.listIgnoreQueryCache(Loader.java:2279)
    at org.hibernate.loader.Loader.list(Loader.java:2274)
    at org.hibernate.loader.hql.QueryLoader.list(QueryLoader.java:470)
    at org.hibernate.hql.internal.ast.QueryTranslatorImpl.list(QueryTranslatorImpl.java:355)
    at org.hibernate.engine.query.spi.HQLQueryPlan.performList(HQLQueryPlan.java:196)
    at org.hibernate.internal.SessionImpl.list(SessionImpl.java:1115)
    at org.hibernate.internal.QueryImpl.list(QueryImpl.java:101)
    at org.hibernate.ejb.QueryImpl.getResultList(QueryImpl.java:252)
    at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
    at sun.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:57)
    at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
    at java.lang.reflect.Method.invoke(Method.java:601)
    at org.springframework.orm.jpa.SharedEntityManagerCreator$DeferredQueryInvocationHandler.invoke(SharedEntityManagerCreator.java:310)
    at $Proxy37.getResultList(Unknown Source)
    at cz.cuni.xrg.intlib.commons.app.scheduling.ScheduleFacade.getAllSchedules(ScheduleFacade.java:37)
    at cz.cuni.xrg.intlib.commons.app.scheduling.ScheduleFacade$$FastClassByCGLIB$$ed01a88b.invoke(<generated>)
    at net.sf.cglib.proxy.MethodProxy.invoke(MethodProxy.java:204)
    at org.springframework.aop.framework.Cglib2AopProxy$DynamicAdvisedInterceptor.intercept(Cglib2AopProxy.java:618)
    at cz.cuni.xrg.intlib.commons.app.scheduling.ScheduleFacade$$EnhancerByCGLIB$$ccfc4c0.getAllSchedules(<generated>)
    at cz.cuni.xrg.intlib.frontend.gui.views.Scheduler.buildMainLayout(Scheduler.java:125)
    at cz.cuni.xrg.intlib.frontend.gui.views.Scheduler.enter(Scheduler.java:277)
    at com.vaadin.navigator.Navigator.navigateTo(Navigator.java:571)
    at com.vaadin.navigator.Navigator.navigateTo(Navigator.java:526)
    at cz.cuni.xrg.intlib.frontend.gui.MenuLayout$NavigateToCommand.menuSelected(MenuLayout.java:53)
    at com.vaadin.ui.MenuBar.changeVariables(MenuBar.java:178)
    at com.vaadin.server.communication.ServerRpcHandler.changeVariables(ServerRpcHandler.java:403)
    at com.vaadin.server.communication.ServerRpcHandler.handleBurst(ServerRpcHandler.java:228)
    at com.vaadin.server.communication.ServerRpcHandler.handleRpc(ServerRpcHandler.java:111)
    at com.vaadin.server.communication.PushHandler$2.run(PushHandler.java:158)
    at com.vaadin.server.communication.PushHandler.callWithUi(PushHandler.java:289)
    at com.vaadin.server.communication.PushHandler.onRequest(PushHandler.java:308)
    at org.atmosphere.cpr.AsynchronousProcessor.action(AsynchronousProcessor.java:259)
    at org.atmosphere.cpr.AsynchronousProcessor.suspended(AsynchronousProcessor.java:166)
    at org.atmosphere.container.TomcatWebSocketUtil.doService(TomcatWebSocketUtil.java:137)
    at org.atmosphere.container.Tomcat7AsyncSupportWithWebSocket.service(Tomcat7AsyncSupportWithWebSocket.java:59)
    at org.atmosphere.cpr.AtmosphereFramework.doCometSupport(AtmosphereFramework.java:1448)
    at org.atmosphere.websocket.DefaultWebSocketProcessor.dispatch(DefaultWebSocketProcessor.java:219)
    at org.atmosphere.websocket.DefaultWebSocketProcessor$2.run(DefaultWebSocketProcessor.java:183)
    at org.atmosphere.util.VoidExecutorService.execute(VoidExecutorService.java:101)
    at org.atmosphere.websocket.DefaultWebSocketProcessor.dispatch(DefaultWebSocketProcessor.java:178)
    at org.atmosphere.websocket.DefaultWebSocketProcessor.invokeWebSocketProtocol(DefaultWebSocketProcessor.java:167)
    at org.atmosphere.container.TomcatWebSocketHandler.onTextMessage(TomcatWebSocketHandler.java:92)
    at org.apache.catalina.websocket.MessageInbound.onTextData(MessageInbound.java:74)
    at org.apache.catalina.websocket.StreamInbound.doOnTextData(StreamInbound.java:186)
    at org.apache.catalina.websocket.StreamInbound.onData(StreamInbound.java:134)
    at org.apache.coyote.http11.upgrade.UpgradeProcessor.upgradeDispatch(UpgradeProcessor.java:83)
    at org.apache.coyote.AbstractProtocol$AbstractConnectionHandler.process(AbstractProtocol.java:587)
    at org.apache.tomcat.util.net.JIoEndpoint$SocketProcessor.run(JIoEndpoint.java:310)
    at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1110)
    at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:603)
    at java.lang.Thread.run(Thread.java:722)
