### ISSUE TITLE
DPU templates not working

### ISSUE THREAD

**Issue by jakubklimek** [mff-uk/odcs#166]
With backend working, frontend after clicking DPU templates throws this:

javax.persistence.PersistenceException: org.hibernate.exception.SQLGrammarException: Could not open connection
 at org.hibernate.ejb.AbstractEntityManagerImpl.convert(AbstractEntityManagerImpl.java:1361)
 at org.hibernate.ejb.AbstractEntityManagerImpl.convert(AbstractEntityManagerImpl.java:1289)
 at org.hibernate.ejb.QueryImpl.getResultList(QueryImpl.java:261)
 at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
 at sun.reflect.NativeMethodAccessorImpl.invoke(Unknown Source)
 at sun.reflect.DelegatingMethodAccessorImpl.invoke(Unknown Source)
 at java.lang.reflect.Method.invoke(Unknown Source)
 at org.springframework.orm.jpa.SharedEntityManagerCreator$DeferredQueryInvocationHandler.invoke(SharedEntityManagerCreator.java:310)
 at com.sun.proxy.$Proxy38.getResultList(Unknown Source)
 at cz.cuni.xrg.intlib.commons.app.dpu.DPUFacade.getAllTemplates(DPUFacade.java:56)
 at cz.cuni.xrg.intlib.commons.app.dpu.DPUFacade$$FastClassByCGLIB$$94c8b7be.invoke(<generated>)
 at net.sf.cglib.proxy.MethodProxy.invoke(MethodProxy.java:204)
 at org.springframework.aop.framework.Cglib2AopProxy$DynamicAdvisedInterceptor.intercept(Cglib2AopProxy.java:618)
 at cz.cuni.xrg.intlib.commons.app.dpu.DPUFacade$$EnhancerByCGLIB$$1cde0104_4.getAllTemplates(<generated>)
 at cz.cuni.xrg.intlib.frontend.gui.components.DPUTree.fillTree(DPUTree.java:136)
 at cz.cuni.xrg.intlib.frontend.gui.components.DPUTree.buildMainLayout(DPUTree.java:91)
 at cz.cuni.xrg.intlib.frontend.gui.components.DPUTree.<init>(DPUTree.java:32)
 at cz.cuni.xrg.intlib.frontend.gui.views.DPU.buildDpuLayout(DPU.java:220)
 at cz.cuni.xrg.intlib.frontend.gui.views.DPU.buildMainLayout(DPU.java:187)
 at cz.cuni.xrg.intlib.frontend.gui.views.DPU.enter(DPU.java:717)
 at com.vaadin.navigator.Navigator.navigateTo(Navigator.java:571)
 at com.vaadin.navigator.Navigator.navigateTo(Navigator.java:526)
 at cz.cuni.xrg.intlib.frontend.gui.MenuLayout$NavigateToCommand.menuSelected(MenuLayout.java:53)
 at com.vaadin.ui.MenuBar.changeVariables(MenuBar.java:178)
 at com.vaadin.server.communication.ServerRpcHandler.changeVariables(ServerRpcHandler.java:403)
 at com.vaadin.server.communication.ServerRpcHandler.handleBurst(ServerRpcHandler.java:228)
 at com.vaadin.server.communication.ServerRpcHandler.handleRpc(ServerRpcHandler.java:111)
 at com.vaadin.server.communication.PushHandler$2.run(PushHandler.java:158)
 at com.vaadin.server.communication.PushHandler.callWithUi(PushHandler.java:289)
 at com.vaadin.server.communication.PushHandler.onRequest(PushHandler.java:308)
 at org.atmosphere.cpr.AsynchronousProcessor.action(AsynchronousProcessor.java:259)
 at org.atmosphere.cpr.AsynchronousProcessor.suspended(AsynchronousProcessor.java:166)
 at org.atmosphere.container.TomcatWebSocketUtil.doService(TomcatWebSocketUtil.java:137)
 at org.atmosphere.container.Tomcat7AsyncSupportWithWebSocket.service(Tomcat7AsyncSupportWithWebSocket.java:59)
 at org.atmosphere.cpr.AtmosphereFramework.doCometSupport(AtmosphereFramework.java:1448)
 at org.atmosphere.websocket.DefaultWebSocketProcessor.dispatch(DefaultWebSocketProcessor.java:219)
 at org.atmosphere.websocket.DefaultWebSocketProcessor$2.run(DefaultWebSocketProcessor.java:183)
 at org.atmosphere.util.VoidExecutorService.execute(VoidExecutorService.java:101)
 at org.atmosphere.websocket.DefaultWebSocketProcessor.dispatch(DefaultWebSocketProcessor.java:178)
 at org.atmosphere.websocket.DefaultWebSocketProcessor.invokeWebSocketProtocol(DefaultWebSocketProcessor.java:167)
 at org.atmosphere.container.TomcatWebSocketHandler.onTextMessage(TomcatWebSocketHandler.java:92)
 at org.apache.catalina.websocket.MessageInbound.onTextData(MessageInbound.java:74)
 at org.apache.catalina.websocket.StreamInbound.doOnTextData(StreamInbound.java:186)
 at org.apache.catalina.websocket.StreamInbound.onData(StreamInbound.java:134)
 at org.apache.coyote.http11.upgrade.UpgradeProcessor.upgradeDispatch(UpgradeProcessor.java:83)
 at org.apache.coyote.AbstractProtocol$AbstractConnectionHandler.process(AbstractProtocol.java:587)
 at org.apache.tomcat.util.net.JIoEndpoint$SocketProcessor.run(JIoEndpoint.java:310)
 at java.util.concurrent.ThreadPoolExecutor.runWorker(Unknown Source)
 at java.util.concurrent.ThreadPoolExecutor$Worker.run(Unknown Source)
 at java.lang.Thread.run(Unknown Source)
 Caused by: org.hibernate.exception.SQLGrammarException: Could not open connection
 at org.hibernate.exception.internal.SQLStateConversionDelegate.convert(SQLStateConversionDelegate.java:122)
 at org.hibernate.exception.internal.StandardSQLExceptionConverter.convert(StandardSQLExceptionConverter.java:47)
 at org.hibernate.engine.jdbc.spi.SqlExceptionHelper.convert(SqlExceptionHelper.java:125)
 at org.hibernate.engine.jdbc.spi.SqlExceptionHelper.convert(SqlExceptionHelper.java:110)
 at org.hibernate.engine.jdbc.internal.LogicalConnectionImpl.obtainConnection(LogicalConnectionImpl.java:304)
 at org.hibernate.engine.jdbc.internal.LogicalConnectionImpl.getConnection(LogicalConnectionImpl.java:169)
 at org.hibernate.engine.jdbc.internal.proxy.ConnectionProxyHandler.extractPhysicalConnection(ConnectionProxyHandler.java:82)
 at org.hibernate.engine.jdbc.internal.proxy.ConnectionProxyHandler.continueInvocation(ConnectionProxyHandler.java:138)
 at org.hibernate.engine.jdbc.internal.proxy.AbstractProxyHandler.invoke(AbstractProxyHandler.java:81)
 at com.sun.proxy.$Proxy39.prepareStatement(Unknown Source)
 at org.hibernate.engine.jdbc.internal.StatementPreparerImpl$5.doPrepare(StatementPreparerImpl.java:147)
 at org.hibernate.engine.jdbc.internal.StatementPreparerImpl$StatementPreparationTemplate.prepareStatement(StatementPreparerImpl.java:166)
 at org.hibernate.engine.jdbc.internal.StatementPreparerImpl.prepareQueryStatement(StatementPreparerImpl.java:145)
 at org.hibernate.loader.Loader.prepareQueryStatement(Loader.java:1739)
 at org.hibernate.loader.Loader.doQuery(Loader.java:828)
 at org.hibernate.loader.Loader.doQueryAndInitializeNonLazyCollections(Loader.java:289)
 at org.hibernate.loader.Loader.doList(Loader.java:2463)
 at org.hibernate.loader.Loader.doList(Loader.java:2449)
 at org.hibernate.loader.Loader.listIgnoreQueryCache(Loader.java:2279)
 at org.hibernate.loader.Loader.list(Loader.java:2274)
 at org.hibernate.loader.hql.QueryLoader.list(QueryLoader.java:470)
 at org.hibernate.hql.internal.ast.QueryTranslatorImpl.list(QueryTranslatorImpl.java:355)
 at org.hibernate.engine.query.spi.HQLQueryPlan.performList(HQLQueryPlan.java:196)
 at org.hibernate.internal.SessionImpl.list(SessionImpl.java:1115)
 at org.hibernate.internal.QueryImpl.list(QueryImpl.java:101)
 at org.hibernate.ejb.QueryImpl.getResultList(QueryImpl.java:252)
 ... 47 more
 Caused by: virtuoso.jdbc4.VirtuosoException: Connection failed: Connection refused: connect
 at virtuoso.jdbc4.VirtuosoConnection.connect(Unknown Source)
 at virtuoso.jdbc4.VirtuosoConnection.connect(Unknown Source)
 at virtuoso.jdbc4.VirtuosoConnection.<init>(Unknown Source)
 at virtuoso.jdbc4.Driver.connect(Unknown Source)
 at java.sql.DriverManager.getConnection(Unknown Source)
 at java.sql.DriverManager.getConnection(Unknown Source)
 at org.springframework.jdbc.datasource.DriverManagerDataSource.getConnectionFromDriverManager(DriverManagerDataSource.java:173)
 at org.springframework.jdbc.datasource.DriverManagerDataSource.getConnectionFromDriver(DriverManagerDataSource.java:164)
 at org.springframework.jdbc.datasource.AbstractDriverBasedDataSource.getConnectionFromDriver(AbstractDriverBasedDataSource.java:149)
 at org.springframework.jdbc.datasource.AbstractDriverBasedDataSource.getConnection(AbstractDriverBasedDataSource.java:119)
 at org.hibernate.ejb.connection.InjectedDataSourceConnectionProvider.getConnection(InjectedDataSourceConnectionProvider.java:67)
 at org.hibernate.internal.AbstractSessionImpl$NonContextualJdbcConnectionAccess.obtainConnection(AbstractSessionImpl.java:276)
 at org.hibernate.engine.jdbc.internal.LogicalConnectionImpl.obtainConnection(LogicalConnectionImpl.java:297)
 ... 68 more

**Comment by jakubklimek** [comment]
Probably caused by merging of settings from persistence.xml? How does frontend now know where the database is? Surely Tomcat cannot access some users home to get the settings...

**Comment by tomas-knap** [comment]
In other words, you have remove db settings from commons-app, but after that the only config for database connection is in config.properties. But the question is, how can Tomcat, running under a different user typically, access the config.properties file?

**Comment by janvojt** [comment]
You are correct. All DB connections use the same config. The point was to have a single central configuration.

Configuration needs to be in path `$HOME/.intlib/config.properties` of the user running the application. To be more precise, the path is obtained from system environment with `System.getProperty("user.home")`.

Obvious consequence is, that if tomcat is running on a different user than backend, both users need the config in their home for both applications to work correctly. I myself run it this way and I use a symlink, so that I do not have to configure each application separately.

After a discussion, we concluded the best place to put external configuration in, is the user's home. It is quite independent of platform used as it is not very likely anyone comes across OS with no home dir for user these days. I agree this is not very user friendly, however we plan on creating an installator in the final release, which will take care of this.

**Comment by jakubklimek** [comment]
I don’t think this is a good idea for the frontend part. Tomcat usually runs as tomcat on linux (SYSTEM) on windows and there is no reason to put anything into home of these users (they don’t have to have a homedir). I would rather duplicate the setting and put it in web.xml of the frontend WAR, which is I think a more standard way of configuring servlets.

**Comment by janvojt** [comment]
It is true that servlet configuration is usually in WAR file. However we wanted to make both applications configurable without rebuilding WAR/JAR files. I don't really care which way it is done, you can discuss this with @tomas-knap and I can change it then.
