### ISSUE TITLE
Issue when running backend with Virtuoso 7

### ISSUE THREAD

**Issue by jakubklimek** [mff-uk/odcs#214]
Clean ODCS, run dbpedia pipeline, exception is thrown. Possibly due to Virtuoso 7 and maybe old jdbc driver??

```
2013-08-06 10:38:36,233 [Thread-4] TRACE o.h.type.descriptor.sql.BasicBinder - binding parameter [1] as [BIGINT] - 1
2013-08-06 10:38:36,236 [Thread-4] DEBUG org.hibernate.loader.Loader - Result set row: 0
2013-08-06 10:38:36,237 [Thread-4] TRACE o.h.t.descriptor.sql.BasicExtractor - Found [null] as column [id5_0_]
2013-08-06 10:38:36,254 [Thread-4] DEBUG o.h.e.jdbc.spi.SqlExceptionHelper - Bad column number : 0 not in 1<n<17 [n/a]
virtuoso.jdbc4.VirtuosoException: Bad column number : 0 not in 1<n<17
    at virtuoso.jdbc4.VirtuosoRow.getLong(Unknown Source) ~[jdbc-driver-4.jar:na]
    at virtuoso.jdbc4.VirtuosoResultSet.getLong(Unknown Source) ~[jdbc-driver-4.jar:na]
    at virtuoso.jdbc4.VirtuosoResultSet.getLong(Unknown Source) ~[jdbc-driver-4.jar:na]
    at sun.reflect.GeneratedMethodAccessor5.invoke(Unknown Source) ~[na:na]
    at sun.reflect.DelegatingMethodAccessorImpl.invoke(Unknown Source) ~[na:1.7.0_25]
    at java.lang.reflect.Method.invoke(Unknown Source) ~[na:1.7.0_25]
    at org.hibernate.engine.jdbc.internal.proxy.AbstractResultSetProxyHandler.continueInvocation(AbstractResultSetProxyHandler.java:104) ~[hibernate-core-4.0.1.Final.jar:4.0.1.Final]
    at org.hibernate.engine.jdbc.internal.proxy.AbstractProxyHandler.invoke(AbstractProxyHandler.java:81) ~[hibernate-core-4.0.1.Final.jar:4.0.1.Final]
    at com.sun.proxy.$Proxy37.getLong(Unknown Source) ~[na:na]
    at org.hibernate.type.descriptor.sql.BigIntTypeDescriptor$2.doExtract(BigIntTypeDescriptor.java:66) [hibernate-core-4.0.1.Final.jar:4.0.1.Final]
    at org.hibernate.type.descriptor.sql.BasicExtractor.extract(BasicExtractor.java:65) [hibernate-core-4.0.1.Final.jar:4.0.1.Final]
    at org.hibernate.type.AbstractStandardBasicType.nullSafeGet(AbstractStandardBasicType.java:269) [hibernate-core-4.0.1.Final.jar:4.0.1.Final]
    at org.hibernate.type.AbstractStandardBasicType.nullSafeGet(AbstractStandardBasicType.java:265) [hibernate-core-4.0.1.Final.jar:4.0.1.Final]
    at org.hibernate.type.AbstractStandardBasicType.nullSafeGet(AbstractStandardBasicType.java:238) [hibernate-core-4.0.1.Final.jar:4.0.1.Final]
    at org.hibernate.type.AbstractStandardBasicType.hydrate(AbstractStandardBasicType.java:357) [hibernate-core-4.0.1.Final.jar:4.0.1.Final]
    at org.hibernate.loader.Loader.extractKeysFromResultSet(Loader.java:702) [hibernate-core-4.0.1.Final.jar:4.0.1.Final]
    at org.hibernate.loader.Loader.getRowFromResultSet(Loader.java:635) [hibernate-core-4.0.1.Final.jar:4.0.1.Final]
    at org.hibernate.loader.Loader.doQuery(Loader.java:856) [hibernate-core-4.0.1.Final.jar:4.0.1.Final]
    at org.hibernate.loader.Loader.doQueryAndInitializeNonLazyCollections(Loader.java:289) [hibernate-core-4.0.1.Final.jar:4.0.1.Final]
    at org.hibernate.loader.Loader.doQueryAndInitializeNonLazyCollections(Loader.java:259) [hibernate-core-4.0.1.Final.jar:4.0.1.Final]
    at org.hibernate.loader.Loader.loadEntity(Loader.java:2058) [hibernate-core-4.0.1.Final.jar:4.0.1.Final]
    at org.hibernate.loader.entity.AbstractEntityLoader.load(AbstractEntityLoader.java:82) [hibernate-core-4.0.1.Final.jar:4.0.1.Final]
    at org.hibernate.loader.entity.AbstractEntityLoader.load(AbstractEntityLoader.java:72) [hibernate-core-4.0.1.Final.jar:4.0.1.Final]
    at org.hibernate.persister.entity.AbstractEntityPersister.load(AbstractEntityPersister.java:3697) [hibernate-core-4.0.1.Final.jar:4.0.1.Final]
    at org.hibernate.event.internal.DefaultLoadEventListener.loadFromDatasource(DefaultLoadEventListener.java:439) [hibernate-core-4.0.1.Final.jar:4.0.1.Final]
    at org.hibernate.event.internal.DefaultLoadEventListener.doLoad(DefaultLoadEventListener.java:420) [hibernate-core-4.0.1.Final.jar:4.0.1.Final]
    at org.hibernate.event.internal.DefaultLoadEventListener.load(DefaultLoadEventListener.java:204) [hibernate-core-4.0.1.Final.jar:4.0.1.Final]
    at org.hibernate.event.internal.DefaultLoadEventListener.proxyOrLoad(DefaultLoadEventListener.java:251) [hibernate-core-4.0.1.Final.jar:4.0.1.Final]
    at org.hibernate.event.internal.DefaultLoadEventListener.onLoad(DefaultLoadEventListener.java:148) [hibernate-core-4.0.1.Final.jar:4.0.1.Final]
    at org.hibernate.internal.SessionImpl.fireLoad(SessionImpl.java:954) [hibernate-core-4.0.1.Final.jar:4.0.1.Final]
    at org.hibernate.internal.SessionImpl.get(SessionImpl.java:870) [hibernate-core-4.0.1.Final.jar:4.0.1.Final]
    at org.hibernate.event.internal.DefaultMergeEventListener.entityIsDetached(DefaultMergeEventListener.java:460) [hibernate-core-4.0.1.Final.jar:4.0.1.Final]
    at org.hibernate.event.internal.DefaultMergeEventListener.onMerge(DefaultMergeEventListener.java:256) [hibernate-core-4.0.1.Final.jar:4.0.1.Final]
    at org.hibernate.event.internal.DefaultMergeEventListener.onMerge(DefaultMergeEventListener.java:86) [hibernate-core-4.0.1.Final.jar:4.0.1.Final]
    at org.hibernate.internal.SessionImpl.fireMerge(SessionImpl.java:781) [hibernate-core-4.0.1.Final.jar:4.0.1.Final]
    at org.hibernate.internal.SessionImpl.merge(SessionImpl.java:766) [hibernate-core-4.0.1.Final.jar:4.0.1.Final]
    at org.hibernate.internal.SessionImpl.merge(SessionImpl.java:770) [hibernate-core-4.0.1.Final.jar:4.0.1.Final]
    at org.hibernate.ejb.AbstractEntityManagerImpl.merge(AbstractEntityManagerImpl.java:867) [hibernate-entitymanager-4.0.1.Final.jar:4.0.1.Final]
    at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method) ~[na:1.7.0_25]
    at sun.reflect.NativeMethodAccessorImpl.invoke(Unknown Source) ~[na:1.7.0_25]
    at sun.reflect.DelegatingMethodAccessorImpl.invoke(Unknown Source) ~[na:1.7.0_25]
    at java.lang.reflect.Method.invoke(Unknown Source) ~[na:1.7.0_25]
    at org.springframework.orm.jpa.SharedEntityManagerCreator$SharedEntityManagerInvocationHandler.invoke(SharedEntityManagerCreator.java:240) [spring-orm-3.1.2.RELEASE.jar:3.1.2.RELEASE]
    at com.sun.proxy.$Proxy31.merge(Unknown Source) [na:na]
    at cz.cuni.xrg.intlib.commons.app.pipeline.PipelineFacade.save(PipelineFacade.java:173) [classes/:na]
    at cz.cuni.xrg.intlib.commons.app.pipeline.PipelineFacade$$FastClassByCGLIB$$13bb3988.invoke(<generated>) [cglib-3.0.jar:na]
    at net.sf.cglib.proxy.MethodProxy.invoke(MethodProxy.java:204) [cglib-3.0.jar:na]
    at org.springframework.aop.framework.Cglib2AopProxy$CglibMethodInvocation.invokeJoinpoint(Cglib2AopProxy.java:689) [spring-aop-3.1.2.RELEASE.jar:3.1.2.RELEASE]
    at org.springframework.aop.framework.ReflectiveMethodInvocation.proceed(ReflectiveMethodInvocation.java:150) [spring-aop-3.1.2.RELEASE.jar:3.1.2.RELEASE]
    at org.springframework.transaction.interceptor.TransactionInterceptor.invoke(TransactionInterceptor.java:110) [spring-tx-3.1.2.RELEASE.jar:3.1.2.RELEASE]
    at org.springframework.aop.framework.ReflectiveMethodInvocation.proceed(ReflectiveMethodInvocation.java:172) [spring-aop-3.1.2.RELEASE.jar:3.1.2.RELEASE]
    at org.springframework.aop.framework.Cglib2AopProxy$DynamicAdvisedInterceptor.intercept(Cglib2AopProxy.java:622) [spring-aop-3.1.2.RELEASE.jar:3.1.2.RELEASE]
    at cz.cuni.xrg.intlib.commons.app.pipeline.PipelineFacade$$EnhancerByCGLIB$$6ba19244.save(<generated>) [cglib-3.0.jar:na]
    at cz.cuni.xrg.intlib.backend.execution.Engine.run(Engine.java:112) [classes/:na]
    at cz.cuni.xrg.intlib.backend.execution.Engine.checkDatabase(Engine.java:129) [classes/:na]
    at cz.cuni.xrg.intlib.backend.execution.Engine.onEvent(Engine.java:194) [classes/:na]
    at cz.cuni.xrg.intlib.backend.execution.Engine.onApplicationEvent(Engine.java:212) [classes/:na]
    at cz.cuni.xrg.intlib.backend.execution.Engine.onApplicationEvent(Engine.java:1) [classes/:na]
    at org.springframework.context.event.SimpleApplicationEventMulticaster.multicastEvent(SimpleApplicationEventMulticaster.java:97) [spring-context-3.1.2.RELEASE.jar:3.1.2.RELEASE]
    at org.springframework.context.support.AbstractApplicationContext.publishEvent(AbstractApplicationContext.java:324) [spring-context-3.1.2.RELEASE.jar:3.1.2.RELEASE]
    at cz.cuni.xrg.intlib.backend.Heartbeat.run(Heartbeat.java:42) [classes/:na]
    at java.lang.Thread.run(Unknown Source) [na:1.7.0_25]
2013-08-06 10:38:36,256 [Thread-4] WARN  o.h.e.jdbc.spi.SqlExceptionHelper - SQL Error: -4, SQLState: 42000
2013-08-06 10:38:36,256 [Thread-4] ERROR o.h.e.jdbc.spi.SqlExceptionHelper - Bad column number : 0 not in 1<n<17
2013-08-06 10:38:36,265 [Thread-4] INFO  o.h.e.i.DefaultLoadEventListener - HHH000327: Error performing load command : org.hibernate.exception.SQLGrammarException: Bad column number : 0 not in 1<n<17
2013-08-06 10:38:36,268 [Thread-4] DEBUG o.h.ejb.AbstractEntityManagerImpl - Mark transaction for rollback
2013-08-06 10:38:36,268 [Thread-4] DEBUG o.s.orm.jpa.JpaTransactionManager - Initiating transaction rollback
2013-08-06 10:38:36,269 [Thread-4] DEBUG o.s.orm.jpa.JpaTransactionManager - Rolling back JPA transaction on EntityManager [org.hibernate.ejb.EntityManagerImpl@272a335c]
2013-08-06 10:38:36,269 [Thread-4] DEBUG o.h.e.t.spi.AbstractTransactionImpl - rolling back
Exception in thread "Thread-4" javax.persistence.PersistenceException: org.hibernate.exception.SQLGrammarException: Bad column number : 0 not in 1<n<17
    at org.hibernate.ejb.AbstractEntityManagerImpl.convert(AbstractEntityManagerImpl.java:1361)
    at org.hibernate.ejb.AbstractEntityManagerImpl.convert(AbstractEntityManagerImpl.java:1289)
    at org.hibernate.ejb.AbstractEntityManagerImpl.convert(AbstractEntityManagerImpl.java:1295)
    at org.hibernate.ejb.AbstractEntityManagerImpl.merge(AbstractEntityManagerImpl.java:876)
    at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
    at sun.reflect.NativeMethodAccessorImpl.invoke(Unknown Source)
    at sun.reflect.DelegatingMethodAccessorImpl.invoke(Unknown Source)
    at java.lang.reflect.Method.invoke(Unknown Source)
    at org.springframework.orm.jpa.SharedEntityManagerCreator$SharedEntityManagerInvocationHandler.invoke(SharedEntityManagerCreator.java:240)
    at com.sun.proxy.$Proxy31.merge(Unknown Source)
    at cz.cuni.xrg.intlib.commons.app.pipeline.PipelineFacade.save(PipelineFacade.java:173)
    at cz.cuni.xrg.intlib.commons.app.pipeline.PipelineFacade$$FastClassByCGLIB$$13bb3988.invoke(<generated>)
    at net.sf.cglib.proxy.MethodProxy.invoke(MethodProxy.java:204)
    at org.springframework.aop.framework.Cglib2AopProxy$CglibMethodInvocation.invokeJoinpoint(Cglib2AopProxy.java:689)
    at org.springframework.aop.framework.ReflectiveMethodInvocation.proceed(ReflectiveMethodInvocation.java:150)
    at org.springframework.transaction.interceptor.TransactionInterceptor.invoke(TransactionInterceptor.java:110)
    at org.springframework.aop.framework.ReflectiveMethodInvocation.proceed(ReflectiveMethodInvocation.java:172)
    at org.springframework.aop.framework.Cglib2AopProxy$DynamicAdvisedInterceptor.intercept(Cglib2AopProxy.java:622)
    at cz.cuni.xrg.intlib.commons.app.pipeline.PipelineFacade$$EnhancerByCGLIB$$6ba19244.save(<generated>)
    at cz.cuni.xrg.intlib.backend.execution.Engine.run(Engine.java:112)
    at cz.cuni.xrg.intlib.backend.execution.Engine.checkDatabase(Engine.java:129)
    at cz.cuni.xrg.intlib.backend.execution.Engine.onEvent(Engine.java:194)
    at cz.cuni.xrg.intlib.backend.execution.Engine.onApplicationEvent(Engine.java:212)
    at cz.cuni.xrg.intlib.backend.execution.Engine.onApplicationEvent(Engine.java:1)
    at org.springframework.context.event.SimpleApplicationEventMulticaster.multicastEvent(SimpleApplicationEventMulticaster.java:97)
    at org.springframework.context.support.AbstractApplicationContext.publishEvent(AbstractApplicationContext.java:324)
    at cz.cuni.xrg.intlib.backend.Heartbeat.run(Heartbeat.java:42)
    at java.lang.Thread.run(Unknown Source)
Caused by: org.hibernate.exception.SQLGrammarException: Bad column number : 0 not in 1<n<17
    at org.hibernate.exception.internal.SQLStateConversionDelegate.convert(SQLStateConversionDelegate.java:122)
    at org.hibernate.exception.internal.StandardSQLExceptionConverter.convert(StandardSQLExceptionConverter.java:47)
    at org.hibernate.engine.jdbc.spi.SqlExceptionHelper.convert(SqlExceptionHelper.java:125)
    at org.hibernate.engine.jdbc.spi.SqlExceptionHelper.convert(SqlExceptionHelper.java:110)
    at org.hibernate.engine.jdbc.internal.proxy.AbstractResultSetProxyHandler.continueInvocation(AbstractResultSetProxyHandler.java:108)
    at org.hibernate.engine.jdbc.internal.proxy.AbstractProxyHandler.invoke(AbstractProxyHandler.java:81)
    at com.sun.proxy.$Proxy37.getLong(Unknown Source)
    at org.hibernate.type.descriptor.sql.BigIntTypeDescriptor$2.doExtract(BigIntTypeDescriptor.java:66)
    at org.hibernate.type.descriptor.sql.BasicExtractor.extract(BasicExtractor.java:65)
    at org.hibernate.type.AbstractStandardBasicType.nullSafeGet(AbstractStandardBasicType.java:269)
    at org.hibernate.type.AbstractStandardBasicType.nullSafeGet(AbstractStandardBasicType.java:265)
    at org.hibernate.type.AbstractStandardBasicType.nullSafeGet(AbstractStandardBasicType.java:238)
    at org.hibernate.type.AbstractStandardBasicType.hydrate(AbstractStandardBasicType.java:357)
    at org.hibernate.loader.Loader.extractKeysFromResultSet(Loader.java:702)
    at org.hibernate.loader.Loader.getRowFromResultSet(Loader.java:635)
    at org.hibernate.loader.Loader.doQuery(Loader.java:856)
    at org.hibernate.loader.Loader.doQueryAndInitializeNonLazyCollections(Loader.java:289)
    at org.hibernate.loader.Loader.doQueryAndInitializeNonLazyCollections(Loader.java:259)
    at org.hibernate.loader.Loader.loadEntity(Loader.java:2058)
    at org.hibernate.loader.entity.AbstractEntityLoader.load(AbstractEntityLoader.java:82)
    at org.hibernate.loader.entity.AbstractEntityLoader.load(AbstractEntityLoader.java:72)
    at org.hibernate.persister.entity.AbstractEntityPersister.load(AbstractEntityPersister.java:3697)
    at org.hibernate.event.internal.DefaultLoadEventListener.loadFromDatasource(DefaultLoadEventListener.java:439)
    at org.hibernate.event.internal.DefaultLoadEventListener.doLoad(DefaultLoadEventListener.java:420)
    at org.hibernate.event.internal.DefaultLoadEventListener.load(DefaultLoadEventListener.java:204)
    at org.hibernate.event.internal.DefaultLoadEventListener.proxyOrLoad(DefaultLoadEventListener.java:251)
    at org.hibernate.event.internal.DefaultLoadEventListener.onLoad(DefaultLoadEventListener.java:148)
    at org.hibernate.internal.SessionImpl.fireLoad(SessionImpl.java:954)
    at org.hibernate.internal.SessionImpl.get(SessionImpl.java:870)
    at org.hibernate.event.internal.DefaultMergeEventListener.entityIsDetached(DefaultMergeEventListener.java:460)
    at org.hibernate.event.internal.DefaultMergeEventListener.onMerge(DefaultMergeEventListener.java:256)
    at org.hibernate.event.internal.DefaultMergeEventListener.onMerge(DefaultMergeEventListener.java:86)
    at org.hibernate.internal.SessionImpl.fireMerge(SessionImpl.java:781)
    at org.hibernate.internal.SessionImpl.merge(SessionImpl.java:766)
    at org.hibernate.internal.SessionImpl.merge(SessionImpl.java:770)
    at org.hibernate.ejb.AbstractEntityManagerImpl.merge(AbstractEntityManagerImpl.java:867)
    ... 24 more
Caused by: virtuoso.jdbc4.VirtuosoException: Bad column number : 0 not in 1<n<17
    at virtuoso.jdbc4.VirtuosoRow.getLong(Unknown Source)
    at virtuoso.jdbc4.VirtuosoResultSet.getLong(Unknown Source)
    at virtuoso.jdbc4.VirtuosoResultSet.getLong(Unknown Source)
    at sun.reflect.GeneratedMethodAccessor5.invoke(Unknown Source)
    at sun.reflect.DelegatingMethodAccessorImpl.invoke(Unknown Source)
    at java.lang.reflect.Method.invoke(Unknown Source)
    at org.hibernate.engine.jdbc.internal.proxy.AbstractResultSetProxyHandler.continueInvocation(AbstractResultSetProxyHandler.java:104)
    ... 55 more
2013-08-06 10:38:36,273 [Thread-4] DEBUG o.h.e.t.i.jdbc.JdbcTransaction - rolled JDBC Connection
2013-08-06 10:38:36,273 [Thread-4] DEBUG o.h.e.t.i.jdbc.JdbcTransaction - re-enabling autocommit
2013-08-06 10:38:36,276 [Thread-4] DEBUG o.s.orm.jpa.JpaTransactionManager - Closing JPA EntityManager [org.hibernate.ejb.EntityManagerImpl@272a335c] after transaction
2013-08-06 10:38:36,276 [Thread-4] DEBUG o.s.o.jpa.EntityManagerFactoryUtils - Closing JPA EntityManager
2013-08-06 10:38:36,276 [Thread-4] DEBUG o.h.e.j.i.LogicalConnectionImpl - Releasing JDBC connection
2013-08-06 10:38:36,277 [Thread-4] DEBUG o.h.e.j.i.LogicalConnectionImpl - Released JDBC connection
2013-08-06 10:38:36,277 [Thread-4] DEBUG o.h.e.j.i.p.ConnectionProxyHandler - HHH000163: Logical connection releasing its physical connection
```

**Comment by janvojt** [comment]
I tested this week with a new JDBC driver and did not encounter this issue. I am closing.
