### ISSUE TITLE
Problems when clicking run/debug on PipelineList

### ISSUE THREAD

**Issue by tomas-knap** [mff-uk/odcs#234]
For exception shown, see below. In case of corrections, please put them firstly to release 0.3

Steps to reproduce: 
http://odcs.xrg.cz:8080/etl-manager/#!PipelineList
Try to run/debug pipeline. 

Backend is stopped but that does not matter, the error occurs before connection to backend is needed. 

Exception: 

```
com.vaadin.server.ServerRpcManager$RpcInvocationException: Unable to invoke method click in com.vaadin.shared.ui.button.ButtonServerRpc
 at com.vaadin.server.ServerRpcManager.applyInvocation(ServerRpcManager.java:170)
 at com.vaadin.server.ServerRpcManager.applyInvocation(ServerRpcManager.java:118)
 at com.vaadin.server.communication.ServerRpcHandler.handleBurst(ServerRpcHandler.java:214)
 at com.vaadin.server.communication.ServerRpcHandler.handleRpc(ServerRpcHandler.java:111)
 at com.vaadin.server.communication.PushHandler$2.run(PushHandler.java:158)
 at com.vaadin.server.communication.PushHandler.callWithUi(PushHandler.java:289)
 at com.vaadin.server.communication.PushHandler.onRequest(PushHandler.java:308)
 at org.atmosphere.cpr.AsynchronousProcessor.action(AsynchronousProcessor.java:259)
 at org.atmosphere.cpr.AsynchronousProcessor.suspended(AsynchronousProcessor.java:166)
 at org.atmosphere.container.TomcatWebSocketUtil.doService(TomcatWebSocketUtil.java:137)
 at org.atmosphere.container.Tomcat7AsyncSupportWithWebSocket.service(Tomcat7AsyncSupportWithWebSocket.java:59)
 at org.atmosphere.cpr.AtmosphereFramework.doCometSupport(AtmosphereFramework.java:1448)
 at org.atmosphere.websocket.DefaultWebSocketProcessor.dispatch(DefaultWebSocketProcessor.java:219)
 at org.atmosphere.websocket.DefaultWebSocketProcessor$2.run(DefaultWebSocketProcessor.java:183)
 at org.atmosphere.util.VoidExecutorService.execute(VoidExecutorService.java:101)
 at org.atmosphere.websocket.DefaultWebSocketProcessor.dispatch(DefaultWebSocketProcessor.java:178)
 at org.atmosphere.websocket.DefaultWebSocketProcessor.invokeWebSocketProtocol(DefaultWebSocketProcessor.java:167)
 at org.atmosphere.container.TomcatWebSocketHandler.onTextMessage(TomcatWebSocketHandler.java:92)
 at org.apache.catalina.websocket.MessageInbound.onTextData(MessageInbound.java:74)
 at org.apache.catalina.websocket.StreamInbound.doOnTextData(StreamInbound.java:186)
 at org.apache.catalina.websocket.StreamInbound.onData(StreamInbound.java:134)
 at org.apache.coyote.http11.upgrade.UpgradeProcessor.upgradeDispatch(UpgradeProcessor.java:83)
 at org.apache.coyote.AbstractProtocol$AbstractConnectionHandler.process(AbstractProtocol.java:587)
 at org.apache.tomcat.util.net.JIoEndpoint$SocketProcessor.run(JIoEndpoint.java:310)
 at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1145)
 at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:615)
 at java.lang.Thread.run(Thread.java:722) Caused by: java.lang.reflect.InvocationTargetException
 at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
 at sun.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:57)
 at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
 at java.lang.reflect.Method.invoke(Method.java:601)
 at com.vaadin.server.ServerRpcManager.applyInvocation(ServerRpcManager.java:168) ... 26 more Caused by: com.vaadin.event.ListenerMethod$MethodException: Invocation of method buttonClick in cz.cuni.xrg.intlib.frontend.gui.views.PipelineList$actionColumnGenerator$4 failed.
 at com.vaadin.event.ListenerMethod.receiveEvent(ListenerMethod.java:528)
 at com.vaadin.event.EventRouter.fireEvent(EventRouter.java:167)
 at com.vaadin.server.AbstractClientConnector.fireEvent(AbstractClientConnector.java:968)
 at com.vaadin.ui.Button.fireClick(Button.java:368)
 at com.vaadin.ui.Button$1.click(Button.java:57) ... 31 more Caused by: javax.persistence.PersistenceException: org.hibernate.exception.ConstraintViolationException: SR133: Can not set NULL to not nullable column 'DB.INTLIB.EXEC_PIPELINE.context_id'
 at org.hibernate.ejb.AbstractEntityManagerImpl.convert(AbstractEntityManagerImpl.java:1361)
 at org.hibernate.ejb.AbstractEntityManagerImpl.convert(AbstractEntityManagerImpl.java:1289)
 at org.hibernate.ejb.AbstractEntityManagerImpl.convert(AbstractEntityManagerImpl.java:1295)
 at org.hibernate.ejb.AbstractEntityManagerImpl.persist(AbstractEntityManagerImpl.java:859)
 at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
 at sun.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:57)
 at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
 at java.lang.reflect.Method.invoke(Method.java:601)
 at org.springframework.orm.jpa.SharedEntityManagerCreator$SharedEntityManagerInvocationHandler.invoke(SharedEntityManagerCreator.java:240)
 at com.sun.proxy.$Proxy102.persist(Unknown Source)
 at cz.cuni.xrg.intlib.commons.app.pipeline.PipelineFacade.save(PipelineFacade.java:171)
 at cz.cuni.xrg.intlib.commons.app.pipeline.PipelineFacade$$FastClassByCGLIB$$13bb3988.invoke(<generated>)
 at net.sf.cglib.proxy.MethodProxy.invoke(MethodProxy.java:204)
 at org.springframework.aop.framework.Cglib2AopProxy$CglibMethodInvocation.invokeJoinpoint(Cglib2AopProxy.java:689)
 at org.springframework.aop.framework.ReflectiveMethodInvocation.proceed(ReflectiveMethodInvocation.java:150)
 at org.springframework.transaction.interceptor.TransactionInterceptor.invoke(TransactionInterceptor.java:110)
 at org.springframework.aop.framework.ReflectiveMethodInvocation.proceed(ReflectiveMethodInvocation.java:172)
 at org.springframework.aop.framework.Cglib2AopProxy$DynamicAdvisedInterceptor.intercept(Cglib2AopProxy.java:622)
 at cz.cuni.xrg.intlib.commons.app.pipeline.PipelineFacade$$EnhancerByCGLIB$$63301fd9.save(<generated>)
 at cz.cuni.xrg.intlib.frontend.gui.views.PipelineList.runPipeline(PipelineList.java:44)
 at cz.cuni.xrg.intlib.frontend.gui.views.PipelineList$actionColumnGenerator$4.buttonClick(PipelineList.java:138)
 at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
 at sun.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:57)
 at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
 at java.lang.reflect.Method.invoke(Method.java:601)
 at com.vaadin.event.ListenerMethod.receiveEvent(ListenerMethod.java:508) ... 35 more Caused by: org.hibernate.exception.ConstraintViolationException: SR133: Can not set NULL to not nullable column 'DB.INTLIB.EXEC_PIPELINE.context_id'
 at org.hibernate.exception.internal.SQLStateConversionDelegate.convert(SQLStateConversionDelegate.java:128)
 at org.hibernate.exception.internal.StandardSQLExceptionConverter.convert(StandardSQLExceptionConverter.java:47)
 at org.hibernate.engine.jdbc.spi.SqlExceptionHelper.convert(SqlExceptionHelper.java:125)
 at org.hibernate.engine.jdbc.spi.SqlExceptionHelper.convert(SqlExceptionHelper.java:110)
 at org.hibernate.engine.jdbc.internal.proxy.AbstractStatementProxyHandler.continueInvocation(AbstractStatementProxyHandler.java:129)
 at org.hibernate.engine.jdbc.internal.proxy.AbstractProxyHandler.invoke(AbstractProxyHandler.java:81)
 at com.sun.proxy.$Proxy106.executeUpdate(Unknown Source)
 at org.hibernate.id.insert.AbstractSelectingDelegate.performInsert(AbstractSelectingDelegate.java:58)
 at org.hibernate.persister.entity.AbstractEntityPersister.insert(AbstractEntityPersister.java:2757)
 at org.hibernate.persister.entity.AbstractEntityPersister.insert(AbstractEntityPersister.java:3268)
 at org.hibernate.action.internal.EntityIdentityInsertAction.execute(EntityIdentityInsertAction.java:78)
 at org.hibernate.engine.spi.ActionQueue.execute(ActionQueue.java:272)
 at org.hibernate.event.internal.AbstractSaveEventListener.performSaveOrReplicate(AbstractSaveEventListener.java:304)
 at org.hibernate.event.internal.AbstractSaveEventListener.performSave(AbstractSaveEventListener.java:195)
 at org.hibernate.event.internal.AbstractSaveEventListener.saveWithGeneratedId(AbstractSaveEventListener.java:128)
 at org.hibernate.ejb.event.EJB3PersistEventListener.saveWithGeneratedId(EJB3PersistEventListener.java:78)
 at org.hibernate.event.internal.DefaultPersistEventListener.entityIsTransient(DefaultPersistEventListener.java:208)
 at org.hibernate.event.internal.DefaultPersistEventListener.onPersist(DefaultPersistEventListener.java:151)
 at org.hibernate.event.internal.DefaultPersistEventListener.onPersist(DefaultPersistEventListener.java:78)
 at org.hibernate.internal.SessionImpl.firePersist(SessionImpl.java:725)
 at org.hibernate.internal.SessionImpl.persist(SessionImpl.java:701)
 at org.hibernate.internal.SessionImpl.persist(SessionImpl.java:705)
 at org.hibernate.ejb.AbstractEntityManagerImpl.persist(AbstractEntityManagerImpl.java:853) ... 57 more Caused by: virtuoso.jdbc4.VirtuosoException: SR133: Can not set NULL to not nullable column 'DB.INTLIB.EXEC_PIPELINE.context_id'
 at virtuoso.jdbc4.VirtuosoResultSet.process_result(Unknown Source)
 at virtuoso.jdbc4.VirtuosoResultSet.getMoreResults(Unknown Source)
 at virtuoso.jdbc4.VirtuosoPreparedStatement.sendQuery(Unknown Source)
 at virtuoso.jdbc4.VirtuosoPreparedStatement.executeUpdate(Unknown Source)
 at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
 at sun.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:57)
 at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
 at java.lang.reflect.Method.invoke(Method.java:601)
 at org.hibernate.engine.jdbc.internal.proxy.AbstractStatementProxyHandler.continueInvocation(AbstractStatementProxyHandler.java:122) ... 75 more
```

**Comment by bogo777** [comment]
I think that the problem originates in this commit: https://github.com/mff-uk/intlib/commit/80ae09a7d03bf1846ba157e9943024eb95162eec
so in release-0.3 it should be working ok. But I will try it and repair it there if needed.

**Comment by tomas-knap** [comment]
The problem must be also elsewhere, because it occurs in release 0.3 (I was building & deploying 0.3). Any further ideas?

**Comment by bogo777** [comment]
Do you have also release 0.3 database? I cannot reproduce this error on master and in release 0.3 database column context_id was nullable so this error should not occur.
https://github.com/mff-uk/intlib/blob/release-0.3.0/db/virtuoso/rdbms/schema.sql

**Comment by tomas-knap** [comment]
Yes, should be, I simply checkouted 0.3 and took the db/schema.sql available. But I will check. How can I easily find I have the wrong schema.sql?

**Comment by bogo777** [comment]
In 0.3 schema.sql should contain table definition for EXEC_PIPELINE:
CREATE TABLE "DB"."INTLIB"."EXEC_PIPELINE"
(
  "id" INTEGER IDENTITY,
  "status" INTEGER,
  "pipeline_id" INTEGER,
  "debug_mode" SMALLINT,
  "t_start" DATETIME,
  "t_end" DATETIME,
  "context_id" INTEGER,
  "schedule_id" INTEGER,
  "silent_mode" SMALLINT,
  "debugnode_id" INTEGER,
  PRIMARY KEY ("id")
);
In master it looks like this:
CREATE TABLE "DB"."INTLIB"."EXEC_PIPELINE"
(
  "id" INTEGER IDENTITY,
  "status" INTEGER,
  "pipeline_id" INTEGER,
  "debug_mode" SMALLINT,
  "t_start" DATETIME,
  "t_end" DATETIME,
  "context_id" INTEGER NOT NULL,
  "schedule_id" INTEGER,
  "silent_mode" SMALLINT,
  "debugnode_id" INTEGER,
  PRIMARY KEY ("id")
);

**Comment by tomas-knap** [comment]
It should be correct for 0.3, my exec_pipeline table def: 

create table "DB"."INTLIB"."EXEC_PIPELINE"
(
  "id" INTEGER IDENTITY,
  "status" INTEGER,
  "pipeline_id" INTEGER,
  "debug_mode" SMALLINT,
  "t_start" DATETIME,
  "t_end" DATETIME,
  "context_id" INTEGER,
  "schedule_id" INTEGER,
  "silent_mode" SMALLINT,
  "debugnode_id" INTEGER,
  PRIMARY KEY ("id")
);

ALTER TABLE "DB"."INTLIB"."EXEC_PIPELINE"
  ADD CONSTRAINT "EXEC_PIPELINE_PPL_MODEL_id_id" FOREIGN KEY ("pipeline_id")
    REFERENCES "DB"."INTLIB"."PPL_MODEL" ("id") ON UPDATE CASCADE ON DELETE CASCADE;

ALTER TABLE "DB"."INTLIB"."EXEC_PIPELINE"
  ADD CONSTRAINT "EXEC_PIPELINE_PPL_NODE_id_id" FOREIGN KEY ("debugnode_id")
    REFERENCES "DB"."INTLIB"."PPL_NODE" ("id") ON UPDATE CASCADE ON DELETE CASCADE;

ALTER TABLE "DB"."INTLIB"."EXEC_PIPELINE"
  ADD CONSTRAINT "EXEC_PIPELINE_EXEC_SCHEDULE_id_id" FOREIGN KEY ("schedule_id")
    REFERENCES "DB"."INTLIB"."EXEC_SCHEDULE" ("id") ON UPDATE CASCADE ON DELETE SET NULL;

ALTER TABLE "DB"."INTLIB"."EXEC_PIPELINE"
  ADD CONSTRAINT "EXEC_PIPELINE_EXEC_CONTEXT_PIPELINE_id_id" FOREIGN KEY ("context_id")
    REFERENCES "DB"."INTLIB"."EXEC_CONTEXT_PIPELINE" ("id") ON UPDATE CASCADE ON DELETE SET NULL;

**Comment by bogo777** [comment]
Did you have other version of database before? Maybe tables were dropped incorrectly and wrong version remained in database.

I cannot think of other reason for the exception which is causing this:
org.hibernate.exception.ConstraintViolationException: SR133: Can not set NULL to not nullable column 'DB.INTLIB.EXEC_PIPELINE.context_id' 

You can check table definition in database via Conductor:
Database -> DB.INTLIB.EXEC_PIPELINE -> Definition. context_id column should be nullable for version 0.3

If it is, maybe Honza can help, I am out of ideas.

**Comment by tomas-knap** [comment]
Bohuslav, thanks. 

Database for just created, no old records. 

Honzo, can you please check that?

**Comment by janvojt** [comment]
I cannot reproduce on release-0.3.0. Like Bohuslav said, the root cause is that column `context_id` changed to `NOT NULL`. I am changing milestone and lowering priority.

If you encountered this on branch release-0.3.0, you must have had old database schema. When changing releases on the same database, I suggest you run DROP statements from schema.sql in both releases manually and make sure they are successful or table does not exist. Then run the whole schema.sql script from the release you checked out into with git.

**Comment by janvojt** [comment]
I cannot reproduce this on master because of issue #239.

**Comment by tomas-knap** [comment]
Thanks, the manual rebuild of the intlib db structure worked
