### ISSUE TITLE
DPU upload vaadin error?

### ISSUE THREAD

**Issue by jakubklimek** [mff-uk/odcs#247]
When saving DPU (create DPU template), it uploads, but when clicking Save, a red exclamation mark appears with following exception:

com.vaadin.server.ServerRpcManager$RpcInvocationException: Unable to invoke method click in com.vaadin.shared.ui.button.ButtonServerRpc
 at com.vaadin.server.ServerRpcManager.applyInvocation(ServerRpcManager.java:170)
 at com.vaadin.server.ServerRpcManager.applyInvocation(ServerRpcManager.java:118)
 at com.vaadin.server.communication.ServerRpcHandler.handleBurst(ServerRpcHandler.java:214)
 at com.vaadin.server.communication.ServerRpcHandler.handleRpc(ServerRpcHandler.java:111)
 at com.vaadin.server.communication.PushHandler$2.run(PushHandler.java:158)
 at com.vaadin.server.communication.PushHandler.callWithUi(PushHandler.java:289)
 at com.vaadin.server.communication.PushHandler.onRequest(PushHandler.java:308)
 at org.atmosphere.cpr.AsynchronousProcessor.action(AsynchronousProcessor.java:259)
 at org.atmosphere.cpr.AsynchronousProcessor.suspended(AsynchronousProcessor.java:166)
 at org.atmosphere.container.TomcatWebSocketUtil.doService(TomcatWebSocketUtil.java:137)
 at org.atmosphere.container.Tomcat7AsyncSupportWithWebSocket.service(Tomcat7AsyncSupportWithWebSocket.java:59)
 at org.atmosphere.cpr.AtmosphereFramework.doCometSupport(AtmosphereFramework.java:1448)
 at org.atmosphere.websocket.DefaultWebSocketProcessor.dispatch(DefaultWebSocketProcessor.java:219)
 at org.atmosphere.websocket.DefaultWebSocketProcessor$2.run(DefaultWebSocketProcessor.java:183)
 at org.atmosphere.util.VoidExecutorService.execute(VoidExecutorService.java:101)
 at org.atmosphere.websocket.DefaultWebSocketProcessor.dispatch(DefaultWebSocketProcessor.java:178)
 at org.atmosphere.websocket.DefaultWebSocketProcessor.invokeWebSocketProtocol(DefaultWebSocketProcessor.java:167)
 at org.atmosphere.container.TomcatWebSocketHandler.onTextMessage(TomcatWebSocketHandler.java:92)
 at org.apache.catalina.websocket.MessageInbound.onTextData(MessageInbound.java:74)
 at org.apache.catalina.websocket.StreamInbound.doOnTextData(StreamInbound.java:186)
 at org.apache.catalina.websocket.StreamInbound.onData(StreamInbound.java:134)
 at org.apache.coyote.http11.upgrade.UpgradeProcessor.upgradeDispatch(UpgradeProcessor.java:83)
 at org.apache.coyote.AbstractProtocol$AbstractConnectionHandler.process(AbstractProtocol.java:587)
 at org.apache.tomcat.util.net.JIoEndpoint$SocketProcessor.run(JIoEndpoint.java:310)
 at java.util.concurrent.ThreadPoolExecutor.runWorker(Unknown Source)
 at java.util.concurrent.ThreadPoolExecutor$Worker.run(Unknown Source)
 at java.lang.Thread.run(Unknown Source)
 Caused by: java.lang.reflect.InvocationTargetException
 at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
 at sun.reflect.NativeMethodAccessorImpl.invoke(Unknown Source)
 at sun.reflect.DelegatingMethodAccessorImpl.invoke(Unknown Source)
 at java.lang.reflect.Method.invoke(Unknown Source)
 at com.vaadin.server.ServerRpcManager.applyInvocation(ServerRpcManager.java:168)
 ... 26 more
 Caused by: com.vaadin.event.ListenerMethod$MethodException: Invocation of method buttonClick in cz.cuni.xrg.intlib.frontend.gui.components.DPUCreate$6 failed.
 at com.vaadin.event.ListenerMethod.receiveEvent(ListenerMethod.java:528)
 at com.vaadin.event.EventRouter.fireEvent(EventRouter.java:167)
 at com.vaadin.server.AbstractClientConnector.fireEvent(AbstractClientConnector.java:968)
 at com.vaadin.ui.Button.fireClick(Button.java:368)
 at com.vaadin.ui.Button$1.click(Button.java:57)
 ... 31 more
 Caused by: java.lang.NoClassDefFoundError: cz/cuni/xrg/intlib/commons/configuration/Config
 at java.lang.Class.getDeclaredConstructors0(Native Method)
 at java.lang.Class.privateGetDeclaredConstructors(Unknown Source)
 at java.lang.Class.getConstructor0(Unknown Source)
 at java.lang.Class.newInstance(Unknown Source)
 at cz.cuni.xrg.intlib.commons.app.module.BundleContainer.loadClass(BundleContainer.java:67)
 at cz.cuni.xrg.intlib.commons.app.module.OSGIFramework.loadClass(OSGIFramework.java:216)
 at cz.cuni.xrg.intlib.commons.app.module.ModuleFacade.getObject(ModuleFacade.java:98)
 at cz.cuni.xrg.intlib.frontend.gui.components.DPUCreate$6.buttonClick(DPUCreate.java:376)
 at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
 at sun.reflect.NativeMethodAccessorImpl.invoke(Unknown Source)
 at sun.reflect.DelegatingMethodAccessorImpl.invoke(Unknown Source)
 at java.lang.reflect.Method.invoke(Unknown Source)
 at com.vaadin.event.ListenerMethod.receiveEvent(ListenerMethod.java:508)
 ... 35 more
 Caused by: java.lang.ClassNotFoundException: cz.cuni.xrg.intlib.commons.configuration.Config cannot be found by Extractor_psp_cz_metadata_0.0.1
 at org.eclipse.osgi.internal.loader.BundleLoader.findClassInternal(BundleLoader.java:455)
 at org.eclipse.osgi.internal.loader.BundleLoader.findClass(BundleLoader.java:421)
 at org.eclipse.osgi.internal.loader.BundleLoader.findClass(BundleLoader.java:412)
 at org.eclipse.osgi.internal.baseadaptor.DefaultClassLoader.loadClass(DefaultClassLoader.java:107)
 at java.lang.ClassLoader.loadClass(Unknown Source)
 ... 48 more

**Comment by tomas-knap** [comment]
This error is caused by wrong outdated implementation of the DPU PSP Extractor, get the latest version of PSP DPU from git

**Comment by tomas-knap** [comment]
Problem was solved, but such exception should be handled properly. Petre, could you please add that to Maria's dialog for DPU upload?

**Comment by skodapetr** [comment]
What exactly should I add?

Could you please provide me more information about the "outdated" implementation of DPU? Does it not have the interfaces against current commons?

For such case my commit should change the exception to classNotFound and this can solve the situations? Maybe if there still exist that jar file we can try it to upload in current version to find out what happen?

**Comment by jakubklimek** [comment]
It could be one of the older ones here: https://github.com/mff-uk/DPUs/commits/master/Extractor_psp_cz/target/Extractor_psp_cz_metadata-0.0.1.jar

**Comment by tomas-knap** [comment]
Petre, just please check that proper error message is used when trying to upload the Jar jakub has provided. I also created issue #251 for Bohuslav to provide better error messages in GUI - instead of "Unable to invoke method click" proper error should be mentioned

**Comment by tomas-knap** [comment]
Jakub, please test that

**Comment by jakubklimek** [comment]
Currently, I get another exception when uploading old jar:
![image](https://f.cloud.github.com/assets/718827/1087598/5ed019a0-161c-11e3-8697-fb319114c231.png)
