### ISSUE TITLE
DPU removal fails

### ISSUE THREAD

**Issue by janvojt** [mff-uk/odcs#25]
#### Exception is thrown when DPU removal is attempted from web interface.

Most likely caused by closed and reopened Hibernate session. In a new session Hibernate is not managing DPU object, and thus throws exception about detached entity upon attempted removal.
#### Possible solutions:
- catch exception, refetch object, and remove afterwards
  - quick woraround
- implement OpenSessionInView paradigm
  - more complex solution, would also resolve lazy initialization of objects

```
Caused by: java.lang.IllegalArgumentException: Removing a detached instance cz.cuni.xrg.intlib.commons.app.dpu.DPU#5
    at org.hibernate.ejb.event.EJB3DeleteEventListener.performDetachedEntityDeletionCheck(EJB3DeleteEventListener.java:67)
    at org.hibernate.event.internal.DefaultDeleteEventListener.onDelete(DefaultDeleteEventListener.java:107)
    at org.hibernate.event.internal.DefaultDeleteEventListener.onDelete(DefaultDeleteEventListener.java:74)
    at org.hibernate.internal.SessionImpl.fireDelete(SessionImpl.java:822)
    at org.hibernate.internal.SessionImpl.delete(SessionImpl.java:801)
    at org.hibernate.ejb.AbstractEntityManagerImpl.remove(AbstractEntityManagerImpl.java:883)
    at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
    at sun.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:57)
    at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
    at java.lang.reflect.Method.invoke(Method.java:601)
    at org.springframework.orm.jpa.SharedEntityManagerCreator$SharedEntityManagerInvocationHandler.invoke(SharedEntityManagerCreator.java:240)
    at $Proxy25.remove(Unknown Source)
    at cz.cuni.xrg.intlib.commons.app.dpu.DPUFacade.delete(DPUFacade.java:108)
    at cz.cuni.xrg.intlib.commons.app.dpu.DPUFacade$$FastClassByCGLIB$$94c8b7be.invoke(<generated>)
    at net.sf.cglib.proxy.MethodProxy.invoke(MethodProxy.java:204)
    at org.springframework.aop.framework.Cglib2AopProxy$CglibMethodInvocation.invokeJoinpoint(Cglib2AopProxy.java:689)
    at org.springframework.aop.framework.ReflectiveMethodInvocation.proceed(ReflectiveMethodInvocation.java:150)
    at org.springframework.transaction.interceptor.TransactionInterceptor.invoke(TransactionInterceptor.java:110)
    at org.springframework.aop.framework.ReflectiveMethodInvocation.proceed(ReflectiveMethodInvocation.java:172)
    at org.springframework.aop.framework.Cglib2AopProxy$DynamicAdvisedInterceptor.intercept(Cglib2AopProxy.java:622)
    at cz.cuni.xrg.intlib.commons.app.dpu.DPUFacade$$EnhancerByCGLIB$$dd1f63c5.delete(<generated>)
    at cz.cuni.xrg.intlib.frontend.gui.views.DPU$8.buttonClick(DPU.java:438)
    at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
    at sun.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:57)
    at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
    at java.lang.reflect.Method.invoke(Method.java:601)
    at com.vaadin.event.ListenerMethod.receiveEvent(ListenerMethod.java:508)
    ... 32 more
```

**Comment by janvojt** [comment]
Implemented the first proposed solution for now.
