### ISSUE TITLE
Pipeline Worker exception more descriptive

### ISSUE THREAD

**Issue by tomas-knap** [mff-uk/odcs#254]
I come across problem being described by the log below. However, engine shows in execution monitor/log   only "PipelineWorker exception", with no detail. Could you be please more descriptive?

![screen shot 2013-08-20 at 1 23 24 am](https://f.cloud.github.com/assets/3014917/990197/5db6b090-0926-11e3-9905-465a2ae40acf.png)

```
013-08-20 01:18:07,672 [pool-2-thread-2] WARN  o.h.e.jdbc.spi.SqlExceptionHelper - SQL Error: -8, SQLState: 40001
2013-08-20 01:18:07,672 [pool-2-thread-2] ERROR o.h.e.jdbc.spi.SqlExceptionHelper - SR172: Transaction deadlocked
Exception in thread "pool-2-thread-2" org.springframework.orm.jpa.JpaSystemException: org.hibernate.exception.LockAcquisitionException: SR172: Transaction deadlocked; nested exception is javax.persistence.PersistenceException: org.hibernate.exception.LockAcquisitionException: SR172: Transaction deadlocked
    at org.springframework.orm.jpa.EntityManagerFactoryUtils.convertJpaAccessExceptionIfPossible(EntityManagerFactoryUtils.java:326)
    at org.springframework.orm.jpa.DefaultJpaDialect.translateExceptionIfPossible(DefaultJpaDialect.java:120)
    at org.springframework.orm.jpa.JpaTransactionManager.doCommit(JpaTransactionManager.java:516)
    at org.springframework.transaction.support.AbstractPlatformTransactionManager.processCommit(AbstractPlatformTransactionManager.java:754)
    at org.springframework.transaction.support.AbstractPlatformTransactionManager.commit(AbstractPlatformTransactionManager.java:723)
    at org.springframework.transaction.interceptor.TransactionAspectSupport.commitTransactionAfterReturning(TransactionAspectSupport.java:394)
    at org.springframework.transaction.interceptor.TransactionInterceptor.invoke(TransactionInterceptor.java:120)
    at org.springframework.aop.framework.ReflectiveMethodInvocation.proceed(ReflectiveMethodInvocation.java:172)
    at org.springframework.aop.framework.Cglib2AopProxy$DynamicAdvisedInterceptor.intercept(Cglib2AopProxy.java:622)
    at cz.cuni.xrg.intlib.commons.app.pipeline.PipelineFacade$$EnhancerByCGLIB$$7a8ac3c9.save(<generated>)
    at cz.cuni.xrg.intlib.backend.execution.PipelineWorker.run(PipelineWorker.java:424)
    at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1145)
    at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:615)
    at java.lang.Thread.run(Thread.java:722)
Caused by: javax.persistence.PersistenceException: org.hibernate.exception.LockAcquisitionException: SR172: Transaction deadlocked
    at org.hibernate.ejb.AbstractEntityManagerImpl.convert(AbstractEntityManagerImpl.java:1361)
    at org.hibernate.ejb.AbstractEntityManagerImpl.convert(AbstractEntityManagerImpl.java:1289)
    at org.hibernate.ejb.TransactionImpl.commit(TransactionImpl.java:78)
    at org.springframework.orm.jpa.JpaTransactionManager.doCommit(JpaTransactionManager.java:512)
    ... 11 more
Caused by: org.hibernate.exception.LockAcquisitionException: SR172: Transaction deadlocked
    at org.hibernate.exception.internal.SQLStateConversionDelegate.convert(SQLStateConversionDelegate.java:139)
    at org.hibernate.exception.internal.StandardSQLExceptionConverter.convert(StandardSQLExceptionConverter.java:47)
    at org.hibernate.engine.jdbc.spi.SqlExceptionHelper.convert(SqlExceptionHelper.java:125)
    at org.hibernate.engine.jdbc.spi.SqlExceptionHelper.convert(SqlExceptionHelper.java:110)
    at org.hibernate.engine.jdbc.internal.proxy.AbstractStatementProxyHandler.continueInvocation(AbstractStatementProxyHandler.java:129)
    at org.hibernate.engine.jdbc.internal.proxy.AbstractProxyHandler.invoke(AbstractProxyHandler.java:81)
    at com.sun.proxy.$Proxy35.executeUpdate(Unknown Source)
    at org.hibernate.engine.jdbc.batch.internal.NonBatchingBatch.addToBatch(NonBatchingBatch.java:56)
    at org.hibernate.persister.entity.AbstractEntityPersister.update(AbstractEntityPersister.java:3006)
    at org.hibernate.persister.entity.AbstractEntityPersister.updateOrInsert(AbstractEntityPersister.java:2908)
    at org.hibernate.persister.entity.AbstractEntityPersister.update(AbstractEntityPersister.java:3237)
    at org.hibernate.action.internal.EntityUpdateAction.execute(EntityUpdateAction.java:113)
    at org.hibernate.engine.spi.ActionQueue.execute(ActionQueue.java:272)
    at org.hibernate.engine.spi.ActionQueue.executeActions(ActionQueue.java:264)
    at org.hibernate.engine.spi.ActionQueue.executeActions(ActionQueue.java:187)
    at org.hibernate.event.internal.AbstractFlushingEventListener.performExecutions(AbstractFlushingEventListener.java:326)
    at org.hibernate.event.internal.DefaultFlushEventListener.onFlush(DefaultFlushEventListener.java:52)
    at org.hibernate.internal.SessionImpl.flush(SessionImpl.java:1081)
    at org.hibernate.internal.SessionImpl.managedFlush(SessionImpl.java:315)
    at org.hibernate.engine.transaction.internal.jdbc.JdbcTransaction.beforeTransactionCommit(JdbcTransaction.java:101)
    at org.hibernate.engine.transaction.spi.AbstractTransactionImpl.commit(AbstractTransactionImpl.java:175)
    at org.hibernate.ejb.TransactionImpl.commit(TransactionImpl.java:73)
    ... 12 more
Caused by: virtuoso.jdbc4.VirtuosoException: SR172: Transaction deadlocked
    at virtuoso.jdbc4.VirtuosoResultSet.process_result(Unknown Source)
    at virtuoso.jdbc4.VirtuosoResultSet.getMoreResults(Unknown Source)
    at virtuoso.jdbc4.VirtuosoPreparedStatement.sendQuery(Unknown Source)
    at virtuoso.jdbc4.VirtuosoPreparedStatement.executeUpdate(Unknown Source)
    at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
    at sun.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:57)
    at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
    at java.lang.reflect.Method.invoke(Method.java:601)
    at org.hibernate.engine.jdbc.internal.proxy.AbstractStatementProxyHandler.continueInvocation(AbstractStatementProxyHandler.java:122)
    ... 29 more
```

**Comment by skodapetr** [comment]
Yes and no :) DPU Records are more descriptive ..

In fact the information is stored in database in table LOGGING_EVENT_EXCEPTION. Where I believe the complete stack can be found (I test this by query into DB).

So it's more for Honza, Bohuslav .. 
Honza: Should connect LOGGING_EVENT_EXCEPTION table to the LogMessage .. and maybe implement method that join the List<String> (from that table) into single String .. and merge with current message. 
Bohuslav: Should use new this new method.

or I can try to do this myself .. but this probably do not have sufficient priority? Please decide and reassign.

**Comment by janvojt** [comment]
I finished my part as explained by Petr. I am assigning Bohuslav to use relevant method `LogFacade.getLogException(LogMessage)` in frontend.
