### ISSUE TITLE
Pipeline running multiple times and seems scheduled at the same time

### ISSUE THREAD

**Issue by jakubklimek** [mff-uk/odcs#260]
In master d4c5426b6366d3117019e1921dedd67d1727c36a when I deploy the psp_cz DPU (which is now in the DPU project) and I create a simple pipeline where psp_cz extractor parses years 1918 to 1921 and passes data to RDF file loader and run it, it starts, and in a while it starts for a second time and so on and multiple instances run simultaneuously. At the same time the pipeline is seen as SCHEDULED in the execution monitor.

Maybe that is the issue? That the pipeline seems scheduled and is ran again because of this?

See the log:

<pre><code>2013-08-20 12:55:42,626 [pool-2-thread-1] DEBUG c.c.x.i.b.execution.PipelineWorker - Started
2013-08-20 12:55:43,780 [pool-2-thread-1] INFO  c.c.x.i.commons.extractor.Extract - Starting extraction. From year: 1918 To: 2013 Output: C:\Users\Kuba\Documents\GitHub\intlib\backend\working\9\working\dpu_8\tmp/sbirka.ttl
2013-08-20 12:55:46,564 [pool-2-thread-1] INFO  c.c.x.i.commons.extractor.Extract - Processed 1918 in 2740ms
Downloading URL (attempt 0): www.psp.cz/sqw/sbirka.sqw?cz=241&r=1919
Downloaded URL (attempt 0) in 202 ms : www.psp.cz/sqw/sbirka.sqw?cz=241&r=1919
Downloading URL (attempt 0): www.psp.cz/sqw/sbirka.sqw?cz=242&r=1919
Downloaded URL (attempt 0) in 157 ms : www.psp.cz/sqw/sbirka.sqw?cz=242&r=1919
Downloading URL (attempt 0): www.psp.cz/sqw/sbirka.sqw?cz=243&r=1919
Downloaded URL (attempt 0) in 157 ms : www.psp.cz/sqw/sbirka.sqw?cz=243&r=1919
Downloading URL (attempt 0): www.psp.cz/sqw/sbirka.sqw?cz=244&r=1919
Downloaded URL (attempt 0) in 186 ms : www.psp.cz/sqw/sbirka.sqw?cz=244&r=1919
Downloading URL (attempt 0): www.psp.cz/sqw/sbirka.sqw?cz=245&r=1919
Downloaded URL (attempt 0) in 152 ms : www.psp.cz/sqw/sbirka.sqw?cz=245&r=1919
Downloading URL (attempt 0): www.psp.cz/sqw/sbirka.sqw?cz=246&r=1919
Warning (retrying): HTTP error fetching URL
Downloading URL (attempt 1): www.psp.cz/sqw/sbirka.sqw?cz=246&r=1919
Downloaded URL (attempt 1) in 169 ms : www.psp.cz/sqw/sbirka.sqw?cz=246&r=1919
Downloading URL (attempt 0): www.psp.cz/sqw/sbirka.sqw?cz=247&r=1919
Downloaded URL (attempt 0) in 247 ms : www.psp.cz/sqw/sbirka.sqw?cz=247&r=1919
Downloading URL (attempt 0): www.psp.cz/sqw/sbirka.sqw?cz=248&r=1919
Downloaded URL (attempt 0) in 153 ms : www.psp.cz/sqw/sbirka.sqw?cz=248&r=1919
Downloading URL (attempt 0): www.psp.cz/sqw/sbirka.sqw?cz=249&r=1919
Downloaded URL (attempt 0) in 204 ms : www.psp.cz/sqw/sbirka.sqw?cz=249&r=1919
Downloading URL (attempt 0): www.psp.cz/sqw/sbirka.sqw?cz=250&r=1919
Downloaded URL (attempt 0) in 164 ms : www.psp.cz/sqw/sbirka.sqw?cz=250&r=1919
Downloading URL (attempt 0): www.psp.cz/sqw/sbirka.sqw?cz=251&r=1919
Warning (retrying): HTTP error fetching URL
2013-08-20 12:55:53,682 [pool-2-thread-2] DEBUG c.c.x.i.b.execution.PipelineWorker - Started
2013-08-20 12:55:54,275 [pool-2-thread-2] INFO  c.c.x.i.commons.extractor.Extract - Starting extraction. From year: 1918 To: 2013 Output: C:\Users\Kuba\Documents\GitHub\intlib\backend\working\9\working\dpu_8\tmp/sbirka.ttl
Downloading URL (attempt 1): www.psp.cz/sqw/sbirka.sqw?cz=251&r=1919
Downloaded URL (attempt 1) in 223 ms : www.psp.cz/sqw/sbirka.sqw?cz=251&r=1919
2013-08-20 12:55:55,762 [pool-2-thread-2] INFO  c.c.x.i.commons.extractor.Extract - Processed 1918 in 1411ms
Downloading URL (attempt 0): www.psp.cz/sqw/sbirka.sqw?cz=252&r=1919
Downloaded URL (attempt 0) in 146 ms : www.psp.cz/sqw/sbirka.sqw?cz=252&r=1919
Downloading URL (attempt 0): www.psp.cz/sqw/sbirka.sqw?cz=253&r=1919
Downloaded URL (attempt 0) in 136 ms : www.psp.cz/sqw/sbirka.sqw?cz=253&r=1919
Downloading URL (attempt 0): www.psp.cz/sqw/sbirka.sqw?cz=254&r=1919
Downloaded URL (attempt 0) in 63 ms : www.psp.cz/sqw/sbirka.sqw?cz=254&r=1919
Downloading URL (attempt 0): www.psp.cz/sqw/sbirka.sqw?cz=255&r=1919
Downloaded URL (attempt 0) in 144 ms : www.psp.cz/sqw/sbirka.sqw?cz=255&r=1919
Downloading URL (attempt 0): www.psp.cz/sqw/sbirka.sqw?cz=256&r=1919
Warning (retrying): HTTP error fetching URL
Downloading URL (attempt 1): www.psp.cz/sqw/sbirka.sqw?cz=256&r=1919
Downloading URL (attempt 0): www.psp.cz/sqw/sbirka.sqw?cz=256&r=1919
Downloaded URL (attempt 1) in 183 ms : www.psp.cz/sqw/sbirka.sqw?cz=256&r=1919
Downloading URL (attempt 0): www.psp.cz/sqw/sbirka.sqw?cz=257&r=1919
Downloaded URL (attempt 0) in 180 ms : www.psp.cz/sqw/sbirka.sqw?cz=256&r=1919
Downloading URL (attempt 0): www.psp.cz/sqw/sbirka.sqw?cz=257&r=1919</code></pre>

**Comment by skodapetr** [comment]
Are there also two record in frontned - execution monitor as well?

How did you start the execution? Using "run" button in pipeline list?

**Comment by jakubklimek** [comment]
No, there is only one record in execution manager and it says SCHEDULED.

Yes, I started it using "run" button in pipeline list.

**Comment by jakubklimek** [comment]
Actually, now I left it running for a while and it got started again for the third time. So it just keeps starting it again and again... really seems like an issue with the pipeline viewed as SCHEDULED even if it is actually running.

**Comment by skodapetr** [comment]
I have uploaded changes that should fix this. Please try it now.

**Comment by jakubklimek** [comment]
With this version the pipeline crashes in the DPU:

<pre><code>2013-08-20 13:45:29,651 [pool-2-thread-1] DEBUG c.c.x.i.b.execution.PipelineWorker - Started
2013-08-20 13:45:30,930 [pool-2-thread-1] ERROR c.c.x.i.b.execution.PipelineWorker - PipelineWorker: Exception
org.springframework.beans.factory.BeanCreationException: Error creating bean with name 'extractContext' defined in class path resource [backend-context.xml]: Instantiation of bean failed; nested exception is org.springframework.beans.BeanInstantiationException: Could not instantiate bean class [cz.cuni.xrg.intlib.backend.context.ExtendedExtractContext]: Constructor threw exception; nested exception is java.lang.NullPointerException
    at org.springframework.beans.factory.support.AbstractAutowireCapableBeanFactory.instantiateBean(AbstractAutowireCapableBeanFactory.java:997) ~[spring-beans-3.1.2.RELEASE.jar:3.1.2.RELEASE]
    at org.springframework.beans.factory.support.AbstractAutowireCapableBeanFactory.createBeanInstance(AbstractAutowireCapableBeanFactory.java:943) ~[spring-beans-3.1.2.RELEASE.jar:3.1.2.RELEASE]
    at org.springframework.beans.factory.support.AbstractAutowireCapableBeanFactory.doCreateBean(AbstractAutowireCapableBeanFactory.java:485) ~[spring-beans-3.1.2.RELEASE.jar:3.1.2.RELEASE]
    at org.springframework.beans.factory.support.AbstractAutowireCapableBeanFactory.createBean(AbstractAutowireCapableBeanFactory.java:456) ~[spring-beans-3.1.2.RELEASE.jar:3.1.2.RELEASE]
    at org.springframework.beans.factory.support.AbstractBeanFactory.doGetBean(AbstractBeanFactory.java:313) ~[spring-beans-3.1.2.RELEASE.jar:3.1.2.RELEASE]
    at org.springframework.beans.factory.support.AbstractBeanFactory.getBean(AbstractBeanFactory.java:197) ~[spring-beans-3.1.2.RELEASE.jar:3.1.2.RELEASE]
    at cz.cuni.xrg.intlib.backend.execution.PipelineWorker.getContextForNodeExtractor(PipelineWorker.java:500) ~[classes/:na]
    at cz.cuni.xrg.intlib.backend.execution.PipelineWorker.runNode(PipelineWorker.java:643) ~[classes/:na]
    at cz.cuni.xrg.intlib.backend.execution.PipelineWorker.run(PipelineWorker.java:339) ~[classes/:na]
    at java.util.concurrent.ThreadPoolExecutor.runWorker(Unknown Source) ~[na:1.7.0_25]
    at java.util.concurrent.ThreadPoolExecutor$Worker.run(Unknown Source) ~[na:1.7.0_25]
    at java.lang.Thread.run(Unknown Source) ~[na:1.7.0_25]
Caused by: org.springframework.beans.BeanInstantiationException: Could not instantiate bean class [cz.cuni.xrg.intlib.backend.context.ExtendedExtractContext]: Constructor threw exception; nested exception is java.lang.NullPointerException
    at org.springframework.beans.BeanUtils.instantiateClass(BeanUtils.java:162) ~[spring-beans-3.1.2.RELEASE.jar:3.1.2.RELEASE]
    at org.springframework.beans.factory.support.SimpleInstantiationStrategy.instantiate(SimpleInstantiationStrategy.java:76) ~[spring-beans-3.1.2.RELEASE.jar:3.1.2.RELEASE]
    at org.springframework.beans.factory.support.AbstractAutowireCapableBeanFactory.instantiateBean(AbstractAutowireCapableBeanFactory.java:990) ~[spring-beans-3.1.2.RELEASE.jar:3.1.2.RELEASE]
    ... 11 common frames omitted
Caused by: java.lang.NullPointerException: null
    at cz.cuni.xrg.intlib.backend.context.ExtendedContext.getGeneralWorkingDir(ExtendedContext.java:229) ~[classes/:na]
    at cz.cuni.xrg.intlib.backend.context.ExtendedExtractContext.<init>(ExtendedExtractContext.java:28) ~[classes/:na]
    at sun.reflect.NativeConstructorAccessorImpl.newInstance0(Native Method) ~[na:1.7.0_25]
    at sun.reflect.NativeConstructorAccessorImpl.newInstance(Unknown Source) ~[na:1.7.0_25]
    at sun.reflect.DelegatingConstructorAccessorImpl.newInstance(Unknown Source) ~[na:1.7.0_25]
    at java.lang.reflect.Constructor.newInstance(Unknown Source) ~[na:1.7.0_25]
    at org.springframework.beans.BeanUtils.instantiateClass(BeanUtils.java:147) ~[spring-beans-3.1.2.RELEASE.jar:3.1.2.RELEASE]
    ... 13 common frames omitted
2013-08-20 13:45:30,994 [pool-2-thread-1] DEBUG c.c.x.i.b.execution.PipelineWorker - Finished
2013-08-20 13:45:31,035 [pool-2-thread-1] DEBUG c.c.x.i.b.execution.PipelineWorker - Clean up
2013-08-20 13:45:31,086 [pool-2-thread-1] ERROR c.c.x.i.b.execution.PipelineWorker - execution failed</code></pre>

**Comment by jakubklimek** [comment]
Tested and working
