### ISSUE TITLE
Pipeline marked as successful even though there are exceptions

### ISSUE THREAD

**Issue by jakubklimek** [mff-uk/odcs#265]
I ran the buyer-profiles DPU extractor. It ran OK, produces two TTL files as usual. I upload them to RDFDataRepositories as two DataUnits. Here, I got the following exception:

<pre><code>2013-08-21 10:31:33,231 [pool-2-thread-1] INFO  c.c.x.i.rdf.impl.VirtuosoRDFRepo - Virtuoso repository successfully incicialized
2013-08-21 10:31:33,268 [pool-2-thread-1] INFO  c.c.x.i.rdf.impl.VirtuosoRDFRepo - Set new data graph - http://ex16_dpu11_du0
2013-08-21 10:31:33,309 [pool-2-thread-1] INFO  c.c.x.i.rdf.impl.VirtuosoRDFRepo - Virtuoso repository successfully incicialized
2013-08-21 10:31:33,345 [pool-2-thread-1] INFO  c.c.x.i.rdf.impl.VirtuosoRDFRepo - Set new data graph - http://ex16_dpu11_du1
2013-08-21 10:31:33,480 [pool-2-thread-1] DEBUG org.openrdf.rio.RDFParserRegistry - Registered service class org.openrdf.rio.binary.BinaryRDFParserFactory
2013-08-21 10:31:33,530 [pool-2-thread-1] DEBUG org.openrdf.rio.RDFParserRegistry - Registered service class org.openrdf.rio.n3.N3ParserFactory
2013-08-21 10:31:33,593 [pool-2-thread-1] DEBUG org.openrdf.rio.RDFParserRegistry - Registered service class org.openrdf.rio.ntriples.NTriplesParserFactory
2013-08-21 10:31:33,634 [pool-2-thread-1] DEBUG org.openrdf.rio.RDFParserRegistry - Registered service class org.openrdf.rio.rdfxml.RDFXMLParserFactory
2013-08-21 10:31:33,697 [pool-2-thread-1] DEBUG org.openrdf.rio.RDFParserRegistry - Registered service class org.openrdf.rio.trig.TriGParserFactory
2013-08-21 10:31:33,739 [pool-2-thread-1] DEBUG org.openrdf.rio.RDFParserRegistry - Registered service class org.openrdf.rio.trix.TriXParserFactory
2013-08-21 10:31:33,795 [pool-2-thread-1] DEBUG org.openrdf.rio.RDFParserRegistry - Registered service class org.openrdf.rio.turtle.TurtleParserFactory
2013-08-21 10:31:33,837 [pool-2-thread-1] DEBUG org.openrdf.rio.RDFParserRegistry - Registered service class org.openrdf.rio.nquads.NQuadsParserFactory
2013-08-21 10:35:29,004 [pool-2-thread-1] ERROR o.o.rio.helpers.ParseErrorLogger - [Rio fatal] Expected an RDF value here, found ' ' (81208, -1)
2013-08-21 10:35:29,070 [pool-2-thread-1] DEBUG c.c.x.i.rdf.impl.VirtuosoRDFRepo - Problem parsing triples
org.openrdf.repository.RepositoryException: Problem parsing triples
    at virtuoso.sesame2.driver.VirtuosoRepositoryConnection.add(VirtuosoRepositoryConnection.java:1031) ~[virtuoso-sesame-7.0.1.jar:na]
    at cz.cuni.xrg.intlib.rdf.impl.LocalRDFRepo.addInputStreamToRepository(LocalRDFRepo.java:599) [classes/:na]
    at cz.cuni.xrg.intlib.rdf.impl.LocalRDFRepo.addFileToRepository(LocalRDFRepo.java:624) [classes/:na]
    at cz.cuni.xrg.intlib.rdf.impl.LocalRDFRepo.extractFromFile(LocalRDFRepo.java:502) [classes/:na]
    at cz.cuni.xrg.intlib.rdf.impl.LocalRDFRepo.extractFromLocalTurtleFile(LocalRDFRepo.java:415) [classes/:na]
    at cz.opendata.linked.buyer_profiles.Extractor.extract(Extractor.java:140) ~[na:na]
    at cz.cuni.xrg.intlib.backend.execution.PipelineWorker.runExtractor(PipelineWorker.java:714) ~[classes/:na]
    at cz.cuni.xrg.intlib.backend.execution.PipelineWorker.runNode(PipelineWorker.java:648) ~[classes/:na]
    at cz.cuni.xrg.intlib.backend.execution.PipelineWorker.run(PipelineWorker.java:339) ~[classes/:na]
    at java.util.concurrent.ThreadPoolExecutor.runWorker(Unknown Source) ~[na:1.7.0_25]
    at java.util.concurrent.ThreadPoolExecutor$Worker.run(Unknown Source) ~[na:1.7.0_25]
    at java.lang.Thread.run(Unknown Source) ~[na:1.7.0_25]
Caused by: org.openrdf.rio.RDFParseException: Expected an RDF value here, found ' ' [line 81208]
    at org.openrdf.rio.helpers.RDFParserBase.reportFatalError(RDFParserBase.java:582) ~[sesame-rio-api-2.7.0-beta1.jar:na]
    at org.openrdf.rio.turtle.TurtleParser.reportFatalError(TurtleParser.java:1103) ~[sesame-rio-turtle-2.7.0-beta1.jar:na]
    at org.openrdf.rio.turtle.TurtleParser.parseValue(TurtleParser.java:548) ~[sesame-rio-turtle-2.7.0-beta1.jar:na]
    at org.openrdf.rio.turtle.TurtleParser.parsePredicate(TurtleParser.java:391) ~[sesame-rio-turtle-2.7.0-beta1.jar:na]
    at org.openrdf.rio.turtle.TurtleParser.parsePredicateObjectList(TurtleParser.java:311) ~[sesame-rio-turtle-2.7.0-beta1.jar:na]
    at org.openrdf.rio.turtle.TurtleParser.parseTriples(TurtleParser.java:301) ~[sesame-rio-turtle-2.7.0-beta1.jar:na]
    at org.openrdf.rio.turtle.TurtleParser.parseStatement(TurtleParser.java:208) ~[sesame-rio-turtle-2.7.0-beta1.jar:na]
    at org.openrdf.rio.turtle.TurtleParser.parse(TurtleParser.java:186) ~[sesame-rio-turtle-2.7.0-beta1.jar:na]
    at virtuoso.sesame2.driver.VirtuosoRepositoryConnection.add(VirtuosoRepositoryConnection.java:1025) ~[virtuoso-sesame-7.0.1.jar:na]
    ... 11 common frames omitted
2013-08-21 10:35:29,124 [pool-2-thread-1] ERROR c.c.x.i.commons.extractor.Extract - Cannot put TTL to repository.
2013-08-21 10:35:30,278 [pool-2-thread-1] INFO  c.c.x.i.rdf.impl.VirtuosoRDFRepo - Virtuoso repository successfully incicialized
2013-08-21 10:35:30,361 [pool-2-thread-1] INFO  c.c.x.i.rdf.impl.VirtuosoRDFRepo - Set new data graph - http://ex16_dpu10_du0
2013-08-21 10:35:30,592 [pool-2-thread-1] INFO  c.c.x.i.rdf.impl.VirtuosoRDFRepo - START merging 803966 triples from <http://ex16_dpu11_du0> TO <http://ex16_dpu10_du0>.
2013-08-21 10:35:55,798 [pool-2-thread-1] INFO  c.c.x.i.rdf.impl.VirtuosoRDFRepo - Merged SUCESSFULL
2013-08-21 10:35:55,863 [pool-2-thread-1] INFO  c.c.x.i.rdf.impl.VirtuosoRDFRepo - Virtuoso repository successfully incicialized
2013-08-21 10:35:55,918 [pool-2-thread-1] INFO  c.c.x.i.rdf.impl.VirtuosoRDFRepo - Set new data graph - http://ex16_dpu10_du1
2013-08-21 10:35:56,086 [pool-2-thread-1] INFO  c.c.x.i.rdf.impl.VirtuosoRDFRepo - START merging 24228 triples from <http://ex16_dpu11_du1> TO <http://ex16_dpu10_du1>.
2013-08-21 10:35:56,954 [pool-2-thread-1] INFO  c.c.x.i.rdf.impl.VirtuosoRDFRepo - Merged SUCESSFULL
2013-08-21 10:38:09,317 [pool-2-thread-1] INFO  c.c.x.i.rdf.impl.VirtuosoRDFRepo - Virtuoso repository successfully incicialized
2013-08-21 10:38:09,360 [pool-2-thread-1] INFO  c.c.x.i.rdf.impl.VirtuosoRDFRepo - Set new data graph - http://ex16_dpu12_du0
2013-08-21 10:38:09,593 [pool-2-thread-1] INFO  c.c.x.i.rdf.impl.VirtuosoRDFRepo - START merging 803966 triples from <http://ex16_dpu11_du0> TO <http://ex16_dpu12_du0>.
2013-08-21 10:38:33,923 [pool-2-thread-1] INFO  c.c.x.i.rdf.impl.VirtuosoRDFRepo - Merged SUCESSFULL
2013-08-21 10:38:33,959 [pool-2-thread-1] INFO  c.c.x.i.rdf.impl.VirtuosoRDFRepo - Virtuoso repository successfully incicialized
2013-08-21 10:38:33,994 [pool-2-thread-1] INFO  c.c.x.i.rdf.impl.VirtuosoRDFRepo - Set new data graph - http://ex16_dpu12_du1
2013-08-21 10:38:34,160 [pool-2-thread-1] INFO  c.c.x.i.rdf.impl.VirtuosoRDFRepo - START merging 24228 triples from <http://ex16_dpu11_du1> TO <http://ex16_dpu12_du1>.
2013-08-21 10:38:35,552 [pool-2-thread-1] INFO  c.c.x.i.rdf.impl.VirtuosoRDFRepo - Merged SUCESSFULL
2013-08-21 10:40:54,095 [pool-2-thread-1] DEBUG c.c.x.i.b.execution.PipelineWorker - Finished
2013-08-21 10:40:54,148 [pool-2-thread-1] DEBUG c.c.x.i.b.execution.PipelineWorker - Clean up
2013-08-21 10:41:13,097 [pool-2-thread-1] INFO  c.c.x.i.rdf.impl.VirtuosoRDFRepo - Virtuoso repository succesfully shut down
2013-08-21 10:41:13,099 [Thread-7] DEBUG c.c.x.i.rdf.impl.VirtuosoRDFRepo - Repository destroyed SUCCESSFULL
2013-08-21 10:41:13,608 [pool-2-thread-1] INFO  c.c.x.i.rdf.impl.VirtuosoRDFRepo - Virtuoso repository succesfully shut down
2013-08-21 10:41:13,616 [Thread-8] DEBUG c.c.x.i.rdf.impl.VirtuosoRDFRepo - Repository destroyed SUCCESSFULL
2013-08-21 10:41:27,068 [pool-2-thread-1] INFO  c.c.x.i.rdf.impl.VirtuosoRDFRepo - Virtuoso repository succesfully shut down
2013-08-21 10:41:27,069 [Thread-9] DEBUG c.c.x.i.rdf.impl.VirtuosoRDFRepo - Repository destroyed SUCCESSFULL
2013-08-21 10:41:27,408 [pool-2-thread-1] INFO  c.c.x.i.rdf.impl.VirtuosoRDFRepo - Virtuoso repository succesfully shut down
2013-08-21 10:41:27,410 [Thread-10] DEBUG c.c.x.i.rdf.impl.VirtuosoRDFRepo - Repository destroyed SUCCESSFULL
2013-08-21 10:41:35,564 [pool-2-thread-1] INFO  c.c.x.i.rdf.impl.VirtuosoRDFRepo - Virtuoso repository succesfully shut down
2013-08-21 10:41:35,567 [Thread-11] DEBUG c.c.x.i.rdf.impl.VirtuosoRDFRepo - Repository destroyed SUCCESSFULL
2013-08-21 10:41:35,939 [pool-2-thread-1] INFO  c.c.x.i.rdf.impl.VirtuosoRDFRepo - Virtuoso repository succesfully shut down
2013-08-21 10:41:35,940 [Thread-12] DEBUG c.c.x.i.rdf.impl.VirtuosoRDFRepo - Repository destroyed SUCCESSFULL</code></pre>

However, in the execution monitor this pipeline is marked as successful and all temp files were deleted.

Firstly, the outcome should be failure, keeping all temp files in place for debugging.

Actually, the TTL is not valid on the line indicated, that is true.

**Comment by jakubklimek** [comment]
Actually, as I think about it, this might not be an issue after all. The exception is handled within the DPU, so on the outside, it looks as everything worked OK. I need to throw ExtractException here.
