### ISSUE TITLE
When DPU file not found, strange exception is in the log

### ISSUE THREAD

**Issue by jakubklimek** [mff-uk/odcs#275]
When the JAR of DPU which is in pipeline is missing and the pipeline is run, in the log I see:
PipelineWorker: Structure exception

In console there is an exception that makes more sense:

<pre><code>2013-08-21 15:02:18,610 [pool-2-thread-1] ERROR c.c.x.i.b.execution.PipelineWorker - PipelineWorker: Structure exception
cz.cuni.xrg.intlib.backend.execution.StructureException: Failed to load instance of DPU from file.
    at cz.cuni.xrg.intlib.backend.execution.PipelineWorker.runNode(PipelineWorker.java:620) ~[classes/:na]
    at cz.cuni.xrg.intlib.backend.execution.PipelineWorker.run(PipelineWorker.java:339) ~[classes/:na]
    at java.util.concurrent.ThreadPoolExecutor.runWorker(Unknown Source) ~[na:1.7.0_25]
    at java.util.concurrent.ThreadPoolExecutor$Worker.run(Unknown Source) ~[na:1.7.0_25]
    at java.lang.Thread.run(Unknown Source) ~[na:1.7.0_25]
Caused by: java.io.FileNotFoundException: File 'C:\Users\Kuba\Documents\GitHub\intlib\target\dpu\Extractor_ares-0.0.1.jar' does not exist.
    at cz.cuni.xrg.intlib.commons.app.module.ModuleFacade.checkExistance(ModuleFacade.java:134) ~[classes/:na]
    at cz.cuni.xrg.intlib.commons.app.module.ModuleFacade.getObject(ModuleFacade.java:94) ~[classes/:na]
    at cz.cuni.xrg.intlib.commons.app.dpu.DPURecord.loadInstance(DPURecord.java:110) ~[classes/:na]
    at cz.cuni.xrg.intlib.backend.execution.PipelineWorker.runNode(PipelineWorker.java:618) ~[classes/:na]
    ... 4 common frames omitted</code></pre>

**Comment by skodapetr** [comment]
This is in my opinion the same as #254.

**Comment by tomas-knap** [comment]
Honza, please look at #254 and adjust correspondingly. Discuss with Bohuslav.

Honza: Should connect LOGGING_EVENT_EXCEPTION table to the LogMessage .. and maybe implement method that join the List (from that table) into single String .. and merge with current message. 
Bohuslav: Should use new this new method.

**Comment by tomas-knap** [comment]
duplicated with #254
