### ISSUE TITLE
RDF parsing exception

### ISSUE THREAD

**Issue by tomas-knap** [mff-uk/odcs#276]
What does the following error mean? (the selected one)

![screen shot 2013-08-21 at 6 06 53 pm](https://f.cloud.github.com/assets/3014917/1002373/cb4f758c-0a7b-11e3-8487-cf097dda4feb.png)

**Comment by tomas-knap** [comment]
Aha, tak log backendu mi hlasi:

org.openrdf.repository.RepositoryException: Problem parsing triples
    at virtuoso.sesame2.driver.VirtuosoRepositoryConnection.add(VirtuosoRepositoryConnection.java:1031) ~[virtuoso-sesame-7.0.1.jar:na]
    at cz.cuni.xrg.intlib.rdf.impl.LocalRDFRepo.addInputStreamToRepository(LocalRDFRepo.java:599) [RDF-0.0.1.jar:na]
    at cz.cuni.xrg.intlib.rdf.impl.LocalRDFRepo.addFileToRepository(LocalRDFRepo.java:624) [RDF-0.0.1.jar:na]
    at cz.cuni.xrg.intlib.rdf.impl.LocalRDFRepo.extractFromFile(LocalRDFRepo.java:502) [RDF-0.0.1.jar:na]
    at cz.cuni.xrg.intlib.rdf.impl.LocalRDFRepo.extractFromLocalTurtleFile(LocalRDFRepo.java:415) [RDF-0.0.1.jar:na]
    at cz.cuni.mff.xrg.intlib.extractor.jtaggerExtractor.JTaggerExtractor.extract(JTaggerExtractor.java:234) [bundlefile:na]
    at cz.cuni.xrg.intlib.backend.execution.PipelineWorker.runExtractor(PipelineWorker.java:714) [backend-0.0.1.jar:na]
    at cz.cuni.xrg.intlib.backend.execution.PipelineWorker.runNode(PipelineWorker.java:648) [backend-0.0.1.jar:na]
    at cz.cuni.xrg.intlib.backend.execution.PipelineWorker.run(PipelineWorker.java:339) [backend-0.0.1.jar:na]
    at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1145) [na:1.7.0_21]
    at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:615) [na:1.7.0_21]
    at java.lang.Thread.run(Thread.java:722) [na:1.7.0_21]
Caused by: org.openrdf.rio.UnsupportedRDFormatException: No parser factory available for RDF format Turtle (mimeTypes=text/turtle, application/x-turtle; ext=ttl)
    at org.openrdf.rio.Rio.createParser(Rio.java:173) ~[sesame-rio-api-2.7.0-beta1.jar:na]
    at org.openrdf.rio.Rio.createParser(Rio.java:188) ~[sesame-rio-api-2.7.0-beta1.jar:na]
    at virtuoso.sesame2.driver.VirtuosoRepositoryConnection.add(VirtuosoRepositoryConnection.java:935) ~[virtuoso-sesame-7.0.1.jar:na]
    ... 11 common frames omitted

**Comment by tomas-knap** [comment]
1. oprav prosim, aby v gui byla videt lepsi hlaska
2. proc to hlasi?
