### ISSUE TITLE
When running and deleting a pipeline at the same time, backend crashes

### ISSUE THREAD

**Issue by jakubklimek** [mff-uk/odcs#279]
I am not able to stop or unschedule tasks in the current version. Therefore, when I run backend and there is a pipeline scheduled, what I can do is copy it and delete it before it runs to stop it. This time I was a bit late and deleted the pipeline roughly at the same time it started and this exception happened and the backend crashed:

<pre><code>2013-08-22 08:33:12,425 [pool-2-thread-1] DEBUG c.c.x.i.b.execution.PipelineWorker - Started
2013-08-22 08:33:14,058 [pool-2-thread-1] WARN  o.h.e.jdbc.spi.SqlExceptionHelper - SQL Error: -8, SQLState: S1000
2013-08-22 08:33:14,088 [pool-2-thread-1] ERROR o.h.e.jdbc.spi.SqlExceptionHelper - SR306: INSERT statement conflicted with FOREIGN KEY constraint referencing table "DB.INTLIB.DPU_INSTANCE"
2013-08-22 08:33:14,153 [pool-2-thread-1] WARN  o.h.e.jdbc.spi.SqlExceptionHelper - SQL Error: -8, SQLState: S1000
2013-08-22 08:33:14,193 [pool-2-thread-1] ERROR o.h.e.jdbc.spi.SqlExceptionHelper - SR306: INSERT statement conflicted with FOREIGN KEY constraint referencing table "DB.INTLIB.DPU_INSTANCE"
Exception in thread "pool-2-thread-1" javax.persistence.PersistenceException: org.hibernate.exception.GenericJDBCException: SR306: INSERT statement conflicted with FOREIGN KEY constraint referencing table "DB.INTLIB.DPU_INSTANCE"
    at org.hibernate.ejb.AbstractEntityManagerImpl.convert(AbstractEntityManagerImpl.java:1361)
    at org.hibernate.ejb.AbstractEntityManagerImpl.convert(AbstractEntityManagerImpl.java:1289)
    at org.hibernate.ejb.AbstractEntityManagerImpl.convert(AbstractEntityManagerImpl.java:1295)
    at org.hibernate.ejb.AbstractEntityManagerImpl.persist(AbstractEntityManagerImpl.java:859)
    at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
    at sun.reflect.NativeMethodAccessorImpl.invoke(Unknown Source)
    at sun.reflect.DelegatingMethodAccessorImpl.invoke(Unknown Source)
    at java.lang.reflect.Method.invoke(Unknown Source)
    at org.springframework.orm.jpa.SharedEntityManagerCreator$SharedEntityManagerInvocationHandler.invoke(SharedEntityManagerCreator.java:240)
    at com.sun.proxy.$Proxy31.persist(Unknown Source)
    at cz.cuni.xrg.intlib.commons.app.dpu.DPUFacade.save(DPUFacade.java:248)
    at cz.cuni.xrg.intlib.commons.app.dpu.DPUFacade$$FastClassByCGLIB$$94c8b7be.invoke(<generated>)
    at net.sf.cglib.proxy.MethodProxy.invoke(MethodProxy.java:204)
    at org.springframework.aop.framework.Cglib2AopProxy$CglibMethodInvocation.invokeJoinpoint(Cglib2AopProxy.java:689)
    at org.springframework.aop.framework.ReflectiveMethodInvocation.proceed(ReflectiveMethodInvocation.java:150)
    at org.springframework.transaction.interceptor.TransactionInterceptor.invoke(TransactionInterceptor.java:110)
    at org.springframework.aop.framework.ReflectiveMethodInvocation.proceed(ReflectiveMethodInvocation.java:172)
    at org.springframework.aop.framework.Cglib2AopProxy$DynamicAdvisedInterceptor.intercept(Cglib2AopProxy.java:622)
    at cz.cuni.xrg.intlib.commons.app.dpu.DPUFacade$$EnhancerByCGLIB$$c077483f.save(<generated>)
    at cz.cuni.xrg.intlib.backend.EventListenerDatabase.onPipelineEvent(EventListenerDatabase.java:44)
    at cz.cuni.xrg.intlib.backend.EventListenerDatabase.onApplicationEvent(EventListenerDatabase.java:53)
    at org.springframework.context.event.SimpleApplicationEventMulticaster.multicastEvent(SimpleApplicationEventMulticaster.java:97)
    at org.springframework.context.support.AbstractApplicationContext.publishEvent(AbstractApplicationContext.java:324)
    at cz.cuni.xrg.intlib.backend.execution.PipelineWorker.run(PipelineWorker.java:373)
    at java.util.concurrent.ThreadPoolExecutor.runWorker(Unknown Source)
    at java.util.concurrent.ThreadPoolExecutor$Worker.run(Unknown Source)
    at java.lang.Thread.run(Unknown Source)
Caused by: org.hibernate.exception.GenericJDBCException: SR306: INSERT statement conflicted with FOREIGN KEY constraint referencing table "DB.INTLIB.DPU_INSTANCE"
    at org.hibernate.exception.internal.StandardSQLExceptionConverter.convert(StandardSQLExceptionConverter.java:52)
    at org.hibernate.engine.jdbc.spi.SqlExceptionHelper.convert(SqlExceptionHelper.java:125)
    at org.hibernate.engine.jdbc.spi.SqlExceptionHelper.convert(SqlExceptionHelper.java:110)
    at org.hibernate.engine.jdbc.internal.proxy.AbstractStatementProxyHandler.continueInvocation(AbstractStatementProxyHandler.java:129)
    at org.hibernate.engine.jdbc.internal.proxy.AbstractProxyHandler.invoke(AbstractProxyHandler.java:81)
    at com.sun.proxy.$Proxy36.executeUpdate(Unknown Source)
    at org.hibernate.id.insert.AbstractSelectingDelegate.performInsert(AbstractSelectingDelegate.java:58)
    at org.hibernate.persister.entity.AbstractEntityPersister.insert(AbstractEntityPersister.java:2757)
    at org.hibernate.persister.entity.AbstractEntityPersister.insert(AbstractEntityPersister.java:3268)
    at org.hibernate.action.internal.EntityIdentityInsertAction.execute(EntityIdentityInsertAction.java:78)
    at org.hibernate.engine.spi.ActionQueue.execute(ActionQueue.java:272)
    at org.hibernate.event.internal.AbstractSaveEventListener.performSaveOrReplicate(AbstractSaveEventListener.java:304)
    at org.hibernate.event.internal.AbstractSaveEventListener.performSave(AbstractSaveEventListener.java:195)
    at org.hibernate.event.internal.AbstractSaveEventListener.saveWithGeneratedId(AbstractSaveEventListener.java:128)
    at org.hibernate.ejb.event.EJB3PersistEventListener.saveWithGeneratedId(EJB3PersistEventListener.java:78)
    at org.hibernate.event.internal.DefaultPersistEventListener.entityIsTransient(DefaultPersistEventListener.java:208)
    at org.hibernate.event.internal.DefaultPersistEventListener.onPersist(DefaultPersistEventListener.java:151)
    at org.hibernate.event.internal.DefaultPersistEventListener.onPersist(DefaultPersistEventListener.java:78)
    at org.hibernate.internal.SessionImpl.firePersist(SessionImpl.java:725)
    at org.hibernate.internal.SessionImpl.persist(SessionImpl.java:701)
    at org.hibernate.internal.SessionImpl.persist(SessionImpl.java:705)
    at org.hibernate.ejb.AbstractEntityManagerImpl.persist(AbstractEntityManagerImpl.java:853)
    ... 23 more
Caused by: virtuoso.jdbc4.VirtuosoException: SR306: INSERT statement conflicted with FOREIGN KEY constraint referencing table "DB.INTLIB.DPU_INSTANCE"
    at virtuoso.jdbc4.VirtuosoResultSet.process_result(Unknown Source)
    at virtuoso.jdbc4.VirtuosoResultSet.getMoreResults(Unknown Source)
    at virtuoso.jdbc4.VirtuosoPreparedStatement.sendQuery(Unknown Source)
    at virtuoso.jdbc4.VirtuosoPreparedStatement.executeUpdate(Unknown Source)
    at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
    at sun.reflect.NativeMethodAccessorImpl.invoke(Unknown Source)
    at sun.reflect.DelegatingMethodAccessorImpl.invoke(Unknown Source)
    at java.lang.reflect.Method.invoke(Unknown Source)
    at org.hibernate.engine.jdbc.internal.proxy.AbstractStatementProxyHandler.continueInvocation(AbstractStatementProxyHandler.java:122)
    ... 41 more</code></pre>

**Comment by janvojt** [comment]
This is resolved by commit 6efb72cd. Also #273 is relevant to this case and is to be tested.
