### ISSUE TITLE
Transaction deadlocked

### ISSUE THREAD

**Issue by tomas-knap** [mff-uk/odcs#287]
When running the same pipeline twice, sometimes the following error occurs. Jirka, please try that

Steps to reproduces: Prepare pipeline which is running at least one minute (e.g. dbpedia pipeline, but with some SPARQL query). RUn the pipeline twice or more times. Kill backend. Restart backend, all these pipelines starts at the same time. Watch for this exception. 

2013-08-24 14:45:24,842 [pool-2-thread-2] INFO  c.c.m.x.i.e.silklinker.SilkLinker - Output 'confirmed links' is being prepared
2013-08-24 14:45:24,845 [pool-2-thread-2] INFO  c.c.x.i.rdf.impl.VirtuosoRDFRepo - Virtuoso repository successfully incicialized
2013-08-24 14:45:24,849 [pool-2-thread-2] INFO  c.c.x.i.rdf.impl.VirtuosoRDFRepo - Set new data graph - http://linked.opendata.cz/resource/odcs/internal/pipeline/exec/38/dpu/6/du/0
2013-08-24 14:45:24,856 [pool-2-thread-1] DEBUG org.openrdf.rio.RDFParserRegistry - Registered service class org.openrdf.rio.binary.BinaryRDFParserFactory
2013-08-24 14:45:24,863 [pool-2-thread-1] DEBUG org.openrdf.rio.RDFParserRegistry - Registered service class org.openrdf.rio.nquads.NQuadsParserFactory
2013-08-24 14:45:24,868 [pool-2-thread-1] DEBUG org.openrdf.rio.RDFParserRegistry - Registered service class org.openrdf.rio.n3.N3ParserFactory
2013-08-24 14:45:24,873 [pool-2-thread-1] DEBUG org.openrdf.rio.RDFParserRegistry - Registered service class org.openrdf.rio.rdfxml.RDFXMLParserFactory
2013-08-24 14:45:24,881 [pool-2-thread-1] DEBUG org.openrdf.rio.RDFParserRegistry - Registered service class org.openrdf.rio.trix.TriXParserFactory
2013-08-24 14:45:24,889 [pool-2-thread-1] DEBUG org.openrdf.rio.RDFParserRegistry - Registered service class org.openrdf.rio.turtle.TurtleParserFactory
2013-08-24 14:45:24,894 [pool-2-thread-1] DEBUG org.openrdf.rio.RDFParserRegistry - Registered service class org.openrdf.rio.trig.TriGParserFactory
2013-08-24 14:45:24,904 [pool-2-thread-1] DEBUG org.openrdf.rio.RDFParserRegistry - Registered service class org.openrdf.rio.ntriples.NTriplesParserFactory
2013-08-24 14:45:24,926 [pool-2-thread-1] INFO  c.c.m.x.i.e.silklinker.SilkLinker - Output 'to verify links' is being prepared
2013-08-24 14:45:24,926 [pool-2-thread-2] INFO  c.c.m.x.i.e.silklinker.SilkLinker - Output 'to verify links' is being prepared
2013-08-24 14:45:24,930 [pool-2-thread-2] INFO  c.c.x.i.rdf.impl.VirtuosoRDFRepo - Virtuoso repository successfully incicialized
2013-08-24 14:45:24,930 [pool-2-thread-1] INFO  c.c.x.i.rdf.impl.VirtuosoRDFRepo - Virtuoso repository successfully incicialized
2013-08-24 14:45:24,933 [pool-2-thread-2] INFO  c.c.x.i.rdf.impl.VirtuosoRDFRepo - Set new data graph - http://linked.opendata.cz/resource/odcs/internal/pipeline/exec/38/dpu/6/du/1
2013-08-24 14:45:24,933 [pool-2-thread-1] INFO  c.c.x.i.rdf.impl.VirtuosoRDFRepo - Set new data graph - http://linked.opendata.cz/resource/odcs/internal/pipeline/exec/35/dpu/6/du/1
2013-08-24 14:45:25,109 [pool-2-thread-2] WARN  o.h.e.jdbc.spi.SqlExceptionHelper - SQL Error: -8, SQLState: 40001
2013-08-24 14:45:25,112 [pool-2-thread-1] WARN  o.h.e.jdbc.spi.SqlExceptionHelper - SQL Error: -8, SQLState: 40001
2013-08-24 14:45:25,114 [pool-2-thread-2] ERROR o.h.e.jdbc.spi.SqlExceptionHelper - SR172: Transaction deadlocked
2013-08-24 14:45:25,116 [pool-2-thread-1] ERROR o.h.e.jdbc.spi.SqlExceptionHelper - SR172: Transaction deadlocked
Exception in thread "pool-2-thread-1" Exception in thread "pool-2-thread-2" org.springframework.orm.jpa.JpaSystemException: org.hibernate.exception.LockAcquisitionException: SR172: Transaction deadlocked; nested exception is javax.persistence.PersistenceException: org.hibernate.exception.LockAcquisitionException: SR172: Transaction deadlocked
    at org.springframework.orm.jpa.EntityManagerFactoryUtils.convertJpaAccessExceptionIfPossible(EntityManagerFactoryUtils.java:326)
    at org.springframework.orm.jpa.DefaultJpaDialect.translateExceptionIfPossible(DefaultJpaDialect.java:120)
    at org.springframework.orm.jpa.JpaTransactionManager.doCommit(JpaTransactionManager.java:516)
    at org.springframework.transaction.support.AbstractPlatformTransactionManager.processCommit(AbstractPlatformTransactionManager.java:754)
    at org.springframework.transaction.support.AbstractPlatformTransactionManager.commit(AbstractPlatformTransactionManager.java:723)
    at org.springframework.transaction.interceptor.TransactionAspectSupport.commitTransactionAfterReturning(TransactionAspectSupport.java:394)
    at org.springframework.transaction.interceptor.TransactionInterceptor.invoke(TransactionInterceptor.java:120)
    at org.springframework.aop.framework.ReflectiveMethodInvocation.proceed(ReflectiveMethodInvocation.java:172)
    at org.springframework.aop.framework.Cglib2AopProxy$DynamicAdvisedInterceptor.intercept(Cglib2AopProxy.java:622)
    at cz.cuni.xrg.intlib.commons.app.pipeline.PipelineFacade$$EnhancerByCGLIB$$f73d2cdd.save(<generated>)
    at cz.cuni.xrg.intlib.backend.execution.PipelineWorker.run(PipelineWorker.java:391)
    at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1145)
    at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:615)
    at java.lang.Thread.run(Thread.java:722)
Caused by: javax.persistence.PersistenceException: org.hibernate.exception.LockAcquisitionException: SR172: Transaction deadlocked
    at org.hibernate.ejb.AbstractEntityManagerImpl.convert(AbstractEntityManagerImpl.java:1361)
    at org.hibernate.ejb.AbstractEntityManagerImpl.convert(AbstractEntityManagerImpl.java:1289)
    at org.hibernate.ejb.TransactionImpl.commit(TransactionImpl.java:78)
    at org.springframework.orm.jpa.JpaTransactionManager.doCommit(JpaTransactionManager.java:512)
    ... 11 more
Caused by: org.hibernate.exception.LockAcquisitionException: SR172: Transaction deadlocked
    at org.hibernate.exception.internal.SQLStateConversionDelegate.convert(SQLStateConversionDelegate.java:139)
    at org.hibernate.exception.internal.StandardSQLExceptionConverter.convert(StandardSQLExceptionConverter.java:47)
    at org.hibernate.engine.jdbc.spi.SqlExceptionHelper.convert(SqlExceptionHelper.java:125)
    at org.hibernate.engine.jdbc.spi.SqlExceptionHelper.convert(SqlExceptionHelper.java:110)
    at org.hibernate.engine.jdbc.internal.proxy.AbstractStatementProxyHandler.continueInvocation(AbstractStatementProxyHandler.java:129)
    at org.hibernate.engine.jdbc.internal.proxy.AbstractProxyHandler.invoke(AbstractProxyHandler.java:81)
    at com.sun.proxy.$Proxy35.executeUpdate(Unknown Source)
    at org.hibernate.engine.jdbc.batch.internal.NonBatchingBatch.addToBatch(NonBatchingBatch.java:56)
    at org.hibernate.persister.collection.OneToManyPersister.doUpdateRows(OneToManyPersister.java:230)
    at org.hibernate.persister.collection.AbstractCollectionPersister.updateRows(AbstractCollectionPersister.java:1574)
    at org.hibernate.action.internal.CollectionUpdateAction.execute(CollectionUpdateAction.java:84)
    at org.hibernate.engine.spi.ActionQueue.execute(ActionQueue.java:272)
    at org.hibernate.engine.spi.ActionQueue.executeActions(ActionQueue.java:264)
    at org.hibernate.engine.spi.ActionQueue.executeActions(ActionQueue.java:189)
    at org.hibernate.event.internal.AbstractFlushingEventListener.performExecutions(AbstractFlushingEventListener.java:326)
    at org.hibernate.event.internal.DefaultFlushEventListener.onFlush(DefaultFlushEventListener.java:52)
    at org.hibernate.internal.SessionImpl.flush(SessionImpl.java:1081)
    at org.hibernate.internal.SessionImpl.managedFlush(SessionImpl.java:315)
    at org.hibernate.engine.transaction.internal.jdbc.JdbcTransaction.beforeTransactionCommit(JdbcTransaction.java:101)
    at org.hibernate.engine.transaction.spi.AbstractTransactionImpl.commit(AbstractTransactionImpl.java:175)
    at org.hibernate.ejb.TransactionImpl.commit(TransactionImpl.java:73)
    ... 12 more
Caused by: virtuoso.jdbc4.VirtuosoException: SR172: Transaction deadlocked
    at virtuoso.jdbc4.VirtuosoResultSet.process_result(Unknown Source)
    at virtuoso.jdbc4.VirtuosoResultSet.getMoreResults(Unknown Source)
    at virtuoso.jdbc4.VirtuosoPreparedStatement.sendQuery(Unknown Source)
    at virtuoso.jdbc4.VirtuosoPreparedStatement.executeUpdate(Unknown Source)
    at sun.reflect.GeneratedMethodAccessor21.invoke(Unknown Source)
    at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
    at java.lang.reflect.Method.invoke(Method.java:601)
    at org.hibernate.engine.jdbc.internal.proxy.AbstractStatementProxyHandler.continueInvocation(AbstractStatementProxyHandler.java:122)
    ... 28 more
org.springframework.orm.jpa.JpaSystemException: org.hibernate.exception.LockAcquisitionException: SR172: Transaction deadlocked; nested exception is javax.persistence.PersistenceException: org.hibernate.exception.LockAcquisitionException: SR172: Transaction deadlocked
    at org.springframework.orm.jpa.EntityManagerFactoryUtils.convertJpaAccessExceptionIfPossible(EntityManagerFactoryUtils.java:326)
    at org.springframework.orm.jpa.DefaultJpaDialect.translateExceptionIfPossible(DefaultJpaDialect.java:120)
    at org.springframework.orm.jpa.JpaTransactionManager.doCommit(JpaTransactionManager.java:516)
    at org.springframework.transaction.support.AbstractPlatformTransactionManager.processCommit(AbstractPlatformTransactionManager.java:754)
    at org.springframework.transaction.support.AbstractPlatformTransactionManager.commit(AbstractPlatformTransactionManager.java:723)
    at org.springframework.transaction.interceptor.TransactionAspectSupport.commitTransactionAfterReturning(TransactionAspectSupport.java:394)
    at org.springframework.transaction.interceptor.TransactionInterceptor.invoke(TransactionInterceptor.java:120)
    at org.springframework.aop.framework.ReflectiveMethodInvocation.proceed(ReflectiveMethodInvocation.java:172)
    at org.springframework.aop.framework.Cglib2AopProxy$DynamicAdvisedInterceptor.intercept(Cglib2AopProxy.java:622)
    at cz.cuni.xrg.intlib.commons.app.pipeline.PipelineFacade$$EnhancerByCGLIB$$f73d2cdd.save(<generated>)
    at cz.cuni.xrg.intlib.backend.execution.PipelineWorker.run(PipelineWorker.java:391)
    at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1145)
    at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:615)
    at java.lang.Thread.run(Thread.java:722)
Caused by: javax.persistence.PersistenceException: org.hibernate.exception.LockAcquisitionException: SR172: Transaction deadlocked
    at org.hibernate.ejb.AbstractEntityManagerImpl.convert(AbstractEntityManagerImpl.java:1361)
    at org.hibernate.ejb.AbstractEntityManagerImpl.convert(AbstractEntityManagerImpl.java:1289)
    at org.hibernate.ejb.TransactionImpl.commit(TransactionImpl.java:78)
    at org.springframework.orm.jpa.JpaTransactionManager.doCommit(JpaTransactionManager.java:512)
    ... 11 more
Caused by: org.hibernate.exception.LockAcquisitionException: SR172: Transaction deadlocked
    at org.hibernate.exception.internal.SQLStateConversionDelegate.convert(SQLStateConversionDelegate.java:139)
    at org.hibernate.exception.internal.StandardSQLExceptionConverter.convert(StandardSQLExceptionConverter.java:47)
    at org.hibernate.engine.jdbc.spi.SqlExceptionHelper.convert(SqlExceptionHelper.java:125)
    at org.hibernate.engine.jdbc.spi.SqlExceptionHelper.convert(SqlExceptionHelper.java:110)
    at org.hibernate.engine.jdbc.internal.proxy.AbstractStatementProxyHandler.continueInvocation(AbstractStatementProxyHandler.java:129)
    at org.hibernate.engine.jdbc.internal.proxy.AbstractProxyHandler.invoke(AbstractProxyHandler.java:81)
    at com.sun.proxy.$Proxy35.executeUpdate(Unknown Source)
    at org.hibernate.engine.jdbc.batch.internal.NonBatchingBatch.addToBatch(NonBatchingBatch.java:56)
    at org.hibernate.persister.collection.OneToManyPersister.doUpdateRows(OneToManyPersister.java:230)
    at org.hibernate.persister.collection.AbstractCollectionPersister.updateRows(AbstractCollectionPersister.java:1574)
    at org.hibernate.action.internal.CollectionUpdateAction.execute(CollectionUpdateAction.java:84)
    at org.hibernate.engine.spi.ActionQueue.execute(ActionQueue.java:272)
    at org.hibernate.engine.spi.ActionQueue.executeActions(ActionQueue.java:264)
    at org.hibernate.engine.spi.ActionQueue.executeActions(ActionQueue.java:189)
    at org.hibernate.event.internal.AbstractFlushingEventListener.performExecutions(AbstractFlushingEventListener.java:326)
    at org.hibernate.event.internal.DefaultFlushEventListener.onFlush(DefaultFlushEventListener.java:52)
    at org.hibernate.internal.SessionImpl.flush(SessionImpl.java:1081)
    at org.hibernate.internal.SessionImpl.managedFlush(SessionImpl.java:315)
    at org.hibernate.engine.transaction.internal.jdbc.JdbcTransaction.beforeTransactionCommit(JdbcTransaction.java:101)
    at org.hibernate.engine.transaction.spi.AbstractTransactionImpl.commit(AbstractTransactionImpl.java:175)
    at org.hibernate.ejb.TransactionImpl.commit(TransactionImpl.java:73)
    ... 12 more
Caused by: virtuoso.jdbc4.VirtuosoException: SR172: Transaction deadlocked
    at virtuoso.jdbc4.VirtuosoResultSet.process_result(Unknown Source)
    at virtuoso.jdbc4.VirtuosoResultSet.getMoreResults(Unknown Source)
    at virtuoso.jdbc4.VirtuosoPreparedStatement.sendQuery(Unknown Source)
    at virtuoso.jdbc4.VirtuosoPreparedStatement.executeUpdate(Unknown Source)
    at sun.reflect.GeneratedMethodAccessor21.invoke(Unknown Source)
    at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
    at java.lang.reflect.Method.invoke(Method.java:601)
    at org.hibernate.engine.jdbc.internal.proxy.AbstractStatementProxyHandler.continueInvocation(AbstractStatementProxyHandler.java:122)
    ... 28 more

**Comment by tomas-knap** [comment]
Jirka, you told me there is a progress in this?

**Comment by tomesj** [comment]
I wasnt deal with that - it was crossed at collab page. That was one of my question I asked you yesterday.

**Comment by tomas-knap** [comment]
Ok, planned if you have time for 0.4.1
