### ISSUE TITLE
Running sample DBpedia pipeline throws NPE

### ISSUE THREAD

**Issue by janvojt** [mff-uk/odcs#32]
```
Pipeline execution terminated because of: java.lang.NullPointerException
    at cz.cuni.xrg.intlib.commons.app.rdf.LocalRDFRepo.extractfromSPARQLEndpoint(LocalRDFRepo.java:870)
    at cz.cuni.xrg.intlib.backend.data.rdf.LocalRDF.extractfromSPARQLEndpoint(LocalRDF.java:208)
    at module.RDF_extractor.extract(RDF_extractor.java:143)
    at cz.cuni.xrg.intlib.backend.execution.PipelineWorker.runExtractor(PipelineWorker.java:462)
    at cz.cuni.xrg.intlib.backend.execution.PipelineWorker.runNode(PipelineWorker.java:435)
    at cz.cuni.xrg.intlib.backend.execution.PipelineWorker.run(PipelineWorker.java:253)
    at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1145)
    at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:615)
    at java.lang.Thread.run(Thread.java:722)
```

**Comment by tomesj** [comment]
BUG fixed - problem solved.
