### ISSUE TITLE
Cannot run DbPedia pipeline

### ISSUE THREAD

**Issue by bogo777** [mff-uk/odcs#325]
When I try to run or debug DbPedia pipeline, execution fails with this message:

Pipeline execution terminated because of: java.lang.NullPointerException
    at cz.cuni.xrg.intlib.rdf.impl.BaseRDFRepo.setDataGraph(BaseRDFRepo.java:2142)
    at cz.cuni.xrg.intlib.rdf.impl.VirtuosoRDFRepo.setDataGraph(VirtuosoRDFRepo.java:84)
    at cz.cuni.xrg.intlib.rdf.impl.VirtuosoRDFRepo.<init>(VirtuosoRDFRepo.java:58)
    at cz.cuni.xrg.intlib.rdf.data.RDFDataUnitFactory.createVirtuosoRDFRepo(RDFDataUnitFactory.java:114)
    at cz.cuni.xrg.intlib.backend.data.DataUnitFactory.create(DataUnitFactory.java:89)
    at cz.cuni.xrg.intlib.backend.context.DataUnitManager.addDataUnit(DataUnitManager.java:277)
    at cz.cuni.xrg.intlib.backend.context.Context.addOutputDataUnit(Context.java:343)
    at cz.cuni.mff.xrg.intlib.extractor.rdf.RDFExtractor.extract(RDFExtractor.java:37)
    at cz.cuni.xrg.intlib.backend.execution.PipelineWorker.runExtractor(PipelineWorker.java:597)
    at cz.cuni.xrg.intlib.backend.execution.PipelineWorker.runNode(PipelineWorker.java:559)
    at cz.cuni.xrg.intlib.backend.execution.PipelineWorker.run(PipelineWorker.java:338)
    at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1145)
    at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:615)
    at java.lang.Thread.run(Thread.java:724)

I have last version of project after clean&build, latest db, and I repaired graph url in SPARQL extractor by removing ",/" from the end. 
I assigned you because you're the last person who commited to the class where the exception came from.

**Comment by tomesj** [comment]
Fix just now by commit 1638a3269f381aa4c992b7b8d99dae401b607cd2 - close #325 issue.
