### ISSUE TITLE
Missing config errors

### ISSUE THREAD

**Issue by jakubklimek** [mff-uk/odcs#335]
When running a version of ODCS that expects something new in config, backend crashes. Could it be done that if backend or frontend don't find their configs where they are supposed to be (or they do, but some properties are missing) it creates what it needs with default values? If not, could it not crash with exception but write a civilized error message?

In general, we should NEVER see exception stack trace - all should be handled unless it is something really unexpected.

<pre><code>INFO: Loading configuration from: C:\Users\Kuba/.intlib/config.properties
07:58:15 [main] DEBUG org.jboss.logging - Logging Provider: org.jboss.logging.Slf4jLoggerProvider
Exception in thread "main" org.springframework.beans.factory.BeanCreationException: Error creating bean with name 'pipelineFacade': Injection of autowired dependencies failed; nested exception is org.springframework.beans.factory.BeanCreationException: Could not autowire field: private cz.cuni.xrg.intlib.commons.app.communication.EmailSender cz.cuni.xrg.intlib.backend.facade.PipelineFacade.emailSender; nested exception is org.springframework.beans.factory.BeanCreationException: Error creating bean with name 'emailSender' defined in class path resource [commons-app-context.xml]: Instantiation of bean failed; nested exception is org.springframework.beans.BeanInstantiationException: Could not instantiate bean class [cz.cuni.xrg.intlib.commons.app.communication.EmailSender]: Constructor threw exception; nested exception is cz.cuni.xrg.intlib.commons.app.conf.MissingConfigPropertyException: Config is missing property: email.enabled.
    at org.springframework.beans.factory.annotation.AutowiredAnnotationBeanPostProcessor.postProcessPropertyValues(AutowiredAnnotationBeanPostProcessor.java:287)
    at org.springframework.beans.factory.support.AbstractAutowireCapableBeanFactory.populateBean(AbstractAutowireCapableBeanFactory.java:1106)
    at org.springframework.beans.factory.support.AbstractAutowireCapableBeanFactory.doCreateBean(AbstractAutowireCapableBeanFactory.java:517)
    at org.springframework.beans.factory.support.AbstractAutowireCapableBeanFactory.createBean(AbstractAutowireCapableBeanFactory.java:456)
    at org.springframework.beans.factory.support.AbstractBeanFactory$1.getObject(AbstractBeanFactory.java:294)
    at org.springframework.beans.factory.support.DefaultSingletonBeanRegistry.getSingleton(DefaultSingletonBeanRegistry.java:225)
    at org.springframework.beans.factory.support.AbstractBeanFactory.doGetBean(AbstractBeanFactory.java:291)
    at org.springframework.beans.factory.support.AbstractBeanFactory.getBean(AbstractBeanFactory.java:193)
    at org.springframework.beans.factory.support.DefaultListableBeanFactory.preInstantiateSingletons(DefaultListableBeanFactory.java:609)
    at org.springframework.context.support.AbstractApplicationContext.finishBeanFactoryInitialization(AbstractApplicationContext.java:918)
    at org.springframework.context.support.AbstractApplicationContext.refresh(AbstractApplicationContext.java:469)
    at org.springframework.context.support.ClassPathXmlApplicationContext.<init>(ClassPathXmlApplicationContext.java:139)
    at org.springframework.context.support.ClassPathXmlApplicationContext.<init>(ClassPathXmlApplicationContext.java:83)
    at cz.cuni.xrg.intlib.backend.AppEntry.init(AppEntry.java:112)
    at cz.cuni.xrg.intlib.backend.AppEntry.run(AppEntry.java:161)
    at cz.cuni.xrg.intlib.backend.AppEntry.main(AppEntry.java:210)
Caused by: org.springframework.beans.factory.BeanCreationException: Could not autowire field: private cz.cuni.xrg.intlib.commons.app.communication.EmailSender cz.cuni.xrg.intlib.backend.facade.PipelineFacade.emailSender; nested exception is org.springframework.beans.factory.BeanCreationException: Error creating bean with name 'emailSender' defined in class path resource [commons-app-context.xml]: Instantiation of bean failed; nested exception is org.springframework.beans.BeanInstantiationException: Could not instantiate bean class [cz.cuni.xrg.intlib.commons.app.communication.EmailSender]: Constructor threw exception; nested exception is cz.cuni.xrg.intlib.commons.app.conf.MissingConfigPropertyException: Config is missing property: email.enabled.
    at org.springframework.beans.factory.annotation.AutowiredAnnotationBeanPostProcessor$AutowiredFieldElement.inject(AutowiredAnnotationBeanPostProcessor.java:506)
    at org.springframework.beans.factory.annotation.InjectionMetadata.inject(InjectionMetadata.java:87)
    at org.springframework.beans.factory.annotation.AutowiredAnnotationBeanPostProcessor.postProcessPropertyValues(AutowiredAnnotationBeanPostProcessor.java:284)
    ... 15 more
Caused by: org.springframework.beans.factory.BeanCreationException: Error creating bean with name 'emailSender' defined in class path resource [commons-app-context.xml]: Instantiation of bean failed; nested exception is org.springframework.beans.BeanInstantiationException: Could not instantiate bean class [cz.cuni.xrg.intlib.commons.app.communication.EmailSender]: Constructor threw exception; nested exception is cz.cuni.xrg.intlib.commons.app.conf.MissingConfigPropertyException: Config is missing property: email.enabled.
    at org.springframework.beans.factory.support.ConstructorResolver.autowireConstructor(ConstructorResolver.java:288)
    at org.springframework.beans.factory.support.AbstractAutowireCapableBeanFactory.autowireConstructor(AbstractAutowireCapableBeanFactory.java:1035)
    at org.springframework.beans.factory.support.AbstractAutowireCapableBeanFactory.createBeanInstance(AbstractAutowireCapableBeanFactory.java:939)
    at org.springframework.beans.factory.support.AbstractAutowireCapableBeanFactory.doCreateBean(AbstractAutowireCapableBeanFactory.java:485)
    at org.springframework.beans.factory.support.AbstractAutowireCapableBeanFactory.createBean(AbstractAutowireCapableBeanFactory.java:456)
    at org.springframework.beans.factory.support.AbstractBeanFactory$1.getObject(AbstractBeanFactory.java:294)
    at org.springframework.beans.factory.support.DefaultSingletonBeanRegistry.getSingleton(DefaultSingletonBeanRegistry.java:225)
    at org.springframework.beans.factory.support.AbstractBeanFactory.doGetBean(AbstractBeanFactory.java:291)
    at org.springframework.beans.factory.support.AbstractBeanFactory.getBean(AbstractBeanFactory.java:193)
    at org.springframework.beans.factory.support.DefaultListableBeanFactory.findAutowireCandidates(DefaultListableBeanFactory.java:876)
    at org.springframework.beans.factory.support.DefaultListableBeanFactory.doResolveDependency(DefaultListableBeanFactory.java:818)
    at org.springframework.beans.factory.support.DefaultListableBeanFactory.resolveDependency(DefaultListableBeanFactory.java:735)
    at org.springframework.beans.factory.annotation.AutowiredAnnotationBeanPostProcessor$AutowiredFieldElement.inject(AutowiredAnnotationBeanPostProcessor.java:478)
    ... 17 more
Caused by: org.springframework.beans.BeanInstantiationException: Could not instantiate bean class [cz.cuni.xrg.intlib.commons.app.communication.EmailSender]: Constructor threw exception; nested exception is cz.cuni.xrg.intlib.commons.app.conf.MissingConfigPropertyException: Config is missing property: email.enabled.
    at org.springframework.beans.BeanUtils.instantiateClass(BeanUtils.java:162)
    at org.springframework.beans.factory.support.SimpleInstantiationStrategy.instantiate(SimpleInstantiationStrategy.java:110)
    at org.springframework.beans.factory.support.ConstructorResolver.autowireConstructor(ConstructorResolver.java:280)
    ... 29 more
Caused by: cz.cuni.xrg.intlib.commons.app.conf.MissingConfigPropertyException: Config is missing property: email.enabled.
    at cz.cuni.xrg.intlib.commons.app.conf.AppConfig.getString(AppConfig.java:58)
    at cz.cuni.xrg.intlib.commons.app.conf.AppConfig.getBoolean(AppConfig.java:85)
    at cz.cuni.xrg.intlib.commons.app.communication.EmailSender.<init>(EmailSender.java:72)
    at sun.reflect.NativeConstructorAccessorImpl.newInstance0(Native Method)
    at sun.reflect.NativeConstructorAccessorImpl.newInstance(Unknown Source)
    at sun.reflect.DelegatingConstructorAccessorImpl.newInstance(Unknown Source)
    at java.lang.reflect.Constructor.newInstance(Unknown Source)
    at org.springframework.beans.BeanUtils.instantiateClass(BeanUtils.java:147)
    ... 31 more</code></pre>

**Comment by skodapetr** [comment]
But I thing that the default value is not the best solution. The `MissingConfigPropertyException` extends `RuntimeException`, so it's never catch in the application .. and if it is thrown then it terminate the execution with stack-trace.

We may consider writing more civilized message in place where this exception is thrown. But this does not save us from stack trace. 

I have been discussing the possibility of writing special logback appender that will not print out stack trace. But as the backend should run as a daemon without console .. is it worth of the effort? And how should we present user such "problem"?

I reassign to Honza as experienced programmer and author the the configuration.  Honzam could you please comment on this.

**Comment by tomas-knap** [comment]
The idea is that the backedn will e.g. write log.warn("Not found value for config property X, using default value Y")

If the default value cannot be deduces, it could end with error.

**Comment by janvojt** [comment]
> In general, we should NEVER see exception stack trace - all should be handled unless it is something really unexpected.

I don't agree, in general runtime exception should be thrown. On the abstract level of `AppConfig`, we do not know what kind of config it is, and do not know if there even exists any usable default value (e.g. filesystem paths, email). The implementation of `AppConfig` is therefore correct.

In some cases though, it is possible to use a default value if none is provided in config file. However it is the responsibility of the class using the `AppConfig` to catch the exception, log info message, and use default value. This is currently done at some places (e.g. [PipelineFacade in backend](https://github.com/mff-uk/intlib/blob/d2b52cca4934d05024f4d0ce00cf163803d6ee2c/backend/src/main/java/cz/cuni/xrg/intlib/backend/facade/PipelineFacade.java#L66)), at other places this functionality is pending to be implemented (e.g. see #469).

In this case, we can use a default value of false for emails.enabed. I will implement it this way and close the issue, as current general attitude towards this problem is correct.

**Comment by tomas-knap** [comment]
See #469
