### ISSUE TITLE
SPARQL extractor not working properly

### ISSUE THREAD

**Issue by jakubklimek** [mff-uk/odcs#371]
The following query executes correctly on http://internal.opendata.cz:8890/sparql in browser.

<pre><code>prefix skos: &lt;http://www.w3.org/2004/02/skos/core#&gt;
prefix adms: &lt;http://www.w3.org/ns/adms#&gt;
construct {?id &lt;http://linked.opendata.cz/ontology/odcs/textValue&gt; ?ic }from &lt;http://linked.opendata.cz/resource/dataset/buyer-profiles/profiles/cz&gt; 
where {?id a adms:Identifier; skos:notation ?ic.} LIMIT 10
</code></pre>

However, the same query fails when executed through a SPARQL Extractor:

<pre><code>Execution failed because of non-specific exception: cz.cuni.xrg.intlib.commons.dpu.DPUException: HTTP/1.1 400 Bad Request. Caused by Virtuoso 37000 Error SP030: SPARQL compiler, line 1: Missing &lt;namespace-iri-string&gt; in PREFIX declaration at '&lt;' before 'http:'
    at cz.cuni.mff.xrg.intlib.extractor.rdf.RDFExtractor.execute(RDFExtractor.java:63)
    at cz.cuni.xrg.intlib.backend.execution.dpu.Executor.executeInstance(Executor.java:278)
    at cz.cuni.xrg.intlib.backend.execution.dpu.Executor.execute(Executor.java:404)
    at cz.cuni.xrg.intlib.backend.execution.dpu.Executor.run(Executor.java:434)
    at java.lang.Thread.run(Unknown Source)
Caused by: cz.cuni.xrg.intlib.rdf.exceptions.InsertPartException: HTTP/1.1 400 Bad Request. Caused by Virtuoso 37000 Error SP030: SPARQL compiler, line 1: Missing <namespace-iri-string> in PREFIX declaration at '&lt;' before 'http:'
    at cz.cuni.xrg.intlib.rdf.impl.BaseRDFRepo.getEndpointStreamReader(BaseRDFRepo.java:1687)
    at cz.cuni.xrg.intlib.rdf.impl.BaseRDFRepo.extractFromSPARQLEndpoint(BaseRDFRepo.java:864)
    at cz.cuni.mff.xrg.intlib.extractor.rdf.RDFExtractor.execute(RDFExtractor.java:54)
    ... 4 more
</code></pre>

**Comment by jakubklimek** [comment]
My bad... forgot to update :D
