### ISSUE TITLE
Tests in commons-app fail.

### ISSUE THREAD

**Issue by janvojt** [mff-uk/odcs#420]
Directory `target` does not exist. Stactrace with following root cause is produced.

```
Caused by: cz.cuni.xrg.intlib.commons.app.module.LibsLoadFailedException: Invalid library path: /home/janvojt/workspace/intlib/target/lib/backend
    at cz.cuni.xrg.intlib.commons.app.module.ModuleFacade.installDirectory(ModuleFacade.java:217) ~[classes/:na]
    at cz.cuni.xrg.intlib.commons.app.module.ModuleFacade.installDirectories(ModuleFacade.java:198) ~[classes/:na]
    at cz.cuni.xrg.intlib.commons.app.module.ModuleFacade.start(ModuleFacade.java:66) ~[classes/:na]
    ... 62 common frames omitted
```

**Comment by janvojt** [comment]
The problem occurs only when executing `clean` before `install` target. Directory `target` is deleted during clean, however it is not recreated in the commons-app `install` target. Seems like this directory is created elsewhere. Solution would then probably be to put building of this module before the build of commons-app. (If you use skipTests profile, everything seems to work fine).

**Comment by skodapetr** [comment]
Well it's not so easy as the library folder contains for example commons-web which (in project hierarchy) is descendant of commons/app. So it's little bit circle dependency during test phase. 

But as OSGI is not used during tests as far as I know . I disable it's automatic start up in test-context.

**Comment by janvojt** [comment]
Retest OK.
