### ISSUE TITLE
Problem with DPU dialog implementation appears cannot be differentiate from a problem with the core app 

### ISSUE THREAD

**Issue by tomas-knap** [mff-uk/odcs#421]
I was preparing dialog for SILK extractor and did some mistake when designing the dialog. When I click on DPU template -Silk, I got message: 

![screen shot 2013-09-08 at 12 07 34 pm](https://f.cloud.github.com/assets/3014917/1102911/b4c0c798-186e-11e3-9afe-6b60933b0fe0.png)

From such message, it is not clear whether the problem is in the core application of DPU itself (more probable). So the stacktrace must be analyzed and the error message should clearly state that there is some problem in the DPU dialog, on line XX, short description YY.

**Comment by bogo777** [comment]
Added custom error notification for loading DPU dialog.
But I do not know, how to find the right exception in stack to show line XX.
I made error in buyer-profiles dialog and got this exception:

java.lang.IllegalArgumentException: Component cannot be added inside it's own content
    at com.vaadin.ui.AbstractComponentContainer.addComponent(AbstractComponentContainer.java:204) ~[vaadin-server-7.1.0.jar:7.1.0]
    at com.vaadin.ui.GridLayout.addComponent(GridLayout.java:231) ~[vaadin-server-7.1.0.jar:7.1.0]
    at com.vaadin.ui.GridLayout.addComponent(GridLayout.java:297) ~[vaadin-server-7.1.0.jar:7.1.0]
    at com.vaadin.ui.GridLayout.addComponent(GridLayout.java:369) ~[vaadin-server-7.1.0.jar:7.1.0]
    at cz.opendata.linked.buyer_profiles.ExtractorDialog.buildMainLayout(ExtractorDialog.java:75) ~[na:na]
    at cz.opendata.linked.buyer_profiles.ExtractorDialog.<init>(ExtractorDialog.java:32) ~[na:na]
    at cz.opendata.linked.buyer_profiles.Extractor.getConfigurationDialog(Extractor.java:48) ~[na:na]
    at cz.cuni.xrg.intlib.frontend.auxiliaries.dpu.DPURecordWrap.loadConfigDialog(DPURecordWrap.java:89) ~[DPURecordWrap.class:na]
    at cz.cuni.xrg.intlib.frontend.auxiliaries.dpu.DPURecordWrap.getDialog(DPURecordWrap.java:49) ~[DPURecordWrap.class:na]
    at cz.cuni.xrg.intlib.frontend.auxiliaries.dpu.DPUTemplateWrap.getDialog(DPUTemplateWrap.java:13) ~[DPUTemplateWrap.class:na]
    at cz.cuni.xrg.intlib.frontend.gui.views.DPU.buildDPUDetailLayout(DPU.java:391) [DPU.class:na]
    at cz.cuni.xrg.intlib.frontend.gui.views.DPU.selectNewDPU(DPU.java:338) [DPU.class:na]
    at cz.cuni.xrg.intlib.frontend.gui.views.DPU.access$400(DPU.java:77) [DPU.class:na]
    at cz.cuni.xrg.intlib.frontend.gui.views.DPU$4.itemClick(DPU.java:300) [DPU$4.class:na]
    at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method) ~[na:1.7.0_21]
    at sun.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:57) ~[na:1.7.0_21]
    at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43) ~[na:1.7.0_21]
    at java.lang.reflect.Method.invoke(Method.java:601) ~[na:1.7.0_21]
    at com.vaadin.event.ListenerMethod.receiveEvent(ListenerMethod.java:508) [vaadin-server-7.1.0.jar:7.1.0]
    at com.vaadin.event.EventRouter.fireEvent(EventRouter.java:167) [vaadin-server-7.1.0.jar:7.1.0]
    at com.vaadin.server.AbstractClientConnector.fireEvent(AbstractClientConnector.java:968) [vaadin-server-7.1.0.jar:7.1.0]
    at com.vaadin.ui.Tree.changeVariables(Tree.java:470) [vaadin-server-7.1.0.jar:7.1.0]
    at com.vaadin.server.communication.ServerRpcHandler.changeVariables(ServerRpcHandler.java:403) [vaadin-server-7.1.0.jar:7.1.0]
    at com.vaadin.server.communication.ServerRpcHandler.handleBurst(ServerRpcHandler.java:228) [vaadin-server-7.1.0.jar:7.1.0]
    at com.vaadin.server.communication.ServerRpcHandler.handleRpc(ServerRpcHandler.java:111) [vaadin-server-7.1.0.jar:7.1.0]
    at com.vaadin.server.communication.PushHandler$2.run(PushHandler.java:158) [vaadin-server-7.1.0.jar:7.1.0]
    at com.vaadin.server.communication.PushHandler.callWithUi(PushHandler.java:289) [vaadin-server-7.1.0.jar:7.1.0]
    at com.vaadin.server.communication.PushHandler.onRequest(PushHandler.java:308) [vaadin-server-7.1.0.jar:7.1.0]
    at cz.cuni.xrg.intlib.frontend.IntlibPushHandler.onRequest(IntlibPushHandler.java:44) [IntlibPushHandler.class:na]
    at org.atmosphere.cpr.AsynchronousProcessor.action(AsynchronousProcessor.java:259) [atmosphere-runtime-1.0.14.vaadin3.jar:1.0.14.vaadin3]
    at org.atmosphere.cpr.AsynchronousProcessor.suspended(AsynchronousProcessor.java:166) [atmosphere-runtime-1.0.14.vaadin3.jar:1.0.14.vaadin3]
    at org.atmosphere.container.TomcatWebSocketUtil.doService(TomcatWebSocketUtil.java:137) [atmosphere-runtime-1.0.14.vaadin3.jar:1.0.14.vaadin3]
    at org.atmosphere.container.Tomcat7AsyncSupportWithWebSocket.service(Tomcat7AsyncSupportWithWebSocket.java:59) [atmosphere-runtime-1.0.14.vaadin3.jar:1.0.14.vaadin3]
    at org.atmosphere.cpr.AtmosphereFramework.doCometSupport(AtmosphereFramework.java:1448) [atmosphere-runtime-1.0.14.vaadin3.jar:1.0.14.vaadin3]
    at org.atmosphere.websocket.DefaultWebSocketProcessor.dispatch(DefaultWebSocketProcessor.java:219) [atmosphere-runtime-1.0.14.vaadin3.jar:1.0.14.vaadin3]
    at org.atmosphere.websocket.DefaultWebSocketProcessor$2.run(DefaultWebSocketProcessor.java:183) [atmosphere-runtime-1.0.14.vaadin3.jar:1.0.14.vaadin3]
    at org.atmosphere.util.VoidExecutorService.execute(VoidExecutorService.java:101) [atmosphere-runtime-1.0.14.vaadin3.jar:1.0.14.vaadin3]
    at org.atmosphere.websocket.DefaultWebSocketProcessor.dispatch(DefaultWebSocketProcessor.java:178) [atmosphere-runtime-1.0.14.vaadin3.jar:1.0.14.vaadin3]
    at org.atmosphere.websocket.DefaultWebSocketProcessor.invokeWebSocketProtocol(DefaultWebSocketProcessor.java:167) [atmosphere-runtime-1.0.14.vaadin3.jar:1.0.14.vaadin3]
    at org.atmosphere.container.TomcatWebSocketHandler.onTextMessage(TomcatWebSocketHandler.java:92) [atmosphere-runtime-1.0.14.vaadin3.jar:1.0.14.vaadin3]
    at org.apache.catalina.websocket.MessageInbound.onTextData(MessageInbound.java:74) [catalina.jar:7.0.34]
    at org.apache.catalina.websocket.StreamInbound.doOnTextData(StreamInbound.java:186) [catalina.jar:7.0.34]
    at org.apache.catalina.websocket.StreamInbound.onData(StreamInbound.java:134) [catalina.jar:7.0.34]
    at org.apache.coyote.http11.upgrade.UpgradeProcessor.upgradeDispatch(UpgradeProcessor.java:83) [tomcat-coyote.jar:7.0.34]
    at org.apache.coyote.AbstractProtocol$AbstractConnectionHandler.process(AbstractProtocol.java:587) [tomcat-coyote.jar:7.0.34]
    at org.apache.tomcat.util.net.JIoEndpoint$SocketProcessor.run(JIoEndpoint.java:310) [tomcat-coyote.jar:7.0.34]
    at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1145) [na:1.7.0_21]
    at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:615) [na:1.7.0_21]
    at java.lang.Thread.run(Thread.java:722) [na:1.7.0_21]

I guess what would be nice to show is location of this:
at cz.opendata.linked.buyer_profiles.ExtractorDialog.buildMainLayout(ExtractorDialog.java:75) ~[na:na]
But it is in the middle of the stack...

**Comment by tomas-knap** [comment]
yes, that is true, one option is to select first X lines from the stack trace, alternatively, if the packages for dpus would have certain naming conventions, we can grep only the relevant messages. Or we should wrap all DPU exceptions to our exception DPUException, so that we know which part of the stack is from the dpu - we can then provide info that error occurs in DPU and user may click and get detail - stack trace associated with his DPU execution. That would be the best I think

**Comment by tomas-knap** [comment]
Explore how to customize error messages, so that we can show main message, stack trace hidable, email to admin etc. Customization will be useful to support custom behavior when dealing with exceptions. For example, Petr may parse the exception above in DPURecordWrap and throw our custom rich exception

**Comment by tomas-knap** [comment]
Bohuslav, is there any way how to customize the error message as described in the prev commment?

**Comment by bogo777** [comment]
Vaadin's Notifications aren't that customizable -> There are 2 strings, which are shown, which can contain HTML, and the visual can be styled by CSS.
Email as link should not be a problem, but hideable stack trace will. We could use Window class(used for details - DPU, Record,...), for showing all that.
Maybe not customization, but template for error messages would be better - Every exception has message and stack trace, email to admin is known from app. So it is maybe more about how error mesage should look always.

**Comment by tomas-knap** [comment]
Probably it would be nicer if we have our own dialog for that. But then, we should have such dialog for all big red error messages. I am putting this issue to 0.4
