### ISSUE TITLE
Weird backend exception

### ISSUE THREAD

**Issue by jakubklimek** [mff-uk/odcs#432]
I ran backend and got this exception. However, I could not reproduce it:

<pre><code>11:38:17 [main] INFO  c.c.x.i.b.execution.Engine - Working dir: C:\Users\Kuba\Documents\GitHub\intlib\backend\working
11:38:19 [main] INFO  c.c.x.i.backend.AppEntry - Starting TCP/IP server ...
11:38:19 [main] INFO  c.c.x.i.backend.AppEntry - Heartbeat is running ... 
11:38:19 [main] INFO  c.c.x.i.backend.AppEntry - Module's directory: C:\Users\Kuba\Documents\GitHub\intlib\target\
11:38:19 [main] INFO  c.c.x.i.backend.AppEntry - Listening on port: 5010
11:38:19 [main] INFO  c.c.x.i.backend.AppEntry - Running ...
Exception in thread "pool-1-thread-1" java.lang.RuntimeException: java.io.EOFException
    at cz.cuni.xrg.intlib.backend.communication.ClientCommunicator.run(ClientCommunicator.java:51)
    at java.util.concurrent.ThreadPoolExecutor.runWorker(Unknown Source)
    at java.util.concurrent.ThreadPoolExecutor$Worker.run(Unknown Source)
    at java.lang.Thread.run(Unknown Source)
Caused by: java.io.EOFException
    at java.io.DataInputStream.readInt(Unknown Source)
    at cz.cuni.xrg.intlib.backend.communication.ClientCommunicator.run(ClientCommunicator.java:47)
    ... 3 more
</code></pre>

**Comment by tomas-knap** [comment]
Does not happen since that time
