### ISSUE TITLE
Replace DPU seems to be not working

### ISSUE THREAD

**Issue by jakubklimek** [mff-uk/odcs#461]
I had a problem in PSP.CZ dpu - i forgot to make the annotated DataUnit public. So it failed. Then I fixed the problem, replaced DPU via frontend. In the filesystem on the server, DPU had current date, so it was probably replaced there as well. However, when I ran the pipeline containing the DPU, it failed again even though the same DPU worked for me locally. It seems that somehow the old replaced DPU is running.

**Comment by skodapetr** [comment]
Unfortunately yes this is an issue. I discuss the solution with Thomas. Just to give the idea:
DPUs are loaded on demand in frontend as well as in backend, but once loaded they do not react on actions in DPU's directory. Reload DPU with every execution is not probably the right way how to deal with this .. so we have to find reliable way how frontned give backned know that he should reload the bundle. And also we need some "reload" function the will not break for running executions and so on.

**Comment by jakubklimek** [comment]
Actually, the problem was that I replaced dpu v1 with v2. v2 was copied to backend, but v1 wasn't deleted. In frontend, it showed that the dpu is v2, however, in fact, backend was still running v1. When we deleted the v1 file it failed with file not found exception

**Comment by jakubklimek** [comment]
Currently in the deployed version I also get this: https://github.com/mff-uk/intlib/issues/480

**Comment by jakubklimek** [comment]
I tried to test it but I probably ran into another issue:

1) Locally (newest version with folder watcher) tested:
When I ran ODCS without the DPU JAR in place, it wrote nothing.
When I put it there (not via frontend), backend logged a change, but pipeline still failed:

<pre><code>Loading of DPURecord implementation thrown following exception: cz.cuni.xrg.intlib.commons.app.module.ClassLoadFailedException: java.lang.ClassNotFoundException: Cannot load "cz.opendata.linked.ares.updates.Extractor" because the bundle "file:///C:\Users\Kuba\Documents\GitHub\intlib\target\dpu\Extractor_ares_updates-0.0.1.jar" cannot be resolved.
    at cz.cuni.xrg.intlib.commons.app.module.BundleContainer.loadClass(BundleContainer.java:62)
    at cz.cuni.xrg.intlib.commons.app.module.OSGIFramework.loadClass(OSGIFramework.java:229)
    at cz.cuni.xrg.intlib.commons.app.module.ModuleFacade.getObject(ModuleFacade.java:108)
    at cz.cuni.xrg.intlib.commons.app.dpu.DPURecord.loadInstance(DPURecord.java:119)
    at cz.cuni.xrg.intlib.backend.execution.dpu.Executor.loadInstance(Executor.java:168)
    at cz.cuni.xrg.intlib.backend.execution.dpu.Executor.loadInstance(Executor.java:339)
    at cz.cuni.xrg.intlib.backend.execution.dpu.Executor.execute(Executor.java:361)
    at cz.cuni.xrg.intlib.backend.execution.dpu.Executor.run(Executor.java:436)
    at java.lang.Thread.run(Unknown Source)
Caused by: java.lang.ClassNotFoundException: Cannot load "cz.opendata.linked.ares.updates.Extractor" because the bundle "file:///C:\Users\Kuba\Documents\GitHub\intlib\target\dpu\Extractor_ares_updates-0.0.1.jar" cannot be resolved.
    at org.eclipse.osgi.framework.internal.core.BundleHost.loadClass(BundleHost.java:227)
    at org.eclipse.osgi.framework.internal.core.AbstractBundle.loadClass(AbstractBundle.java:1212)
    at cz.cuni.xrg.intlib.commons.app.module.BundleContainer.loadClass(BundleContainer.java:60)
    ... 8 more</code></pre>

But that is caused by some missing package again, isn't it? Have you changed anything else?

2) When I played around a bit and replaced via frontend, backend logged the detected change when the upload started, not when it ended. Are you sure this is not going to be a problem?

**Comment by skodapetr** [comment]
1.1) in case of missing DPU jar file only pipeline-event (message), this information is not again logged ... but I can add at least debug information for that .. 
1.2) yes this is caused by missing package, I do not know about any change in package list since last issue about this
2.1) can be a problem .. I take a look on this

**Comment by skodapetr** [comment]
As to the 2.1 we need to resolve #480 first, then we can discuss optimal way in which detect DPU changes

1.2) Have you change the package list of that DPU? 
The steps to reproduce are: 
1) delete DPU 
2) run execution, that will fail for missing DPU
3) copy DPU back
4) run the pipeline again

**Comment by skodapetr** [comment]
2.1 we use special file now, so this should not be relevant any more
