### ISSUE TITLE
Backend exceptions

### ISSUE THREAD

**Issue by jakubklimek** [mff-uk/odcs#468]
When I recompiled backend, all my DPUs disappeared as always and I forgot about it. I ran the pipeline and it failed because it could not find the file. That is OK. I then supplied the JAR file and ran the pipeline again (without restarting). I got these exceptions (I know I have to restart, but this points to another unhandled exception point):

<pre><code>12:29:26 [pool-2-thread-4] DEBUG c.c.x.i.b.e.p.Executor - Started
Exception in thread "Thread-8" java.lang.NullPointerException
    at cz.cuni.xrg.intlib.backend.context.Context.addOutputDataUnit(Context.java:210)
    at cz.cuni.xrg.intlib.backend.execution.dpu.impl.AnnotationProcessor.annotationOutput(AnnotationProcessor.java:230)
    at cz.cuni.xrg.intlib.backend.execution.dpu.impl.AnnotationProcessor.preAction(AnnotationProcessor.java:263)
    at cz.cuni.xrg.intlib.backend.execution.dpu.Executor.executePreExecutors(Executor.java:258)
    at cz.cuni.xrg.intlib.backend.execution.dpu.Executor.execute(Executor.java:375)
    at cz.cuni.xrg.intlib.backend.execution.dpu.Executor.run(Executor.java:434)
    at java.lang.Thread.run(Unknown Source)
12:29:28 [pool-2-thread-4] DEBUG c.c.x.i.b.e.p.Executor - Execution failed
12:29:29 [pool-2-thread-4] DEBUG c.c.x.i.b.e.p.Executor - Clean up ...
Exception in thread "pool-2-thread-4" java.lang.NullPointerException
    at cz.cuni.xrg.intlib.backend.context.Context.delete(Context.java:171)
    at cz.cuni.xrg.intlib.backend.execution.pipeline.Executor.cleanup(Executor.java:219)
    at cz.cuni.xrg.intlib.backend.execution.pipeline.Executor.execute(Executor.java:374)
    at cz.cuni.xrg.intlib.backend.execution.pipeline.Executor.run(Executor.java:385)
    at java.util.concurrent.ThreadPoolExecutor.runWorker(Unknown Source)
    at java.util.concurrent.ThreadPoolExecutor$Worker.run(Unknown Source)
    at java.lang.Thread.run(Unknown Source)</code></pre>

**Comment by jakubklimek** [comment]
Actually, it did this even after backend restart.... I will investigate some more

**Comment by jakubklimek** [comment]
Yes, it is broken :)
