### ISSUE TITLE
SPARQL Loader fails when target Virtuoso fails - it should retry

### ISSUE THREAD

**Issue by jakubklimek** [mff-uk/odcs#486]
SPARQL Loader fails when target Virtuoso fails - it should retry - the same as the rest of ODCS

<pre><code>12:01:32 [Thread-9] DEBUG c.c.x.i.r.i.VirtuosoRDFRepo - Data 812/1269 part loaded successful
12:01:33 [Thread-9] DEBUG c.c.x.i.r.i.VirtuosoRDFRepo - Data 813/1269 part loaded successful
12:01:33 [Thread-9] DEBUG c.c.x.i.r.i.VirtuosoRDFRepo - Data 814/1269 part loaded successful
12:01:34 [Thread-9] DEBUG c.c.x.i.r.i.VirtuosoRDFRepo - Endpoint URL stream can not open. 
12:01:34 [Thread-9] ERROR c.c.x.i.b.e.dpu.Executor - Execution:DPUException
cz.cuni.xrg.intlib.commons.dpu.DPUException: Endpoint URL stream can not open. Connection refused: connect
    at cz.cuni.mff.xrg.intlib.loader.rdf.RDFLoader.execute(RDFLoader.java:60) ~[na:na]
    at cz.cuni.xrg.intlib.backend.execution.dpu.Executor.executeInstance(Executor.java:286) [classes/:na]
    at cz.cuni.xrg.intlib.backend.execution.dpu.Executor.execute(Executor.java:409) [classes/:na]
    at cz.cuni.xrg.intlib.backend.execution.dpu.Executor.run(Executor.java:446) [classes/:na]
    at java.lang.Thread.run(Unknown Source) ~[na:1.7.0_25]
Caused by: cz.cuni.xrg.intlib.rdf.exceptions.RDFException: Endpoint URL stream can not open. Connection refused: connect
    at cz.cuni.xrg.intlib.rdf.impl.BaseRDFRepo.getEndpointStreamReader(BaseRDFRepo.java:1864) ~[classes/:na]
    at cz.cuni.xrg.intlib.rdf.impl.BaseRDFRepo.loadDataParts(BaseRDFRepo.java:678) ~[classes/:na]
    at cz.cuni.xrg.intlib.rdf.impl.BaseRDFRepo.loadToSPARQLEndpoint(BaseRDFRepo.java:591) ~[classes/:na]
    at cz.cuni.mff.xrg.intlib.loader.rdf.RDFLoader.execute(RDFLoader.java:57) ~[na:na]
    ... 4 common frames omitted
Caused by: java.net.ConnectException: Connection refused: connect
    at java.net.DualStackPlainSocketImpl.connect0(Native Method) ~[na:1.7.0_25]
    at java.net.DualStackPlainSocketImpl.socketConnect(Unknown Source) ~[na:1.7.0_25]
    at java.net.AbstractPlainSocketImpl.doConnect(Unknown Source) ~[na:1.7.0_25]
    at java.net.AbstractPlainSocketImpl.connectToAddress(Unknown Source) ~[na:1.7.0_25]
    at java.net.AbstractPlainSocketImpl.connect(Unknown Source) ~[na:1.7.0_25]
    at java.net.PlainSocketImpl.connect(Unknown Source) ~[na:1.7.0_25]
    at java.net.SocksSocketImpl.connect(Unknown Source) ~[na:1.7.0_25]
    at java.net.Socket.connect(Unknown Source) ~[na:1.7.0_25]
    at java.net.Socket.connect(Unknown Source) ~[na:1.7.0_25]
    at sun.net.NetworkClient.doConnect(Unknown Source) ~[na:1.7.0_25]
    at sun.net.www.http.HttpClient.openServer(Unknown Source) ~[na:1.7.0_25]
    at sun.net.www.http.HttpClient.openServer(Unknown Source) ~[na:1.7.0_25]
    at sun.net.www.http.HttpClient.parseHTTPHeader(Unknown Source) ~[na:1.7.0_25]
    at sun.net.www.http.HttpClient.parseHTTP(Unknown Source) ~[na:1.7.0_25]
    at sun.net.www.protocol.http.HttpURLConnection.getInputStream(Unknown Source) ~[na:1.7.0_25]
    at java.net.HttpURLConnection.getResponseCode(Unknown Source) ~[na:1.7.0_25]
    at cz.cuni.xrg.intlib.rdf.impl.BaseRDFRepo.getEndpointStreamReader(BaseRDFRepo.java:1818) ~[classes/:na]
    ... 7 common frames omitted</code></pre>

**Comment by tomas-knap** [comment]
The commit does not solve the issue, right?

**Comment by tomesj** [comment]
Yes, you right. I wrote bad issue number to this commit.

**Comment by tomas-knap** [comment]
Nastavitelne cekani v dialogu, a umoznit zkouset donekonecna (-1)

**Comment by tomas-knap** [comment]
Treti moznost - v pripade chyby v jedne parts zkusit cele znovu

**Comment by tomas-knap** [comment]
Have to test when issue #678 is solved

**Comment by tomas-knap** [comment]
Jirko, jeste prosim otestuj jednu vec: Vypni databazi do ktere se ma loadovat. Spust pipeline s loaderem do te db. Zkontroluj, ze loader se i tak snazi o pripojeni. Pak zapni db. A napis jak to dopadlo. Udelej tohle prosim prioritne pred vsemi jinymi issues

**Comment by tomesj** [comment]
Pokouší se o připojení, ale jakmile obnovím databázi - pustím virtuoso, tak to celé spadne. 
Něco mě napadlo - kdyžtak to pak probereme :-)

**Comment by tomas-knap** [comment]
Jirko, jeste k tomu dialogu: 

![screen shot 2013-11-28 at 11 26 23 am](https://f.cloud.github.com/assets/3014917/1639016/c57b37f6-5817-11e3-91de-afcffdb18173.png)

Automaticky nastav, ze defaultne ceka 1000ms. To nesmi byt mandatory. 
Taky to uprav tak, ze kdyz da 0 do number tries, tak to proste znovu nezkusi a rovnou skonci. Az kdyz da uzivatel -1, tak to zkousi porad.

**Comment by tomesj** [comment]
Aktuálně je tam defaultně nastaveno -1 a 1000.
Musíš mít aktuální DB (configuraci obohacenou tímto nastavením - skript jsem posílal). Pokud to nemáš, je tam asi automaticky nastaveno 0,0. To bude asi i u DPU, které už se někde používají, s tím já asi nic neudělám - u nových už by to mělo být jak jsem psal - tedy defaultně -1 (nekonečno) a 1000ms.

Přidám tedy to, že když je to 0, tak se nic nezkouší a rovnou se končí :-)

**Comment by tomas-knap** [comment]
OK

**Comment by tomas-knap** [comment]
Jirko, prave jsem zkousel. SPARQL loader loadoval do DB X. Kdyz jsem ji zabil, ohlasilo mi to hlasku: 

2013-12-02 17:36:15,633 [dpu: SPARQL Loader odcs] DEBUG exec:617 dpu:408 cz.cuni.mff.xrg.odcs.loader.rdf.SPARQLoader - Data 47/100 part loaded successful
2013-12-02 17:36:15,664 [dpu: SPARQL Loader odcs] DEBUG exec:617 dpu:408 cz.cuni.mff.xrg.odcs.loader.rdf.SPARQLoader - Data 48/100 part loaded successful
2013-12-02 17:36:15,696 [dpu: SPARQL Loader odcs] DEBUG exec:617 dpu:408 cz.cuni.mff.xrg.odcs.loader.rdf.SPARQLoader - Data 49/100 part loaded successful
2013-12-02 17:36:15,819 [dpu: SPARQL Loader odcs] DEBUG exec:617 dpu:408 cz.cuni.mff.xrg.odcs.rdf.repositories.LocalRDFRepo - Endpoint URL stream cannot be opened. 
2013-12-02 17:36:15,820 [dpu: SPARQL Loader odcs] DEBUG exec:617 dpu:408 cz.cuni.mff.xrg.odcs.rdf.repositories.LocalRDFRepo - Endpoint URL stream cannot be opened. 
2013-12-02 17:36:15,821 [dpu: SPARQL Loader odcs] ERROR exec:617 dpu:408 cz.cuni.mff.xrg.odcs.backend.dpu.event.DPUMessage - DPU 'SPARQL Loader odcs' publish message short: 'Endpoint URL stream cannot be opened. Connection refused' long: ''
2013-12-02 17:36:15,830 [dpu: SPARQL Loader odcs] ERROR exec:617 dpu:408 c.c.m.x.o.b.pipeline.event.PipelineFailedEvent - Pipeline failed on DPU 'SPARQL Loader odcs' because of the exception
cz.cuni.mff.xrg.odcs.commons.dpu.DPUException: Endpoint URL stream cannot be opened. Connection refused
    at cz.cuni.mff.xrg.odcs.loader.rdf.RDFLoader.execute(RDFLoader.java:102) ~[na:na]
    at cz.cuni.mff.xrg.odcs.backend.execution.dpu.Executor.executeInstance(Executor.java:211) [backend-1.0.0.jar:na]
    at cz.cuni.mff.xrg.odcs.backend.execution.dpu.Executor.execute(Executor.java:322) [backend-1.0.0.jar:na]
    at cz.cuni.mff.xrg.odcs.backend.execution.dpu.Executor.run(Executor.java:398) [backend-1.0.0.jar:na]
    at java.lang.Thread.run(Thread.java:724) [na:1.7.0_40]
Caused by: cz.cuni.mff.xrg.odcs.rdf.exceptions.RDFException: Endpoint URL stream cannot be opened. Connection refused
    at cz.cuni.mff.xrg.odcs.rdf.repositories.BaseRDFRepo.getEndpointStreamReader(BaseRDFRepo.java:1607) ~[RDF-1.0.0.jar:na]
    at cz.cuni.mff.xrg.odcs.rdf.repositories.BaseRDFRepo.clearEndpointGraph(BaseRDFRepo.java:1443) ~[RDF-1.0.0.jar:na]
    at cz.cuni.mff.xrg.odcs.loader.rdf.SPARQLoader.loadGraphDataToEndpoint(SPARQLoader.java:260) ~[na:na]
    at cz.cuni.mff.xrg.odcs.loader.rdf.SPARQLoader.loadToSPARQLEndpoint(SPARQLoader.java:213) ~[na:na]
    at cz.cuni.mff.xrg.odcs.loader.rdf.RDFLoader.execute(RDFLoader.java:94) ~[na:na]
    ... 4 common frames omitted
Caused by: java.net.ConnectException: Connection refused
    at java.net.PlainSocketImpl.socketConnect(Native Method) ~[na:1.7.0_40]
    at java.net.AbstractPlainSocketImpl.doConnect(AbstractPlainSocketImpl.java:339) ~[na:1.7.0_40]
    at java.net.AbstractPlainSocketImpl.connectToAddress(AbstractPlainSocketImpl.java:200) ~[na:1.7.0_40]
    at java.net.AbstractPlainSocketImpl.connect(AbstractPlainSocketImpl.java:182) ~[na:1.7.0_40]
    at java.net.SocksSocketImpl.connect(SocksSocketImpl.java:392) ~[na:1.7.0_40]
    at java.net.Socket.connect(Socket.java:579) ~[na:1.7.0_40]
    at java.net.Socket.connect(Socket.java:528) ~[na:1.7.0_40]
    at sun.net.NetworkClient.doConnect(NetworkClient.java:180) ~[na:1.7.0_40]
    at sun.net.www.http.HttpClient.openServer(HttpClient.java:432) ~[na:1.7.0_40]
    at sun.net.www.http.HttpClient.openServer(HttpClient.java:527) ~[na:1.7.0_40]
    at sun.net.www.http.HttpClient.<init>(HttpClient.java:211) ~[na:1.7.0_40]
    at sun.net.www.http.HttpClient.New(HttpClient.java:308) ~[na:1.7.0_40]
    at sun.net.www.http.HttpClient.New(HttpClient.java:340) ~[na:1.7.0_40]
    at sun.net.www.protocol.http.HttpURLConnection.setNewClient(HttpURLConnection.java:663) ~[na:1.7.0_40]
    at sun.net.www.protocol.http.HttpURLConnection.setNewClient(HttpURLConnection.java:651) ~[na:1.7.0_40]
    at sun.net.www.protocol.http.HttpURLConnection.writeRequests(HttpURLConnection.java:631) ~[na:1.7.0_40]
    at sun.net.www.protocol.http.HttpURLConnection.getInputStream(HttpURLConnection.java:1321) ~[na:1.7.0_40]
    at java.net.HttpURLConnection.getResponseCode(HttpURLConnection.java:468) ~[na:1.7.0_40]
    at cz.cuni.mff.xrg.odcs.rdf.repositories.BaseRDFRepo.getEndpointStreamReader(BaseRDFRepo.java:1523) ~[RDF-1.0.0.jar:na]
    ... 8 common frames omitted
2013-12-02 17:36:15,861 [dpu: SPARQL Loader odcs] INFO  exec:617 dpu:408 cz.cuni.mff.xrg.odcs.backend.dpu.event.DPUEvent - DPU 'SPARQL Loader odcs' finished
2013-12-02 17:36:17,077 [taskExecutor-10] INFO  exec: dpu: c.c.mff.xrg.odcs.backend.logback.SqlAppenderImpl - Fetch done for 30 logs in 4 ms
2013-12-02 17:36:18,675 [pool-2-thread-6] DEBUG exec:617 dpu: c.c.m.x.o.backend.execution.pipeline.impl.CleanUp - CleanUp start .. 
2013-12-02 17:36:18,675 [pool-2-thread-6] INFO  exec:617 dpu: cz.cuni.mff.xrg.odcs.rdf.repositories.LocalRDFRepo - Save OUTPUT graph http://linked.opendata.cz/resource/odcs/internal/pipeline/exec/617/dpu/406/du/0\- in dir: /data/odcs/backend/working/617/storage/dpu_406/0
2013-12-02 17:36:18,675 [pool-2-thread-6] DEBUG exec:617 dpu: cz.cuni.mff.xrg.odcs.rdf.repositories.LocalRDFRepo - saving to directory:/data/odcs/backend/working/617/storage/dpu_406/0
2013-12-02 17:36:18,725 [pool-2-thread-6] INFO  exec:617 dpu: cz.cuni.mff.xrg.odcs.rdf.repositories.LocalRDFRepo - Releasing DPU LocalRdf: /data/odcs/backend/working/617/storage/dpu_406/0
2013-12-02 17:36:18,725 [pool-2-thread-6] INFO  exec:617 dpu: cz.cuni.mff.xrg.odcs.rdf.repositories.LocalRDFRepo - Relelased LocalRdf: /data/odcs/backend/working/617/storage/dpu_406/0
2013-12-02 17:36:18,725 [pool-2-thread-6] INFO  exec:617 dpu: cz.cuni.mff.xrg.odcs.rdf.repositories.LocalRDFRepo - Save OUTPUT graph http://linked.opendata.cz/resource/odcs/internal/pipeline/exec/617/dpu/408/du/0\- in dir: /data/odcs/backend/working/617/storage/dpu_408/0

Jak je to mozne??? Mam nastaveno opakovani na -1. Jakto, ze to nezkusi znovu? Testuj si doma dokola nasledujici scenar: 
- udelej si na localhostu novou DB
- Mas pipeline se SPARQL extractorem a loaderem. Pustis extractor, jakmile se ma pustit loader, zabijes tu DB, do ktere nahrava loader. 
- Sleduj, jak se to chova, spravne chovani je: Ohlasit problem (nelze nahrat part X/Y, problem s otevrenim endpointu napr.) a PAK to musi zkusit znovu (tedy pokud je v settings parametr pro opakovani). 

Tohle uz melo davno fungovat, to ma vysokou prioritu.

**Comment by tomesj** [comment]
Upravil jsem vše potřebné a otestoval
- nyní už to vždy doběhne a nahraje všechny trojice
- během výpadku se správně loguje, kde je chyba - že se DB pokouší připojit tam a tam, nahrát/ připravit určitý data part znovu, atd...
- dojde-li k výpadku během nahrání např. 1/16 až 13/60 part se nahrál úspěšně a při pokusu nahrát 14/60 došlo k přerušení DB...Je to opět hlášeno a po obnovení DB se pokračuje nahráním 14/60 ...až 60/60

Jediný problém je ten, že ne všechny logy se objevují ve výpise aplikace v záložce LOGS (v konzoli se ale objevují) 
- tedy například chybí info o tom, že se nahrály nějaké party, i když se ve zkutečnosti nahráli, což by mohlo někoho mást ....Či nejsou vidět všechny zalogované pokusy o navázání připojení, ale je vidět třeba 1 pak nějaká mezera a pak třeba 7,8, atd...
- tedy to by chtělo ještě nějak ošetřit, ale to už bude úkol pro někoho jiného (pokud se s tím dá něco dělat)
- v konzoli je ale vidět vše. Momentálně se všechna data i party nahrají jak mají (nedojde k žádné ztrátě)

Můžeš si to důkladně vyzkoušet - já se tomu teď docela věnoval a myslím, že z hlediska výpadků je to už OK :-) Zbývá teda dořešit jen aby bylo vidět všechno logování u nás v tabulce a ne jen v konzoli :-)

**Comment by tomas-knap** [comment]
Jirko, diky. 

Jak je mozne, ze nejake info chybi v DB mezi logy, ale je v backend.log? Je v tom nejaky rad nebo pokazde chybi neco jineho?

**Comment by skodapetr** [comment]
Jirka: Máš sample těchto logů? Tj. co chybí z čeho ..

**Comment by tomesj** [comment]
Zdravím,
ne řád v tom moc není - jednou chybí to, jednou zase něco jiného - nejlepší zkusit rovnou u sebe :-)
Žádný konkrétní příklady bohužel nemám, jen jsem na to narazil, tak jsem to zmínil, aby se to vědělo :-)

**Comment by jakubklimek** [comment]
V tom pripade na to vytvorte zvlastni issue, ne?

**Comment by tomesj** [comment]
Založil jsem na to teda extra issue: #874

**Comment by tomas-knap** [comment]
The exception does not occur. But there is still a problem with loader, see #970
