### ISSUE TITLE
Upgrade of Virtuoso JDBC driver in RDF module to version 4 causes pipeline runs to fail.

### ISSUE THREAD

**Issue by janvojt** [mff-uk/odcs#489]
RDF module is written against Virtuoso JDBC version 3 and is not compatible with version 4. Module commons-app uses version 4, and frontend includes both modules, which can cause unexpected behaviour. The resolution I see is to upgrade JDBC in RDF and make it compatible with newer version 4.

Also, failed run does not have any errors logged, which is weird.
![screenshot from 2013-09-15 23 54 14](https://f.cloud.github.com/assets/2247062/1146255/e51089cc-1e51-11e3-8ee7-b04ff0775ac8.png)

**Comment by janvojt** [comment]
Just a small remark - the newest pipeline run succeeded because I switched JDBC back to version 3 to verify the cause of the problem.

**Comment by tomesj** [comment]
When I tried use virtuoso JDBC version 4 in RDF, I got :

Exception in thread "main" java.lang.NoClassDefFoundError: virtuoso/jdbc3/VirtuosoConnectionPoolDataSource
    at virtuoso.sesame2.driver.VirtuosoRepository.<init>(VirtuosoRepository.java:56)
    at virtuoso.sesame2.driver.VirtuosoRepository.<init>(VirtuosoRepository.java:159)
    at cz.cuni.xrg.intlib.rdf.impl.VirtuosoRDFRepo.<init>(VirtuosoRDFRepo.java:62)
    at cz.cuni.xrg.intlib.rdf.data.RDFDataUnitFactory.createVirtuosoRDFRepo(RDFDataUnitFactory.java:116)
    at cz.xrg.intlib.rdf.reports.XMLReport.loadBIGDataTOEndpoint(XMLReport.java:314)
    at cz.xrg.intlib.rdf.reports.XMLReport.main(XMLReport.java:426)
Caused by: java.lang.ClassNotFoundException: virtuoso.jdbc3.VirtuosoConnectionPoolDataSource
    at java.net.URLClassLoader$1.run(URLClassLoader.java:366)
    at java.net.URLClassLoader$1.run(URLClassLoader.java:355)
    at java.security.AccessController.doPrivileged(Native Method)
    at java.net.URLClassLoader.findClass(URLClassLoader.java:354)
    at java.lang.ClassLoader.loadClass(ClassLoader.java:423)
    at sun.misc.Launcher$AppClassLoader.loadClass(Launcher.java:308)
    at java.lang.ClassLoader.loadClass(ClassLoader.java:356)
    ... 6 more

**Comment by tomesj** [comment]
I found alternative solution - if we will use last version of virtuoso provider,  we can use JDBC version 4. I was written to Tomas for solution. He have call with Austrians and try to give version we need for that.

**Comment by tomas-knap** [comment]
I think it is not a problem to have two different versions, so I would suggest to have JDBC version 3, so that we can use the sesameProvider tested and imporved by SWC. I was discussing with Alex, they do not have newer version. 

Is it a problem to have two versions?

**Comment by tomas-knap** [comment]
What is the current status of this? Jirka, which version are you using in current master branch?

**Comment by tomesj** [comment]
We actually use version 3 and provider from SWC :-)

**Comment by tomas-knap** [comment]
Ok, so frontend uses version 4 and rdf module version 3 or both use version 3?

**Comment by tomesj** [comment]
Frontend uses version 4, RDF version 3. Honza want to use same version 4.

**Comment by tomas-knap** [comment]
I will leave it for now, postponed.

**Comment by janvojt** [comment]
Actually, commons-app uses version 4, RDF uses version 3. Therefore frontend has both 3 and 4 as a dependency.

I thought this might be causing problems. However it is (functionally) OK, because these versions use different namespaces (virtuoso.jdbc4, virtuoso.jdbc3).

**Comment by janvojt** [comment]
If we want to go with 3, I guess we can close this issue. Or even better, if there is time, we can downgrade JDBC to version 3 in commons-app, to eliminate having same library in 2 different versions in one application. It should not be a problem.

**Comment by tomas-knap** [comment]
I think, it is ok as it is
