### ISSUE TITLE
When replacing JAR file with a JAR file having problem with the dialog, there is no way how to replace it further

### ISSUE THREAD

**Issue by tomas-knap** [mff-uk/odcs#515]
I prepared DPU dialog with an error in the dialog (calling setValue on readOnly text field). When I was replacing the existing (and correct) DPU JAR file with the new one, it cause the dpu template dialog to disappear completely! 

Solution: Even in case of the problems, the tab general and dpu instances should be available, so that I can e.g. replace the wrong jar with a new one. The only think which could fail is to shod the DPU template configuration. 

Please discuss with Petr

**Comment by tomas-knap** [comment]
Create DPU, with readonly text box. Then when loading configuration to the dialog, call textBox.setValue();

**Comment by kukharm** [comment]
Replace give exception

Oct 05, 2013 5:09:17 PM com.vaadin.server.DefaultErrorHandler doDefault
SEVERE: 
com.vaadin.server.UploadException: Upload failed
    at com.vaadin.server.communication.FileUploadHandler.streamToReceiver(FileUploadHandler.java:594)
    at com.vaadin.server.communication.FileUploadHandler.handleFileUploadValidationAndData(FileUploadHandler.java:432)
    at com.vaadin.server.communication.FileUploadHandler.doHandleSimpleMultipartFileUpload(FileUploadHandler.java:395)
    at com.vaadin.server.communication.FileUploadHandler.handleRequest(FileUploadHandler.java:280)
    at com.vaadin.server.VaadinService.handleRequest(VaadinService.java:1371)
    at com.vaadin.server.VaadinServlet.service(VaadinServlet.java:238)
    at cz.cuni.mff.xrg.odcs.frontend.IntlibApplicationServlet.service(IntlibApplicationServlet.java:64)
    at javax.servlet.http.HttpServlet.service(HttpServlet.java:728)
    at org.apache.catalina.core.ApplicationFilterChain.internalDoFilter(ApplicationFilterChain.java:305)
    at org.apache.catalina.core.ApplicationFilterChain.doFilter(ApplicationFilterChain.java:210)
    at org.apache.catalina.core.StandardWrapperValve.invoke(StandardWrapperValve.java:222)
    at org.apache.catalina.core.StandardContextValve.invoke(StandardContextValve.java:123)
    at org.apache.catalina.authenticator.AuthenticatorBase.invoke(AuthenticatorBase.java:472)
    at org.apache.catalina.core.StandardHostValve.invoke(StandardHostValve.java:171)
    at org.apache.catalina.valves.ErrorReportValve.invoke(ErrorReportValve.java:99)
    at org.apache.catalina.valves.AccessLogValve.invoke(AccessLogValve.java:936)
    at org.apache.catalina.core.StandardEngineValve.invoke(StandardEngineValve.java:118)
    at org.apache.catalina.connector.CoyoteAdapter.service(CoyoteAdapter.java:407)
    at org.apache.coyote.http11.AbstractHttp11Processor.process(AbstractHttp11Processor.java:1004)
    at org.apache.coyote.AbstractProtocol$AbstractConnectionHandler.process(AbstractProtocol.java:589)
    at org.apache.tomcat.util.net.JIoEndpoint$SocketProcessor.run(JIoEndpoint.java:310)
    at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1110)
    at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:603)
    at java.lang.Thread.run(Thread.java:722)
Caused by: com.vaadin.event.ListenerMethod$MethodException: Invocation of method uploadSucceeded in cz.cuni.mff.xrg.odcs.frontend.gui.AuthAwareUploadSucceededWrapper failed.
    at com.vaadin.event.ListenerMethod.receiveEvent(ListenerMethod.java:528)
    at com.vaadin.event.EventRouter.fireEvent(EventRouter.java:167)
    at com.vaadin.server.AbstractClientConnector.fireEvent(AbstractClientConnector.java:969)
    at com.vaadin.ui.Upload.fireUploadSuccess(Upload.java:811)
    at com.vaadin.ui.Upload$1.streamingFinished(Upload.java:1070)
    at com.vaadin.server.communication.FileUploadHandler.streamToReceiver(FileUploadHandler.java:567)
    ... 23 more
Caused by: com.vaadin.data.Property$ReadOnlyException
    at com.vaadin.ui.AbstractField.setValue(AbstractField.java:465)
    at com.vaadin.ui.AbstractField.setValue(AbstractField.java:445)
    at com.vaadin.ui.AbstractTextField.setValue(AbstractTextField.java:432)
    at cz.cuni.mff.xrg.odcs.loader.file.FileLoaderDialog.setConfiguration(FileLoaderDialog.java:256)
    at cz.cuni.mff.xrg.odcs.loader.file.FileLoaderDialog.setConfiguration(FileLoaderDialog.java:1)
    at cz.cuni.mff.xrg.odcs.commons.module.dialog.BaseConfigDialog.setConfig(BaseConfigDialog.java:41)
    at cz.cuni.mff.xrg.odcs.frontend.auxiliaries.dpu.DPURecordWrap.loadConfigIntoDialog(DPURecordWrap.java:124)
    at cz.cuni.mff.xrg.odcs.frontend.auxiliaries.dpu.DPURecordWrap.configuredDialog(DPURecordWrap.java:75)
    at cz.cuni.mff.xrg.odcs.frontend.auxiliaries.dpu.DPUTemplateWrap.configuredDialog(DPUTemplateWrap.java:1)
    at cz.cuni.mff.xrg.odcs.frontend.gui.views.DPU.buildDPUDetailLayout(DPU.java:398)
    at cz.cuni.mff.xrg.odcs.frontend.gui.views.DPU.selectNewDPU(DPU.java:936)
    at cz.cuni.mff.xrg.odcs.frontend.gui.views.DPU.access$12(DPU.java:924)
    at cz.cuni.mff.xrg.odcs.frontend.gui.views.DPU$7.uploadSucceeded(DPU.java:563)
    at cz.cuni.mff.xrg.odcs.frontend.gui.AuthAwareUploadSucceededWrapper.uploadSucceeded(AuthAwareUploadSucceededWrapper.java:44)
    at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
    at sun.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:57)
    at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
    at java.lang.reflect.Method.invoke(Method.java:601)
    at com.vaadin.event.ListenerMethod.receiveEvent(ListenerMethod.java:508)
    ... 28 more
