### ISSUE TITLE
RDF extractor - in case of errors, there should be two options how to behave:

### ISSUE THREAD

**Issue by tomas-knap** [mff-uk/odcs#517]
On one of the pipelines, there was invalid rdf file containing wrong URI. However, this was just one file from hundreds of files. But extractor throws an exception and ends. 

Solution: Add choice to extractor's dialog whether it should fail after the first exception occurs or whether it logs the errors as warnings and omits such data in the result (similarly as in case of SPARQL laoder, where there are also two choices - skip problematic parts or end when problematic part occurs). 

5:45:50 [Thread-13] DEBUG c.c.x.i.c.m.u.DataUnitUtils - File path /Users/tomasknap/Documents/PROJECTS/ETL-SWProj/intlib/backend/working/78/working/dpu_19/tmp/6out.ttl
15:45:50 [Thread-13] ERROR o.o.r.h.ParseErrorLogger - [Rio fatal] Not a valid (absolute) URI:  (68, -1)
15:45:50 [Thread-13] DEBUG c.c.x.i.r.i.VirtuosoRDFRepo - Problem parsing triples
org.openrdf.repository.RepositoryException: Problem parsing triples
    at virtuoso.sesame2.driver.VirtuosoRepositoryConnection.add(VirtuosoRepositoryConnection.java:1031) ~[virtuoso-sesame-7.0.1.jar:na]
    at cz.cuni.xrg.intlib.rdf.impl.BaseRDFRepo.addInputStreamToRepository(BaseRDFRepo.java:2096) [RDF-0.0.1.jar:na]
    at cz.cuni.xrg.intlib.rdf.impl.BaseRDFRepo.addFileToRepository(BaseRDFRepo.java:2121) [RDF-0.0.1.jar:na]
    at cz.cuni.xrg.intlib.rdf.impl.BaseRDFRepo.extractFromFile(BaseRDFRepo.java:263) [RDF-0.0.1.jar:na]
    at cz.cuni.xrg.intlib.rdf.impl.BaseRDFRepo.extractFromFile(BaseRDFRepo.java:144) [RDF-0.0.1.jar:na]
    at cz.cuni.xrg.intlib.rdf.impl.BaseRDFRepo.addFromTurtleFile(BaseRDFRepo.java:158) [RDF-0.0.1.jar:na]
    at cz.cuni.mff.xrg.intlib.extractor.simplexslt.SimpleXSLT.execute(SimpleXSLT.java:193) [bundlefile:na]
    at cz.cuni.xrg.intlib.backend.execution.dpu.Executor.executeInstance(Executor.java:286) [backend-0.0.1.jar:na]
    at cz.cuni.xrg.intlib.backend.execution.dpu.Executor.execute(Executor.java:409) [backend-0.0.1.jar:na]
    at cz.cuni.xrg.intlib.backend.execution.dpu.Executor.run(Executor.java:446) [backend-0.0.1.jar:na]
    at java.lang.Thread.run(Thread.java:722) [na:1.7.0_21]
Caused by: org.openrdf.rio.RDFParseException: Not a valid (absolute) URI:  [line 68]
    at org.openrdf.rio.helpers.RDFParserBase.reportFatalError(RDFParserBase.java:623) ~[sesame-rio-api-2.7.0-beta1.jar:na]
    at org.openrdf.rio.turtle.TurtleParser.reportFatalError(TurtleParser.java:1114) ~[sesame-rio-turtle-2.7.0-beta1.jar:na]
    at org.openrdf.rio.helpers.RDFParserBase.createURI(RDFParserBase.java:341) ~[sesame-rio-api-2.7.0-beta1.jar:na]
    at org.openrdf.rio.helpers.RDFParserBase.resolveURI(RDFParserBase.java:328) ~[sesame-rio-api-2.7.0-beta1.jar:na]
    at org.openrdf.rio.turtle.TurtleParser.parseURI(TurtleParser.java:855) ~[sesame-rio-turtle-2.7.0-beta1.jar:na]
    at org.openrdf.rio.turtle.TurtleParser.parseValue(TurtleParser.java:525) ~[sesame-rio-turtle-2.7.0-beta1.jar:na]
    at org.openrdf.rio.turtle.TurtleParser.parseSubject(TurtleParser.java:360) ~[sesame-rio-turtle-2.7.0-beta1.jar:na]
    at org.openrdf.rio.turtle.TurtleParser.parseTriples(TurtleParser.java:299) ~[sesame-rio-turtle-2.7.0-beta1.jar:na]
    at org.openrdf.rio.turtle.TurtleParser.parseStatement(TurtleParser.java:208) ~[sesame-rio-turtle-2.7.0-beta1.jar:na]
    at org.openrdf.rio.turtle.TurtleParser.parse(TurtleParser.java:186) ~[sesame-rio-turtle-2.7.0-beta1.jar:na]
    at virtuoso.sesame2.driver.VirtuosoRepositoryConnection.add(VirtuosoRepositoryConnection.java:1025) ~[virtuoso-sesame-7.0.1.jar:na]
    ... 10 common frames omitted
Caused by: java.lang.IllegalArgumentException: Not a valid (absolute) URI: 
    at org.openrdf.model.impl.URIImpl.setURIString(URIImpl.java:68) ~[sesame-model-2.7.0-beta1.jar:na]
    at org.openrdf.model.impl.URIImpl.<init>(URIImpl.java:57) ~[sesame-model-2.7.0-beta1.jar:na]
    at org.openrdf.model.impl.ValueFactoryImpl.createURI(ValueFactoryImpl.java:38) ~[sesame-model-2.7.0-beta1.jar:na]
    at org.openrdf.rio.helpers.RDFParserBase.createURI(RDFParserBase.java:338) ~[sesame-rio-api-2.7.0-beta1.jar:na]
    ... 18 common frames omitted
15:45:50 [Thread-13] ERROR c.c.x.i.b.e.dpu.Executor - Execution:DataUnitException
cz.cuni.xrg.intlib.rdf.exceptions.RDFException: Error by adding file to repository Problem parsing triples
    at cz.cuni.xrg.intlib.rdf.impl.BaseRDFRepo.addFileToRepository(BaseRDFRepo.java:2143) ~[RDF-0.0.1.jar:na]
    at cz.cuni.xrg.intlib.rdf.impl.BaseRDFRepo.extractFromFile(BaseRDFRepo.java:263) ~[RDF-0.0.1.jar:na]
    at cz.cuni.xrg.intlib.rdf.impl.BaseRDFRepo.extractFromFile(BaseRDFRepo.java:144) ~[RDF-0.0.1.jar:na]
    at cz.cuni.xrg.intlib.rdf.impl.BaseRDFRepo.addFromTurtleFile(BaseRDFRepo.java:158) ~[RDF-0.0.1.jar:na]
    at cz.cuni.mff.xrg.intlib.extractor.simplexslt.SimpleXSLT.execute(SimpleXSLT.java:193) ~[na:na]
    at cz.cuni.xrg.intlib.backend.execution.dpu.Executor.executeInstance(Executor.java:286) [backend-0.0.1.jar:na]
    at cz.cuni.xrg.intlib.backend.execution.dpu.Executor.execute(Executor.java:409) [backend-0.0.1.jar:na]
    at cz.cuni.xrg.intlib.backend.execution.dpu.Executor.run(Executor.java:446) [backend-0.0.1.jar:na]
    at java.lang.Thread.run(Thread.java:722) [na:1.7.0_21]
Caused by: org.openrdf.repository.RepositoryException: Problem parsing triples
    at virtuoso.sesame2.driver.VirtuosoRepositoryConnection.add(VirtuosoRepositoryConnection.java:1031) ~[virtuoso-sesame-7.0.1.jar:na]
    at cz.cuni.xrg.intlib.rdf.impl.BaseRDFRepo.addInputStreamToRepository(BaseRDFRepo.java:2096) ~[RDF-0.0.1.jar:na]
    at cz.cuni.xrg.intlib.rdf.impl.BaseRDFRepo.addFileToRepository(BaseRDFRepo.java:2121) ~[RDF-0.0.1.jar:na]
    ... 8 common frames omitted
Caused by: org.openrdf.rio.RDFParseException: Not a valid (absolute) URI:  [line 68]
    at org.openrdf.rio.helpers.RDFParserBase.reportFatalError(RDFParserBase.java:623) ~[sesame-rio-api-2.7.0-beta1.jar:na]
    at org.openrdf.rio.turtle.TurtleParser.reportFatalError(TurtleParser.java:1114) ~[sesame-rio-turtle-2.7.0-beta1.jar:na]
    at org.openrdf.rio.helpers.RDFParserBase.createURI(RDFParserBase.java:341) ~[sesame-rio-api-2.7.0-beta1.jar:na]
    at org.openrdf.rio.helpers.RDFParserBase.resolveURI(RDFParserBase.java:328) ~[sesame-rio-api-2.7.0-beta1.jar:na]
    at org.openrdf.rio.turtle.TurtleParser.parseURI(TurtleParser.java:855) ~[sesame-rio-turtle-2.7.0-beta1.jar:na]
    at org.openrdf.rio.turtle.TurtleParser.parseValue(TurtleParser.java:525) ~[sesame-rio-turtle-2.7.0-beta1.jar:na]
    at org.openrdf.rio.turtle.TurtleParser.parseSubject(TurtleParser.java:360) ~[sesame-rio-turtle-2.7.0-beta1.jar:na]
    at org.openrdf.rio.turtle.TurtleParser.parseTriples(TurtleParser.java:299) ~[sesame-rio-turtle-2.7.0-beta1.jar:na]
    at org.openrdf.rio.turtle.TurtleParser.parseStatement(TurtleParser.java:208) ~[sesame-rio-turtle-2.7.0-beta1.jar:na]
    at org.openrdf.rio.turtle.TurtleParser.parse(TurtleParser.java:186) ~[sesame-rio-turtle-2.7.0-beta1.jar:na]
    at virtuoso.sesame2.driver.VirtuosoRepositoryConnection.add(VirtuosoRepositoryConnection.java:1025) ~[virtuoso-sesame-7.0.1.jar:na]
    ... 10 common frames omitted
Caused by: java.lang.IllegalArgumentException: Not a valid (absolute) URI: 
    at org.openrdf.model.impl.URIImpl.setURIString(URIImpl.java:68) ~[sesame-model-2.7.0-beta1.jar:na]
    at org.openrdf.model.impl.URIImpl.<init>(URIImpl.java:57) ~[sesame-model-2.7.0-beta1.jar:na]
    at org.openrdf.model.impl.ValueFactoryImpl.createURI(ValueFactoryImpl.java:38) ~[sesame-model-2.7.0-beta1.jar:na]
    at org.openrdf.rio.helpers.RDFParserBase.createURI(RDFParserBase.java:338) ~[sesame-rio-api-2.7.0-beta1.jar:na]
    ... 18 common frames omitted
15:45:52 [pool-2-thread-1] DEBUG c.c.x.i.b.e.p.Executor - Execution failed

**Comment by tomas-knap** [comment]
Outdated - see #414
