### ISSUE TITLE
Not able to run backend 

### ISSUE THREAD

**Issue by tomesj** [mff-uk/odcs#519]
I can not run backend. I tried to delete and reload database, but the problem is still the same.

<pre> <code>
16:19:46.497 [main] INFO  c.c.x.i.c.a.m.ModuleFacade - Stopping OSGI framework ...
Exception in thread "main" org.springframework.beans.factory.BeanCreationException: Error creating bean with name 'dataUnitFactory' defined in class path resource [backend-context.xml]: Instantiation of bean failed; nested exception is org.springframework.beans.BeanInstantiationException: Could not instantiate bean class [cz.cuni.xrg.intlib.backend.data.DataUnitFactory]: No default constructor found; nested exception is java.lang.NoSuchMethodException: cz.cuni.xrg.intlib.backend.data.DataUnitFactory.<init>()
    at org.springframework.beans.factory.support.AbstractAutowireCapableBeanFactory.instantiateBean(AbstractAutowireCapableBeanFactory.java:997)
    at org.springframework.beans.factory.support.AbstractAutowireCapableBeanFactory.createBeanInstance(AbstractAutowireCapableBeanFactory.java:943)
    at org.springframework.beans.factory.support.AbstractAutowireCapableBeanFactory.doCreateBean(AbstractAutowireCapableBeanFactory.java:485)
    at org.springframework.beans.factory.support.AbstractAutowireCapableBeanFactory.createBean(AbstractAutowireCapableBeanFactory.java:456)
    at org.springframework.beans.factory.support.AbstractBeanFactory$1.getObject(AbstractBeanFactory.java:294)
    at org.springframework.beans.factory.support.DefaultSingletonBeanRegistry.getSingleton(DefaultSingletonBeanRegistry.java:225)
    at org.springframework.beans.factory.support.AbstractBeanFactory.doGetBean(AbstractBeanFactory.java:291)
    at org.springframework.beans.factory.support.AbstractBeanFactory.getBean(AbstractBeanFactory.java:193)
    at org.springframework.beans.factory.support.DefaultListableBeanFactory.preInstantiateSingletons(DefaultListableBeanFactory.java:609)
    at org.springframework.context.support.AbstractApplicationContext.finishBeanFactoryInitialization(AbstractApplicationContext.java:918)
    at org.springframework.context.support.AbstractApplicationContext.refresh(AbstractApplicationContext.java:469)
    at org.springframework.context.support.ClassPathXmlApplicationContext.<init>(ClassPathXmlApplicationContext.java:139)
    at org.springframework.context.support.ClassPathXmlApplicationContext.<init>(ClassPathXmlApplicationContext.java:83)
    at cz.cuni.xrg.intlib.backend.AppEntry.initSpring(AppEntry.java:109)
    at cz.cuni.xrg.intlib.backend.AppEntry.run(AppEntry.java:153)
    at cz.cuni.xrg.intlib.backend.AppEntry.main(AppEntry.java:219)
Caused by: org.springframework.beans.BeanInstantiationException: Could not instantiate bean class [cz.cuni.xrg.intlib.backend.data.DataUnitFactory]: No default constructor found; nested exception is java.lang.NoSuchMethodException: cz.cuni.xrg.intlib.backend.data.DataUnitFactory.<init>()
    at org.springframework.beans.factory.support.SimpleInstantiationStrategy.instantiate(SimpleInstantiationStrategy.java:72)
    at org.springframework.beans.factory.support.AbstractAutowireCapableBeanFactory.instantiateBean(AbstractAutowireCapableBeanFactory.java:990)
    ... 15 more
Caused by: java.lang.NoSuchMethodException: cz.cuni.xrg.intlib.backend.data.DataUnitFactory.<init>()
    at java.lang.Class.getConstructor0(Class.java:2730)
    at java.lang.Class.getDeclaredConstructor(Class.java:2004)
    at org.springframework.beans.factory.support.SimpleInstantiationStrategy.instantiate(SimpleInstantiationStrategy.java:67)
    ... 16 more
</code></pre>

**Comment by skodapetr** [comment]
As written in error the DataUnitFactory has no default ctor. Just create empty ctor for this class and it should be fine. 

I would do that myself .. but I have more local-commited changes that modify database .. so I do not want to push them all now. 

Then please test and close. In case of any problem .. please contact me online (skype).
