### ISSUE TITLE
Debug view - selecting inputs/outputs for browse/query, refactoring

### ISSUE THREAD

**Issue by tomas-knap** [mff-uk/odcs#520]
Bohuslave, please follow the specification/mockup:
https://grips.semantic-web.at/display/LOD2/Debug+Pipeline

**Comment by tomas-knap** [comment]
Bohuslave, so this is prepared for testing?

**Comment by bogo777** [comment]
Zatím ne, je potřeba rozhodnout pár věcí, co s tím souvisí, viz. můj poslední mail, ale zkopíruju to sem:
1. Zobrazení DPU Instance u logů - Musíme se rozhodnout, zda upravíme reprezentaci DPU instance u logů(nový sloupec pomocí triggerů), což zhorší performance při běhu pipeline, nebo to necháme tak, jak to je, což zhorší performance při zobrazování logů a znemožní třídění podle DPU Instance v tabulce(filtrovat půjde) - dpu instances v jine tab jako varchar.
2. Při práci s RDF jsem narazil na Deprecated metodu "makeConstructQueryOverRepository" která ale nemá metodu, co by jí nahrazovala, ale její funkcionalita je potřebná. (vyreseno)
3. Je zde otázka co stím stránkováním. Momentálně totiž výsledek CONSTRUCT dotazu je Graph, který má iterator, je zde tedy možnost si říci jen o určitý počet výsledků(ovšem třeba pro přeskočení na poslední stránku by bylo potřeba načíst všechna data) a výsledek SELECT dotazu je struktura takto neiterovatelná. Možnosti jak mě napadají teď:
   a) explicitně omezit každou query pro zobrazení dat pomocí LIMIT (nejjednosušší, žádný lazy-loading)
   b) stránkování s možností vždy zobrazit pouze následující stránku(+ všechny předchozí) = postupné načítání dat, tak jak uživatel stránkuje (potenciálně snadné pro CONSTRUCT dotazy(úprava na mé straně), nutná netriviální? úprava pro SELECT dotazy(Jirka))
   c) plnohodnotné stránkování (nejsložitější, nevím zda pro to má vůbec Virtuoso podporu)

**Comment by tomas-knap** [comment]
Ad 1) nechme jak je (tedy dpu instance v jine tabulce)
Ad 3) Bohuslav, use proper method for iterating over SELECT (ask jirkafor details)

**Comment by bogo777** [comment]
This should be ready, last thing to decide/implement is paging of RDF data. It point 3. in my last comment. I think only a) or b) are easily implementable.

**Comment by tomas-knap** [comment]
To realize b), there is a method executeSelectQueryAsTuples on baseRDFRepo, you may use. On the returned value, you may call next() to get more data.

But the problem in this case (b), user cannot filter the results right? Cannot sort the columns etc. I would suggest to: 
return and show all results returned by RDF store using the same approach as for logs - lazyloadingcontainer. You can easily get the desired page with results by calling e.g. Select {...} LIMIT 30 OFFSET 10 to show the content of 10.page filled with 30 query solutions.

**Comment by tomas-knap** [comment]
Do you see any problem of applying the same lazyLoading principles as for logs also to RDF data being results on the queries?

**Comment by tomas-knap** [comment]
Browse/Query tab still not working for debug mode?

**Comment by bogo777** [comment]
It works for me fine, it is only enabled on completed execution for now(?)

Question for @tomesj
I am currently implementing LazyLoadingContainer for RDF and I would need size()/count() method for MyTupleQueryResult for SELECT queries. Or maybe completely different method returning count directly, depends on what is easier...
Or is there any way to get the count now?

**Comment by bogo777** [comment]
Lazy container for RDF added, but until I have method described above, value for count of records in SELECT queries is 1000. It might cause errors while querying.

**Comment by tomas-knap** [comment]
See the prev comments, method for getting count of results, I would suggest select count(*) where {?s ?p ?o} query

**Comment by tomesj** [comment]
If I well understand, you need count of rows returns for your given SELECT query, right ?

**Comment by bogo777** [comment]
Yes for SELECT, result of method for CONSTRUCT query is Graph and it has size() method. But if this approach would be faster, we can use it for CONSTRUCT too. I guess that extracting the part after WHERE from query should make it possible to use the count(*) query for both?

**Comment by tomesj** [comment]
Right query for this:

select count (*) where {QUERY}

QUERY=original select/construct query.

I add method size to MyTupleQueryResult - its only for select. Contruct returns Graph and there is no problem to find size.

**Comment by tomesj** [comment]
I finnaly add method getResultSizeForQuery you can call on repository instance. It returns your expected size for SELECT/CONSTRUCT query.

**Comment by bogo777** [comment]
getResultSizeForQuery doesn't work for me. It always throws an InvalidQueryException. 
![image](https://f.cloud.github.com/assets/1550848/1280058/d0550f42-2f47-11e3-9fa1-67358aae1d8f.png)

**Comment by tomesj** [comment]
Sorry, I forgot one important thing. It could be worked fine now.

**Comment by bogo777** [comment]
It works, but only for CONSTRUCT queries, for SELECT I still get the same exception.

**Comment by tomesj** [comment]
Are you sure, your SELECT query is valid - I tested it with about 10 random SELECT query and there was no problem. In case of problem give me please concrete SELECT which dont pass.

**Comment by bogo777** [comment]
![image](https://f.cloud.github.com/assets/1550848/1283772/51ef1f4c-2f8a-11e3-8bb2-5db7e8084602.png)

Or any variant with 1 or 2 columns...

**Comment by tomesj** [comment]
It tested this query as first and now once again and there was no problem by me. I found only bug in case using prefixes in SELECT. But its fixed now. Are you sure, do you use last implementation ?

**Comment by tomas-knap** [comment]
Well, why you do not use simply use query "select count(*) where {?s ?p ?o}"?. I do not know if you can use CONSTRUCT query as subquery in the way above.

**Comment by tomas-knap** [comment]
Why do you need to distinguish getSize for select and construct queries?? In both cases, you can count triples by using query: "select count(*) where {?s ?p ?o}"

**Comment by tomesj** [comment]
1) CONSTRUCT can not be use as subquery for finding size - result is graph and its not problem to find its size
2) SELECT - you dont know concrete given select. 

Query "select count(*) where {?s ?p ?o}" returns always count of all triples, but you want to find out size of select that can be only subset of all triples. 

Example
Graph has 100 triples.
Your select: prefix deb: http://schema.org/ SELECT ?a ?c WHERE {?a deb:address ?c}
It returns only 5 triples.

How to find it - you have to use query:
prefix deb: http://schema.org/
SELECT count(*) as ?size WHERE {SELECT ?a ?c WHERE {?a deb:address ?c}}

and it return right count. Is it clear, now ?

**Comment by tomas-knap** [comment]
Well I don't understand. "select count(*) where {?s ?p ?o}" returns number of all triples/solutions as you wrote. 
prefix deb: http://schema.org/ SELECT count(*) WHERE {?a deb:address ?c} returns number of solutions which match the pattern. WHat else do you need?

**Comment by tomas-knap** [comment]
The query SELECT count(*) as ?size WHERE {SELECT ?a ?c WHERE {?a deb:address ?c}}

can be easily rewritten as SELECT count(*) WHERE {?a deb:address ?c}, or where is the problem?

**Comment by tomesj** [comment]
Yes you right, but I have to assume that queries can be variously plunging. 

Both these queries give the same result, but in your approach you must parse query and replace ?a ?c for count(*).

I just wrap the query and got the same result.

**Comment by tomas-knap** [comment]
Ok. Bohuslav please test these methods and update the issue

**Comment by bogo777** [comment]
Ok, it works for me fine now. 

I had older version of Virtuoso, so that was why the query didn't work.

**Comment by tomas-knap** [comment]
So can we test that?

**Comment by tomas-knap** [comment]
Bohuslav, please:

1) enlarch the space for query 
![screen shot 2013-10-09 at 6 09 53 pm](https://f.cloud.github.com/assets/3014917/1299136/b3cb3f06-30fd-11e3-8fca-ae519bfebfd7.png)

2) Always, when showing result of CONSTRUCT query, the columns should be in order subject, predicate, object. In case of SELECT query, columns should be in the order as they appear in the SELECT

![screen shot 2013-10-09 at 6 11 29 pm](https://f.cloud.github.com/assets/3014917/1299134/a8b29b1e-30fd-11e3-960f-9075d5074698.png)

3) Please add possibility to filter subject/pred/object, ordering not needed if it is a problem. But when clicking on column header, there is an arrow depicting that the columns may be sorted, however sorting is not working

4) Instead of empty comboboxes, for donwload format, always select the first option

**Comment by tomas-knap** [comment]
5) Also when I enter browse/query, specify query and click run, it works. But when i then click browse and again input query and click run, nothing was shown

**Comment by tomas-knap** [comment]
Bohuslav, if needed, delegate certain corrections to Maria.

**Comment by tomas-knap** [comment]
Bohuslav, please write what is missing in this issue, or is it ready for testing?

**Comment by bogo777** [comment]
1) and 4) is done. 5) querying works for me repeatedly
2) I can get names of all bindings from SELECT query result object, but they are not always in the order as in the query. Maybe there could be a support for it in some Query object, which would get it for me?
3) For filtering is this the right part of the query: FILTER regex(str(?object),'_substring_','i') - also should I directly modify the query string -> insert this into WHERE part of the query -> or maybe as I wrote higher, we could have some Query object which would have method like addFilter(substring) which would take care of that.

One more usage for Query object could be LIMIT -> if limit is now explicitly given in the query, it does not work, because another LIMIT is added by paging..This should be discussed with you and @tomesj

**Comment by tomas-knap** [comment]
Bohuslav regarding 2, for select, the order could be different, this is not a big problem, if the standard openRDF methods does not provide the variables as ordered list.

Regarding 3, you should call addFilter or something like that and Jirka should provide the implementation of the method. We need to discuss that with Jirka, please create issue for that. Regarding LIMIT, limit specified in the query should be taken into account when limit for the pages is set. So e.g. if LIMIT is 50 in the user's query and pages are 30, then, the second page should contain only 20 records. Please create also issue for the limit.

**Comment by tomas-knap** [comment]
When clicking browse on dbpedia pipeline

2013-10-21 13:10:24,308 [http-bio-8080-exec-1108] DEBUG org.openrdf.sail.memory.MemoryStore - MemoryStore initialized
2013-10-21 13:10:24,308 [http-bio-8080-exec-1108] INFO  cz.cuni.mff.xrg.odcs.rdf.impl.LocalRDFRepo - New local repository with data graph http://default successfully incicialized.
2013-10-21 13:10:24,308 [http-bio-8080-exec-1108] INFO  cz.cuni.mff.xrg.odcs.rdf.impl.LocalRDFRepo - LOAD INPUT graph http://default in dir: /data/odcs/backend/working/180/storage/dpu_2_RDF_File_Loader/0
2013-10-21 13:10:24,312 [http-bio-8080-exec-1108] ERROR cz.cuni.mff.xrg.odcs.frontend.AppEntry - Uncaught exception
java.lang.NullPointerException: null
    at cz.cuni.mff.xrg.odcs.frontend.container.RDFQuery.size(RDFQuery.java:50) ~[RDFQuery.class:na]
    at org.vaadin.addons.lazyquerycontainer.LazyQueryView.getQuery(LazyQueryView.java:407) ~[vaadin-lazyquerycontainer-2.0.9.jar:2.0.9]
    at org.vaadin.addons.lazyquerycontainer.LazyQueryView.getQuerySize(LazyQueryView.java:392) ~[vaadin-lazyquerycontainer-2.0.9.jar:2.0.9]
    at org.vaadin.addons.lazyquerycontainer.LazyQueryView.size(LazyQueryView.java:219) ~[vaadin-lazyquerycontainer-2.0.9.jar:2.0.9]
    at org.vaadin.addons.lazyquerycontainer.LazyQueryContainer.size(LazyQueryContainer.java:183) ~[vaadin-lazyquerycontainer-2.0.9.jar:2.0.9]
    at cz.cuni.mff.xrg.odcs.frontend.gui.components.RDFQueryView.runQuery(RDFQueryView.java:259) ~[RDFQueryView.class:na]
    at cz.cuni.mff.xrg.odcs.frontend.gui.components.RDFQueryView.browseDataUnit(RDFQueryView.java:277) ~[RDFQueryView.class:na]
    at cz.cuni.mff.xrg.odcs.frontend.gui.components.RDFQueryView.access$000(RDFQueryView.java:47) ~[RDFQueryView.class:na]
    at cz.cuni.mff.xrg.odcs.frontend.gui.components.RDFQueryView$1.componentEvent(RDFQueryView.java:80) ~[RDFQueryView$1.class:na]
    at cz.cuni.mff.xrg.odcs.frontend.gui.components.DataUnitSelector.fireEvent(DataUnitSelector.java:126) ~[DataUnitSelector.class:na]
    at cz.cuni.mff.xrg.odcs.frontend.gui.components.DataUnitSelector.access$300(DataUnitSelector.java:29) ~[DataUnitSelector.class:na]
    at cz.cuni.mff.xrg.odcs.frontend.gui.components.DataUnitSelector$4.buttonClick(DataUnitSelector.java:107) ~[DataUnitSelector$4.class:na]
    at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method) ~[na:1.7.0_40]
    at sun.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:57) ~[na:1.7.0_40]
    at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43) ~[na:1.7.0_40]
    at java.lang.reflect.Method.invoke(Method.java:606) ~[na:1.7.0_40]
    at com.vaadin.event.ListenerMethod.receiveEvent(ListenerMethod.java:508) ~[vaadin-server-7.1.5.jar:7.1.5]
    at com.vaadin.event.EventRouter.fireEvent(EventRouter.java:167) ~[vaadin-server-7.1.5.jar:7.1.5]
    at com.vaadin.server.AbstractClientConnector.fireEvent(AbstractClientConnector.java:969) ~[vaadin-server-7.1.5.jar:7.1.5]
    at com.vaadin.ui.Button.fireClick(Button.java:368) ~[vaadin-server-7.1.5.jar:7.1.5]
    at com.vaadin.ui.Button$1.click(Button.java:57) ~[vaadin-server-7.1.5.jar:7.1.5]
    at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method) ~[na:1.7.0_40]
    at sun.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:57) ~[na:1.7.0_40]
    at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43) ~[na:1.7.0_40]
    at java.lang.reflect.Method.invoke(Method.java:606) ~[na:1.7.0_40]
    at com.vaadin.server.ServerRpcManager.applyInvocation(ServerRpcManager.java:168) ~[vaadin-server-7.1.5.jar:7.1.5]
    at com.vaadin.server.ServerRpcManager.applyInvocation(ServerRpcManager.java:118) ~[vaadin-server-7.1.5.jar:7.1.5]
    at com.vaadin.server.communication.ServerRpcHandler.handleBurst(ServerRpcHandler.java:214) [vaadin-server-7.1.5.jar:7.1.5]
    at com.vaadin.server.communication.ServerRpcHandler.handleRpc(ServerRpcHandler.java:111) [vaadin-server-7.1.5.jar:7.1.5]
    at com.vaadin.server.communication.PushHandler$2.run(PushHandler.java:158) [vaadin-server-7.1.5.jar:7.1.5]
    at com.vaadin.server.communication.PushHandler.callWithUi(PushHandler.java:289) [vaadin-server-7.1.5.jar:7.1.5]
    at com.vaadin.server.communication.PushHandler.onRequest(PushHandler.java:308) [vaadin-server-7.1.5.jar:7.1.5]
    at cz.cuni.mff.xrg.odcs.frontend.IntlibPushHandler.onRequest(IntlibPushHandler.java:44) [IntlibPushHandler.class:na]
    at org.atmosphere.cpr.AsynchronousProcessor.action(AsynchronousProcessor.java:259) [atmosphere-runtime-1.0.14.vaadin4.jar:1.0.14.vaadin4]
    at org.atmosphere.cpr.AsynchronousProcessor.suspended(AsynchronousProcessor.java:166) [atmosphere-runtime-1.0.14.vaadin4.jar:1.0.14.vaadin4]
    at org.atmosphere.container.TomcatWebSocketUtil.doService(TomcatWebSocketUtil.java:137) [atmosphere-runtime-1.0.14.vaadin4.jar:1.0.14.vaadin4]
    at org.atmosphere.container.Tomcat7AsyncSupportWithWebSocket.service(Tomcat7AsyncSupportWithWebSocket.java:59) [atmosphere-runtime-1.0.14.vaadin4.jar:1.0.14.vaadin4]
    at org.atmosphere.cpr.AtmosphereFramework.doCometSupport(AtmosphereFramework.java:1448) [atmosphere-runtime-1.0.14.vaadin4.jar:1.0.14.vaadin4]
    at org.atmosphere.websocket.DefaultWebSocketProcessor.dispatch(DefaultWebSocketProcessor.java:219) [atmosphere-runtime-1.0.14.vaadin4.jar:1.0.14.vaadin4]
    at org.atmosphere.websocket.DefaultWebSocketProcessor$2.run(DefaultWebSocketProcessor.java:183) [atmosphere-runtime-1.0.14.vaadin4.jar:1.0.14.vaadin4]
    at org.atmosphere.util.VoidExecutorService.execute(VoidExecutorService.java:101) [atmosphere-runtime-1.0.14.vaadin4.jar:1.0.14.vaadin4]
    at org.atmosphere.websocket.DefaultWebSocketProcessor.dispatch(DefaultWebSocketProcessor.java:178) [atmosphere-runtime-1.0.14.vaadin4.jar:1.0.14.vaadin4]
    at org.atmosphere.websocket.DefaultWebSocketProcessor.invokeWebSocketProtocol(DefaultWebSocketProcessor.java:167) [atmosphere-runtime-1.0.14.vaadin4.jar:1.0.14.vaadin4]
    at org.atmosphere.container.TomcatWebSocketHandler.onTextMessage(TomcatWebSocketHandler.java:92) [atmosphere-runtime-1.0.14.vaadin4.jar:1.0.14.vaadin4]
    at org.apache.catalina.websocket.MessageInbound.onTextData(MessageInbound.java:74) [catalina.jar:7.0.33]
    at org.apache.catalina.websocket.StreamInbound.doOnTextData(StreamInbound.java:186) [catalina.jar:7.0.33]
    at org.apache.catalina.websocket.StreamInbound.onData(StreamInbound.java:134) [catalina.jar:7.0.33]
    at org.apache.coyote.http11.upgrade.UpgradeProcessor.upgradeDispatch(UpgradeProcessor.java:83) [tomcat-coyote.jar:7.0.33]
    at org.apache.coyote.AbstractProtocol$AbstractConnectionHandler.process(AbstractProtocol.java:587) [tomcat-coyote.jar:7.0.33]
    at org.apache.tomcat.util.net.JIoEndpoint$SocketProcessor.run(JIoEndpoint.java:310) [tomcat-coyote.jar:7.0.33]
    at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1145) [na:1.7.0_40]
    at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:615) [na:1.7.0_40]
    at java.lang.Thread.run(Thread.java:724) [na:1.7.0_40]
2013-10-21 13:10:24,317 [Thread-1480] DEBUG cz.cuni.mff.xrg.odcs.rdf.impl.LocalRDFRepo - Repository with data graph http://default destroyed SUCCESSFULL.

**Comment by tomas-knap** [comment]
Please check that everything is done and close. Filtering for CONSTRUCT queries is disabled
