### ISSUE TITLE
Load from RDF/XML crashes when invalid input (only XML head)

### ISSUE THREAD

**Issue by jakubklimek** [mff-uk/odcs#550]
<pre><code>17:59:26.069 [Thread-95] DEBUG org.xml.sax.XMLReader - XMLReader initialized using JAXP: com.sun.org.apache.xerces.internal.jaxp.SAXParserImpl$JAXPSAXParser@64b4b346
[Fatal Error] :1:39: Premature end of file.
17:59:26.108 [Thread-95] ERROR o.o.r.h.ParseErrorLogger - [Rio fatal] Premature end of file. (1, 39)
17:59:26.113 [Thread-95] DEBUG c.c.x.i.r.i.VirtuosoRDFRepo - Problem parsing triples
org.openrdf.repository.RepositoryException: Problem parsing triples
        at virtuoso.sesame2.driver.VirtuosoRepositoryConnection.add(VirtuosoRepositoryConnection.java:1031) ~[virtuoso-sesame-7.0.1.jar:na]
        at cz.cuni.xrg.intlib.rdf.impl.BaseRDFRepo.addInputStreamToRepository(BaseRDFRepo.java:2129) [RDF-0.0.1.jar:na]
        at cz.cuni.xrg.intlib.rdf.impl.BaseRDFRepo.addFileToRepository(BaseRDFRepo.java:2154) [RDF-0.0.1.jar:na]
        at cz.cuni.xrg.intlib.rdf.impl.BaseRDFRepo.extractFromFile(BaseRDFRepo.java:263) [RDF-0.0.1.jar:na]
        at cz.cuni.xrg.intlib.rdf.impl.BaseRDFRepo.extractFromFile(BaseRDFRepo.java:144) [RDF-0.0.1.jar:na]
        at cz.cuni.xrg.intlib.rdf.impl.BaseRDFRepo.addFromRDFXMLFile(BaseRDFRepo.java:170) [RDF-0.0.1.jar:na]
        at cz.cuni.mff.xrg.intlib.extractor.simplexslt.SimpleXSLT.execute(SimpleXSLT.java:187) [bundlefile:na]
        at cz.cuni.xrg.intlib.backend.execution.dpu.Executor.executeInstance(Executor.java:215) [backend-0.0.1.jar:na]
        at cz.cuni.xrg.intlib.backend.execution.dpu.Executor.execute(Executor.java:321) [backend-0.0.1.jar:na]
        at cz.cuni.xrg.intlib.backend.execution.dpu.Executor.run(Executor.java:391) [backend-0.0.1.jar:na]
        at java.lang.Thread.run(Thread.java:724) [na:1.7.0_40]
Caused by: org.openrdf.rio.RDFParseException: Premature end of file. [line 1, column 39]
        at org.openrdf.rio.helpers.RDFParserBase.reportFatalError(RDFParserBase.java:623) ~[sesame-rio-api-2.7.0-beta1.jar:na]
        at org.openrdf.rio.trix.TriXParser.parse(TriXParser.java:115) ~[sesame-rio-trix-2.7.0-beta1.jar:na]
        at org.openrdf.rio.trix.TriXParser.parse(TriXParser.java:89) ~[sesame-rio-trix-2.7.0-beta1.jar:na]
        at virtuoso.sesame2.driver.VirtuosoRepositoryConnection.add(VirtuosoRepositoryConnection.java:1025) ~[virtuoso-sesame-7.0.1.jar:na]
        ... 10 common frames omitted
Caused by: org.xml.sax.SAXParseException: Premature end of file.
        at com.sun.org.apache.xerces.internal.parsers.AbstractSAXParser.parse(AbstractSAXParser.java:1236) ~[na:1.7.0_40]
        at com.sun.org.apache.xerces.internal.jaxp.SAXParserImpl$JAXPSAXParser.parse(SAXParserImpl.java:628) ~[na:1.7.0_40]
        at info.aduna.xml.SimpleSAXParser.parse(SimpleSAXParser.java:215) ~[sesame-util-2.7.0-beta1.jar:na]
        at info.aduna.xml.SimpleSAXParser.parse(SimpleSAXParser.java:202) ~[sesame-util-2.7.0-beta1.jar:na]
        at org.openrdf.rio.trix.TriXParser.parse(TriXParser.java:106) ~[sesame-rio-trix-2.7.0-beta1.jar:na]
        ... 12 common frames omitted
q
17:59:26.119 [Thread-95] ERROR c.c.x.i.b.d.event.DPUEvent - Failed to create DataUnit for DPU 'XSLT'
cz.cuni.xrg.intlib.rdf.exceptions.RDFException: Error by adding file to repository Problem parsing triples
        at cz.cuni.xrg.intlib.rdf.impl.BaseRDFRepo.addFileToRepository(BaseRDFRepo.java:2176) ~[RDF-0.0.1.jar:na]
        at cz.cuni.xrg.intlib.rdf.impl.BaseRDFRepo.extractFromFile(BaseRDFRepo.java:263) ~[RDF-0.0.1.jar:na]
        at cz.cuni.xrg.intlib.rdf.impl.BaseRDFRepo.extractFromFile(BaseRDFRepo.java:144) ~[RDF-0.0.1.jar:na]
        at cz.cuni.xrg.intlib.rdf.impl.BaseRDFRepo.addFromRDFXMLFile(BaseRDFRepo.java:170) ~[RDF-0.0.1.jar:na]
        at cz.cuni.mff.xrg.intlib.extractor.simplexslt.SimpleXSLT.execute(SimpleXSLT.java:187) ~[na:na]
        at cz.cuni.xrg.intlib.backend.execution.dpu.Executor.executeInstance(Executor.java:215) [backend-0.0.1.jar:na]
        at cz.cuni.xrg.intlib.backend.execution.dpu.Executor.execute(Executor.java:321) [backend-0.0.1.jar:na]
        at cz.cuni.xrg.intlib.backend.execution.dpu.Executor.run(Executor.java:391) [backend-0.0.1.jar:na]
        at java.lang.Thread.run(Thread.java:724) [na:1.7.0_40]
Caused by: org.openrdf.repository.RepositoryException: Problem parsing triples
        at virtuoso.sesame2.driver.VirtuosoRepositoryConnection.add(VirtuosoRepositoryConnection.java:1031) ~[virtuoso-sesame-7.0.1.jar:na]
        at cz.cuni.xrg.intlib.rdf.impl.BaseRDFRepo.addInputStreamToRepository(BaseRDFRepo.java:2129) ~[RDF-0.0.1.jar:na]
        at cz.cuni.xrg.intlib.rdf.impl.BaseRDFRepo.addFileToRepository(BaseRDFRepo.java:2154) ~[RDF-0.0.1.jar:na]
        ... 8 common frames omitted
Caused by: org.openrdf.rio.RDFParseException: Premature end of file. [line 1, column 39]
        at org.openrdf.rio.helpers.RDFParserBase.reportFatalError(RDFParserBase.java:623) ~[sesame-rio-api-2.7.0-beta1.jar:na]
        at org.openrdf.rio.trix.TriXParser.parse(TriXParser.java:115) ~[sesame-rio-trix-2.7.0-beta1.jar:na]
        at org.openrdf.rio.trix.TriXParser.parse(TriXParser.java:89) ~[sesame-rio-trix-2.7.0-beta1.jar:na]
        at virtuoso.sesame2.driver.VirtuosoRepositoryConnection.add(VirtuosoRepositoryConnection.java:1025) ~[virtuoso-sesame-7.0.1.jar:na]
        ... 10 common frames omitted
Caused by: org.xml.sax.SAXParseException: Premature end of file.
        at com.sun.org.apache.xerces.internal.parsers.AbstractSAXParser.parse(AbstractSAXParser.java:1236) ~[na:1.7.0_40]
        at com.sun.org.apache.xerces.internal.jaxp.SAXParserImpl$JAXPSAXParser.parse(SAXParserImpl.java:628) ~[na:1.7.0_40]
        at info.aduna.xml.SimpleSAXParser.parse(SimpleSAXParser.java:215) ~[sesame-util-2.7.0-beta1.jar:na]
        at info.aduna.xml.SimpleSAXParser.parse(SimpleSAXParser.java:202) ~[sesame-util-2.7.0-beta1.jar:na]
        at org.openrdf.rio.trix.TriXParser.parse(TriXParser.java:106) ~[sesame-rio-trix-2.7.0-beta1.jar:na]
        ... 12 common frames omitted
</code></pre>

**Comment by tomesj** [comment]
I think where is the problem:

You call method addFromRDFXMLFile, but your file is not in format RDF/XML, but in TRIX format (I see is called TRIX parser for that). 

Method for parsing  right choise parser for file name suffix (e.g. file.ttl - is choosed TURTLE parser, file.rdf - is choosed RDF/XML parser, ...).

If file has no prefix, default parser is set as name method => addFromRDFXML = RDF/XML parser, addFromTurtle = TTL parser...

So, if you have file in TRIX format - add trig suffix for file and try it again - it could be fine :-)

**Comment by tomas-knap** [comment]
Jirka, 

please test the method addFromRDFXMLFile. IT should consume RDF/XML file and add such file to RDF rep. Please verify that and write here as soon as possible. 

In RDF File extractor/loader, the format of file is determined automatically or user may select from combo box, that is fine. But when calling from anywhere method addFromRDFXMLFile, it must consume RDFXML file. Check that please

**Comment by tomesj** [comment]
OK, I check it now, but I think that consume RDF/XML file :-)

**Comment by tomas-knap** [comment]
See #563
