### ISSUE TITLE
When updating DPU while it is in use

### ISSUE THREAD

**Issue by tomas-knap** [mff-uk/odcs#556]
12:15:59.377 [Thread-3] DEBUG c.c.x.i.c.a.m.o.OSGIChangeManager - Udating DPU in: Simple_XSLT
12:15:59.640 [Thread-3] DEBUG c.c.x.i.c.a.m.i.FileNotifierClient - Failed to delete notification file.
java.nio.file.NoSuchFileException: /data/odcs/target/dpu/Simple_XSLT/Simple_XSLT-0.0.1.jar.update
 at sun.nio.fs.UnixException.translateToIOException(UnixException.java:86) ~[na:1.7.0_40]
 at sun.nio.fs.UnixException.rethrowAsIOException(UnixException.java:102) ~[na:1.7.0_40]
 at sun.nio.fs.UnixException.rethrowAsIOException(UnixException.java:107) ~[na:1.7.0_40]
 at sun.nio.fs.UnixFileSystemProvider.implDelete(UnixFileSystemProvider.java:244) ~[na:1.7.0_40]
 at sun.nio.fs.AbstractFileSystemProvider.delete(AbstractFileSystemProvider.java:103) ~[na:1.7.0_40]
 at java.nio.file.Files.delete(Files.java:1077) ~[na:1.7.0_40]
 at cz.cuni.xrg.intlib.commons.app.module.impl.FileNotifierServer.onNotification(FileNotifierServer.java:270) [commons-app-0.0.1.jar:na]
 at cz.cuni.xrg.intlib.commons.app.module.impl.FileNotifierServer.run(FileNotifierServer.java:318) [commons-app-0.0.1.jar:na]
 at java.lang.Thread.run(Thread.java:724) [na:1.7.0_40]

**Comment by skodapetr** [comment]
Yes it is possible. It is just a debug message. The reason is simple. As we do not know if backend, frontned is running both try to delete this file. So one of them must fail. But I can remove this message from log. 

Prevent such behaviour would require to know who is backend and who not .. like backend try to delete after 1 second and frontend immediately. Should we try this approach?

**Comment by jakubklimek** [comment]
Well.. it is a stack trace = critical error that needs to be looked into, results produced from this point are not safe.

If you know that this can happen, you need to catch the exception and write a user-friendly message like "I tried to delete xxx and failed, but is is ok as ... probably deleted it before me"

And why do they both try to delete?

**Comment by skodapetr** [comment]
Both utilize the same FileNotifierServer.
The server watch directory and if file is created then publish notification event and try to delete the notification directory. So the communication medium is file system.

The problem is that we do not know if run only backend, only frontned or both are running. So every instance try to delete for case that it's the only running instance of FileNotifierServer.
