### ISSUE TITLE
schedulig rule creation exception

### ISSUE THREAD

**Issue by kukharm** [mff-uk/odcs#568]
I tried to create scheduling rule and got exception

[EL Warning]: 2013-10-01 00:18:05.531--UnitOfWork(18432983)--Exception [EclipseLink-4002](Eclipse Persistence Services - 2.5.1.v20130824-981335c): org.eclipse.persistence.exceptions.DatabaseException
Internal Exception: virtuoso.jdbc4.VirtuosoException: SR133: Can not set NULL to not nullable column 'DB.INTLIB.SCH_SCH_NOTIFICATION.schedule_id'
Error Code: -8
Call: INSERT INTO sch_sch_notification (ID, type_error, type_success, schedule_id) VALUES (?, ?, ?, ?)
    bind => [4 parameters bound]
Query: InsertObjectQuery(cz.cuni.mff.xrg.odcs.commons.app.scheduling.ScheduleNotificationRecord@16f05e8)
00:18:05.537 [http-bio-8080-exec-9] ERROR c.c.m.x.o.f.AppEntry - Uncaught exception
virtuoso.jdbc4.VirtuosoException: SR133: Can not set NULL to not nullable column 'DB.INTLIB.SCH_SCH_NOTIFICATION.schedule_id'
    at virtuoso.jdbc4.VirtuosoResultSet.process_result(Unknown Source) ~[jdbc-driver-4.jar:na]
    at virtuoso.jdbc4.VirtuosoResultSet.getMoreResults(Unknown Source) ~[jdbc-driver-4.jar:na]
    at virtuoso.jdbc4.VirtuosoPreparedStatement.sendQuery(Unknown Source) ~[jdbc-driver-4.jar:na]
    at virtuoso.jdbc4.VirtuosoPreparedStatement.executeUpdate(Unknown Source) ~[jdbc-driver-4.jar:na]
    at org.eclipse.persistence.internal.databaseaccess.DatabaseAccessor.executeDirectNoSelect(DatabaseAccessor.java:890) ~[eclipselink-2.5.1-RC1.jar:2.5.1.v20130824-981335c]
    at org.eclipse.persistence.internal.databaseaccess.DatabaseAccessor.executeNoSelect(DatabaseAccessor.java:962) ~[eclipselink-2.5.1-RC1.jar:2.5.1.v20130824-981335c]
    at org.eclipse.persistence.internal.databaseaccess.DatabaseAccessor.basicExecuteCall(DatabaseAccessor.java:631) ~[eclipselink-2.5.1-RC1.jar:2.5.1.v20130824-981335c]
    at org.eclipse.persistence.internal.databaseaccess.DatabaseAccessor.executeCall(DatabaseAccessor.java:558) ~[eclipselink-2.5.1-RC1.jar:2.5.1.v20130824-981335c]
    at org.eclipse.persistence.internal.sessions.AbstractSession.basicExecuteCall(AbstractSession.java:1991) ~[eclipselink-2.5.1-RC1.jar:2.5.1.v20130824-981335c]
    at org.eclipse.persistence.sessions.server.ClientSession.executeCall(ClientSession.java:298) ~[eclipselink-2.5.1-RC1.jar:2.5.1.v20130824-981335c]
    at org.eclipse.persistence.internal.queries.DatasourceCallQueryMechanism.executeCall(DatasourceCallQueryMechanism.java:242) ~[eclipselink-2.5.1-RC1.jar:2.5.1.v20130824-981335c]
    at org.eclipse.persistence.internal.queries.DatasourceCallQueryMechanism.executeCall(DatasourceCallQueryMechanism.java:228) ~[eclipselink-2.5.1-RC1.jar:2.5.1.v20130824-981335c]
    at org.eclipse.persistence.internal.queries.DatasourceCallQueryMechanism.insertObject(DatasourceCallQueryMechanism.java:377) ~[eclipselink-2.5.1-RC1.jar:2.5.1.v20130824-981335c]
    at org.eclipse.persistence.internal.queries.StatementQueryMechanism.insertObject(StatementQueryMechanism.java:165) ~[eclipselink-2.5.1-RC1.jar:2.5.1.v20130824-981335c]
    at org.eclipse.persistence.internal.queries.StatementQueryMechanism.insertObject(StatementQueryMechanism.java:180) ~[eclipselink-2.5.1-RC1.jar:2.5.1.v20130824-981335c]
    at org.eclipse.persistence.internal.queries.DatabaseQueryMechanism.insertObjectForWrite(DatabaseQueryMechanism.java:489) ~[eclipselink-2.5.1-RC1.jar:2.5.1.v20130824-981335c]
    at org.eclipse.persistence.queries.InsertObjectQuery.executeCommit(InsertObjectQuery.java:80) ~[eclipselink-2.5.1-RC1.jar:2.5.1.v20130824-981335c]
    at org.eclipse.persistence.queries.InsertObjectQuery.executeCommitWithChangeSet(InsertObjectQuery.java:90) ~[eclipselink-2.5.1-RC1.jar:2.5.1.v20130824-981335c]
    at org.eclipse.persistence.internal.queries.DatabaseQueryMechanism.executeWriteWithChangeSet(DatabaseQueryMechanism.java:301) ~[eclipselink-2.5.1-RC1.jar:2.5.1.v20130824-981335c]
    at org.eclipse.persistence.queries.WriteObjectQuery.executeDatabaseQuery(WriteObjectQuery.java:58) ~[eclipselink-2.5.1-RC1.jar:2.5.1.v20130824-981335c]
    at org.eclipse.persistence.queries.DatabaseQuery.execute(DatabaseQuery.java:899) ~[eclipselink-2.5.1-RC1.jar:2.5.1.v20130824-981335c]
    at org.eclipse.persistence.queries.DatabaseQuery.executeInUnitOfWork(DatabaseQuery.java:798) ~[eclipselink-2.5.1-RC1.jar:2.5.1.v20130824-981335c]
    at org.eclipse.persistence.queries.ObjectLevelModifyQuery.executeInUnitOfWorkObjectLevelModifyQuery(ObjectLevelModifyQuery.java:108) ~[eclipselink-2.5.1-RC1.jar:2.5.1.v20130824-981335c]
    at org.eclipse.persistence.queries.ObjectLevelModifyQuery.executeInUnitOfWork(ObjectLevelModifyQuery.java:85) ~[eclipselink-2.5.1-RC1.jar:2.5.1.v20130824-981335c]
    at org.eclipse.persistence.internal.sessions.UnitOfWorkImpl.internalExecuteQuery(UnitOfWorkImpl.java:2896) ~[eclipselink-2.5.1-RC1.jar:2.5.1.v20130824-981335c]
    at org.eclipse.persistence.internal.sessions.AbstractSession.executeQuery(AbstractSession.java:1793) ~[eclipselink-2.5.1-RC1.jar:2.5.1.v20130824-981335c]
    at org.eclipse.persistence.internal.sessions.AbstractSession.executeQuery(AbstractSession.java:1775) ~[eclipselink-2.5.1-RC1.jar:2.5.1.v20130824-981335c]
    at org.eclipse.persistence.internal.sessions.AbstractSession.executeQuery(AbstractSession.java:1726) ~[eclipselink-2.5.1-RC1.jar:2.5.1.v20130824-981335c]
    at org.eclipse.persistence.internal.sessions.CommitManager.commitNewObjectsForClassWithChangeSet(CommitManager.java:226) ~[eclipselink-2.5.1-RC1.jar:2.5.1.v20130824-981335c]
    at org.eclipse.persistence.internal.sessions.CommitManager.commitAllObjectsForClassWithChangeSet(CommitManager.java:193) ~[eclipselink-2.5.1-RC1.jar:2.5.1.v20130824-981335c]
    at org.eclipse.persistence.internal.sessions.CommitManager.commitAllObjectsWithChangeSet(CommitManager.java:138) ~[eclipselink-2.5.1-RC1.jar:2.5.1.v20130824-981335c]
    at org.eclipse.persistence.internal.sessions.AbstractSession.writeAllObjectsWithChangeSet(AbstractSession.java:4196) ~[eclipselink-2.5.1-RC1.jar:2.5.1.v20130824-981335c]
    at org.eclipse.persistence.internal.sessions.UnitOfWorkImpl.commitToDatabase(UnitOfWorkImpl.java:1441) ~[eclipselink-2.5.1-RC1.jar:2.5.1.v20130824-981335c]
    at org.eclipse.persistence.internal.sessions.UnitOfWorkImpl.commitToDatabaseWithChangeSet(UnitOfWorkImpl.java:1531) ~[eclipselink-2.5.1-RC1.jar:2.5.1.v20130824-981335c]
    at org.eclipse.persistence.internal.sessions.RepeatableWriteUnitOfWork.commitRootUnitOfWork(RepeatableWriteUnitOfWork.java:277) ~[eclipselink-2.5.1-RC1.jar:2.5.1.v20130824-981335c]
    at org.eclipse.persistence.internal.sessions.UnitOfWorkImpl.commitAndResume(UnitOfWorkImpl.java:1169) ~[eclipselink-2.5.1-RC1.jar:2.5.1.v20130824-981335c]
    at org.eclipse.persistence.internal.jpa.transaction.EntityTransactionImpl.commit(EntityTransactionImpl.java:132) ~[eclipselink-2.5.1-RC1.jar:2.5.1.v20130824-981335c]
    at org.springframework.orm.jpa.JpaTransactionManager.doCommit(JpaTransactionManager.java:512) ~[spring-orm-3.1.2.RELEASE.jar:3.1.2.RELEASE]
    at org.springframework.transaction.support.AbstractPlatformTransactionManager.processCommit(AbstractPlatformTransactionManager.java:754) ~[spring-tx-3.1.2.RELEASE.jar:3.1.2.RELEASE]
    at org.springframework.transaction.support.AbstractPlatformTransactionManager.commit(AbstractPlatformTransactionManager.java:723) ~[spring-tx-3.1.2.RELEASE.jar:3.1.2.RELEASE]
    at org.springframework.transaction.interceptor.TransactionAspectSupport.commitTransactionAfterReturning(TransactionAspectSupport.java:394) ~[spring-tx-3.1.2.RELEASE.jar:3.1.2.RELEASE]
    at org.springframework.transaction.interceptor.TransactionInterceptor.invoke(TransactionInterceptor.java:120) ~[spring-tx-3.1.2.RELEASE.jar:3.1.2.RELEASE]
    at org.springframework.aop.framework.ReflectiveMethodInvocation.proceed(ReflectiveMethodInvocation.java:172) ~[spring-aop-3.0.7.RELEASE.jar:3.0.7.RELEASE]
    at org.springframework.aop.framework.Cglib2AopProxy$DynamicAdvisedInterceptor.intercept(Cglib2AopProxy.java:621) ~[spring-aop-3.0.7.RELEASE.jar:3.0.7.RELEASE]
    at cz.cuni.mff.xrg.odcs.commons.app.scheduling.ScheduleFacade$$EnhancerByCGLIB$$3f81d040.save(<generated>) ~[cglib-3.0.jar:na]
    at cz.cuni.mff.xrg.odcs.frontend.gui.components.SchedulePipeline$5.buttonClick(SchedulePipeline.java:449) ~[SchedulePipeline$5.class:na]
    at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method) ~[na:1.7.0_04]
    at sun.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:57) ~[na:1.7.0_04]
    at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43) ~[na:1.7.0_04]
    at java.lang.reflect.Method.invoke(Method.java:601) ~[na:1.7.0_04]
    at com.vaadin.event.ListenerMethod.receiveEvent(ListenerMethod.java:508) ~[vaadin-server-7.1.5.jar:7.1.5]
    at com.vaadin.event.EventRouter.fireEvent(EventRouter.java:167) ~[vaadin-server-7.1.5.jar:7.1.5]
    at com.vaadin.server.AbstractClientConnector.fireEvent(AbstractClientConnector.java:969) ~[vaadin-server-7.1.5.jar:7.1.5]
    at com.vaadin.ui.Button.fireClick(Button.java:368) ~[vaadin-server-7.1.5.jar:7.1.5]
    at com.vaadin.ui.Button$1.click(Button.java:57) ~[vaadin-server-7.1.5.jar:7.1.5]
    at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method) ~[na:1.7.0_04]
    at sun.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:57) ~[na:1.7.0_04]
    at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43) ~[na:1.7.0_04]
    at java.lang.reflect.Method.invoke(Method.java:601) ~[na:1.7.0_04]
    at com.vaadin.server.ServerRpcManager.applyInvocation(ServerRpcManager.java:168) ~[vaadin-server-7.1.5.jar:7.1.5]
    at com.vaadin.server.ServerRpcManager.applyInvocation(ServerRpcManager.java:118) ~[vaadin-server-7.1.5.jar:7.1.5]
    at com.vaadin.server.communication.ServerRpcHandler.handleBurst(ServerRpcHandler.java:214) [vaadin-server-7.1.5.jar:7.1.5]
    at com.vaadin.server.communication.ServerRpcHandler.handleRpc(ServerRpcHandler.java:111) [vaadin-server-7.1.5.jar:7.1.5]
    at com.vaadin.server.communication.PushHandler$2.run(PushHandler.java:158) [vaadin-server-7.1.5.jar:7.1.5]
    at com.vaadin.server.communication.PushHandler.callWithUi(PushHandler.java:289) [vaadin-server-7.1.5.jar:7.1.5]
    at com.vaadin.server.communication.PushHandler.onRequest(PushHandler.java:308) [vaadin-server-7.1.5.jar:7.1.5]
    at cz.cuni.mff.xrg.odcs.frontend.IntlibPushHandler.onRequest(IntlibPushHandler.java:44) [IntlibPushHandler.class:na]
    at org.atmosphere.cpr.AsynchronousProcessor.action(AsynchronousProcessor.java:259) [atmosphere-runtime-1.0.14.vaadin4.jar:1.0.14.vaadin4]
    at org.atmosphere.cpr.AsynchronousProcessor.suspended(AsynchronousProcessor.java:166) [atmosphere-runtime-1.0.14.vaadin4.jar:1.0.14.vaadin4]
    at org.atmosphere.container.TomcatWebSocketUtil.doService(TomcatWebSocketUtil.java:137) [atmosphere-runtime-1.0.14.vaadin4.jar:1.0.14.vaadin4]
    at org.atmosphere.container.Tomcat7AsyncSupportWithWebSocket.service(Tomcat7AsyncSupportWithWebSocket.java:59) [atmosphere-runtime-1.0.14.vaadin4.jar:1.0.14.vaadin4]
    at org.atmosphere.cpr.AtmosphereFramework.doCometSupport(AtmosphereFramework.java:1448) [atmosphere-runtime-1.0.14.vaadin4.jar:1.0.14.vaadin4]
    at org.atmosphere.websocket.DefaultWebSocketProcessor.dispatch(DefaultWebSocketProcessor.java:219) [atmosphere-runtime-1.0.14.vaadin4.jar:1.0.14.vaadin4]
    at org.atmosphere.websocket.DefaultWebSocketProcessor$2.run(DefaultWebSocketProcessor.java:183) [atmosphere-runtime-1.0.14.vaadin4.jar:1.0.14.vaadin4]
    at org.atmosphere.util.VoidExecutorService.execute(VoidExecutorService.java:101) [atmosphere-runtime-1.0.14.vaadin4.jar:1.0.14.vaadin4]
    at org.atmosphere.websocket.DefaultWebSocketProcessor.dispatch(DefaultWebSocketProcessor.java:178) [atmosphere-runtime-1.0.14.vaadin4.jar:1.0.14.vaadin4]
    at org.atmosphere.websocket.DefaultWebSocketProcessor.invokeWebSocketProtocol(DefaultWebSocketProcessor.java:167) [atmosphere-runtime-1.0.14.vaadin4.jar:1.0.14.vaadin4]
    at org.atmosphere.container.TomcatWebSocketHandler.onTextMessage(TomcatWebSocketHandler.java:92) [atmosphere-runtime-1.0.14.vaadin4.jar:1.0.14.vaadin4]
    at org.apache.catalina.websocket.MessageInbound.onTextData(MessageInbound.java:74) [catalina.jar:7.0.34]
    at org.apache.catalina.websocket.StreamInbound.doOnTextData(StreamInbound.java:186) [catalina.jar:7.0.34]
    at org.apache.catalina.websocket.StreamInbound.onData(StreamInbound.java:134) [catalina.jar:7.0.34]
    at org.apache.coyote.http11.upgrade.UpgradeProcessor.upgradeDispatch(UpgradeProcessor.java:83) [tomcat-coyote.jar:7.0.34]
    at org.apache.coyote.AbstractProtocol$AbstractConnectionHandler.process(AbstractProtocol.java:587) [tomcat-coyote.jar:7.0.34]
    at org.apache.tomcat.util.net.JIoEndpoint$SocketProcessor.run(JIoEndpoint.java:310) [tomcat-coyote.jar:7.0.34]
    at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1110) [na:1.7.0_04]
    at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:603) [na:1.7.0_04]
    at java.lang.Thread.run(Thread.java:722) [na:1.7.0_04]

**Comment by skodapetr** [comment]
Hi, this is my fault probably. I think that it can be fixed by updating database regarding Jan's last database update commit.

**Comment by kukharm** [comment]
Hi Petr, i have it after last commit

**Comment by tomas-knap** [comment]
![screen shot 2013-10-01 at 5 15 58 pm](https://f.cloud.github.com/assets/3014917/1246349/731cee52-2aac-11e3-91f0-4e706333ee1e.png)
