### ISSUE TITLE
SPARQLTest#constructAllTest fails

### ISSUE THREAD

**Issue by janvojt** [mff-uk/odcs#592]
(on revision 13d32633)

```
-------------------------------------------------------------------------------
Test set: cz.cuni.mff.xrg.odcs.transformer.SPARQL.SPARQLTest
-------------------------------------------------------------------------------
Tests run: 1, Failures: 0, Errors: 1, Skipped: 0, Time elapsed: 0.389 sec <<< FAILURE!
constructAllTest(cz.cuni.mff.xrg.odcs.transformer.SPARQL.SPARQLTest)  Time elapsed: 0.388 sec  <<< ERROR!
cz.cuni.mff.xrg.odcs.rdf.exceptions.RDFException: Missing input file in resource.
    at cz.cuni.mff.xrg.odcs.dpu.test.TestEnvironment.createRdfInputFromResource(TestEnvironment.java:173)
    at cz.cuni.mff.xrg.odcs.transformer.SPARQL.SPARQLTest.constructAllTest(SPARQLTest.java:25)
```

**Comment by skodapetr** [comment]
Please try it now.
