### ISSUE TITLE
Problems when replacing DPU TEmplate jar file

### ISSUE THREAD

**Issue by tomas-knap** [mff-uk/odcs#614]
kuba zkousel updatovat nejake svoje DPU (Buyers Profile), pricemz mu to spadlo na NumberFormatException a to na radku, kde nacita konfiguraci z dialogu. Zrejme se proste nevytvorila spravna defaultni konfigurace, zustaly tam null a pak to spadlo na Integer.Parse(null).
1. Jak je mozne, ze se defaultni konfigurace nevytvorila? Config pro tohle DPU vypada normalne:

<pre><code>/**
 *
 * Put your DPU's configuration here.
 *
 */
public class ExtractorConfig implements DPUConfigObject {
    
    /**
     * 
     */
    private static final long serialVersionUID = 3509477277481754571L;

    public boolean rewriteCache = false;
    
    public boolean accessProfiles = true;
    
    public int timeout = 10000;
    
    public int interval = 0;
    
    public boolean currentYearOnly = false;
    
    @Override
    public boolean isValid() {
        return true;
    }

}</code></pre>

Nasledne jsme narazili na dalsi problemy/otazky:
1. Proc to spadlo na NumberFormatException? Tedy pri nahravani JARka se rovnou zkousi i vytvorit dialog?
2. GUI se potom nedalo pouzit, stale to pri clicku na libovolne jine DPU hlasilo tu samou chybu. To je divne, melo by to zahlasit jednou a konec. 
3. V DPU_TEmplates table je ve sloupci configuration NULL az do chvile nez clovek tu defaultni konf manualne ulozi. To je diskutabilni, proc se rovnou po vytvoreni jarka ta defaultni konf nezapisuje do DB?

**Comment by tomas-knap** [comment]
takhle vypada ta Exception:

INFO: Installed AtmosphereInterceptor  Track Message Size Interceptor using |. 
Oct 10, 2013 3:20:49 PM org.atmosphere.cpr.AtmosphereFramework addAtmosphereHandler
INFO: Installed AtmosphereHandler cz.cuni.mff.xrg.odcs.frontend.IntlibPushHandler mapped to context-path: /*
Oct 10, 2013 3:21:52 PM com.vaadin.server.DefaultErrorHandler doDefault
SEVERE: 
com.vaadin.server.ServerRpcManager$RpcInvocationException: Unable to invoke method click in com.vaadin.shared.ui.button.ButtonServerRpc
    at com.vaadin.server.ServerRpcManager.applyInvocation(ServerRpcManager.java:170)
    at com.vaadin.server.ServerRpcManager.applyInvocation(ServerRpcManager.java:118)
    at com.vaadin.server.communication.ServerRpcHandler.handleBurst(ServerRpcHandler.java:214)
    at com.vaadin.server.communication.ServerRpcHandler.handleRpc(ServerRpcHandler.java:111)
    at com.vaadin.server.communication.PushHandler$2.run(PushHandler.java:158)
    at com.vaadin.server.communication.PushHandler.callWithUi(PushHandler.java:289)
    at com.vaadin.server.communication.PushHandler.onRequest(PushHandler.java:308)
    at cz.cuni.mff.xrg.odcs.frontend.IntlibPushHandler.onRequest(IntlibPushHandler.java:44)
    at org.atmosphere.cpr.AsynchronousProcessor.action(AsynchronousProcessor.java:259)
    at org.atmosphere.cpr.AsynchronousProcessor.suspended(AsynchronousProcessor.java:166)
    at org.atmosphere.container.TomcatWebSocketUtil.doService(TomcatWebSocketUtil.java:137)
    at org.atmosphere.container.Tomcat7AsyncSupportWithWebSocket.service(Tomcat7AsyncSupportWithWebSocket.java:59)
    at org.atmosphere.cpr.AtmosphereFramework.doCometSupport(AtmosphereFramework.java:1448)
    at org.atmosphere.websocket.DefaultWebSocketProcessor.dispatch(DefaultWebSocketProcessor.java:219)
    at org.atmosphere.websocket.DefaultWebSocketProcessor$2.run(DefaultWebSocketProcessor.java:183)
    at org.atmosphere.util.VoidExecutorService.execute(VoidExecutorService.java:101)
    at org.atmosphere.websocket.DefaultWebSocketProcessor.dispatch(DefaultWebSocketProcessor.java:178)
    at org.atmosphere.websocket.DefaultWebSocketProcessor.invokeWebSocketProtocol(DefaultWebSocketProcessor.java:167)
    at org.atmosphere.container.TomcatWebSocketHandler.onTextMessage(TomcatWebSocketHandler.java:92)
    at org.apache.catalina.websocket.MessageInbound.onTextData(MessageInbound.java:74)
    at org.apache.catalina.websocket.StreamInbound.doOnTextData(StreamInbound.java:186)
    at org.apache.catalina.websocket.StreamInbound.onData(StreamInbound.java:134)
    at org.apache.coyote.http11.upgrade.UpgradeProcessor.upgradeDispatch(UpgradeProcessor.java:83)
    at org.apache.coyote.AbstractProtocol$AbstractConnectionHandler.process(AbstractProtocol.java:587)
    at org.apache.tomcat.util.net.JIoEndpoint$SocketProcessor.run(JIoEndpoint.java:310)
    at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1145)
    at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:615)
    at java.lang.Thread.run(Thread.java:724)
Caused by: java.lang.reflect.InvocationTargetException
    at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
    at sun.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:57)
    at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
    at java.lang.reflect.Method.invoke(Method.java:606)
    at com.vaadin.server.ServerRpcManager.applyInvocation(ServerRpcManager.java:168)
    ... 27 more
Caused by: com.vaadin.event.ListenerMethod$MethodException: Invocation of method buttonClick in org.vaadin.dialogs.DefaultConfirmDialogFactory$2 failed.
    at com.vaadin.event.ListenerMethod.receiveEvent(ListenerMethod.java:528)
    at com.vaadin.event.EventRouter.fireEvent(EventRouter.java:167)
    at com.vaadin.server.AbstractClientConnector.fireEvent(AbstractClientConnector.java:969)
    at com.vaadin.ui.Button.fireClick(Button.java:368)
    at com.vaadin.ui.Button$1.click(Button.java:57)
    ... 32 more
Caused by: com.vaadin.event.ListenerMethod$MethodException: Invocation of method selectedTabChange in cz.cuni.mff.xrg.odcs.frontend.gui.views.DPU$5 failed.
    at com.vaadin.event.ListenerMethod.receiveEvent(ListenerMethod.java:528)
    at com.vaadin.event.EventRouter.fireEvent(EventRouter.java:167)
    at com.vaadin.server.AbstractClientConnector.fireEvent(AbstractClientConnector.java:969)
    at com.vaadin.ui.TabSheet.fireSelectedTabChange(TabSheet.java:837)
    at com.vaadin.ui.TabSheet.addTab(TabSheet.java:312)
    at com.vaadin.ui.TabSheet.addTab(TabSheet.java:271)
    at com.vaadin.ui.TabSheet.addTab(TabSheet.java:247)
    at cz.cuni.mff.xrg.odcs.frontend.gui.views.DPU.buildDPUDetailLayout(DPU.java:402)
    at cz.cuni.mff.xrg.odcs.frontend.gui.views.DPU.selectNewDPU(DPU.java:1047)
    at cz.cuni.mff.xrg.odcs.frontend.gui.views.DPU.selectNewDPU(DPU.java:1075)
    at cz.cuni.mff.xrg.odcs.frontend.gui.views.DPU.access$400(DPU.java:87)
    at cz.cuni.mff.xrg.odcs.frontend.gui.views.DPU$4$1.onClose(DPU.java:327)
    at org.vaadin.dialogs.DefaultConfirmDialogFactory$2.buttonClick(DefaultConfirmDialogFactory.java:145)
    at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
    at sun.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:57)
    at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
    at java.lang.reflect.Method.invoke(Method.java:606)
    at com.vaadin.event.ListenerMethod.receiveEvent(ListenerMethod.java:508)
    ... 36 more
Caused by: java.lang.NumberFormatException: For input string: ""
    at java.lang.NumberFormatException.forInputString(NumberFormatException.java:65)
    at java.lang.Integer.parseInt(Integer.java:504)
    at java.lang.Integer.parseInt(Integer.java:527)
    at cz.opendata.linked.ares.updates.ExtractorDialog.getConfiguration(ExtractorDialog.java:67)
    at cz.opendata.linked.ares.updates.ExtractorDialog.getConfiguration(ExtractorDialog.java:14)
    at cz.cuni.mff.xrg.odcs.commons.module.dialog.BaseConfigDialog.hasConfigChanged(BaseConfigDialog.java:85)
    at cz.cuni.mff.xrg.odcs.frontend.gui.views.DPU.isChanged(DPU.java:1001)
    at cz.cuni.mff.xrg.odcs.frontend.gui.views.DPU$5.selectedTabChange(DPU.java:377)
    at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
    at sun.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:57)
    at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
    at java.lang.reflect.Method.invoke(Method.java:606)
    at com.vaadin.event.ListenerMethod.receiveEvent(ListenerMethod.java:508)
    ... 53 more

**Comment by skodapetr** [comment]
1) Actually the default configuration "was" null .. this has been changed, so now it create default configuration. imho: unfortunately this was not the source of this issue. But good idea to mention this.

1) Well there were "error" in DPU dialog. Without try-catch the DPU try to convert string to int. If the input txtArea is empty, then this failed with NumberFormatException. The dialog should throw ConfigException if there is any problem not NumberFormatException which is in fact RuntimeException.

2) This was caused by the fact that the exception was probably newer caught .. so Vaadin keep inform about this. But I'm not sure about this. 

3) same as first 1) just be aware that not every default configuration is valid ie. isValid == false (for example silk).

**Comment by tomas-knap** [comment]
Petre, so did you adjust something, or where the problem was? Which of the points I mentioned need to be still solved by separated issues?
