### ISSUE TITLE
Could not commit JPA transaction

### ISSUE THREAD

**Issue by tomas-knap** [mff-uk/odcs#624]
The db went down, odcs was trying to reconnect, then we restarted db and the following error occurs - Transaction cannot be commited. Why is the transaction rollback only?

```
Downloading URL (attempt 0): www.e-zakazky.cz/Profil-Zadavatele/da1756a3-58a3-4636-a5fe-c42255a534b1/XMLdataVZ?od=01012013&do=31122013
2013-10-11 15:54:21,434 [Thread-40] DEBUG exec:10130 dpu:14 c.c.m.xrg.odcs.commons.dpu.DPU - Downloaded URL (attempt 0) in 10 ms : www.e-zakazky.cz/Profil-Zadavatele/da1756a3-58a3-4636-a5fe-c42255a534b1/XMLdataVZ?od=01012013&do=31122013
2013-10-11 15:54:21,435 [Thread-40] DEBUG exec:10130 dpu:14 c.c.m.xrg.odcs.commons.dpu.DPU - 13858
2013-10-11 15:54:21,435 [Thread-40] DEBUG exec:10130 dpu:14 c.c.m.xrg.odcs.commons.dpu.DPU - Parsing profile #20458: http://www.e-zakazky.cz/Profil-Zadavatele/da1756a3-58a3-4636-a5fe-c42255a534b1
2013-10-11 15:54:21,435 [Thread-40] DEBUG exec:10130 dpu:14 c.c.m.xrg.odcs.commons.dpu.DPU - http://www.e-zakazky.cz/Profil-Zadavatele/da1756a3-58a3-4636-a5fe-c42255a534b1/XMLdataVZ?od=01012013&do=31122013 size 13
2013-10-11 15:54:21,435 [Thread-40] DEBUG exec:10130 dpu:14 c.c.m.xrg.odcs.commons.dpu.DPU - Downloading URL (attempt 0): www.vestnikverejnychzakazek.cz/Views/Form/Display/340116
Exception in thread "Thread-107" org.springframework.transaction.TransactionSystemException: Could not commit JPA transaction; nested exception is javax.persistence.RollbackException: Transaction rolled back because transaction was set to RollbackOnly.
    at org.springframework.orm.jpa.JpaTransactionManager.doCommit(JpaTransactionManager.java:521)
    at org.springframework.transaction.support.AbstractPlatformTransactionManager.processCommit(AbstractPlatformTransactionManager.java:754)
    at org.springframework.transaction.support.AbstractPlatformTransactionManager.commit(AbstractPlatformTransactionManager.java:723)
    at org.springframework.transaction.interceptor.TransactionAspectSupport.commitTransactionAfterReturning(TransactionAspectSupport.java:394)
    at org.springframework.transaction.interceptor.TransactionInterceptor.invoke(TransactionInterceptor.java:120)
    at org.springframework.aop.framework.ReflectiveMethodInvocation.proceed(ReflectiveMethodInvocation.java:172)
    at org.springframework.aop.framework.Cglib2AopProxy$DynamicAdvisedInterceptor.intercept(Cglib2AopProxy.java:622)
    at cz.cuni.mff.xrg.odcs.backend.facade.PipelineFacade$$EnhancerByCGLIB$$b3b144ad.save(<generated>)
    at cz.cuni.mff.xrg.odcs.backend.execution.dpu.Executor.execute(Executor.java:315)
    at cz.cuni.mff.xrg.odcs.backend.execution.dpu.Executor.run(Executor.java:393)
    at java.lang.Thread.run(Thread.java:724)
Caused by: javax.persistence.RollbackException: Transaction rolled back because transaction was set to RollbackOnly.
    at org.eclipse.persistence.internal.jpa.transaction.EntityTransactionImpl.commit(EntityTransactionImpl.java:141)
    at org.springframework.orm.jpa.JpaTransactionManager.doCommit(JpaTransactionManager.java:512)
    ... 10 more
2013-10-11 15:54:22,399 [pool-2-thread-14] DEBUG exec:10138 dpu:29 c.c.m.x.o.b.e.p.impl.CleanUp - CleanUp start .. 
2013-10-11 15:54:22,404 [pool-2-thread-14] INFO  exec:10138 dpu:29 c.c.m.x.o.r.i.VirtuosoRDFRepo - Virtuoso repository with data graph <http://linked.opendata.cz/resource/odcs/internal/pipeline/exec/10138/dpu/28/du/0> succesfully shut down
2013-10-11 15:54:22,405 [Thread-108] DEBUG exec:10138 dpu:29 c.c.m.x.o.r.i.VirtuosoRDFRepo - Repository with data graph
```

**Comment by tomas-knap** [comment]
Could duplicate #798

**Comment by tomas-knap** [comment]
Honzo, zkusim. Jak funguje ten @Order(1)? Resp. jaka je myslenka te upravy?

**Comment by janvojt** [comment]
Je to poradie, v ktorom AspectJ pusta aspekty. Nastavil som to na 1 preto, aby sa aspekt odchytavajuci vynimku (pre offline db) spustal pred aspektom na zacatie transakcie.

**Comment by tomas-knap** [comment]
Does not appear now
