### ISSUE TITLE
Extractor problem .. 

### ISSUE THREAD

**Issue by skodapetr** [mff-uk/odcs#670]
When I use dbPedia pipeline and set  SPARQL Extractor "Extraction failed if there is no triples" .. the execution failed with exception - DPUs should use context.sendMessage(Error .. otherwise backedn print stack trace which is not desired .. 
Also the exception does not give a reason .. why there are no triples?

```
2013-10-17 20:58:28,123 [Thread-8] DEBUG exec:117 dpu:1 c.c.m.x.o.e.rdf.RDFExtractor - RDFDataUnitException
cz.cuni.mff.xrg.odcs.rdf.exceptions.RDFException: No extracted triples from SPARQL endpoint
    at cz.cuni.mff.xrg.odcs.rdf.impl.BaseRDFRepo.caseNoTriples(BaseRDFRepo.java:1047) ~[classes/:na]
    at cz.cuni.mff.xrg.odcs.rdf.impl.BaseRDFRepo.extractFromSPARQLEndpoint(BaseRDFRepo.java:960) ~[classes/:na]
    at cz.cuni.mff.xrg.odcs.extractor.rdf.RDFExtractor.execute(RDFExtractor.java:65) ~[na:na]
    at cz.cuni.mff.xrg.odcs.backend.execution.dpu.Executor.executeInstance(Executor.java:217) [classes/:na]
    at cz.cuni.mff.xrg.odcs.backend.execution.dpu.Executor.execute(Executor.java:323) [classes/:na]
    at cz.cuni.mff.xrg.odcs.backend.execution.dpu.Executor.run(Executor.java:393) [classes/:na]
    at java.lang.Thread.run(Thread.java:722) [na:1.7.0_17]
2013-10-17 20:58:28,241 [Thread-8] ERROR exec:117 dpu:1 c.c.m.x.o.b.p.e.PipelineFailedEvent - Pipeline failed on DPU 'SPARQL DBPedia' because of the exception
cz.cuni.mff.xrg.odcs.commons.dpu.DPUException: No extracted triples from SPARQL endpoint
    at cz.cuni.mff.xrg.odcs.extractor.rdf.RDFExtractor.execute(RDFExtractor.java:76) ~[na:na]
    at cz.cuni.mff.xrg.odcs.backend.execution.dpu.Executor.executeInstance(Executor.java:217) [classes/:na]
    at cz.cuni.mff.xrg.odcs.backend.execution.dpu.Executor.execute(Executor.java:323) [classes/:na]
    at cz.cuni.mff.xrg.odcs.backend.execution.dpu.Executor.run(Executor.java:393) [classes/:na]
    at java.lang.Thread.run(Thread.java:722) [na:1.7.0_17]
Caused by: cz.cuni.mff.xrg.odcs.rdf.exceptions.RDFException: No extracted triples from SPARQL endpoint
    at cz.cuni.mff.xrg.odcs.rdf.impl.BaseRDFRepo.caseNoTriples(BaseRDFRepo.java:1047) ~[classes/:na]
    at cz.cuni.mff.xrg.odcs.rdf.impl.BaseRDFRepo.extractFromSPARQLEndpoint(BaseRDFRepo.java:960) ~[classes/:na]
    at cz.cuni.mff.xrg.odcs.extractor.rdf.RDFExtractor.execute(RDFExtractor.java:65) ~[na:na]
    ... 4 common frames omitted
2013-10-17 20:58:28,539 [Thread-8] INFO  exec:117 dpu:1 c.c.m.x.o.b.dpu.event.DPUEvent - DPU 'SPARQL DBPedia' finished

```

**Comment by tomesj** [comment]
So if I understand, just add calling context.sendMessage(...)

**Comment by skodapetr** [comment]
Instead of rethrow DPUException(RDFException), yes.

And question at the very end .. is there possibility to find out .. why there have not been any triples extracted?

**Comment by tomesj** [comment]
No - cause of why I can not find out. I can know only result - no triples extracted. 

So I add context.sendMessage(...)

And throw RDFException - fail (as specification)
