### ISSUE TITLE
Copy pipeline exception

### ISSUE THREAD

**Issue by kukharm** [mff-uk/odcs#672]
I try to copy pipeline by Copy button in Pipelines section and get the exception 

java.lang.NullPointerException: null
    at cz.cuni.mff.xrg.odcs.commons.app.pipeline.graph.PipelineGraph.<init>(PipelineGraph.java:81) ~[commons-app-1.0.0.jar:na]
    at cz.cuni.mff.xrg.odcs.commons.app.pipeline.Pipeline.<init>(Pipeline.java:106) ~[commons-app-1.0.0.jar:na]
    at cz.cuni.mff.xrg.odcs.commons.app.pipeline.PipelineFacade.copyPipeline(PipelineFacade.java:71) ~[commons-app-1.0.0.jar:na]
    at cz.cuni.mff.xrg.odcs.commons.app.pipeline.PipelineFacade$$FastClassByCGLIB$$b54802f8.invoke(<generated>) ~[cglib-3.0.jar:na]
    at net.sf.cglib.proxy.MethodProxy.invoke(MethodProxy.java:204) ~[cglib-3.0.jar:na]
    at org.springframework.aop.framework.Cglib2AopProxy$CglibMethodInvocation.invokeJoinpoint(Cglib2AopProxy.java:688) ~[spring-aop-3.0.7.RELEASE.jar:3.0.7.RELEASE]
    at org.springframework.aop.framework.ReflectiveMethodInvocation.proceed(ReflectiveMethodInvocation.java:150) ~[spring-aop-3.0.7.RELEASE.jar:3.0.7.RELEASE]
    at org.springframework.security.access.intercept.aopalliance.MethodSecurityInterceptor.invoke(MethodSecurityInterceptor.java:64) ~[spring-security-core-3.1.4.RELEASE.jar:3.1.4.RELEASE]
    at org.springframework.aop.framework.ReflectiveMethodInvocation.proceed(ReflectiveMethodInvocation.java:172) ~[spring-aop-3.0.7.RELEASE.jar:3.0.7.RELEASE]
    at org.springframework.aop.framework.Cglib2AopProxy$DynamicAdvisedInterceptor.intercept(Cglib2AopProxy.java:621) ~[spring-aop-3.0.7.RELEASE.jar:3.0.7.RELEASE]
    at cz.cuni.mff.xrg.odcs.commons.app.pipeline.PipelineFacade$$EnhancerByCGLIB$$b182dfc4.copyPipeline(<generated>) ~[cglib-3.0.jar:na]
    at cz.cuni.mff.xrg.odcs.frontend.gui.views.PipelineList$actionColumnGenerator$2.buttonClick(PipelineList.java:283) ~[PipelineList$actionColumnGenerator$2.class:na]
    at sun.reflect.GeneratedMethodAccessor49.invoke(Unknown Source) ~[na:na]
    at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43) ~[na:1.7.0_04]
    at java.lang.reflect.Method.invoke(Method.java:601) ~[na:1.7.0_04]
    at com.vaadin.event.ListenerMethod.receiveEvent(ListenerMethod.java:508) ~[vaadin-server-7.1.5.jar:7.1.5]
    at com.vaadin.event.EventRouter.fireEvent(EventRouter.java:167) ~[vaadin-server-7.1.5.jar:7.1.5]
    at com.vaadin.server.AbstractClientConnector.fireEvent(AbstractClientConnector.java:969) ~[vaadin-server-7.1.5.jar:7.1.5]
    at com.vaadin.ui.Button.fireClick(Button.java:368) ~[vaadin-server-7.1.5.jar:7.1.5]
    at com.vaadin.ui.Button$1.click(Button.java:57) ~[vaadin-server-7.1.5.jar:7.1.5]
    at sun.reflect.GeneratedMethodAccessor69.invoke(Unknown Source) ~[na:na]
    at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43) ~[na:1.7.0_04]
    at java.lang.reflect.Method.invoke(Method.java:601) ~[na:1.7.0_04]
    at com.vaadin.server.ServerRpcManager.applyInvocation(ServerRpcManager.java:168) ~[vaadin-server-7.1.5.jar:7.1.5]
    at com.vaadin.server.ServerRpcManager.applyInvocation(ServerRpcManager.java:118) ~[vaadin-server-7.1.5.jar:7.1.5]
    at com.vaadin.server.communication.ServerRpcHandler.handleBurst(ServerRpcHandler.java:214) [vaadin-server-7.1.5.jar:7.1.5]
    at com.vaadin.server.communication.ServerRpcHandler.handleRpc(ServerRpcHandler.java:111) [vaadin-server-7.1.5.jar:7.1.5]
    at com.vaadin.server.communication.PushHandler$2.run(PushHandler.java:158) [vaadin-server-7.1.5.jar:7.1.5]
    at com.vaadin.server.communication.PushHandler.callWithUi(PushHandler.java:289) [vaadin-server-7.1.5.jar:7.1.5]
    at com.vaadin.server.communication.PushHandler.onRequest(PushHandler.java:308) [vaadin-server-7.1.5.jar:7.1.5]
    at cz.cuni.mff.xrg.odcs.frontend.IntlibPushHandler.onRequest(IntlibPushHandler.java:44) [IntlibPushHandler.class:na]
    at org.atmosphere.cpr.AsynchronousProcessor.action(AsynchronousProcessor.java:259) [atmosphere-runtime-1.0.14.vaadin4.jar:1.0.14.vaadin4]
    at org.atmosphere.cpr.AsynchronousProcessor.suspended(AsynchronousProcessor.java:166) [atmosphere-runtime-1.0.14.vaadin4.jar:1.0.14.vaadin4]
    at org.atmosphere.container.TomcatWebSocketUtil.doService(TomcatWebSocketUtil.java:137) [atmosphere-runtime-1.0.14.vaadin4.jar:1.0.14.vaadin4]
    at org.atmosphere.container.Tomcat7AsyncSupportWithWebSocket.service(Tomcat7AsyncSupportWithWebSocket.java:59) [atmosphere-runtime-1.0.14.vaadin4.jar:1.0.14.vaadin4]
    at org.atmosphere.cpr.AtmosphereFramework.doCometSupport(AtmosphereFramework.java:1448) [atmosphere-runtime-1.0.14.vaadin4.jar:1.0.14.vaadin4]
    at org.atmosphere.websocket.DefaultWebSocketProcessor.dispatch(DefaultWebSocketProcessor.java:219) [atmosphere-runtime-1.0.14.vaadin4.jar:1.0.14.vaadin4]
    at org.atmosphere.websocket.DefaultWebSocketProcessor$2.run(DefaultWebSocketProcessor.java:183) [atmosphere-runtime-1.0.14.vaadin4.jar:1.0.14.vaadin4]
    at org.atmosphere.util.VoidExecutorService.execute(VoidExecutorService.java:101) [atmosphere-runtime-1.0.14.vaadin4.jar:1.0.14.vaadin4]
    at org.atmosphere.websocket.DefaultWebSocketProcessor.dispatch(DefaultWebSocketProcessor.java:178) [atmosphere-runtime-1.0.14.vaadin4.jar:1.0.14.vaadin4]
    at org.atmosphere.websocket.DefaultWebSocketProcessor.invokeWebSocketProtocol(DefaultWebSocketProcessor.java:167) [atmosphere-runtime-1.0.14.vaadin4.jar:1.0.14.vaadin4]
    at org.atmosphere.container.TomcatWebSocketHandler.onTextMessage(TomcatWebSocketHandler.java:92) [atmosphere-runtime-1.0.14.vaadin4.jar:1.0.14.vaadin4]
    at org.apache.catalina.websocket.MessageInbound.onTextData(MessageInbound.java:74) [catalina.jar:7.0.34]
    at org.apache.catalina.websocket.StreamInbound.doOnTextData(StreamInbound.java:186) [catalina.jar:7.0.34]
    at org.apache.catalina.websocket.StreamInbound.onData(StreamInbound.java:134) [catalina.jar:7.0.34]
    at org.apache.coyote.http11.upgrade.UpgradeProcessor.upgradeDispatch(UpgradeProcessor.java:83) [tomcat-coyote.jar:7.0.34]
    at org.apache.coyote.AbstractProtocol$AbstractConnectionHandler.process(AbstractProtocol.java:587) [tomcat-coyote.jar:7.0.34]
    at org.apache.tomcat.util.net.JIoEndpoint$SocketProcessor.run(JIoEndpoint.java:310) [tomcat-coyote.jar:7.0.34]
    at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1110) [na:1.7.0_04]
    at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:603) [na:1.7.0_04]
    at java.lang.Thread.run(Thread.java:722) [na:1.7.0_04]

**Comment by tomas-knap** [comment]
+1
