### ISSUE TITLE
Copy DPU template Error

### ISSUE THREAD

**Issue by kukharm** [mff-uk/odcs#676]
I try to copy DPU template by Copy button in the DPU Templates section. Nothings happens, new DPU was not created, in the logs i get error message

12:57:00.447 [http-bio-8080-exec-4] DEBUG c.c.m.x.o.c.a.m.o.OSGIModuleFacade - Installing bundle from 'RDF_extractor'/'RDF_extractor-1.0.0.jar'
12:57:00.506 [http-bio-8080-exec-4] ERROR c.c.m.x.o.f.g.ViewComponent - Failed to load configuration for 1
cz.cuni.mff.xrg.odcs.commons.configuration.ConfigException: com.thoughtworks.xstream.mapper.CannotResolveClassException: cz.cuni.mff.xrg.odcs.loader.file.FileLoaderConfig
    at cz.cuni.mff.xrg.odcs.commons.module.config.ConfigWrap.deserialize(ConfigWrap.java:83) ~[na:na]
    at cz.cuni.mff.xrg.odcs.commons.module.dialog.BaseConfigDialog.setConfig(BaseConfigDialog.java:44) ~[na:na]
    at cz.cuni.mff.xrg.odcs.frontend.auxiliaries.dpu.DPURecordWrap.loadConfigIntoDialog(DPURecordWrap.java:147) ~[DPURecordWrap.class:na]
    at cz.cuni.mff.xrg.odcs.frontend.auxiliaries.dpu.DPURecordWrap.configuredDialog(DPURecordWrap.java:90) ~[DPURecordWrap.class:na]
    at cz.cuni.mff.xrg.odcs.frontend.auxiliaries.dpu.DPUTemplateWrap.configuredDialog(DPUTemplateWrap.java:1) ~[DPUTemplateWrap.class:na]
    at cz.cuni.mff.xrg.odcs.frontend.gui.views.DPU.conigureDPUDialog(DPU.java:1147) [DPU.class:na]
    at cz.cuni.mff.xrg.odcs.frontend.gui.views.DPU.buildDPUDetailLayout(DPU.java:434) [DPU.class:na]
    at cz.cuni.mff.xrg.odcs.frontend.gui.views.DPU.selectNewDPU(DPU.java:1024) [DPU.class:na]
    at cz.cuni.mff.xrg.odcs.frontend.gui.views.DPU.selectNewDPU(DPU.java:1052) [DPU.class:na]
    at cz.cuni.mff.xrg.odcs.frontend.gui.views.DPU.access$7(DPU.java:1041) [DPU.class:na]
    at cz.cuni.mff.xrg.odcs.frontend.gui.views.DPU$4.itemClick(DPU.java:329) [DPU$4.class:na]
    at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method) ~[na:1.7.0_04]
    at sun.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:57) ~[na:1.7.0_04]
    at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43) ~[na:1.7.0_04]
    at java.lang.reflect.Method.invoke(Method.java:601) ~[na:1.7.0_04]
    at com.vaadin.event.ListenerMethod.receiveEvent(ListenerMethod.java:508) [vaadin-server-7.1.5.jar:7.1.5]
    at com.vaadin.event.EventRouter.fireEvent(EventRouter.java:167) [vaadin-server-7.1.5.jar:7.1.5]
    at com.vaadin.server.AbstractClientConnector.fireEvent(AbstractClientConnector.java:969) [vaadin-server-7.1.5.jar:7.1.5]
    at com.vaadin.ui.Tree.changeVariables(Tree.java:470) [vaadin-server-7.1.5.jar:7.1.5]
    at com.vaadin.server.communication.ServerRpcHandler.changeVariables(ServerRpcHandler.java:403) [vaadin-server-7.1.5.jar:7.1.5]
    at com.vaadin.server.communication.ServerRpcHandler.handleBurst(ServerRpcHandler.java:228) [vaadin-server-7.1.5.jar:7.1.5]
    at com.vaadin.server.communication.ServerRpcHandler.handleRpc(ServerRpcHandler.java:111) [vaadin-server-7.1.5.jar:7.1.5]
    at com.vaadin.server.communication.PushHandler$2.run(PushHandler.java:158) [vaadin-server-7.1.5.jar:7.1.5]
    at com.vaadin.server.communication.PushHandler.callWithUi(PushHandler.java:289) [vaadin-server-7.1.5.jar:7.1.5]
    at com.vaadin.server.communication.PushHandler.onRequest(PushHandler.java:308) [vaadin-server-7.1.5.jar:7.1.5]
    at cz.cuni.mff.xrg.odcs.frontend.IntlibPushHandler.onRequest(IntlibPushHandler.java:44) [IntlibPushHandler.class:na]
    at org.atmosphere.cpr.AsynchronousProcessor.action(AsynchronousProcessor.java:259) [atmosphere-runtime-1.0.14.vaadin4.jar:1.0.14.vaadin4]
    at org.atmosphere.cpr.AsynchronousProcessor.suspended(AsynchronousProcessor.java:166) [atmosphere-runtime-1.0.14.vaadin4.jar:1.0.14.vaadin4]
    at org.atmosphere.container.TomcatWebSocketUtil.doService(TomcatWebSocketUtil.java:137) [atmosphere-runtime-1.0.14.vaadin4.jar:1.0.14.vaadin4]
    at org.atmosphere.container.Tomcat7AsyncSupportWithWebSocket.service(Tomcat7AsyncSupportWithWebSocket.java:59) [atmosphere-runtime-1.0.14.vaadin4.jar:1.0.14.vaadin4]
    at org.atmosphere.cpr.AtmosphereFramework.doCometSupport(AtmosphereFramework.java:1448) [atmosphere-runtime-1.0.14.vaadin4.jar:1.0.14.vaadin4]
    at org.atmosphere.websocket.DefaultWebSocketProcessor.dispatch(DefaultWebSocketProcessor.java:219) [atmosphere-runtime-1.0.14.vaadin4.jar:1.0.14.vaadin4]
    at org.atmosphere.websocket.DefaultWebSocketProcessor$2.run(DefaultWebSocketProcessor.java:183) [atmosphere-runtime-1.0.14.vaadin4.jar:1.0.14.vaadin4]
    at org.atmosphere.util.VoidExecutorService.execute(VoidExecutorService.java:101) [atmosphere-runtime-1.0.14.vaadin4.jar:1.0.14.vaadin4]
    at org.atmosphere.websocket.DefaultWebSocketProcessor.dispatch(DefaultWebSocketProcessor.java:178) [atmosphere-runtime-1.0.14.vaadin4.jar:1.0.14.vaadin4]
    at org.atmosphere.websocket.DefaultWebSocketProcessor.invokeWebSocketProtocol(DefaultWebSocketProcessor.java:167) [atmosphere-runtime-1.0.14.vaadin4.jar:1.0.14.vaadin4]
    at org.atmosphere.container.TomcatWebSocketHandler.onTextMessage(TomcatWebSocketHandler.java:92) [atmosphere-runtime-1.0.14.vaadin4.jar:1.0.14.vaadin4]
    at org.apache.catalina.websocket.MessageInbound.onTextData(MessageInbound.java:74) [catalina.jar:7.0.34]
    at org.apache.catalina.websocket.StreamInbound.doOnTextData(StreamInbound.java:186) [catalina.jar:7.0.34]
    at org.apache.catalina.websocket.StreamInbound.onData(StreamInbound.java:134) [catalina.jar:7.0.34]
    at org.apache.coyote.http11.upgrade.UpgradeProcessor.upgradeDispatch(UpgradeProcessor.java:83) [tomcat-coyote.jar:7.0.34]
    at org.apache.coyote.AbstractProtocol$AbstractConnectionHandler.process(AbstractProtocol.java:587) [tomcat-coyote.jar:7.0.34]
    at org.apache.tomcat.util.net.JIoEndpoint$SocketProcessor.run(JIoEndpoint.java:310) [tomcat-coyote.jar:7.0.34]
    at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1110) [na:1.7.0_04]
    at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:603) [na:1.7.0_04]
    at java.lang.Thread.run(Thread.java:722) [na:1.7.0_04]
Caused by: com.thoughtworks.xstream.mapper.CannotResolveClassException: cz.cuni.mff.xrg.odcs.loader.file.FileLoaderConfig
    at com.thoughtworks.xstream.mapper.DefaultMapper.realClass(DefaultMapper.java:56) ~[xstream-1.4.4.jar:na]
    at com.thoughtworks.xstream.mapper.MapperWrapper.realClass(MapperWrapper.java:30) ~[xstream-1.4.4.jar:na]
    at com.thoughtworks.xstream.mapper.DynamicProxyMapper.realClass(DynamicProxyMapper.java:55) ~[xstream-1.4.4.jar:na]
    at com.thoughtworks.xstream.mapper.MapperWrapper.realClass(MapperWrapper.java:30) ~[xstream-1.4.4.jar:na]
    at com.thoughtworks.xstream.mapper.PackageAliasingMapper.realClass(PackageAliasingMapper.java:88) ~[xstream-1.4.4.jar:na]
    at com.thoughtworks.xstream.mapper.MapperWrapper.realClass(MapperWrapper.java:30) ~[xstream-1.4.4.jar:na]
    at com.thoughtworks.xstream.mapper.ClassAliasingMapper.realClass(ClassAliasingMapper.java:79) ~[xstream-1.4.4.jar:na]
    at com.thoughtworks.xstream.mapper.MapperWrapper.realClass(MapperWrapper.java:30) ~[xstream-1.4.4.jar:na]
    at com.thoughtworks.xstream.mapper.MapperWrapper.realClass(MapperWrapper.java:30) ~[xstream-1.4.4.jar:na]
    at com.thoughtworks.xstream.mapper.MapperWrapper.realClass(MapperWrapper.java:30) ~[xstream-1.4.4.jar:na]
    at com.thoughtworks.xstream.mapper.MapperWrapper.realClass(MapperWrapper.java:30) ~[xstream-1.4.4.jar:na]
    at com.thoughtworks.xstream.mapper.MapperWrapper.realClass(MapperWrapper.java:30) ~[xstream-1.4.4.jar:na]
    at com.thoughtworks.xstream.mapper.MapperWrapper.realClass(MapperWrapper.java:30) ~[xstream-1.4.4.jar:na]
    at com.thoughtworks.xstream.mapper.ArrayMapper.realClass(ArrayMapper.java:74) ~[xstream-1.4.4.jar:na]
    at com.thoughtworks.xstream.mapper.MapperWrapper.realClass(MapperWrapper.java:30) ~[xstream-1.4.4.jar:na]
    at com.thoughtworks.xstream.mapper.MapperWrapper.realClass(MapperWrapper.java:30) ~[xstream-1.4.4.jar:na]
    at com.thoughtworks.xstream.mapper.MapperWrapper.realClass(MapperWrapper.java:30) ~[xstream-1.4.4.jar:na]
    at com.thoughtworks.xstream.mapper.MapperWrapper.realClass(MapperWrapper.java:30) ~[xstream-1.4.4.jar:na]
    at com.thoughtworks.xstream.mapper.MapperWrapper.realClass(MapperWrapper.java:30) ~[xstream-1.4.4.jar:na]
    at com.thoughtworks.xstream.mapper.MapperWrapper.realClass(MapperWrapper.java:30) ~[xstream-1.4.4.jar:na]
    at com.thoughtworks.xstream.mapper.MapperWrapper.realClass(MapperWrapper.java:30) ~[xstream-1.4.4.jar:na]
    at com.thoughtworks.xstream.mapper.CachingMapper.realClass(CachingMapper.java:45) ~[xstream-1.4.4.jar:na]
    at com.thoughtworks.xstream.core.util.HierarchicalStreams.readClassType(HierarchicalStreams.java:29) ~[xstream-1.4.4.jar:na]
    at com.thoughtworks.xstream.core.TreeUnmarshaller.start(TreeUnmarshaller.java:133) ~[xstream-1.4.4.jar:na]
    at com.thoughtworks.xstream.core.AbstractTreeMarshallingStrategy.unmarshal(AbstractTreeMarshallingStrategy.java:32) ~[xstream-1.4.4.jar:na]
    at com.thoughtworks.xstream.XStream.unmarshal(XStream.java:1058) ~[xstream-1.4.4.jar:na]
    at com.thoughtworks.xstream.XStream.unmarshal(XStream.java:1030) ~[xstream-1.4.4.jar:na]
    at com.thoughtworks.xstream.XStream$2.readFromStream(XStream.java:1723) ~[xstream-1.4.4.jar:na]
    at com.thoughtworks.xstream.core.util.CustomObjectInputStream.readObjectOverride(CustomObjectInputStream.java:104) ~[xstream-1.4.4.jar:na]
    at java.io.ObjectInputStream.readObject(ObjectInputStream.java:363) ~[na:1.7.0_04]
    at cz.cuni.mff.xrg.odcs.commons.module.config.ConfigWrap.deserialize(ConfigWrap.java:76) ~[na:na]
    ... 45 common frames omitted

**Comment by skodapetr** [comment]
Could you please provide more details? I try it with non-root template created from DBPeadia extractor and it works fine.

question for you. how should it behave when I try to copy root-template (ie has no paret) ? As it do nothing .. which is good .. but then I would expect thete there will be no copy button .. or it can create a copy and add it to the sub tree ?

**Comment by kukharm** [comment]
On the DPU Templates section of the main menu, in the dpu tree i have only standard DPUs. I select SPARQL Extractor and press "Copy" button under details dialog. I expect that new DPU template "Copy of SPARQL Extractor" will appear in the tree (it works that way before) but it does not happened and any error message that something wrong does not appear... nothing happens. But in logs there an error   

In Editing pipeline section the button "Save as DPU template" works fine. The problem is only in  DPU Templates section

**Comment by skodapetr** [comment]
Well . for top level DPUs there should no possibility to "copy" .. as say our comment in code: 
// Copy DPU Template Button, may copy only DPU of 3 level.

But there were some problems with disabling the button. So you can try to copy the top DPU .. which .. do not create error on my side .. but ends up with some strange results .. like DPU Template without owner .. which is not visible ..

**Comment by kukharm** [comment]
Yes, you are right, i forgot about this condition, initially it was disabled for 2-level DPUs.
