### ISSUE TITLE
Local in-memory store Out of Mem

### ISSUE THREAD

**Issue by tomas-knap** [mff-uk/odcs#724]
2013-11-03 09:05:51,964 [dpu: ARES] DEBUG exec:241 dpu:162 c.c.m.xrg.odcs.commons.dpu.DPU - Got from cache 35052: http://wwwinfo.mfcr.cz/cgi-bin/ares/darv_or.cgi?ico=02064651
2013-11-03 09:05:55,019 [taskScheduler-1] TRACE exec: dpu: c.c.m.x.o.c.a.s.Schedule - onTimeCheck finished
2013-11-03 09:06:16,685 [taskScheduler-4] TRACE exec: dpu: c.c.m.x.o.b.execution.Engine - Checking for new executions.
2013-11-03 09:06:26,391 [taskScheduler-2] TRACE exec: dpu: c.c.m.x.o.c.a.s.Schedule - onTimeCheck started
2013-11-03 09:06:26,391 [dpu: ARES] DEBUG exec:241 dpu:162 c.c.m.xrg.odcs.commons.dpu.DPU - Got from cache 35053: http://wwwinfo.mfcr.cz/cgi-bin/ares/darv_bas.cgi?ico=02064723
2013-11-03 09:06:39,642 [taskScheduler-2] TRACE exec: dpu: c.c.m.x.o.c.a.s.Schedule - onTimeCheck finished
2013-11-03 09:06:36,042 [dpu: ARES] ERROR exec:241 dpu:162 c.c.m.x.o.b.p.e.PipelineFailedEvent - Pipeline failed on DPU: 'ARES' because of the error
java.lang.OutOfMemoryError: Java heap space
2013-11-03 09:06:42,782 [taskScheduler-1] TRACE exec: dpu: c.c.m.x.o.b.execution.Engine - Checking for new executions.
2013-11-03 09:06:42,788 [dpu: ARES] INFO  exec:241 dpu:162 c.c.m.x.o.b.dpu.event.DPUEvent - DPU 'ARES' finished
2013-11-03 09:06:46,007 [pool-2-thread-13] DEBUG exec:241 dpu:162 c.c.m.x.o.b.e.p.impl.CleanUp - CleanUp start .. 
2013-11-03 09:07:04,057 [taskScheduler-1] TRACE exec: dpu: c.c.m.x.o.b.execution.Engine - Checking for new executions.
2013-11-03 09:07:10,547 [taskScheduler-2] TRACE exec: dpu: c.c.m.x.o.c.a.s.Schedule - onTimeCheck started
2013-11-03 09:07:10,549 [Finalizer] WARN  exec: dpu: o.o.s.m.MemoryStoreConnection - Rolling back transaction due to connection close
java.lang.Throwable: null
    at org.openrdf.sail.helpers.SailConnectionBase.close(SailConnectionBase.java:209) [sesame-sail-api-2.7.0-beta1.jar:na]
    at org.openrdf.sail.helpers.SailConnectionBase.finalize(SailConnectionBase.java:246) [sesame-sail-api-2.7.0-beta1.jar:na]
    at java.lang.ref.Finalizer.invokeFinalizeMethod(Native Method) [na:1.7.0_40]
    at java.lang.ref.Finalizer.runFinalizer(Finalizer.java:101) [na:1.7.0_40]
    at java.lang.ref.Finalizer.access$100(Finalizer.java:32) [na:1.7.0_40]
    at java.lang.ref.Finalizer$FinalizerThread.run(Finalizer.java:190) [na:1.7.0_40]
2013-11-03 09:07:10,549 [Finalizer] DEBUG exec: dpu: o.o.sail.memory.MemoryStore - rolling back transaction
2013-11-03 09:07:10,554 [taskScheduler-2] TRACE exec: dpu: c.c.m.x.o.c.a.s.Schedule - onTimeCheck finished
2013-11-03 09:07:14,700 [MemoryStore synchronization] DEBUG exec:241 dpu:162 o.o.sail.memory.MemoryStore - Data synced to file
2013-11-03 09:07:16,413 [MemoryStore synchronization] DEBUG exec:241 dpu:162 o.o.sail.memory.MemoryStore - Data synced to file
2013-11-03 09:07:27,185 [taskScheduler-3] TRACE exec: dpu: c.c.m.x.o.b.execution.Engine - Checking for new executions.
2013-11-03 09:07:40,554 [taskScheduler-1] TRACE exec: dpu: c.c.m.x.o.c.a.s.Schedule - onTimeCheck started
2013-11-03 09:07:40,557 [taskScheduler-1] TRACE exec: dpu: c.c.m.x.o.c.a.s.Schedule - onTimeCheck finished
2013-11-03 09:07:47,187 [taskScheduler-4] TRACE exec: dpu: c.c.m.x.o.b.execution.Engine - Checking for new executions.
2013-11-03 09:08:07,190 [taskScheduler-4] TRACE exec: dpu: c.c.m.x.o.b.execution.Engine - Checking for new executions.
2013-11-03 09:08:10,557 [taskScheduler-1] TRACE exec: dpu: c.c.m.x.o.c.a.s.Schedule - onTimeCheck started

**Comment by tomas-knap** [comment]
Check that this is not happening for native store!

**Comment by tomas-knap** [comment]
melo by to minimalne vyhodit vyjimku, kdyz tenhle stav nastane, aktualne to pokracuje dal, vlakno s DPU umre, ale execution pokracuje

**Comment by tomas-knap** [comment]
co timeout pro dpu execution?
