### ISSUE TITLE
schedulig rule exception

### ISSUE THREAD

**Issue by kukharm** [mff-uk/odcs#731]
In schedule a pipeline dialog i select Pipeline (in mandatory combobox) and get the exception 
![ex](https://f.cloud.github.com/assets/3471169/1470280/ac6570c0-45b5-11e3-813e-d26c17db979f.jpg)

```
java.lang.UnsupportedOperationException: null
    at cz.cuni.mff.xrg.odcs.frontend.container.ReadOnlyContainer.containsId(ReadOnlyContainer.java:196) ~[ReadOnlyContainer.class:na]
    at com.vaadin.ui.AbstractSelect.setValue(AbstractSelect.java:701) ~[vaadin-server-7.1.5.jar:7.1.5]
    at com.vaadin.ui.ComboBox.changeVariables(ComboBox.java:664) ~[vaadin-server-7.1.5.jar:7.1.5]
    at com.vaadin.server.communication.ServerRpcHandler.changeVariables(ServerRpcHandler.java:403) [vaadin-server-7.1.5.jar:7.1.5]
    at com.vaadin.server.communication.ServerRpcHandler.handleBurst(ServerRpcHandler.java:228) [vaadin-server-7.1.5.jar:7.1.5]
    at com.vaadin.server.communication.ServerRpcHandler.handleRpc(ServerRpcHandler.java:111) [vaadin-server-7.1.5.jar:7.1.5]
    at com.vaadin.server.communication.UidlRequestHandler.synchronizedHandleRequest(UidlRequestHandler.java:91) [vaadin-server-7.1.5.jar:7.1.5]
    at com.vaadin.server.SynchronizedRequestHandler.handleRequest(SynchronizedRequestHandler.java:37) [vaadin-server-7.1.5.jar:7.1.5]
    at com.vaadin.server.VaadinService.handleRequest(VaadinService.java:1371) [vaadin-server-7.1.5.jar:7.1.5]
    at com.vaadin.server.VaadinServlet.service(VaadinServlet.java:238) [vaadin-server-7.1.5.jar:7.1.5]
    at cz.cuni.mff.xrg.odcs.frontend.IntlibApplicationServlet.service(IntlibApplicationServlet.java:52) [IntlibApplicationServlet.class:na]
    at javax.servlet.http.HttpServlet.service(HttpServlet.java:728) [servlet-api.jar:na]
    at org.apache.catalina.core.ApplicationFilterChain.internalDoFilter(ApplicationFilterChain.java:305) [catalina.jar:7.0.34]
    at org.apache.catalina.core.ApplicationFilterChain.doFilter(ApplicationFilterChain.java:210) [catalina.jar:7.0.34]
    at org.apache.catalina.core.StandardWrapperValve.invoke(StandardWrapperValve.java:222) [catalina.jar:7.0.34]
    at org.apache.catalina.core.StandardContextValve.invoke(StandardContextValve.java:123) [catalina.jar:7.0.34]
    at org.apache.catalina.authenticator.AuthenticatorBase.invoke(AuthenticatorBase.java:472) [catalina.jar:7.0.34]
    at org.apache.catalina.core.StandardHostValve.invoke(StandardHostValve.java:171) [catalina.jar:7.0.34]
    at org.apache.catalina.valves.ErrorReportValve.invoke(ErrorReportValve.java:99) [catalina.jar:7.0.34]
    at org.apache.catalina.valves.AccessLogValve.invoke(AccessLogValve.java:936) [catalina.jar:7.0.34]
    at org.apache.catalina.core.StandardEngineValve.invoke(StandardEngineValve.java:118) [catalina.jar:7.0.34]
    at org.apache.catalina.connector.CoyoteAdapter.service(CoyoteAdapter.java:407) [catalina.jar:7.0.34]
    at org.apache.coyote.http11.AbstractHttp11Processor.process(AbstractHttp11Processor.java:1004) [tomcat-coyote.jar:7.0.34]
    at org.apache.coyote.AbstractProtocol$AbstractConnectionHandler.process(AbstractProtocol.java:589) [tomcat-coyote.jar:7.0.34]
    at org.apache.tomcat.util.net.JIoEndpoint$SocketProcessor.run(JIoEndpoint.java:312) [tomcat-coyote.jar:7.0.34]
    at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1110) [na:1.7.0_04]
    at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:603) [na:1.7.0_04]
    at java.lang.Thread.run(Thread.java:722) [na:1.7.0_04]
```

**Comment by skodapetr** [comment]
Tohle asi nebude zrovna na Honzu. Jde o to, ze podle vseho se tam pouziva ten container, jenž je určený pouze pro ten PagedFiltrableTable. Tj. zřejmě se tam volá stejná factory metoda .. tedy řešením by bylo mít na to vlastní. 

Což by i dávalo smysl, neb tady stačí Id, name .. a né jako v table, tam je toho třeba více (možná tam bude i user a last execution).

**Comment by tomas-knap** [comment]
Tedy pouzit opet ten novy container?

**Comment by tomas-knap** [comment]
This should be solved soon, because I already deployed that bug on the server ;)

**Comment by skodapetr** [comment]
Spíše naopak. Použít ten starý pro rychlé řešení :)

**Comment by janvojt** [comment]
This is resolved in current version by not using the ReadOnlyContainer.
