### ISSUE TITLE
Problems after first deploy, tomcat needed to be restarted

### ISSUE THREAD

**Issue by tomas-knap** [mff-uk/odcs#789]
Kolega zkousel instalaci: Jo a ještě jsem zapomněl, po prvním deploymentu mi nešly seběhnout žádné pipeliny, hlásilo to výjimku níže. Po restartu (tomcatu i backendu) už to šlo.

Can you reproduce the problem and avoid? Is the Spring magic responsible?

2013-11-17 13:23:28,573 [taskScheduler-3] ERROR exec: dpu: o.s.s.s.TaskUtils$LoggingErrorHandler - Unexpected error
occurred in scheduled task.
java.lang.NoClassDefFoundError: cz/cuni/mff/xrg/odcs/backend/pipeline/event/PipelineFailedEvent
        at java.lang.Class.getDeclaredConstructors0(Native Method) ~[na:1.7.0_45]
        at java.lang.Class.privateGetDeclaredConstructors(Unknown Source) ~[na:1.7.0_45]
        at java.lang.Class.getDeclaredConstructors(Unknown Source) ~[na:1.7.0_45]
        at org.springframework.beans.factory.annotation.AutowiredAnnotationBeanPostProcessor.determineCandidateConst
ructors(AutowiredAnnotationBeanPostProcessor.java:229) ~[spring-beans-3.1.2.RELEASE.jar:3.1.2.RELEASE]
        at org.springframework.beans.factory.support.AbstractAutowireCapableBeanFactory.determineConstructorsFromBea
nPostProcessors(AbstractAutowireCapableBeanFactory.java:962) ~[spring-beans-3.1.2.RELEASE.jar:3.1.2.RELEASE]
        at org.springframework.beans.factory.support.AbstractAutowireCapableBeanFactory.createBeanInstance(AbstractA
utowireCapableBeanFactory.java:935) ~[spring-beans-3.1.2.RELEASE.jar:3.1.2.RELEASE]
        at org.springframework.beans.factory.support.AbstractAutowireCapableBeanFactory.doCreateBean(AbstractAutowir
eCapableBeanFactory.java:485) ~[spring-beans-3.1.2.RELEASE.jar:3.1.2.RELEASE]
        at org.springframework.beans.factory.support.AbstractAutowireCapableBeanFactory.createBean(AbstractAutowireC
apableBeanFactory.java:456) ~[spring-beans-3.1.2.RELEASE.jar:3.1.2.RELEASE]
        at org.springframework.beans.factory.support.AbstractBeanFactory.doGetBean(AbstractBeanFactory.java:313) ~[s
pring-beans-3.1.2.RELEASE.jar:3.1.2.RELEASE]
        at org.springframework.beans.factory.support.AbstractBeanFactory.getBean(AbstractBeanFactory.java:197) ~[spr
ing-beans-3.1.2.RELEASE.jar:3.1.2.RELEASE]
        at org.springframework.beans.factory.support.DefaultListableBeanFactory.getBean(DefaultListableBeanFactory.j
ava:274) ~[spring-beans-3.1.2.RELEASE.jar:3.1.2.RELEASE]
        at cz.cuni.mff.xrg.odcs.backend.execution.Engine.run(Engine.java:100) ~[backend-1.0.0.jar:na]
        at cz.cuni.mff.xrg.odcs.backend.execution.Engine.checkDatabase(Engine.java:123) ~[backend-1.0.0.jar:na]
        at sun.reflect.GeneratedMethodAccessor12.invoke(Unknown Source) ~[na:na]
        at sun.reflect.DelegatingMethodAccessorImpl.invoke(Unknown Source) ~[na:1.7.0_45]
        at java.lang.reflect.Method.invoke(Unknown Source) ~[na:1.7.0_45]
        at org.springframework.scheduling.support.ScheduledMethodRunnable.run(ScheduledMethodRunnable.java:64) ~[spr
ing-context-3.1.2.RELEASE.jar:3.1.2.RELEASE]
        at org.springframework.scheduling.support.DelegatingErrorHandlingRunnable.run(DelegatingErrorHandlingRunnabl
e.java:53) ~[spring-context-3.1.2.RELEASE.jar:3.1.2.RELEASE]
        at java.util.concurrent.Executors$RunnableAdapter.call(Unknown Source) [na:1.7.0_45]
        at java.util.concurrent.FutureTask.runAndReset(Unknown Source) [na:1.7.0_45]
        at java.util.concurrent.ScheduledThreadPoolExecutor$ScheduledFutureTask.access$301(Unknown Source) [na:1.7.0
_45]
        at java.util.concurrent.ScheduledThreadPoolExecutor$ScheduledFutureTask.run(Unknown Source) [na:1.7.0_45]
        at java.util.concurrent.ThreadPoolExecutor.runWorker(Unknown Source) [na:1.7.0_45]
        at java.util.concurrent.ThreadPoolExecutor$Worker.run(Unknown Source) [na:1.7.0_45]
        at java.lang.Thread.run(Unknown Source) [na:1.7.0_45]
Caused by: java.lang.ClassNotFoundException: cz.cuni.mff.xrg.odcs.backend.pipeline.event.PipelineFailedEvent
        at java.net.URLClassLoader$1.run(Unknown Source) ~[na:1.7.0_45]
        at java.net.URLClassLoader$1.run(Unknown Source) ~[na:1.7.0_45]
        at java.security.AccessController.doPrivileged(Native Method) ~[na:1.7.0_45]
        at java.net.URLClassLoader.findClass(Unknown Source) ~[na:1.7.0_45]
        at java.lang.ClassLoader.loadClass(Unknown Source) ~[na:1.7.0_45]
        at sun.misc.Launcher$AppClassLoader.loadClass(Unknown Source) ~[na:1.7.0_45]
        at java.lang.ClassLoader.loadClass(Unknown Source) ~[na:1.7.0_45]
        ... 25 common frames omitted
)

**Comment by skodapetr** [comment]
Asi ano .. podle toho exec, dpu hádám, že jde o backend log .. tam bych toto vskutku nečekal.

Nicméně java.lang.ClassNotFoundException (původní příčina) není asi něco co bychom mohli ovlivnit .. kdyžtak jeslti máš celý log? Ale i tak, nevím zda něco svedeme bez debug-trace level logu ze springu ...
