### ISSUE TITLE
Problem when debugging from canvas 

### ISSUE THREAD

**Issue by tomas-knap** [mff-uk/odcs#803]
Prepare the pipeline, clicked on debug on one DPU, 

![screen shot 2013-11-21 at 4 02 03 pm](https://f.cloud.github.com/assets/3014917/1592571/f2fbe784-52bd-11e3-8119-15747ff66d6b.png)

2013-11-21 16:01:58,570 [http-bio-8080-exec-7] ERROR cz.cuni.mff.xrg.odcs.frontend.AppEntry - Uncaught exception
java.lang.NullPointerException: null
    at cz.cuni.mff.xrg.odcs.frontend.gui.views.PipelineEdit.openDebug(PipelineEdit.java:670) ~[PipelineEdit.class:na]
    at cz.cuni.mff.xrg.odcs.frontend.gui.views.PipelineEdit.access$200(PipelineEdit.java:64) ~[PipelineEdit.class:na]
    at cz.cuni.mff.xrg.odcs.frontend.gui.views.PipelineEdit$3.componentEvent(PipelineEdit.java:217) ~[PipelineEdit$3.class:na]
    at cz.cuni.mff.xrg.odcs.frontend.gui.components.pipelinecanvas.PipelineCanvas.fireEvent(PipelineCanvas.java:321) ~[PipelineCanvas.class:na]
    at cz.cuni.mff.xrg.odcs.frontend.gui.components.pipelinecanvas.PipelineCanvas.showDebugWindow(PipelineCanvas.java:414) ~[PipelineCanvas.class:na]
    at cz.cuni.mff.xrg.odcs.frontend.gui.components.pipelinecanvas.PipelineCanvas.access$500(PipelineCanvas.java:30) ~[PipelineCanvas.class:na]
    at cz.cuni.mff.xrg.odcs.frontend.gui.components.pipelinecanvas.PipelineCanvas$1.onDebugRequested(PipelineCanvas.java:97) ~[PipelineCanvas$1.class:na]
    at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method) ~[na:1.7.0_21]
    at sun.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:57) ~[na:1.7.0_21]
    at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43) ~[na:1.7.0_21]
    at java.lang.reflect.Method.invoke(Method.java:601) ~[na:1.7.0_21]
    at com.vaadin.server.ServerRpcManager.applyInvocation(ServerRpcManager.java:168) ~[vaadin-server-7.1.5.jar:7.1.5]
    at com.vaadin.server.ServerRpcManager.applyInvocation(ServerRpcManager.java:118) ~[vaadin-server-7.1.5.jar:7.1.5]
    at com.vaadin.server.communication.ServerRpcHandler.handleBurst(ServerRpcHandler.java:214) [vaadin-server-7.1.5.jar:7.1.5]
    at com.vaadin.server.communication.ServerRpcHandler.handleRpc(ServerRpcHandler.java:111) [vaadin-server-7.1.5.jar:7.1.5]
    at com.vaadin.server.communication.UidlRequestHandler.synchronizedHandleRequest(UidlRequestHandler.java:91) [vaadin-server-7.1.5.jar:7.1.5]
    at com.vaadin.server.SynchronizedRequestHandler.handleRequest(SynchronizedRequestHandler.java:37) [vaadin-server-7.1.5.jar:7.1.5]
    at com.vaadin.server.VaadinService.handleRequest(VaadinService.java:1371) [vaadin-server-7.1.5.jar:7.1.5]
    at com.vaadin.server.VaadinServlet.service(VaadinServlet.java:238) [vaadin-server-7.1.5.jar:7.1.5]
    at cz.cuni.mff.xrg.odcs.frontend.IntlibApplicationServlet.service(IntlibApplicationServlet.java:52) [IntlibApplicationServlet.class:na]
    at javax.servlet.http.HttpServlet.service(HttpServlet.java:728) [servlet-api.jar:na]
    at org.apache.catalina.core.ApplicationFilterChain.internalDoFilter(ApplicationFilterChain.java:305) [catalina.jar:7.0.39]
    at org.apache.catalina.core.ApplicationFilterChain.doFilter(ApplicationFilterChain.java:210) [catalina.jar:7.0.39]
    at org.apache.catalina.core.StandardWrapperValve.invoke(StandardWrapperValve.java:222) [catalina.jar:7.0.39]
    at org.apache.catalina.core.StandardContextValve.invoke(StandardContextValve.java:123) [catalina.jar:7.0.39]
    at org.apache.catalina.authenticator.AuthenticatorBase.invoke(AuthenticatorBase.java:472) [catalina.jar:7.0.39]
    at org.apache.catalina.core.StandardHostValve.invoke(StandardHostValve.java:171) [catalina.jar:7.0.39]
    at org.apache.catalina.valves.ErrorReportValve.invoke(ErrorReportValve.java:99) [catalina.jar:7.0.39]
    at org.apache.catalina.valves.AccessLogValve.invoke(AccessLogValve.java:947) [catalina.jar:7.0.39]
    at org.apache.catalina.core.StandardEngineValve.invoke(StandardEngineValve.java:118) [catalina.jar:7.0.39]
    at org.apache.catalina.connector.CoyoteAdapter.service(CoyoteAdapter.java:408) [catalina.jar:7.0.39]
    at org.apache.coyote.http11.AbstractHttp11Processor.process(AbstractHttp11Processor.java:1009) [tomcat-coyote.jar:7.0.39]
    at org.apache.coyote.AbstractProtocol$AbstractConnectionHandler.process(AbstractProtocol.java:589) [tomcat-coyote.jar:7.0.39]
    at org.apache.tomcat.util.net.JIoEndpoint$SocketProcessor.run(JIoEndpoint.java:312) [tomcat-coyote.jar:7.0.39]
    at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1145) [na:1.7.0_21]
    at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:615) [na:1.7.0_21]
    at java.lang.Thread.run(Thread.java:722) [na:1.7.0_21]

**Comment by tomas-knap** [comment]
Please check that, debugging is not possible from canvas now
