### ISSUE TITLE
Problem when clicking on exec monitor

### ISSUE THREAD

**Issue by tomas-knap** [mff-uk/odcs#814]
Second exec record was open, I clicked on the first one. Could be related to #812 

![screen shot 2013-11-22 at 11 51 38 am](https://f.cloud.github.com/assets/3014917/1599997/3a6db27c-5364-11e3-9457-fb2a4bac9430.png)

2013-11-22 11:51:21,316 [http-bio-8080-exec-267] DEBUG c.c.m.x.o.f.g.v.e.ExecutionListPresenterImpl - ExecutionMonitor refreshed.
2013-11-22 11:51:21,573 [http-bio-8080-exec-267] ERROR cz.cuni.mff.xrg.odcs.frontend.AppEntry - Uncaught exception
java.lang.NullPointerException: null
    at cz.cuni.mff.xrg.odcs.frontend.container.ReadOnlyContainer.getObject(ReadOnlyContainer.java:186) ~[ReadOnlyContainer.class:na]
    at cz.cuni.mff.xrg.odcs.frontend.container.ValueProperty.<init>(ValueProperty.java:22) ~[ValueProperty.class:na]
    at cz.cuni.mff.xrg.odcs.frontend.container.GeneralProperty.bind(GeneralProperty.java:36) ~[GeneralProperty.class:na]
    at cz.cuni.mff.xrg.odcs.frontend.container.ValueItem.getItemProperty(ValueItem.java:22) ~[ValueItem.class:na]
    at cz.cuni.mff.xrg.odcs.frontend.gui.views.executionlist.ExecutionListViewImpl$15.itemClick(ExecutionListViewImpl.java:409) ~[ExecutionListViewImpl$15.class:na]
    at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method) ~[na:1.7.0_40]
    at sun.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:57) ~[na:1.7.0_40]
    at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43) ~[na:1.7.0_40]
    at java.lang.reflect.Method.invoke(Method.java:606) ~[na:1.7.0_40]
    at com.vaadin.event.ListenerMethod.receiveEvent(ListenerMethod.java:508) ~[vaadin-server-7.1.5.jar:7.1.5]
    at com.vaadin.event.EventRouter.fireEvent(EventRouter.java:167) ~[vaadin-server-7.1.5.jar:7.1.5]
    at com.vaadin.server.AbstractClientConnector.fireEvent(AbstractClientConnector.java:969) ~[vaadin-server-7.1.5.jar:7.1.5]
    at com.vaadin.ui.CustomTable.handleClickEvent(CustomTable.java:3035) ~[filteringtable-0.9.0.v7.jar:7.1.5]
    at com.vaadin.ui.CustomTable.changeVariables(CustomTable.java:2830) ~[filteringtable-0.9.0.v7.jar:7.1.5]
    at com.vaadin.server.communication.ServerRpcHandler.changeVariables(ServerRpcHandler.java:403) [vaadin-server-7.1.5.jar:7.1.5]
    at com.vaadin.server.communication.ServerRpcHandler.handleBurst(ServerRpcHandler.java:228) [vaadin-server-7.1.5.jar:7.1.5]
    at com.vaadin.server.communication.ServerRpcHandler.handleRpc(ServerRpcHandler.java:111) [vaadin-server-7.1.5.jar:7.1.5]
    at com.vaadin.server.communication.UidlRequestHandler.synchronizedHandleRequest(UidlRequestHandler.java:91) [vaadin-server-7.1.5.jar:7.1.5]
    at com.vaadin.server.SynchronizedRequestHandler.handleRequest(SynchronizedRequestHandler.java:37) [vaadin-server-7.1.5.jar:7.1.5]
    at com.vaadin.server.VaadinService.handleRequest(VaadinService.java:1371) [vaadin-server-7.1.5.jar:7.1.5]
    at com.vaadin.server.VaadinServlet.service(VaadinServlet.java:238) [vaadin-server-7.1.5.jar:7.1.5]
    at cz.cuni.mff.xrg.odcs.frontend.IntlibApplicationServlet.service(IntlibApplicationServlet.java:52) [IntlibApplicationServlet.class:na]
    at javax.servlet.http.HttpServlet.service(HttpServlet.java:728) [servlet-api.jar:na]
    at org.apache.catalina.core.ApplicationFilterChain.internalDoFilter(ApplicationFilterChain.java:305) [catalina.jar:7.0.33]
    at org.apache.catalina.core.ApplicationFilterChain.doFilter(ApplicationFilterChain.java:210) [catalina.jar:7.0.33]
    at org.apache.catalina.core.StandardWrapperValve.invoke(StandardWrapperValve.java:222) [catalina.jar:7.0.33]
    at org.apache.catalina.core.StandardContextValve.invoke(StandardContextValve.java:123) [catalina.jar:7.0.33]
    at org.apache.catalina.authenticator.AuthenticatorBase.invoke(AuthenticatorBase.java:472) [catalina.jar:7.0.33]
    at org.apache.catalina.core.StandardHostValve.invoke(StandardHostValve.java:171) [catalina.jar:7.0.33]
    at org.apache.catalina.valves.ErrorReportValve.invoke(ErrorReportValve.java:99) [catalina.jar:7.0.33]
    at org.apache.catalina.valves.AccessLogValve.invoke(AccessLogValve.java:931) [catalina.jar:7.0.33]
    at org.apache.catalina.core.StandardEngineValve.invoke(StandardEngineValve.java:118) [catalina.jar:7.0.33]
    at org.apache.catalina.connector.CoyoteAdapter.service(CoyoteAdapter.java:407) [catalina.jar:7.0.33]
    at org.apache.coyote.http11.AbstractHttp11Processor.process(AbstractHttp11Processor.java:1004) [tomcat-coyote.jar:7.0.33]
    at org.apache.coyote.AbstractProtocol$AbstractConnectionHandler.process(AbstractProtocol.java:589) [tomcat-coyote.jar:7.0.33]
    at org.apache.tomcat.util.net.JIoEndpoint$SocketProcessor.run(JIoEndpoint.java:312) [tomcat-coyote.jar:7.0.33]
    at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1145) [na:1.7.0_40]
    at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:615) [na:1.7.0_40]
    at java.lang.Thread.run(Thread.java:724) [na:1.7.0_40]
2013-11-22 11:51:26,276 [http-bio-8080-exec-268] DEBUG org.eclipse.persistence.logging.sql - 2013-11-22 11:51:26.275--ServerSession(362209224)--Connection(2066130761)--Thread(Thread[http-bio-8080-exec-268,5,main])--SELECT CASE  WHEN (MAX(t_last_change) > ?) THEN CAST(? AS INTEGER) ELSE CAST(? AS INTEGER) END FROM exec_pipeline
    bind => [2013-11-22 11:51:21.279, 1, 0]
2013-11-22 11:51:26,279 [http-bio-8080-exec-268] DEBUG org.eclipse.persistence.logging.sql - 2013-11-22 11:51:26.279--ServerSession(362209224)--Connection(592701422)--Thread(Thread[http-bio-8080-exec-268,5,main]

**Comment by skodapetr** [comment]
After come ReadOnlyContainer update (sorry forgot to mention this issue in comit) I have tried to click around a little ... and no exception at all .. please test that
- I also reassign this, as I'm the responsible person for readOnlyContainer
