### ISSUE TITLE
Notifications for the scheduled events

### ISSUE THREAD

**Issue by tomas-knap** [mff-uk/odcs#824]
When clicking on scheduled event, notification tab, save -> 

![screen shot 2013-11-25 at 9 09 21 am](https://f.cloud.github.com/assets/3014917/1611345/23f6354a-55a9-11e3-9d47-84bcf62333cf.png)

2013-11-25 09:09:09,311 [http-bio-8080-exec-280] DEBUG org.eclipse.persistence.logging.sql - 2013-11-25 09:09:09.31--ServerSession(362209224)--Connection(1994737194)--Thread(Thread[http-bio-8080-exec-280,5,main])--SELECT TOP 20,17 ID AS a1, DESCRIPTION AS a2, NAME AS a3, user_id AS a4 FROM ppl_model ORDER BY ID DESC
2013-11-25 09:09:09,316 [http-bio-8080-exec-280] DEBUG org.eclipse.persistence.logging.sql - 2013-11-25 09:09:09.316--ServerSession(362209224)--Connection(1866388302)--Thread(Thread[http-bio-8080-exec-280,5,main])--SELECT ID, type_error, type_success, schedule_id FROM sch_sch_notification WHERE (schedule_id = ?)
    bind => [103]
2013-11-25 09:09:09,330 [http-bio-8080-exec-280] DEBUG org.eclipse.persistence.logging.sql - 2013-11-25 09:09:09.33--ServerSession(362209224)--Connection(131769115)--Thread(Thread[http-bio-8080-exec-280,5,main])--SELECT t1.ID, t1.e_domain, t1.e_user FROM sch_sch_notification_email t0, sch_email t1 WHERE ((t0.notification_id = ?) AND (t1.ID = t0.email_id))
    bind => [106]
2013-11-25 09:09:18,474 [http-bio-8080-exec-283] DEBUG org.eclipse.persistence.logging.sql - 2013-11-25 09:09:18.474--ServerSession(362209224)--Connection(1408571583)--Thread(Thread[http-bio-8080-exec-283,5,main])--SELECT ID, DESCRIPTION, NAME, user_id FROM ppl_model WHERE (ID = ?)
    bind => [115]
2013-11-25 09:09:18,478 [http-bio-8080-exec-283] ERROR cz.cuni.mff.xrg.odcs.frontend.AppEntry - Uncaught exception
java.lang.NullPointerException: null
    at cz.cuni.mff.xrg.odcs.frontend.gui.components.SchedulePipeline$5.buttonClick(SchedulePipeline.java:451) ~[SchedulePipeline$5.class:na]
    at sun.reflect.GeneratedMethodAccessor1261.invoke(Unknown Source) ~[na:na]
    at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43) ~[na:1.7.0_40]
    at java.lang.reflect.Method.invoke(Method.java:606) ~[na:1.7.0_40]
    at com.vaadin.event.ListenerMethod.receiveEvent(ListenerMethod.java:508) ~[vaadin-server-7.1.5.jar:7.1.5]
    at com.vaadin.event.EventRouter.fireEvent(EventRouter.java:167) ~[vaadin-server-7.1.5.jar:7.1.5]
    at com.vaadin.server.AbstractClientConnector.fireEvent(AbstractClientConnector.java:969) ~[vaadin-server-7.1.5.jar:7.1.5]
    at com.vaadin.ui.Button.fireClick(Button.java:368) ~[vaadin-server-7.1.5.jar:7.1.5]
    at com.vaadin.ui.Button$1.click(Button.java:57) ~[vaadin-server-7.1.5.jar:7.1.5]
    at sun.reflect.GeneratedMethodAccessor1272.invoke(Unknown Source) ~[na:na]
    at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43) ~[na:1.7.0_40]
    at java.lang.reflect.Method.invoke(Method.java:606) ~[na:1.7.0_40]
    at com.vaadin.server.ServerRpcManager.applyInvocation(ServerRpcManager.java:168) ~[vaadin-server-7.1.5.jar:7.1.5]
    at com.vaadin.server.ServerRpcManager.applyInvocation(ServerRpcManager.java:118) ~[vaadin-server-7.1.5.jar:7.1.5]
    at com.vaadin.server.communication.ServerRpcHandler.handleBurst(ServerRpcHandler.java:214) [vaadin-server-7.1.5.jar:7.1.5]
    at com.vaadin.server.communication.ServerRpcHandler.handleRpc(ServerRpcHandler.java:111) [vaadin-server-7.1.5.jar:7.1.5]
    at com.vaadin.server.communication.UidlRequestHandler.synchronizedHandleRequest(UidlRequestHandler.java:91) [vaadin-server-7.1.5.jar:7.1.5]
    at com.vaadin.server.SynchronizedRequestHandler.handleRequest(SynchronizedRequestHandler.java:37) [vaadin-server-7.1.5.jar:7.1.5]
    at com.vaadin.server.VaadinService.handleRequest(VaadinService.java:1371) [vaadin-server-7.1.5.jar:7.1.5]
    at com.vaadin.server.VaadinServlet.service(VaadinServlet.java:238) [vaadin-server-7.1.5.jar:7.1.5]
    at cz.cuni.mff.xrg.odcs.frontend.IntlibApplicationServlet.service(IntlibApplicationServlet.java:52) [IntlibApplicationServlet.class:na]
    at javax.servlet.http.HttpServlet.service(HttpServlet.java:728) [servlet-api.jar:na]
    at org.apache.catalina.core.ApplicationFilterChain.internalDoFilter(ApplicationFilterChain.java:305) [catalina.jar:7.0.33]
    at org.apache.catalina.core.ApplicationFilterChain.doFilter(ApplicationFilterChain.java:210) [catalina.jar:7.0.33]
    at org.apache.catalina.core.StandardWrapperValve.invoke(StandardWrapperValve.java:222) [catalina.jar:7.0.33]
    at org.apache.catalina.core.StandardContextValve.invoke(StandardContextValve.java:123) [catalina.jar:7.0.33]
    at org.apache.catalina.authenticator.AuthenticatorBase.invoke(AuthenticatorBase.java:472) [catalina.jar:7.0.33]
    at org.apache.catalina.core.StandardHostValve.invoke(StandardHostValve.java:171) [catalina.jar:7.0.33]
    at org.apache.catalina.valves.ErrorReportValve.invoke(ErrorReportValve.java:99) [catalina.jar:7.0.33]
    at org.apache.catalina.valves.AccessLogValve.invoke(AccessLogValve.java:931) [catalina.jar:7.0.33]
    at org.apache.catalina.core.StandardEngineValve.invoke(StandardEngineValve.java:118) [catalina.jar:7.0.33]
    at org.apache.catalina.connector.CoyoteAdapter.service(CoyoteAdapter.java:407) [catalina.jar:7.0.33]
    at org.apache.coyote.http11.AbstractHttp11Processor.process(AbstractHttp11Processor.java:1004) [tomcat-coyote.jar:7.0.33]
    at org.apache.coyote.AbstractProtocol$AbstractConnectionHandler.process(AbstractProtocol.java:589) [tomcat-coyote.jar:7.0.33]
    at org.apache.tomcat.util.net.JIoEndpoint$SocketProcessor.run(JIoEndpoint.java:312) [tomcat-coyote.jar:7.0.33]
    at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1145) [na:1.7.0_40]
    at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:615) [na:1.7.0_40]
    at java.lang.Thread.run(Thread.java:724) [na:1.7.0_40]

**Comment by bogo777** [comment]
Cannot reproduce on latest version, which version is this? In latest version, SchedulePipeline.java:451 is line with comment.

**Comment by tomas-knap** [comment]
It is the version from 22., but do not know the commit, will retest on the latest version
