### ISSUE TITLE
Not possible to see list pipeline

### ISSUE THREAD

**Issue by tomesj** [mff-uk/odcs#827]
When I log to ODCS and I can list pipelines, I get this error:
![image](https://f.cloud.github.com/assets/3481055/1611747/39051ecc-55b5-11e3-99b4-a05dd94a2843.png)

Others items like DPU TEMPLATE, EXECUTION MONITOR, ... works fine :-)

**Comment by tomesj** [comment]
virtuoso.jdbc4.VirtuosoException: SQ200: No column visibility.
    at virtuoso.jdbc4.VirtuosoResultSet.process_result(Unknown Source) ~[jdbc-driver-4.jar:na]
    at virtuoso.jdbc4.VirtuosoResultSet.<init>(Unknown Source) ~[jdbc-driver-4.jar:na]
    at virtuoso.jdbc4.VirtuosoPreparedStatement.<init>(Unknown Source) ~[jdbc-driver-4.jar:na]
    at virtuoso.jdbc4.VirtuosoConnection.prepareStatement(Unknown Source) ~[jdbc-driver-4.jar:na]
    at virtuoso.jdbc4.VirtuosoConnection.prepareStatement(Unknown Source) ~[jdbc-driver-4.jar:na]
    at org.apache.commons.dbcp.DelegatingConnection.prepareStatement(DelegatingConnection.java:281) ~[commons-dbcp-1.4.jar:1.4]
    at org.apache.commons.dbcp.PoolingDataSource$PoolGuardConnectionWrapper.prepareStatement(PoolingDataSource.java:313) ~[commons-dbcp-1.4.jar:1.4]
    at org.eclipse.persistence.internal.databaseaccess.DatabaseAccessor.prepareStatement(DatabaseAccessor.java:1556) ~[eclipselink-2.5.1.jar:2.5.1.v20130918-f2b9fc5]
    at org.eclipse.persistence.internal.databaseaccess.DatabaseAccessor.prepareStatement(DatabaseAccessor.java:1505) ~[eclipselink-2.5.1.jar:2.5.1.v20130918-f2b9fc5]
    at org.eclipse.persistence.internal.databaseaccess.DatabaseCall.prepareStatement(DatabaseCall.java:778) ~[eclipselink-2.5.1.jar:2.5.1.v20130918-f2b9fc5]
    at org.eclipse.persistence.internal.databaseaccess.DatabaseAccessor.basicExecuteCall(DatabaseAccessor.java:619) ~[eclipselink-2.5.1.jar:2.5.1.v20130918-f2b9fc5]
    at org.eclipse.persistence.internal.databaseaccess.DatabaseAccessor.executeCall(DatabaseAccessor.java:558) ~[eclipselink-2.5.1.jar:2.5.1.v20130918-f2b9fc5]
    at org.eclipse.persistence.internal.sessions.AbstractSession.basicExecuteCall(AbstractSession.java:1991) ~[eclipselink-2.5.1.jar:2.5.1.v20130918-f2b9fc5]
    at org.eclipse.persistence.sessions.server.ServerSession.executeCall(ServerSession.java:570) ~[eclipselink-2.5.1.jar:2.5.1.v20130918-f2b9fc5]
    at org.eclipse.persistence.sessions.server.ClientSession.executeCall(ClientSession.java:250) ~[eclipselink-2.5.1.jar:2.5.1.v20130918-f2b9fc5]
    at org.eclipse.persistence.internal.queries.DatasourceCallQueryMechanism.executeCall(DatasourceCallQueryMechanism.java:242) ~[eclipselink-2.5.1.jar:2.5.1.v20130918-f2b9fc5]
    at org.eclipse.persistence.internal.queries.DatasourceCallQueryMechanism.executeCall(DatasourceCallQueryMechanism.java:228) ~[eclipselink-2.5.1.jar:2.5.1.v20130918-f2b9fc5]
    at org.eclipse.persistence.internal.queries.DatasourceCallQueryMechanism.executeSelectCall(DatasourceCallQueryMechanism.java:299) ~[eclipselink-2.5.1.jar:2.5.1.v20130918-f2b9fc5]
    at org.eclipse.persistence.internal.queries.DatasourceCallQueryMechanism.selectAllRows(DatasourceCallQueryMechanism.java:694) ~[eclipselink-2.5.1.jar:2.5.1.v20130918-f2b9fc5]
    at org.eclipse.persistence.internal.queries.ExpressionQueryMechanism.selectAllRowsFromTable(ExpressionQueryMechanism.java:2738) ~[eclipselink-2.5.1.jar:2.5.1.v20130918-f2b9fc5]
    at org.eclipse.persistence.internal.queries.ExpressionQueryMechanism.selectAllRows(ExpressionQueryMechanism.java:2691) ~[eclipselink-2.5.1.jar:2.5.1.v20130918-f2b9fc5]
    at org.eclipse.persistence.queries.ReadAllQuery.executeObjectLevelReadQuery(ReadAllQuery.java:495) ~[eclipselink-2.5.1.jar:2.5.1.v20130918-f2b9fc5]
    at org.eclipse.persistence.queries.ObjectLevelReadQuery.executeDatabaseQuery(ObjectLevelReadQuery.java:1168) ~[eclipselink-2.5.1.jar:2.5.1.v20130918-f2b9fc5]
    at org.eclipse.persistence.queries.DatabaseQuery.execute(DatabaseQuery.java:899) ~[eclipselink-2.5.1.jar:2.5.1.v20130918-f2b9fc5]
    at org.eclipse.persistence.queries.ObjectLevelReadQuery.execute(ObjectLevelReadQuery.java:1127) ~[eclipselink-2.5.1.jar:2.5.1.v20130918-f2b9fc5]
    at org.eclipse.persistence.queries.ReadAllQuery.execute(ReadAllQuery.java:403) ~[eclipselink-2.5.1.jar:2.5.1.v20130918-f2b9fc5]
    at org.eclipse.persistence.queries.ObjectLevelReadQuery.executeInUnitOfWork(ObjectLevelReadQuery.java:1215) ~[eclipselink-2.5.1.jar:2.5.1.v20130918-f2b9fc5]
    at org.eclipse.persistence.internal.sessions.UnitOfWorkImpl.internalExecuteQuery(UnitOfWorkImpl.java:2896) ~[eclipselink-2.5.1.jar:2.5.1.v20130918-f2b9fc5]
    at org.eclipse.persistence.internal.sessions.AbstractSession.executeQuery(AbstractSession.java:1793) ~[eclipselink-2.5.1.jar:2.5.1.v20130918-f2b9fc5]
    at org.eclipse.persistence.internal.sessions.AbstractSession.executeQuery(AbstractSession.java:1775) ~[eclipselink-2.5.1.jar:2.5.1.v20130918-f2b9fc5]
    at org.eclipse.persistence.internal.sessions.AbstractSession.executeQuery(AbstractSession.java:1740) ~[eclipselink-2.5.1.jar:2.5.1.v20130918-f2b9fc5]
    at org.eclipse.persistence.internal.jpa.QueryImpl.executeReadQuery(QueryImpl.java:258) ~[eclipselink-2.5.1.jar:2.5.1.v20130918-f2b9fc5]
    at org.eclipse.persistence.internal.jpa.QueryImpl.getResultList(QueryImpl.java:469) ~[eclipselink-2.5.1.jar:2.5.1.v20130918-f2b9fc5]
    at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method) ~[na:1.7.0_21]
    at sun.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:57) ~[na:1.7.0_21]
    at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43) ~[na:1.7.0_21]
    at java.lang.reflect.Method.invoke(Method.java:601) ~[na:1.7.0_21]
    at org.springframework.orm.jpa.SharedEntityManagerCreator$DeferredQueryInvocationHandler.invoke(SharedEntityManagerCreator.java:310) ~[spring-orm-3.1.2.RELEASE.jar:3.1.2.RELEASE]
    at com.sun.proxy.$Proxy41.getResultList(Unknown Source) ~[na:na]
    at cz.cuni.mff.xrg.odcs.commons.app.dao.db.DbAccessReadBase.executeList(DbAccessReadBase.java:78) ~[commons-app-1.0.0.jar:na]
    at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method) ~[na:1.7.0_21]
    at sun.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:57) ~[na:1.7.0_21]
    at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43) ~[na:1.7.0_21]
    at java.lang.reflect.Method.invoke(Method.java:601) ~[na:1.7.0_21]
    at org.springframework.aop.support.AopUtils.invokeJoinpointUsingReflection(AopUtils.java:309) ~[spring-aop-3.0.7.RELEASE.jar:3.0.7.RELEASE]
    at org.springframework.aop.framework.ReflectiveMethodInvocation.invokeJoinpoint(ReflectiveMethodInvocation.java:183) ~[spring-aop-3.0.7.RELEASE.jar:3.0.7.RELEASE]
    at org.springframework.aop.framework.ReflectiveMethodInvocation.proceed(ReflectiveMethodInvocation.java:150) ~[spring-aop-3.0.7.RELEASE.jar:3.0.7.RELEASE]
    at org.springframework.transaction.interceptor.TransactionInterceptor.invoke(TransactionInterceptor.java:110) ~[spring-tx-3.1.2.RELEASE.jar:3.1.2.RELEASE]
    at org.springframework.aop.framework.ReflectiveMethodInvocation.proceed(ReflectiveMethodInvocation.java:172) ~[spring-aop-3.0.7.RELEASE.jar:3.0.7.RELEASE]
    at org.springframework.aop.framework.JdkDynamicAopProxy.invoke(JdkDynamicAopProxy.java:202) ~[spring-aop-3.0.7.RELEASE.jar:3.0.7.RELEASE]
    at com.sun.proxy.$Proxy18.executeList(Unknown Source) ~[na:na]
    at cz.cuni.mff.xrg.odcs.frontend.doa.container.CachedSource.loadByIndex(CachedSource.java:139) ~[CachedSource.class:na]
    at cz.cuni.mff.xrg.odcs.frontend.doa.container.CachedSource.getItemIds(CachedSource.java:241) ~[CachedSource.class:na]
    at cz.cuni.mff.xrg.odcs.frontend.container.ReadOnlyContainer.getItemIds(ReadOnlyContainer.java:253) ~[ReadOnlyContainer.class:na]
    at org.tepi.filtertable.paged.PagedFilterTableContainer.getItemIds(PagedFilterTableContainer.java:84) ~[filteringtable-0.9.0.v7.jar:0.9.0.v7]
    at com.vaadin.ui.CustomTable.getItemIds(CustomTable.java:2195) ~[filteringtable-0.9.0.v7.jar:7.1.5]
    at com.vaadin.ui.CustomTable.getVisibleCellsNoCache(CustomTable.java:2145) ~[filteringtable-0.9.0.v7.jar:7.1.5]
    at com.vaadin.ui.CustomTable.refreshRenderedCells(CustomTable.java:1670) ~[filteringtable-0.9.0.v7.jar:7.1.5]
    at com.vaadin.ui.CustomTable.enableContentRefreshing(CustomTable.java:3147) ~[filteringtable-0.9.0.v7.jar:7.1.5]
    at com.vaadin.ui.CustomTable.setContainerDataSource(CustomTable.java:2715) ~[filteringtable-0.9.0.v7.jar:7.1.5]
    at com.vaadin.ui.CustomTable.setContainerDataSource(CustomTable.java:2656) ~[filteringtable-0.9.0.v7.jar:7.1.5]
    at org.tepi.filtertable.FilterTable.setContainerDataSource(FilterTable.java:119) ~[filteringtable-0.9.0.v7.jar:0.9.0.v7]
    at org.tepi.filtertable.paged.PagedFilterTable.setContainerDataSource(PagedFilterTable.java:235) ~[filteringtable-0.9.0.v7.jar:0.9.0.v7]
    at cz.cuni.mff.xrg.odcs.frontend.gui.tables.IntlibPagedTable.setContainerDataSource(IntlibPagedTable.java:210) ~[IntlibPagedTable.class:na]
    at cz.cuni.mff.xrg.odcs.frontend.gui.views.pipelinelist.PipelineListViewImpl.setDisplay(PipelineListViewImpl.java:176) ~[PipelineListViewImpl.class:na]
    at cz.cuni.mff.xrg.odcs.frontend.gui.views.pipelinelist.PipelineListPresenterImpl.enter(PipelineListPresenterImpl.java:53) ~[PipelineListPresenterImpl.class:na]
    at cz.cuni.mff.xrg.odcs.frontend.navigation.PresenterWrap.enterPresenter(PresenterWrap.java:41) ~[PresenterWrap.class:na]
    at cz.cuni.mff.xrg.odcs.frontend.navigation.PresenterViewDisplay.showView(PresenterViewDisplay.java:41) ~[PresenterViewDisplay.class:na]
    at com.vaadin.navigator.Navigator.navigateTo(Navigator.java:568) ~[vaadin-server-7.1.5.jar:7.1.5]
    at com.vaadin.navigator.Navigator.navigateTo(Navigator.java:526) ~[vaadin-server-7.1.5.jar:7.1.5]
    at cz.cuni.mff.xrg.odcs.frontend.navigation.ClassNavigatorImpl.navigateTo(ClassNavigatorImpl.java:49) ~[ClassNavigatorImpl.class:na]
    at cz.cuni.mff.xrg.odcs.frontend.navigation.ClassNavigatorHolder.navigateTo(ClassNavigatorHolder.java:24) ~[ClassNavigatorHolder.class:na]
    at cz.cuni.mff.xrg.odcs.frontend.gui.MenuLayout$NavigateToCommand.menuSelected(MenuLayout.java:204) ~[MenuLayout$NavigateToCommand.class:na]
    at com.vaadin.ui.MenuBar.changeVariables(MenuBar.java:186) ~[vaadin-server-7.1.5.jar:7.1.5]
    at com.vaadin.server.communication.ServerRpcHandler.changeVariables(ServerRpcHandler.java:403) [vaadin-server-7.1.5.jar:7.1.5]
    at com.vaadin.server.communication.ServerRpcHandler.handleBurst(ServerRpcHandler.java:228) [vaadin-server-7.1.5.jar:7.1.5]
    at com.vaadin.server.communication.ServerRpcHandler.handleRpc(ServerRpcHandler.java:111) [vaadin-server-7.1.5.jar:7.1.5]
    at com.vaadin.server.communication.UidlRequestHandler.synchronizedHandleRequest(UidlRequestHandler.java:91) [vaadin-server-7.1.5.jar:7.1.5]
    at com.vaadin.server.SynchronizedRequestHandler.handleRequest(SynchronizedRequestHandler.java:37) [vaadin-server-7.1.5.jar:7.1.5]
    at com.vaadin.server.VaadinService.handleRequest(VaadinService.java:1371) [vaadin-server-7.1.5.jar:7.1.5]
    at com.vaadin.server.VaadinServlet.service(VaadinServlet.java:238) [vaadin-server-7.1.5.jar:7.1.5]
    at cz.cuni.mff.xrg.odcs.frontend.IntlibApplicationServlet.service(IntlibApplicationServlet.java:52) [IntlibApplicationServlet.class:na]
    at javax.servlet.http.HttpServlet.service(HttpServlet.java:728) [servlet-api.jar:na]
    at org.apache.catalina.core.ApplicationFilterChain.internalDoFilter(ApplicationFilterChain.java:305) [catalina.jar:7.0.42]
    at org.apache.catalina.core.ApplicationFilterChain.doFilter(ApplicationFilterChain.java:210) [catalina.jar:7.0.42]
    at org.apache.catalina.core.StandardWrapperValve.invoke(StandardWrapperValve.java:222) [catalina.jar:7.0.42]
    at org.apache.catalina.core.StandardContextValve.invoke(StandardContextValve.java:123) [catalina.jar:7.0.42]
    at org.apache.catalina.authenticator.AuthenticatorBase.invoke(AuthenticatorBase.java:502) [catalina.jar:7.0.42]
    at org.apache.catalina.core.StandardHostValve.invoke(StandardHostValve.java:171) [catalina.jar:7.0.42]
    at org.apache.catalina.valves.ErrorReportValve.invoke(ErrorReportValve.java:99) [catalina.jar:7.0.42]
    at org.apache.catalina.valves.AccessLogValve.invoke(AccessLogValve.java:953) [catalina.jar:7.0.42]
    at org.apache.catalina.core.StandardEngineValve.invoke(StandardEngineValve.java:118) [catalina.jar:7.0.42]
    at org.apache.catalina.connector.CoyoteAdapter.service(CoyoteAdapter.java:408) [catalina.jar:7.0.42]
    at org.apache.coyote.http11.AbstractHttp11Processor.process(AbstractHttp11Processor.java:1023) [tomcat-coyote.jar:7.0.42]
    at org.apache.coyote.AbstractProtocol$AbstractConnectionHandler.process(AbstractProtocol.java:589) [tomcat-coyote.jar:7.0.42]
    at org.apache.tomcat.util.net.AprEndpoint$SocketProcessor.run(AprEndpoint.java:1852) [tomcat-coyote.jar:7.0.42]
    at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1145) [na:1.7.0_21]
    at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:615) [na:1.7.0_21]
    at java.lang.Thread.run(Thread.java:722) [na:1.7.0_21]

**Comment by janvojt** [comment]
Sorry, I forgot to attach update SQL script for commit b7aec22c. Here it is:

``` sql
ALTER TABLE PPL_MODEL ADD "visibility" SMALLINT;
```
