### ISSUE TITLE
SPARQLTest

### ISSUE THREAD

**Issue by skodapetr** [mff-uk/odcs#834]
Aniž bych něco měnil dostal jsem .. 

nejsem si zrovna jistý věcmi jako 

```
for (RDFDataUnit repository : inputs) {
URI dataGraphURI = repository.getDataGraph();
dataSet.addDefaultGraph(dataGraphURI);
}
```

neb v inputs může být klidně null .. což ukazuje podle mě selhání následujícího testu. Přehlížím něco, nebo jen test nezafungoval .. když se toto implementovalo?

```
Tests run: 1, Failures: 0, Errors: 1, Skipped: 0, Time elapsed: 2.43 sec <<< FAILURE!
constructAllTest(cz.cuni.mff.xrg.odcs.transformer.SPARQL.SPARQLTest)  Time elapsed: 2.43 sec  <<< ERROR!
java.lang.NullPointerException: null
    at cz.cuni.mff.xrg.odcs.transformer.SPARQL.SPARQLTransformer.createGraphDataSet(SPARQLTransformer.java:63)
    at cz.cuni.mff.xrg.odcs.transformer.SPARQL.SPARQLTransformer.execute(SPARQLTransformer.java:100)
    at cz.cuni.mff.xrg.odcs.dpu.test.TestEnvironment.run(TestEnvironment.java:272)
    at cz.cuni.mff.xrg.odcs.transformer.SPARQL.SPARQLTest.constructAllTest(SPARQLTest.java:43)
```

**Comment by tomesj** [comment]
Aha...Už to vidím, bral jsem to tak, že všechny vstupy jsou vždy inicializované, jen jsou prázdné, pokud do toho nic nejde - a oni jsou rovnou null. Tak to je potom jasné. 

Přilepím opravu a zavírám (jinak díky za upozornění).
