### ISSUE TITLE
When launching pipeline, problem with logging facade

### ISSUE THREAD

**Issue by tomas-knap** [mff-uk/odcs#854]
There is a warn regarding logging and then the pipeline remains in the status running.

Two problems: 
- with the logging
- it is strange that pipeline do not finish with error

Tested on commit 

commit 9de0c763fd12483e92b96f88fb41d256fedf4fba
Author: bogo777 bogo777@gmail.com
Date:   Thu Nov 28 09:30:32 2013 +0100

2013-11-28 13:33:19,682 [pool-2-thread-2] INFO  exec:573 dpu: c.c.m.x.o.b.p.e.PipelineInfo - Starting execution number: 573 pipeline: DBpedia
2013-11-28 13:33:19,767 [pool-2-thread-2] WARN  exec:573 dpu: o.e.p.logging.default - 2013-11-28 13:33:19.767--UnitOfWork(818444121)--Thread(Thread[pool-2-thread-2,5,main])--
2013-11-28 13:33:20,654 [taskScheduler-4] TRACE exec: dpu: c.c.m.x.o.b.execution.Engine - Checking for new executions.

**Comment by tomas-knap** [comment]
Did not appear on the commit from yesterday

**Comment by tomas-knap** [comment]
![screen shot 2013-11-28 at 3 44 19 pm](https://f.cloud.github.com/assets/3014917/1640519/9660282c-583b-11e3-9adc-cb3131fd3f35.png)

**Comment by tomas-knap** [comment]
2013-11-28 16:57:16,990 [taskScheduler-3] ERROR exec:572 dpu: o.s.s.s.TaskUtils$LoggingErrorHandler - Unexpected error occurred in scheduled task.
org.springframework.transaction.TransactionSystemException: Could not commit JPA transaction; nested exception is javax.persistence.RollbackException: Exception [EclipseLink-4002](Eclipse Persistence Services - 2.5.1.v20130918-f2b9fc5): org.eclipse.persistence.exceptions.DatabaseException
Internal Exception: virtuoso.jdbc4.VirtuosoException: SR197: Non unique primary key on DB.ODCS.EXEC_RECORD.
Error Code: -8
Call: INSERT INTO exec_record (ID, full_message, short_message, r_time, r_type, dpu_id, execution_id) VALUES (?, ?, ?, ?, ?, ?, ?)
    bind => [2937, , Pipeline execution has been restarted., 2013-11-28 16:57:16.868, 6, null, 572]
Query: InsertObjectQuery(cz.cuni.mff.xrg.odcs.commons.app.execution.message.MessageRecord@9611f3e)
    at org.springframework.orm.jpa.JpaTransactionManager.doCommit(JpaTransactionManager.java:521) ~[spring-orm-3.1.2.RELEASE.jar:3.1.2.RELEASE]
    at org.springframework.transaction.support.AbstractPlatformTransactionManager.processCommit(AbstractPlatformTransactionManager.java:754) ~[spring-tx-3.1.2.RELEASE.jar:3.1.2.RELEASE]
    at org.springframework.transaction.support.AbstractPlatformTransactionManager.commit(AbstractPlatformTransactionManager.java:723) ~[spring-tx-3.1.2.RELEASE.jar:3.1.2.RELEASE]
    at org.springframework.transaction.interceptor.TransactionAspectSupport.commitTransactionAfterReturning(TransactionAspectSupport.java:394) ~[spring-tx-3.1.2.RELEASE.jar:3.1.2.RELEASE]
    at org.springframework.transaction.interceptor.TransactionInterceptor.invoke(TransactionInterceptor.java:120) ~[spring-tx-3.1.2.RELEASE.jar:3.1.2.RELEASE]
    at org.springframework.aop.framework.ReflectiveMethodInvocation.proceed(ReflectiveMethodInvocation.java:172) ~[spring-aop-3.1.2.RELEASE.jar:3.1.2.RELEASE]
    at org.springframework.aop.interceptor.ExposeInvocationInterceptor.invoke(ExposeInvocationInterceptor.java:90) ~[spring-aop-3.1.2.RELEASE.jar:3.1.2.RELEASE]
    at org.springframework.aop.framework.ReflectiveMethodInvocation.proceed(ReflectiveMethodInvocation.java:172) ~[spring-aop-3.1.2.RELEASE.jar:3.1.2.RELEASE]
    at org.springframework.aop.framework.Cglib2AopProxy$DynamicAdvisedInterceptor.intercept(Cglib2AopProxy.java:622) ~[spring-aop-3.1.2.RELEASE.jar:3.1.2.RELEASE]
    at cz.cuni.mff.xrg.odcs.commons.app.dpu.DPUFacade$$EnhancerByCGLIB$$b27ad10e.save(<generated>) ~[cglib-3.0.jar:na]
    at cz.cuni.mff.xrg.odcs.backend.EventListenerDatabase.onPipelineEvent(EventListenerDatabase.java:38) ~[backend-1.0.0.jar:na]
    at cz.cuni.mff.xrg.odcs.backend.EventListenerDatabase.onApplicationEvent(EventListenerDatabase.java:47) ~[backend-1.0.0.jar:na]
    at org.springframework.context.event.SimpleApplicationEventMulticaster.multicastEvent(SimpleApplicationEventMulticaster.java:97) ~[spring-context-3.1.2.RELEASE.jar:3.1.2.RELEASE]
    at org.springframework.context.support.AbstractApplicationContext.publishEvent(AbstractApplicationContext.java:324) ~[spring-context-3.1.2.RELEASE.jar:3.1.2.RELEASE]
    at cz.cuni.mff.xrg.odcs.backend.execution.ExecutionSanitizer.sanitizeRunning(ExecutionSanitizer.java:95) ~[backend-1.0.0.jar:na]
    at cz.cuni.mff.xrg.odcs.backend.execution.ExecutionSanitizer.sanitize(ExecutionSanitizer.java:80) ~[backend-1.0.0.jar:na]
    at cz.cuni.mff.xrg.odcs.backend.execution.Engine.startUp(Engine.java:148) ~[backend-1.0.0.jar:na]
    at cz.cuni.mff.xrg.odcs.backend.execution.Engine.checkDatabase(Engine.java:116) ~[backend-1.0.0.jar:na]
    at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method) ~[na:1.7.0_40]
    at sun.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:57) ~[na:1.7.0_40]
    at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43) ~[na:1.7.0_40]
    at java.lang.reflect.Method.invoke(Method.java:606) ~[na:1.7.0_40]
    at org.springframework.scheduling.support.ScheduledMethodRunnable.run(ScheduledMethodRunnable.java:64) ~[spring-context-3.1.2.RELEASE.jar:3.1.2.RELEASE]
    at org.springframework.scheduling.support.DelegatingErrorHandlingRunnable.run(DelegatingErrorHandlingRunnable.java:53) ~[spring-context-3.1.2.RELEASE.jar:3.1.2.RELEASE]
    at java.util.concurrent.Executors$RunnableAdapter.call(Executors.java:471) [na:1.7.0_40]
    at java.util.concurrent.FutureTask.runAndReset(FutureTask.java:304) [na:1.7.0_40]
    at java.util.concurrent.ScheduledThreadPoolExecutor$ScheduledFutureTask.access$301(ScheduledThreadPoolExecutor.java:178) [na:1.7.0_40]
    at java.util.concurrent.ScheduledThreadPoolExecutor$ScheduledFutureTask.run(ScheduledThreadPoolExecutor.java:293) [na:1.7.0_40]
    at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1145) [na:1.7.0_40]
    at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:615) [na:1.7.0_40]
    at java.lang.Thread.run(Thread.java:724) [na:1.7.0_40]
Caused by: javax.persistence.RollbackException: Exception [EclipseLink-4002](Eclipse Persistence Services - 2.5.1.v20130918-f2b9fc5): org.eclipse.persistence.exceptions.DatabaseException
Internal Exception: virtuoso.jdbc4.VirtuosoException: SR197: Non unique primary key on DB.ODCS.EXEC_RECORD.
Error Code: -8

**Comment by tomas-knap** [comment]
non-unique primary key again, relates to #763 #643

**Comment by tomas-knap** [comment]
Duplicates #763 #643
