### ISSUE TITLE
Exception when clicking on the pipeline in pipeline list

### ISSUE THREAD

**Issue by tomas-knap** [mff-uk/odcs#867]
Applies to commit: commit 6dd25f54bd408a93009b8d4cf5a09e65092450da

After using GUI for a while: 

![screen shot 2013-12-02 at 4 49 45 pm](https://f.cloud.github.com/assets/3014917/1655936/85d2f03e-5b6a-11e3-89de-9e79adb43303.png)

```
2013-12-02 16:50:12,003 [http-bio-8080-exec-353] DEBUG org.eclipse.persistence.logging.sql - 2013-12-02 16:50:12.003--ServerSession(793478170)--Connection(1994717211)--Thread(Thread[http-bio-8080-exec-353,5,main])--SELECT TOP 0,1 ID AS a1, t_end AS a2, debug_mode AS a3, t_last_change AS a4, silent_mode AS a5, t_start AS a6, STATUS AS a7, stop AS a8, debugnode_id AS a9, owner_id AS a10, pipeline_id AS a11, schedule_id AS a12, context_id AS a13 FROM exec_pipeline WHERE (((pipeline_id = ?) AND (STATUS IN (?,?,?,?,?,?,?))) AND (t_end IS NOT NULL)) ORDER BY t_end DESC
    bind => [158, 0, 1, 2, 3, 4, 5, 6]
2013-12-02 16:50:12,005 [http-bio-8080-exec-353] DEBUG c.c.m.x.o.f.g.v.p.PipelineListPresenterImpl - Pipeline list refreshed.
2013-12-02 16:50:12,445 [http-bio-8080-exec-353] TRACE c.c.m.xrg.odcs.frontend.doa.container.CachedSource - loadById(null)
2013-12-02 16:50:12,446 [http-bio-8080-exec-353] DEBUG org.eclipse.persistence.logging.sql - 2013-12-02 16:50:12.446--ServerSession(793478170)--Connection(1020479313)--Thread(Thread[http-bio-8080-exec-353,5,main])--SELECT TOP 0,1 ID AS a1, DESCRIPTION AS a2, NAME AS a3, visibility AS a4, user_id AS a5 FROM ppl_model WHERE (ID IS NULL)
2013-12-02 16:50:12,449 [http-bio-8080-exec-353] WARN  c.c.m.xrg.odcs.frontend.doa.container.CachedSource - Failed to load data with id null
2013-12-02 16:50:12,450 [http-bio-8080-exec-353] ERROR cz.cuni.mff.xrg.odcs.frontend.AppEntry - Uncaught exception
java.lang.NullPointerException: null
    at cz.cuni.mff.xrg.odcs.frontend.container.accessor.PipelineAccessor.getValue(PipelineAccessor.java:86) ~[PipelineAccessor.class:na]
    at cz.cuni.mff.xrg.odcs.frontend.container.accessor.PipelineAccessor.getValue(PipelineAccessor.java:19) ~[PipelineAccessor.class:na]
    at cz.cuni.mff.xrg.odcs.frontend.container.GeneralProperty.getValueForObject(GeneralProperty.java:41) ~[GeneralProperty.class:na]
    at cz.cuni.mff.xrg.odcs.frontend.container.ValueProperty.getValue(ValueProperty.java:30) ~[ValueProperty.class:na]
    at cz.cuni.mff.xrg.odcs.frontend.gui.views.pipelinelist.PipelineListViewImpl$3.itemClick(PipelineListViewImpl.java:112) ~[PipelineListViewImpl$3.class:na]
    at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method) ~[na:1.7.0_40]
    at sun.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:57) ~[na:1.7.0_40]
    at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43) ~[na:1.7.0_40]
    at java.lang.reflect.Method.invoke(Method.java:606) ~[na:1.7.0_40]
    at com.vaadin.event.ListenerMethod.receiveEvent(ListenerMethod.java:508) ~[vaadin-server-7.1.8.jar:7.1.8]
    at com.vaadin.event.EventRouter.fireEvent(EventRouter.java:167) ~[vaadin-server-7.1.8.jar:7.1.8]
    at com.vaadin.server.AbstractClientConnector.fireEvent(AbstractClientConnector.java:969) ~[vaadin-server-7.1.8.jar:7.1.8]
    at com.vaadin.ui.CustomTable.handleClickEvent(CustomTable.java:3035) ~[filteringtable-0.9.0.v7.jar:7.1.8]
    at com.vaadin.ui.CustomTable.changeVariables(CustomTable.java:2830) ~[filteringtable-0.9.0.v7.jar:7.1.8]
    at com.vaadin.server.communication.ServerRpcHandler.changeVariables(ServerRpcHandler.java:396) [vaadin-server-7.1.8.jar:7.1.8]
    at com.vaadin.server.communication.ServerRpcHandler.handleBurst(ServerRpcHandler.java:221) [vaadin-server-7.1.8.jar:7.1.8]
    at com.vaadin.server.communication.ServerRpcHandler.handleRpc(ServerRpcHandler.java:111) [vaadin-server-7.1.8.jar:7.1.8]
    at com.vaadin.server.communication.UidlRequestHandler.synchronizedHandleRequest(UidlRequestHandler.java:91) [vaadin-server-7.1.8.jar:7.1.8]
    at com.vaadin.server.SynchronizedRequestHandler.handleRequest(SynchronizedRequestHandler.java:37) [vaadin-server-7.1.8.jar:7.1.8]
    at com.vaadin.server.VaadinService.handleRequest(VaadinService.java:1371) [vaadin-server-7.1.8.jar:7.1.8]
    at com.vaadin.server.VaadinServlet.service(VaadinServlet.java:238) [vaadin-server-7.1.8.jar:7.1.8]
    at cz.cuni.mff.xrg.odcs.frontend.IntlibApplicationServlet.service(IntlibApplicationServlet.java:66) [IntlibApplicationServlet.class:na]
    at javax.servlet.http.HttpServlet.service(HttpServlet.java:728) [servlet-api.jar:na]
    at org.apache.catalina.core.ApplicationFilterChain.internalDoFilter(ApplicationFilterChain.java:305) [catalina.jar:7.0.33]
    at org.apache.catalina.core.ApplicationFilterChain.doFilter(ApplicationFilterChain.java:210) [catalina.jar:7.0.33]
    at org.apache.catalina.core.StandardWrapperValve.invoke(StandardWrapperValve.java:222) [catalina.jar:7.0.33]
    at org.apache.catalina.core.StandardContextValve.invoke(StandardContextValve.java:123) [catalina.jar:7.0.33]
    at org.apache.catalina.authenticator.AuthenticatorBase.invoke(AuthenticatorBase.java:472) [catalina.jar:7.0.33]
    at org.apache.catalina.core.StandardHostValve.invoke(StandardHostValve.java:171) [catalina.jar:7.0.33]
    at org.apache.catalina.valves.ErrorReportValve.invoke(ErrorReportValve.java:99) [catalina.jar:7.0.33]
    at org.apache.catalina.valves.AccessLogValve.invoke(AccessLogValve.java:931) [catalina.jar:7.0.33]
    at org.apache.catalina.core.StandardEngineValve.invoke(StandardEngineValve.java:118) [catalina.jar:7.0.33]
    at org.apache.catalina.connector.CoyoteAdapter.service(CoyoteAdapter.java:407) [catalina.jar:7.0.33]
    at org.apache.coyote.http11.AbstractHttp11Processor.process(AbstractHttp11Processor.java:1004) [tomcat-coyote.jar:7.0.33]
    at org.apache.coyote.AbstractProtocol$AbstractConnectionHandler.process(AbstractProtocol.java:589) [tomcat-coyote.jar:7.0.33]
    at org.apache.tomcat.util.net.JIoEndpoint$SocketProcessor.run(JIoEndpoint.java:312) [tomcat-coyote.jar:7.0.33]
    at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1145) [na:1.7.0_40]
    at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:615) [na:1.7.0_40]
    at java.lang.Thread.run(Thread.java:724) [na:1.7.0_40]
2013-12-02 16:50:16,862 [http-bio-8080-exec-353] DEBUG org.eclipse.persistence.logging.sql - 2013-12-02 16:50:16.862--ServerSession(793478170)--Connection(1455731560)--Thread(Thread[http-bio-8080-exec-353,5,main])--SELECT CASE  WHEN (MAX(t_last_change) > ?) THEN CAST(? AS INTEGER) ELSE CAST(? AS INTEGER) END FROM exec_pipeline
    bind => [2013-12-02 16:50:11.865, 1, 0]
2013-12-02 16:50:16,863 [http-bio-8080-exec-353] DEBUG c.c.m.x.o.f.g.v.p.PipelineListPresenterImpl - Pipeline list refreshed.
2013-12-02 16:50:21,874 [http-bio-8080-exec-353] DEBUG org.eclipse.persistence.logging.sql - 2013-12-02 16:50:21.874--ServerSession(793478170)--Connection(199138649)--Thread(Thread[http-bio-8080-exec-353,5,main])--SELECT CASE  WHEN (MAX(t_last_change) > ?) THEN CAST(? AS INTEGER) ELSE CAST(? AS INTEGER) END FROM exec_pipeline
```

**Comment by skodapetr** [comment]
This seems to be hard to replicate .. from log .. 

```
2013-12-02 16:50:12,445 [http-bio-8080-exec-353] TRACE c.c.m.xrg.odcs.frontend.doa.container.CachedSource - loadById(null)
```

we know how and why ... and we can prevent the exception by ignoring the on-click action .. what we do not know is what is the cause of this (why the table give us object with null as Id ) .. I added few more logs (just few, as this slow down the performance of all tables in ODCS) .. so please if anybody see this exception again, please send me the frontend's log .. better more then less

**Comment by tomas-knap** [comment]
Well, if you know that it happens only rarely, we can just log the problem, do not show anything to the user and simply try the action again.

**Comment by tomas-knap** [comment]
Also please add TODO to the code, so that we know that we do not know the cause, but know that it happens only rarely, and that is the reason why we are simply trying the action again

**Comment by skodapetr** [comment]
Yes we can .. but with that I decrease the chance, that some post me the log .. what about .. let the exception to be thrown for 7 - 10 days .. then we do what you propose? I sill hope that we find the true reason for that.

it probably does not help to try it again .. the problem is, that the on-click action (from table) say that the event is on object with id = null. So we can just ignore .. and hope that user click on something else ..

**Comment by tomas-knap** [comment]
Ok, got the point. If we cannot come with solution till midDecember, we should simply hide it.

**Comment by skodapetr** [comment]
As it shows up .. the ROC can be asked to return ValueObject for null ID despite the fact that no object of null id has ever been created before.
So I added check for id = null into ROC. If the id is not null then return ValueObject with given ID, otherwise return null (according to the documentation) and log .. so let's test ..
