### ISSUE TITLE
Error when refreshing logs in exec detail

### ISSUE THREAD

**Issue by tomas-knap** [mff-uk/odcs#871]
Pipeline ARES test was running, logs were reloaded. During one of the reloads, I click on settings menu item. The error occurred and then view was changed. Petre, please reassign on Honza, if you are not responsible

![screen shot 2013-12-03 at 3 38 08 pm](https://f.cloud.github.com/assets/3014917/1664537/dbd042a2-5c28-11e3-9e6f-5400fa65e640.png)

2013-12-03 15:38:33,192 [http-bio-8080-exec-376] DEBUG org.eclipse.persistence.logging.sql - 2013-12-03 15:38:33.192--ServerSession(1770567193)--Connection(276100375)--Thread(Thread[http-bio-8080-exec-376,5,main])--SELECT TOP 0,1 id AS a1, DPU AS a2, EXECUTION AS a3, logLevel AS a4, message AS a5, logger AS a6, stack_trace AS a7, timestmp AS a8 FROM logging WHERE ((EXECUTION = ?) AND (id IS NULL))
    bind => [628]
2013-12-03 15:38:33,192 [http-bio-8080-exec-376] DEBUG org.eclipse.persistence.logging.sql - 2013-12-03 15:38:33.192--ServerSession(1770567193)--Thread(Thread[http-bio-8080-exec-376,5,main])--SELECT 1
2013-12-03 15:38:33,194 [http-bio-8080-exec-376] WARN  org.eclipse.persistence.logging.Slf4jSessionLogger - Unknown category 'null', the default is used.
2013-12-03 15:38:33,195 [http-bio-8080-exec-376] WARN  org.eclipse.persistence.logging.Slf4jSessionLogger - Unknown category 'null', the default is used.
2013-12-03 15:38:33,195 [http-bio-8080-exec-376] WARN  org.eclipse.persistence.logging.Slf4jSessionLogger - Unknown category 'null', the default is used.
2013-12-03 15:38:33,195 [http-bio-8080-exec-376] WARN  org.eclipse.persistence.logging.Slf4jSessionLogger - Unknown category 'null', the default is used.
2013-12-03 15:38:33,195 [http-bio-8080-exec-376] WARN  org.eclipse.persistence.logging.default - 2013-12-03 15:38:33.195--UnitOfWork(1854325105)--Thread(Thread[http-bio-8080-exec-376,5,main])--
2013-12-03 15:38:33,241 [http-bio-8080-exec-376] ERROR cz.cuni.mff.xrg.odcs.frontend.AppEntry - Uncaught exception
virtuoso.jdbc4.VirtuosoException: Index 1 is not 1<n<0
    at virtuoso.jdbc4.VirtuosoPreparedStatement.setLong(Unknown Source) ~[jdbc-driver-4.jar:na]
    at org.apache.commons.dbcp.DelegatingPreparedStatement.setLong(DelegatingPreparedStatement.java:123) ~[commons-dbcp-1.4.jar:1.4]
    at org.apache.commons.dbcp.DelegatingPreparedStatement.setLong(DelegatingPreparedStatement.java:123) ~[commons-dbcp-1.4.jar:1.4]
    at org.eclipse.persistence.internal.databaseaccess.DatabasePlatform.setParameterValueInDatabaseCall(DatabasePlatform.java:2383) ~[eclipselink-2.5.1.jar:2.5.1.v20130918-f2b9fc5]
    at org.eclipse.persistence.internal.databaseaccess.DatabaseCall.prepareStatement(DatabaseCall.java:797) ~[eclipselink-2.5.1.jar:2.5.1.v20130918-f2b9fc5]
    at org.eclipse.persistence.internal.databaseaccess.DatabaseAccessor.basicExecuteCall(DatabaseAccessor.java:619) ~[eclipselink-2.5.1.jar:2.5.1.v20130918-f2b9fc5]
    at org.eclipse.persistence.internal.databaseaccess.DatabaseAccessor.executeCall(DatabaseAccessor.java:558) ~[eclipselink-2.5.1.jar:2.5.1.v20130918-f2b9fc5]
    at org.eclipse.persistence.internal.sessions.AbstractSession.basicExecuteCall(AbstractSession.java:1991) ~[eclipselink-2.5.1.jar:2.5.1.v20130918-f2b9fc5]
    at org.eclipse.persistence.sessions.server.ServerSession.executeCall(ServerSession.java:570) ~[eclipselink-2.5.1.jar:2.5.1.v20130918-f2b9fc5]
    at org.eclipse.persistence.sessions.server.ClientSession.executeCall(ClientSession.java:250) ~[eclipselink-2.5.1.jar:2.5.1.v20130918-f2b9fc5]
    at org.eclipse.persistence.internal.queries.DatasourceCallQueryMechanism.executeCall(DatasourceCallQueryMechanism.java:242) ~[eclipselink-2.5.1.jar:2.5.1.v20130918-f2b9fc5]
    at org.eclipse.persistence.internal.queries.DatasourceCallQueryMechanism.executeCall(DatasourceCallQueryMechanism.java:228) ~[eclipselink-2.5.1.jar:2.5.1.v20130918-f2b9fc5]
    at org.eclipse.persistence.internal.queries.DatasourceCallQueryMechanism.executeSelectCall(DatasourceCallQueryMechanism.java:299) ~[eclipselink-2.5.1.jar:2.5.1.v20130918-f2b9fc5]
    at org.eclipse.persistence.internal.queries.DatasourceCallQueryMechanism.selectAllRows(DatasourceCallQueryMechanism.java:694) ~[eclipselink-2.5.1.jar:2.5.1.v20130918-f2b9fc5]
    at org.eclipse.persistence.internal.queries.ExpressionQueryMechanism.selectAllRowsFromTable(ExpressionQueryMechanism.java:2738) ~[eclipselink-2.5.1.jar:2.5.1.v20130918-f2b9fc5]
    at org.eclipse.persistence.internal.queries.ExpressionQueryMechanism.selectAllRows(ExpressionQueryMechanism.java:2691) ~[eclipselink-2.5.1.jar:2.5.1.v20130918-f2b9fc5]
    at org.eclipse.persistence.queries.ReadAllQuery.executeObjectLevelReadQuery(ReadAllQuery.java:495) ~[eclipselink-2.5.1.jar:2.5.1.v20130918-f2b9fc5]
    at org.eclipse.persistence.queries.ObjectLevelReadQuery.executeDatabaseQuery(ObjectLevelReadQuery.java:1168) ~[eclipselink-2.5.1.jar:2.5.1.v20130918-f2b9fc5]
    at org.eclipse.persistence.queries.DatabaseQuery.execute(DatabaseQuery.java:899) ~[eclipselink-2.5.1.jar:2.5.1.v20130918-f2b9fc5]
    at org.eclipse.persistence.queries.ObjectLevelReadQuery.execute(ObjectLevelReadQuery.java:1127) ~[eclipselink-2.5.1.jar:2.5.1.v20130918-f2b9fc5]
    at org.eclipse.persistence.queries.ReadAllQuery.execute(ReadAllQuery.java:403) ~[eclipselink-2.5.1.jar:2.5.1.v20130918-f2b9fc5]
    at org.eclipse.persistence.queries.ObjectLevelReadQuery.executeInUnitOfWork(ObjectLevelReadQuery.java:1215) ~[eclipselink-2.5.1.jar:2.5.1.v20130918-f2b9fc5]
    at org.eclipse.persistence.internal.sessions.UnitOfWorkImpl.internalExecuteQuery(UnitOfWorkImpl.java:2896) ~[eclipselink-2.5.1.jar:2.5.1.v20130918-f2b9fc5]
    at org.eclipse.persistence.internal.sessions.AbstractSession.executeQuery(AbstractSession.java:1793) ~[eclipselink-2.5.1.jar:2.5.1.v20130918-f2b9fc5]
    at org.eclipse.persistence.internal.sessions.AbstractSession.executeQuery(AbstractSession.java:1775) ~[eclipselink-2.5.1.jar:2.5.1.v20130918-f2b9fc5]
    at org.eclipse.persistence.internal.sessions.AbstractSession.executeQuery(AbstractSession.java:1740) ~[eclipselink-2.5.1.jar:2.5.1.v20130918-f2b9fc5]
    at org.eclipse.persistence.internal.jpa.QueryImpl.executeReadQuery(QueryImpl.java:258) ~[eclipselink-2.5.1.jar:2.5.1.v20130918-f2b9fc5]
    at org.eclipse.persistence.internal.jpa.QueryImpl.getSingleResult(QueryImpl.java:517) ~[eclipselink-2.5.1.jar:2.5.1.v20130918-f2b9fc5]
    at org.eclipse.persistence.internal.jpa.EJBQueryImpl.getSingleResult(EJBQueryImpl.java:400) ~[eclipselink-2.5.1.jar:2.5.1.v20130918-f2b9fc5]
    at sun.reflect.GeneratedMethodAccessor1786.invoke(Unknown Source) ~[na:na]
    at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43) ~[na:1.7.0_40]
    at java.lang.reflect.Method.invoke(Method.java:606) ~[na:1.7.0_40]
    at org.springframework.orm.jpa.SharedEntityManagerCreator$DeferredQueryInvocationHandler.invoke(SharedEntityManagerCreator.java:310) ~[spring-orm-3.1.2.RELEASE.jar:3.1.2.RELEASE]
    at com.sun.proxy.$Proxy523.getSingleResult(Unknown Source) ~[na:na]
    at cz.cuni.mff.xrg.odcs.commons.app.dao.db.DbAccessReadBase.execute(DbAccessReadBase.java:55) ~[commons-app-1.0.0.jar:na]
    at sun.reflect.GeneratedMethodAccessor1797.invoke(Unknown Source) ~[na:na]
    at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43) ~[na:1.7.0_40]
    at java.lang.reflect.Method.invoke(Method.java:606) ~[na:1.7.0_40]
    at org.springframework.aop.support.AopUtils.invokeJoinpointUsingReflection(AopUtils.java:309) ~[spring-aop-3.0.7.RELEASE.jar:3.0.7.RELEASE]
    at org.springframework.aop.framework.ReflectiveMethodInvocation.invokeJoinpoint(ReflectiveMethodInvocation.java:183) ~[spring-aop-3.0.7.RELEASE.jar:3.0.7.RELEASE]
    at org.springframework.aop.framework.ReflectiveMethodInvocation.proceed(ReflectiveMethodInvocation.java:150) ~[spring-aop-3.0.7.RELEASE.jar:3.0.7.RELEASE]
    at org.springframework.transaction.interceptor.TransactionInterceptor.invoke(TransactionInterceptor.java:110) ~[spring-tx-3.1.2.RELEASE.jar:3.1.2.RELEASE]
    at org.springframework.aop.framework.ReflectiveMethodInvocation.proceed(ReflectiveMethodInvocation.java:172) ~[spring-aop-3.0.7.RELEASE.jar:3.0.7.RELEASE]
    at org.springframework.aop.framework.JdkDynamicAopProxy.invoke(JdkDynamicAopProxy.java:202) ~[spring-aop-3.0.7.RELEASE.jar:3.0.7.RELEASE]
    at com.sun.proxy.$Proxy505.execute(Unknown Source) ~[na:na]
    at cz.cuni.mff.xrg.odcs.frontend.doa.container.CachedSource.loadById(CachedSource.java:177) ~[CachedSource.class:na]
    at cz.cuni.mff.xrg.odcs.frontend.doa.container.CachedSource.getObject(CachedSource.java:246) ~[CachedSource.class:na]
    at cz.cuni.mff.xrg.odcs.frontend.container.ReadOnlyContainer.getObject(ReadOnlyContainer.java:127) ~[ReadOnlyContainer.class:na]
    at cz.cuni.mff.xrg.odcs.frontend.container.ValueProperty.<init>(ValueProperty.java:22) ~[ValueProperty.class:na]
    at cz.cuni.mff.xrg.odcs.frontend.container.GeneralProperty.bind(GeneralProperty.java:36) ~[GeneralProperty.class:na]
    at cz.cuni.mff.xrg.odcs.frontend.container.ValueItem.getItemProperty(ValueItem.java:22) ~[ValueItem.class:na]
    at cz.cuni.mff.xrg.odcs.frontend.gui.tables.LogTable$1.itemClick(LogTable.java:106) ~[LogTable$1.class:na]
    at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method) ~[na:1.7.0_40]
    at sun.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:57) ~[na:1.7.0_40]
    at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43) ~[na:1.7.0_40]
    at java.lang.reflect.Method.invoke(Method.java:606) ~[na:1.7.0_40]
    at com.vaadin.event.ListenerMethod.receiveEvent(ListenerMethod.java:508) ~[vaadin-server-7.1.8.jar:7.1.8]
    at com.vaadin.event.EventRouter.fireEvent(EventRouter.java:167) ~[vaadin-server-7.1.8.jar:7.1.8]
    at com.vaadin.server.AbstractClientConnector.fireEvent(AbstractClientConnector.java:969) ~[vaadin-server-7.1.8.jar:7.1.8]
    at com.vaadin.ui.CustomTable.handleClickEvent(CustomTable.java:3035) ~[filteringtable-0.9.0.v7.jar:7.1.8]
    at com.vaadin.ui.CustomTable.changeVariables(CustomTable.java:2830) ~[filteringtable-0.9.0.v7.jar:7.1.8]
    at com.vaadin.server.communication.ServerRpcHandler.changeVariables(ServerRpcHandler.java:396) [vaadin-server-7.1.8.jar:7.1.8]
    at com.vaadin.server.communication.ServerRpcHandler.handleBurst(ServerRpcHandler.java:221) [vaadin-server-7.1.8.jar:7.1.8]
    at com.vaadin.server.communication.ServerRpcHandler.handleRpc(ServerRpcHandler.java:111) [vaadin-server-7.1.8.jar:7.1.8]
    at com.vaadin.server.communication.UidlRequestHandler.synchronizedHandleRequest(UidlRequestHandler.java:91) [vaadin-server-7.1.8.jar:7.1.8]
    at com.vaadin.server.SynchronizedRequestHandler.handleRequest(SynchronizedRequestHandler.java:37) [vaadin-server-7.1.8.jar:7.1.8]
    at com.vaadin.server.VaadinService.handleRequest(VaadinService.java:1371) [vaadin-server-7.1.8.jar:7.1.8]
    at com.vaadin.server.VaadinServlet.service(VaadinServlet.java:238) [vaadin-server-7.1.8.jar:7.1.8]
    at cz.cuni.mff.xrg.odcs.frontend.IntlibApplicationServlet.service(IntlibApplicationServlet.java:66) [IntlibApplicationServlet.class:na]
    at javax.servlet.http.HttpServlet.service(HttpServlet.java:728) [servlet-api.jar:na]
    at org.apache.catalina.core.ApplicationFilterChain.internalDoFilter(ApplicationFilterChain.java:305) [catalina.jar:7.0.33]
    at org.apache.catalina.core.ApplicationFilterChain.doFilter(ApplicationFilterChain.java:210) [catalina.jar:7.0.33]
    at org.apache.catalina.core.StandardWrapperValve.invoke(StandardWrapperValve.java:222) [catalina.jar:7.0.33]
    at org.apache.catalina.core.StandardContextValve.invoke(StandardContextValve.java:123) [catalina.jar:7.0.33]
    at org.apache.catalina.authenticator.AuthenticatorBase.invoke(AuthenticatorBase.java:472) [catalina.jar:7.0.33]
    at org.apache.catalina.core.StandardHostValve.invoke(StandardHostValve.java:171) [catalina.jar:7.0.33]
    at org.apache.catalina.valves.ErrorReportValve.invoke(ErrorReportValve.java:99) [catalina.jar:7.0.33]
    at org.apache.catalina.valves.AccessLogValve.invoke(AccessLogValve.java:931) [catalina.jar:7.0.33]
    at org.apache.catalina.core.StandardEngineValve.invoke(StandardEngineValve.java:118) [catalina.jar:7.0.33]
    at org.apache.catalina.connector.CoyoteAdapter.service(CoyoteAdapter.java:407) [catalina.jar:7.0.33]
    at org.apache.coyote.http11.AbstractHttp11Processor.process(AbstractHttp11Processor.java:1004) [tomcat-coyote.jar:7.0.33]
    at org.apache.coyote.AbstractProtocol$AbstractConnectionHandler.process(AbstractProtocol.java:589) [tomcat-coyote.jar:7.0.33]
    at org.apache.tomcat.util.net.JIoEndpoint$SocketProcessor.run(JIoEndpoint.java:312) [tomcat-coyote.jar:7.0.33]
    at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1145) [na:1.7.0_40]
    at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:615) [na:1.7.0_40]
    at java.lang.Thread.run(Thread.java:724) [na:1.7.0_40]
2013-12-03 15:38:33,315 [http-bio-8080-exec-376] DEBUG org.eclipse.persistence.logging.sql - 2013-12-03 15:38:33.315--ServerSession(1770567193)--Connection(37389591)--Thread(Thread[http-bio-8080-exec-376,5,main])--SELECT CASE  WHEN (MAX(t_last_change) > ?) THEN CAST(? AS INTEGER) ELSE CAST(? AS INTEGER) END FROM exec_pipeline
    bind => [2013-12-03 15:37:04.937, 1, 0]
2013-12-03 15:38:33,317 [http-bio-8080-exec-376] DEBUG c.c.m.x.o.f.g.v.e.ExecutionListPresenterImpl - ExecutionMonitor refreshed.
2013-12-03 15:38:33,317 [http-bio-8080-exec-376] DEBUG org.eclipse.persistence.logging.sql - 2013-12-03 15:38:33.317--ServerSession(1770567193)--Connection(1341631013)--Thread(Thread[http-bio-8080-exec-376,5,main])--SELECT ID, t_end, debug_mode, t_last_change, silent_mode, t_start, STATUS, stop, debugnode_id, owner_id, pipeline_id, schedule_id, context_id FROM exec_pipeline WHERE (ID = ?)
    bind => [628]
2013-12-03 15:38:33,319 [http-bio-8080-exec-376] DEBUG org.eclipse.persistence.logging.sql - 2013-12-03 15:38:33.319--ServerSession(1770567193)--Connection(2049334012)--Thread(Thread[http-bio-8080-exec-376,5,main])--SELECT ID, t_end, debug_mode, t_last_change, silent_mode, t_start, STATUS, stop, debugnode_id, owner_id, pipeline_id, schedule_id, context_id FROM exec_pipeline WHERE (ID = ?)
    bind => [628]

**Comment by skodapetr** [comment]
ahh .. smutné je, že je to vlastně jako #867 .. jen ty logy na téhle tabulce nemáme .. přidám je na všechny a snad nám to pomůže ..

**Comment by skodapetr** [comment]
Report in #871
