### ISSUE TITLE
NullPointer exception when clicking on Scheduller

### ISSUE THREAD

**Issue by tomas-knap** [mff-uk/odcs#903]
When clicking on scheduler menu item: 

![screen shot 2013-12-12 at 10 11 04 am](https://f.cloud.github.com/assets/3014917/1731703/e98100e8-630e-11e3-958a-b1d5f04e984f.png)

In the logs; 

2013-12-12 10:18:51,817 [http-bio-8080-exec-7] ERROR cz.cuni.mff.xrg.odcs.frontend.AppEntry - Uncaught exception
java.lang.NullPointerException: null
    at cz.cuni.mff.xrg.odcs.frontend.gui.views.Scheduler.getTableData(Scheduler.java:337) ~[Scheduler.class:na]
    at cz.cuni.mff.xrg.odcs.frontend.gui.views.Scheduler.buildMainLayout(Scheduler.java:183) ~[Scheduler.class:na]
    at cz.cuni.mff.xrg.odcs.frontend.gui.views.Scheduler.enter(Scheduler.java:111) ~[Scheduler.class:na]
    at com.vaadin.navigator.Navigator.navigateTo(Navigator.java:571) ~[vaadin-server-7.1.8.jar:7.1.8]
    at com.vaadin.navigator.Navigator.navigateTo(Navigator.java:526) ~[vaadin-server-7.1.8.jar:7.1.8]
    at cz.cuni.mff.xrg.odcs.frontend.navigation.ClassNavigatorImpl.navigateTo(ClassNavigatorImpl.java:49) ~[ClassNavigatorImpl.class:na]
    at cz.cuni.mff.xrg.odcs.frontend.navigation.ClassNavigatorHolder.navigateTo(ClassNavigatorHolder.java:24) ~[ClassNavigatorHolder.class:na]
    at cz.cuni.mff.xrg.odcs.frontend.gui.MenuLayout$NavigateToCommand.menuSelected(MenuLayout.java:204) ~[MenuLayout$NavigateToCommand.class:na]
    at com.vaadin.ui.MenuBar.changeVariables(MenuBar.java:186) ~[vaadin-server-7.1.8.jar:7.1.8]
    at com.vaadin.server.communication.ServerRpcHandler.changeVariables(ServerRpcHandler.java:396) [vaadin-server-7.1.8.jar:7.1.8]
    at com.vaadin.server.communication.ServerRpcHandler.handleBurst(ServerRpcHandler.java:221) [vaadin-server-7.1.8.jar:7.1.8]
    at com.vaadin.server.communication.ServerRpcHandler.handleRpc(ServerRpcHandler.java:111) [vaadin-server-7.1.8.jar:7.1.8]
    at com.vaadin.server.communication.UidlRequestHandler.synchronizedHandleRequest(UidlRequestHandler.java:91) [vaadin-server-7.1.8.jar:7.1.8]
    at com.vaadin.server.SynchronizedRequestHandler.handleRequest(SynchronizedRequestHandler.java:37) [vaadin-server-7.1.8.jar:7.1.8]
    at com.vaadin.server.VaadinService.handleRequest(VaadinService.java:1371) [vaadin-server-7.1.8.jar:7.1.8]
    at com.vaadin.server.VaadinServlet.service(VaadinServlet.java:238) [vaadin-server-7.1.8.jar:7.1.8]
    at cz.cuni.mff.xrg.odcs.frontend.IntlibApplicationServlet.service(IntlibApplicationServlet.java:67) [IntlibApplicationServlet.class:na]
    at javax.servlet.http.HttpServlet.service(HttpServlet.java:728) [servlet-api.jar:na]
    at org.apache.catalina.core.ApplicationFilterChain.internalDoFilter(ApplicationFilterChain.java:305) [catalina.jar:7.0.33]
    at org.apache.catalina.core.ApplicationFilterChain.doFilter(ApplicationFilterChain.java:210) [catalina.jar:7.0.33]
    at org.apache.catalina.core.StandardWrapperValve.invoke(StandardWrapperValve.java:222) [catalina.jar:7.0.33]
    at org.apache.catalina.core.StandardContextValve.invoke(StandardContextValve.java:123) [catalina.jar:7.0.33]
    at org.apache.catalina.authenticator.AuthenticatorBase.invoke(AuthenticatorBase.java:472) [catalina.jar:7.0.33]
    at org.apache.catalina.core.StandardHostValve.invoke(StandardHostValve.java:171) [catalina.jar:7.0.33]
    at org.apache.catalina.valves.ErrorReportValve.invoke(ErrorReportValve.java:99) [catalina.jar:7.0.33]
    at org.apache.catalina.valves.AccessLogValve.invoke(AccessLogValve.java:931) [catalina.jar:7.0.33]
    at org.apache.catalina.core.StandardEngineValve.invoke(StandardEngineValve.java:118) [catalina.jar:7.0.33]
    at org.apache.catalina.connector.CoyoteAdapter.service(CoyoteAdapter.java:407) [catalina.jar:7.0.33]
    at org.apache.coyote.http11.AbstractHttp11Processor.process(AbstractHttp11Processor.java:1004) [tomcat-coyote.jar:7.0.33]
    at org.apache.coyote.AbstractProtocol$AbstractConnectionHandler.process(AbstractProtocol.java:589) [tomcat-coyote.jar:7.0.33]
    at org.apache.tomcat.util.net.JIoEndpoint$SocketProcessor.run(JIoEndpoint.java:312) [tomcat-coyote.jar:7.0.33]
    at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1145) [na:1.7.0_40]
    at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:615) [na:1.7.0_40]
    at java.lang.Thread.run(Thread.java:724) [na:1.7.0_40]
2013-12-12 10:19:36,680 [http-bio-8080-exec-5] TRACE c.c.m.xrg.odcs.frontend.doa.container.CachedSource - loadSize()
2013-12-12 10:19:36,

**Comment by skodapetr** [comment]
I believe that the source of the problem was on the lines: 

```
String description = item.getDescription();
description = description.length()  ...
```

where item is Schedule, if the description is null (and there are null values in odcs's database) then this throw NPE. So I have added the null check into the code.
