### ISSUE TITLE
Debug exception

### ISSUE THREAD

**Issue by kukharm** [mff-uk/odcs#925]
I pressed the Debug button and get exeption 
![debug](https://f.cloud.github.com/assets/3471169/1744724/75a57c34-6422-11e3-8eca-300b1d026869.jpg)

pipeline disappeared from pipeline list.

Also when i Run pipeline no information about execution appears on Execution monitor and pipeline list.

**Comment by skodapetr** [comment]
Do you hace stack trace?

**Comment by kukharm** [comment]
java.lang.NullPointerException: null
    at cz.cuni.mff.xrg.odcs.frontend.gui.views.executionlist.ExecutionListViewImpl.buildDebugView(ExecutionListViewImpl.java:344) ~[ExecutionListViewImpl.class:na]
    at cz.cuni.mff.xrg.odcs.frontend.gui.views.executionlist.ExecutionListViewImpl.buildExecutionDetail(ExecutionListViewImpl.java:297) ~[ExecutionListViewImpl.class:na]
    at cz.cuni.mff.xrg.odcs.frontend.gui.views.executionlist.ExecutionListViewImpl.showExecutionDetail(ExecutionListViewImpl.java:95) ~[ExecutionListViewImpl.class:na]
    at cz.cuni.mff.xrg.odcs.frontend.gui.views.executionlist.ExecutionListPresenterImpl.showDebugEventHandler(ExecutionListPresenterImpl.java:148) ~[ExecutionListPresenterImpl.class:na]
    at cz.cuni.mff.xrg.odcs.frontend.gui.views.executionlist.ExecutionListPresenterImpl.setParameters(ExecutionListPresenterImpl.java:92) ~[ExecutionListPresenterImpl.class:na]
    at cz.cuni.mff.xrg.odcs.frontend.navigation.PresenterWrap.enter(PresenterWrap.java:27) ~[PresenterWrap.class:na]
    at com.vaadin.navigator.Navigator.navigateTo(Navigator.java:571) ~[vaadin-server-7.1.8.jar:7.1.8]
    at com.vaadin.navigator.Navigator.navigateTo(Navigator.java:526) ~[vaadin-server-7.1.8.jar:7.1.8]
    at cz.cuni.mff.xrg.odcs.frontend.navigation.ClassNavigatorImpl.navigateTo(ClassNavigatorImpl.java:60) ~[ClassNavigatorImpl.class:na]
    at cz.cuni.mff.xrg.odcs.frontend.navigation.ClassNavigatorHolder.navigateTo(ClassNavigatorHolder.java:29) ~[ClassNavigatorHolder.class:na]
    at cz.cuni.mff.xrg.odcs.frontend.gui.views.pipelinelist.PipelineListPresenterImpl.runEventHandler(PipelineListPresenterImpl.java:189) ~[PipelineListPresenterImpl.class:na]
    at cz.cuni.mff.xrg.odcs.frontend.gui.views.pipelinelist.PipelineListViewImpl$10.action(PipelineListViewImpl.java:174) ~[PipelineListViewImpl$10.class:na]
    at cz.cuni.mff.xrg.odcs.frontend.gui.tables.ActionColumnGenerator$Action.buttonClick(ActionColumnGenerator.java:32) ~[ActionColumnGenerator$Action.class:na]
    at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method) ~[na:1.7.0_04]
    at sun.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:57) ~[na:1.7.0_04]
    at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43) ~[na:1.7.0_04]
    at java.lang.reflect.Method.invoke(Method.java:601) ~[na:1.7.0_04]
    at com.vaadin.event.ListenerMethod.receiveEvent(ListenerMethod.java:508) ~[vaadin-server-7.1.8.jar:7.1.8]
    at com.vaadin.event.EventRouter.fireEvent(EventRouter.java:167) ~[vaadin-server-7.1.8.jar:7.1.8]
    at com.vaadin.server.AbstractClientConnector.fireEvent(AbstractClientConnector.java:969) ~[vaadin-server-7.1.8.jar:7.1.8]
    at com.vaadin.ui.Button.fireClick(Button.java:368) ~[vaadin-server-7.1.8.jar:7.1.8]
    at com.vaadin.ui.Button$1.click(Button.java:57) ~[vaadin-server-7.1.8.jar:7.1.8]
    at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method) ~[na:1.7.0_04]
    at sun.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:57) ~[na:1.7.0_04]
    at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43) ~[na:1.7.0_04]
    at java.lang.reflect.Method.invoke(Method.java:601) ~[na:1.7.0_04]
    at com.vaadin.server.ServerRpcManager.applyInvocation(ServerRpcManager.java:168) ~[vaadin-server-7.1.8.jar:7.1.8]
    at com.vaadin.server.ServerRpcManager.applyInvocation(ServerRpcManager.java:118) ~[vaadin-server-7.1.8.jar:7.1.8]
    at com.vaadin.server.communication.ServerRpcHandler.handleBurst(ServerRpcHandler.java:207) [vaadin-server-7.1.8.jar:7.1.8]
    at com.vaadin.server.communication.ServerRpcHandler.handleRpc(ServerRpcHandler.java:111) [vaadin-server-7.1.8.jar:7.1.8]
    at com.vaadin.server.communication.UidlRequestHandler.synchronizedHandleRequest(UidlRequestHandler.java:91) [vaadin-server-7.1.8.jar:7.1.8]
    at com.vaadin.server.SynchronizedRequestHandler.handleRequest(SynchronizedRequestHandler.java:37) [vaadin-server-7.1.8.jar:7.1.8]
    at com.vaadin.server.VaadinService.handleRequest(VaadinService.java:1371) [vaadin-server-7.1.8.jar:7.1.8]
    at com.vaadin.server.VaadinServlet.service(VaadinServlet.java:238) [vaadin-server-7.1.8.jar:7.1.8]
    at cz.cuni.mff.xrg.odcs.frontend.IntlibApplicationServlet.service(IntlibApplicationServlet.java:67) [IntlibApplicationServlet.class:na]
    at javax.servlet.http.HttpServlet.service(HttpServlet.java:728) [servlet-api.jar:na]
    at org.apache.catalina.core.ApplicationFilterChain.internalDoFilter(ApplicationFilterChain.java:305) [catalina.jar:7.0.34]
    at org.apache.catalina.core.ApplicationFilterChain.doFilter(ApplicationFilterChain.java:210) [catalina.jar:7.0.34]
    at org.apache.catalina.core.StandardWrapperValve.invoke(StandardWrapperValve.java:222) [catalina.jar:7.0.34]
    at org.apache.catalina.core.StandardContextValve.invoke(StandardContextValve.java:123) [catalina.jar:7.0.34]
    at org.apache.catalina.authenticator.AuthenticatorBase.invoke(AuthenticatorBase.java:472) [catalina.jar:7.0.34]
    at org.apache.catalina.core.StandardHostValve.invoke(StandardHostValve.java:171) [catalina.jar:7.0.34]
    at org.apache.catalina.valves.ErrorReportValve.invoke(ErrorReportValve.java:99) [catalina.jar:7.0.34]
    at org.apache.catalina.valves.AccessLogValve.invoke(AccessLogValve.java:936) [catalina.jar:7.0.34]
    at org.apache.catalina.core.StandardEngineValve.invoke(StandardEngineValve.java:118) [catalina.jar:7.0.34]
    at org.apache.catalina.connector.CoyoteAdapter.service(CoyoteAdapter.java:407) [catalina.jar:7.0.34]
    at org.apache.coyote.http11.AbstractHttp11Processor.process(AbstractHttp11Processor.java:1004) [tomcat-coyote.jar:7.0.34]
    at org.apache.coyote.AbstractProtocol$AbstractConnectionHandler.process(AbstractProtocol.java:589) [tomcat-coyote.jar:7.0.34]
    at org.apache.tomcat.util.net.JIoEndpoint$SocketProcessor.run(JIoEndpoint.java:312) [tomcat-coyote.jar:7.0.34]
    at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1110) [na:1.7.0_04]
    at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:603) [na:1.7.0_04]
    at java.lang.Thread.run(Thread.java:722) [na:1.7.0_04]

**Comment by bogo777** [comment]
Same for me, but it look like execution isn't saved to db. Possibly related to #923.

**Comment by skodapetr** [comment]
Yes this can be .. it looks like our 923 becomes quite popular. On the other hand, we may consider adding some safety check so we do not get NPE, but better something else?

**Comment by tomas-knap** [comment]
Yes, please add proper check.

**Comment by tomas-knap** [comment]
Marie, is there a commit associated with the fix?

**Comment by kukharm** [comment]
I don't know i tested it after Petr's repair on Friday evening and debug was ok

**Comment by tomas-knap** [comment]
ok, reassigning. Bohuslav, please add proper null pointer check, just in case.

**Comment by bogo777** [comment]
Null pointer check added in 36ed9e0e9593538ef27e7c3c1b276e68f1201483.
