### ISSUE TITLE
Problem when creating new pipeline - synchronization

### ISSUE THREAD

**Issue by tomas-knap** [mff-uk/odcs#934]
When I tried to create a new pipeline, I got: 

![screen shot 2013-12-18 at 2 54 50 pm](https://f.cloud.github.com/assets/3014917/1773610/2c696f4e-67ec-11e3-919f-4d47737b2faa.png)

```
2013-12-18 14:56:05,394 [http-bio-8080-exec-228] WARN  org.eclipse.persistence.logging.Slf4jSessionLogger - Unknown category 'null', the default is used.
2013-12-18 14:56:05,394 [http-bio-8080-exec-228] WARN  org.eclipse.persistence.logging.default - 2013-12-18 14:56:05.394--UnitOfWork(941697172)--Thread(Thread[http-bio-8080-exec-228,5,main])--
2013-12-18 14:56:05,396 [http-bio-8080-exec-228] ERROR cz.cuni.mff.xrg.odcs.frontend.AppEntry - Uncaught exception
java.lang.IllegalStateException: During synchronization a new object was found through a relationship that was not marked cascade PERSIST: cz.cuni.mff.xrg.odcs.commons.app.pipeline.Pipeline@7c397bc0.
    at org.eclipse.persistence.internal.sessions.RepeatableWriteUnitOfWork.discoverUnregisteredNewObjects(RepeatableWriteUnitOfWork.java:310) ~[eclipselink-2.5.1.jar:2.5.1.v20130918-f2b9fc5]
    at org.eclipse.persistence.internal.sessions.UnitOfWorkImpl.calculateChanges(UnitOfWorkImpl.java:723) ~[eclipselink-2.5.1.jar:2.5.1.v20130918-f2b9fc5]
    at org.eclipse.persistence.internal.sessions.UnitOfWorkImpl.commitToDatabaseWithChangeSet(UnitOfWorkImpl.java:1516) ~[eclipselink-2.5.1.jar:2.5.1.v20130918-f2b9fc5]
    at org.eclipse.persistence.internal.sessions.RepeatableWriteUnitOfWork.commitRootUnitOfWork(RepeatableWriteUnitOfWork.java:277) ~[eclipselink-2.5.1.jar:2.5.1.v20130918-f2b9fc5]
    at org.eclipse.persistence.internal.sessions.UnitOfWorkImpl.commitAndResume(UnitOfWorkImpl.java:1169) ~[eclipselink-2.5.1.jar:2.5.1.v20130918-f2b9fc5]
    at org.eclipse.persistence.internal.jpa.transaction.EntityTransactionImpl.commit(EntityTransactionImpl.java:132) ~[eclipselink-2.5.1.jar:2.5.1.v20130918-f2b9fc5]
    at org.springframework.orm.jpa.JpaTransactionManager.doCommit(JpaTransactionManager.java:512) ~[spring-orm-3.1.2.RELEASE.jar:3.1.2.RELEASE]
    at org.springframework.transaction.support.AbstractPlatformTransactionManager.processCommit(AbstractPlatformTransactionManager.java:754) ~[spring-tx-3.1.2.RELEASE.jar:3.1.2.RELEASE]
    at org.springframework.transaction.support.AbstractPlatformTransactionManager.commit(AbstractPlatformTransactionManager.java:723) ~[spring-tx-3.1.2.RELEASE.jar:3.1.2.RELEASE]
    at org.springframework.transaction.interceptor.TransactionAspectSupport.commitTransactionAfterReturning(TransactionAspectSupport.java:394) ~[spring-tx-3.1.2.RELEASE.jar:3.1.2.RELEASE]
    at org.springframework.transaction.interceptor.TransactionInterceptor.invoke(TransactionInterceptor.java:120) ~[spring-tx-3.1.2.RELEASE.jar:3.1.2.RELEASE]
    at org.springframework.aop.framework.ReflectiveMethodInvocation.proceed(ReflectiveMethodInvocation.java:172) ~[spring-aop-3.0.7.RELEASE.jar:3.0.7.RELEASE]
    at org.springframework.aop.framework.Cglib2AopProxy$DynamicAdvisedInterceptor.intercept(Cglib2AopProxy.java:621) ~[spring-aop-3.0.7.RELEASE.jar:3.0.7.RELEASE]
    at cz.cuni.mff.xrg.odcs.commons.app.facade.PipelineFacade$$EnhancerByCGLIB$$e2d3c9ad.createOpenEvent(<generated>) ~[cglib-3.0.jar:na]
    at cz.cuni.mff.xrg.odcs.frontend.gui.views.PipelineEdit$1.refresh(PipelineEdit.java:148) ~[PipelineEdit$1.class:na]
    at com.github.wolfie.refresher.Refresher.fireRefreshEvents(Refresher.java:72) ~[refresher-1.2.1.7.jar:1.2.1.7]
    at com.github.wolfie.refresher.Refresher.access$1(Refresher.java:70) ~[refresher-1.2.1.7.jar:1.2.1.7]
    at com.github.wolfie.refresher.Refresher$1.refresh(Refresher.java:35) ~[refresher-1.2.1.7.jar:1.2.1.7]
    at sun.reflect.GeneratedMethodAccessor515.invoke(Unknown Source) ~[na:na]
    at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43) ~[na:1.7.0_40]
    at java.lang.reflect.Method.invoke(Method.java:606) ~[na:1.7.0_40]
    at com.vaadin.server.ServerRpcManager.applyInvocation(ServerRpcManager.java:168) ~[vaadin-server-7.1.8.jar:7.1.8]
    at com.vaadin.server.ServerRpcManager.applyInvocation(ServerRpcManager.java:118) ~[vaadin-server-7.1.8.jar:7.1.8]
    at com.vaadin.server.communication.ServerRpcHandler.handleBurst(ServerRpcHandler.java:207) [vaadin-server-7.1.8.jar:7.1.8]
    at com.vaadin.server.communication.ServerRpcHandler.handleRpc(ServerRpcHandler.java:111) [vaadin-server-7.1.8.jar:7.1.8]
    at com.vaadin.server.communication.UidlRequestHandler.synchronizedHandleRequest(UidlRequestHandler.java:91) [vaadin-server-7.1.8.jar:7.1.8]
    at com.vaadin.server.SynchronizedRequestHandler.handleRequest(SynchronizedRequestHandler.java:37) [vaadin-server-7.1.8.jar:7.1.8]
    at com.vaadin.server.VaadinService.handleRequest(VaadinService.java:1371) [vaadin-server-7.1.8.jar:7.1.8]
    at com.vaadin.server.VaadinServlet.service(VaadinServlet.java:238) [vaadin-server-7.1.8.jar:7.1.8]
    at cz.cuni.mff.xrg.odcs.frontend.IntlibApplicationServlet.service(IntlibApplicationServlet.java:67) [IntlibApplicationServlet.class:na]
    at javax.servlet.http.HttpServlet.service(HttpServlet.java:728) [servlet-api.jar:na]
    at org.apache.catalina.core.ApplicationFilterChain.internalDoFilter(ApplicationFilterChain.java:305) [catalina.jar:7.0.33]
    at org.apache.catalina.core.ApplicationFilterChain.doFilter(ApplicationFilterChain.java:210) [catalina.jar:7.0.33]
    at org.apache.catalina.core.StandardWrapperValve.invoke(StandardWrapperValve.java:222) [catalina.jar:7.0.33]
    at org.apache.catalina.core.StandardContextValve.invoke(StandardContextValve.java:123) [catalina.jar:7.0.33]
    at org.apache.catalina.authenticator.AuthenticatorBase.invoke(AuthenticatorBase.java:472) [catalina.jar:7.0.33]
    at org.apache.catalina.core.StandardHostValve.invoke(StandardHostValve.java:171) [catalina.jar:7.0.33]
    at org.apache.catalina.valves.ErrorReportValve.invoke(ErrorReportValve.java:99) [catalina.jar:7.0.33]
    at org.apache.catalina.valves.AccessLogValve.invoke(AccessLogValve.java:931) [catalina.jar:7.0.33]
    at org.apache.catalina.core.StandardEngineValve.invoke(StandardEngineValve.java:118) [catalina.jar:7.0.33]
    at org.apache.catalina.connector.CoyoteAdapter.service(CoyoteAdapter.java:407) [catalina.jar:7.0.33]
    at org.apache.coyote.http11.AbstractHttp11Processor.process(AbstractHttp11Processor.java:1004) [tomcat-coyote.jar:7.0.33]
    at org.apache.coyote.AbstractProtocol$AbstractConnectionHandler.process(AbstractProtocol.java:589) [tomcat-coyote.jar:7.0.33]
    at org.apache.tomcat.util.net.JIoEndpoint$SocketProcessor.run(JIoEndpoint.java:312) [tomcat-coyote.jar:7.0.33]
    at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1145) [na:1.7.0_40]
    at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:615) [na:1.7.0_40]
    at java.lang.Thread.run(Thread.java:724) [na:1.7.0_40]
knap@xrg14:/data/odcs/log$ 
```

**Comment by tomas-knap** [comment]
@skodape if you have any explanation, please help

**Comment by skodapetr** [comment]
Well imho .. the application try to save into table with the "pipepeline_editing_users" which reference the "pipeline" table. But in this time .. the pipeline is not yet presented in "pipeline" table. So it throws and exception .. but just guessing.
