### ISSUE TITLE
Backend cannot run pipeline when using Virtuoso 7

### ISSUE THREAD

**Issue by janvojt** [mff-uk/odcs#952]
Backend actually only retires to connect over and over again, but after disabling the `DatabaseReconnectAspect` I unveiled the following cause:

```
Exception in thread "dpu: SPARQL Extractor" org.springframework.transaction.TransactionSystemException: Could not commit JPA transaction; nested exception is javax.persistence.RollbackException: Exception [EclipseLink-4002] (Eclipse Persistence Services - 2.5.1.v20130918-f2b9fc5): org.eclipse.persistence.exceptions.DatabaseException
Internal Exception: virtuoso.jdbc4.VirtuosoException: SR175: Uniqueness violation : Violating unique index ix_EXEC_PIPELINE_t_start on table DB.ODCS.EXEC_PIPELINE. Transaction killed.
Error Code: -8
Call: UPDATE exec_pipeline SET t_last_change = ?, t_start = ? WHERE (ID = ?)
    bind => [2013-12-19 17:38:54.0, 2013-12-19 17:39:14.64, 435]
Query: UpdateObjectQuery(cz.cuni.mff.xrg.odcs.commons.app.pipeline.PipelineExecution@1f8)
    at org.springframework.orm.jpa.JpaTransactionManager.doCommit(JpaTransactionManager.java:521)
    at org.springframework.transaction.support.AbstractPlatformTransactionManager.processCommit(AbstractPlatformTransactionManager.java:754)
    at org.springframework.transaction.support.AbstractPlatformTransactionManager.commit(AbstractPlatformTransactionManager.java:723)
    at org.springframework.transaction.interceptor.TransactionAspectSupport.commitTransactionAfterReturning(TransactionAspectSupport.java:394)
    at org.springframework.transaction.interceptor.TransactionInterceptor.invoke(TransactionInterceptor.java:120)
    at org.springframework.aop.framework.ReflectiveMethodInvocation.proceed(ReflectiveMethodInvocation.java:172)
    at org.springframework.aop.framework.Cglib2AopProxy$DynamicAdvisedInterceptor.intercept(Cglib2AopProxy.java:622)
    at cz.cuni.mff.xrg.odcs.commons.app.facade.PipelineFacade$$EnhancerByCGLIB$$3e3a9cb0.save(<generated>)
    at cz.cuni.mff.xrg.odcs.backend.execution.dpu.Executor.execute(Executor.java:344)
    at cz.cuni.mff.xrg.odcs.backend.execution.dpu.Executor.run(Executor.java:433)
    at java.lang.Thread.run(Thread.java:744)
```

**Comment by janvojt** [comment]
This is really weird, because even conductor says index `ix_EXEC_PIPELINE_t_start` is **not** unique.

![screenshot from 2013-12-19 17 56 23](https://f.cloud.github.com/assets/2247062/1784172/a7367b12-68ce-11e3-81fe-dace4d037f22.png)

**Comment by janvojt** [comment]
Dropping the index resolves the issue.

**Comment by tomas-knap** [comment]
Ok, so this is solved? Or dropping the index is a solution, but we are looking for better one?

**Comment by janvojt** [comment]
Well, dropping the index slows down performance. There are many other indices, I would wait if it happens with other index, or try to isolate the problem. It is weird, there is nothing specific about this index. Also, maybe it is a problem with migrating virtuoso database from version 6 to 7 (I used the same files for db).

I did not commit index deletion, because we may forget about it, and have performance problems in future if there are many executions in DB. I would just wait and solve this when other issues are done. This is not a showstopper.

**Comment by janvojt** [comment]
I removed the index to fix this. I checked, and we are not using it in any query. However, the execution start column is sortable in execution list, so sorting by it may be slow if there are many executions. This is most likely a bug in Virtuoso 7 or in the new JDBC.

**Comment by tomas-knap** [comment]
ok, but please create confluence page with Virtuoso 6/7 workarounds and write it there to know

**Comment by janvojt** [comment]
OK, I did: https://grips.semantic-web.at/display/LOD2/Virtuoso+workarounds.

**Comment by tomas-knap** [comment]
Diky!
