### ISSUE TITLE
Check [Ontology] FRBR copy pipeline on ODCS

### ISSUE THREAD

**Issue by tomas-knap** [mff-uk/odcs#963]
Why the data cannot be extracted from the given file?

**Comment by tomas-knap** [comment]
Execution failed because: Content is not allowed in prolog. [line 1, column 1]cz.cuni.mff.xrg.odcs.commons.dpu.DPUException: Content is not allowed in prolog. [line 1, column 1]
    at cz.cuni.mff.xrg.odcs.extractor.file.FileExtractor.execute(FileExtractor.java:83)
    at cz.cuni.mff.xrg.odcs.backend.execution.dpu.Executor.executeInstance(Executor.java:213)
    at cz.cuni.mff.xrg.odcs.backend.execution.dpu.Executor.execute(Executor.java:328)
    at cz.cuni.mff.xrg.odcs.backend.execution.dpu.Executor.run(Executor.java:407)
    at java.lang.Thread.run(Thread.java:724)
Caused by: cz.cuni.mff.xrg.odcs.rdf.exceptions.RDFException: Content is not allowed in prolog. [line 1, column 1]
    at cz.cuni.mff.xrg.odcs.rdf.repositories.BaseRDFRepo.parseFileUsingHandler(BaseRDFRepo.java:1896)
    at cz.cuni.mff.xrg.odcs.rdf.repositories.BaseRDFRepo.parseFileUsingStatisticalHandler(BaseRDFRepo.java:1866)
    at cz.cuni.mff.xrg.odcs.rdf.repositories.BaseRDFRepo.extractDataFileFromHTTPSource(BaseRDFRepo.java:1729)
    at cz.cuni.mff.xrg.odcs.rdf.repositories.BaseRDFRepo.extractFromFile(BaseRDFRepo.java:275)
    at cz.cuni.mff.xrg.odcs.extractor.file.FileExtractor.execute(FileExtractor.java:68)
    ... 4 more
Caused by: org.openrdf.rio.RDFParseException: Content is not allowed in prolog. [line 1, column 1]
    at org.openrdf.rio.helpers.RDFParserHelper.reportFatalError(RDFParserHelper.java:441)
    at org.openrdf.rio.helpers.RDFParserBase.reportFatalError(RDFParserBase.java:657)
    at org.openrdf.rio.rdfxml.RDFXMLParser.reportFatalError(RDFXMLParser.java:1277)
    at org.openrdf.rio.rdfxml.RDFXMLParser.fatalError(RDFXMLParser.java:1434)
    at com.sun.org.apache.xerces.internal.util.ErrorHandlerWrapper.fatalError(ErrorHandlerWrapper.java:180)
    at com.sun.org.apache.xerces.internal.impl.XMLErrorReporter.reportError(XMLErrorReporter.java:441)
    at com.sun.org.apache.xerces.internal.impl.XMLErrorReporter.reportError(XMLErrorReporter.java:368)
    at com.sun.org.apache.xerces.internal.impl.XMLScanner.reportFatalError(XMLScanner.java:1388)
    at com.sun.org.apache.xerces.internal.impl.XMLDocumentScannerImpl$PrologDriver.next(XMLDocumentScannerImpl.java:999)
    at com.sun.org.apache.xerces.internal.impl.XMLDocumentScannerImpl.next(XMLDocumentScannerImpl.java:606)
    at com.sun.org.apache.xerces.internal.impl.XMLNSDocumentScannerImpl.next(XMLNSDocumentScannerImpl.java:116)
    at com.sun.org.apache.xerces.internal.impl.XMLDocumentFragmentScannerImpl.scanDocument(XMLDocumentFragmentScannerImpl.java:511)
    at com.sun.org.apache.xerces.internal.parsers.XML11Configuration.parse(XML11Configuration.java:846)
    at com.sun.org.apache.xerces.internal.parsers.XML11Configuration.parse(XML11Configuration.java:775)
    at com.sun.org.apache.xerces.internal.parsers.XMLParser.parse(XMLParser.java:123)
    at com.sun.org.apache.xerces.internal.parsers.AbstractSAXParser.parse(AbstractSAXParser.java:1210)
    at com.sun.org.apache.xerces.internal.jaxp.SAXParserImpl$JAXPSAXParser.parse(SAXParserImpl.java:628)
    at org.openrdf.rio.rdfxml.RDFXMLParser.parse(RDFXMLParser.java:353)
    at org.openrdf.rio.rdfxml.RDFXMLParser.parse(RDFXMLParser.java:269)
    at cz.cuni.mff.xrg.odcs.rdf.repositories.BaseRDFRepo.parseFileUsingHandler(BaseRDFRepo.java:1894)
    ... 8 more

**Comment by tomas-knap** [comment]
Please check where the problem is. Supplement log, so that it contains more detail information where the problem is (if possible)

**Comment by tomas-knap** [comment]
Based on the validator, it is a valid turtle

**Comment by tomesj** [comment]
Problem fixed - it is fine now :-)

**Comment by bkaempgen** [comment]
Could you shortly mention what the problem was? ;-)

Thanks.

**Comment by tomas-knap** [comment]
Every closed issues should be accompanied with the commit.  @tomesj Please add at least the  explanation.

**Comment by bkaempgen** [comment]
I just solved at least my problem. Prolog error seemed to be because of encoding: 

```
            // Would not work: prolog error
            //ByteArrayInputStream inputstream = new ByteArrayInputStream(w.toString().getBytes());

            // UTF-8 encoding seems important
            InputStream stream = new ByteArrayInputStream(triples.getBytes("UTF-8"));

                            con.add(stream, "", RDFFormat.RDFXML);
```
