### ISSUE TITLE
RDF data validator cannot connect to db - using local RDF store

### ISSUE THREAD

**Issue by tomas-knap** [mff-uk/odcs#978]
When running pipeline ARES test on ODCS (http://odcs.xrg.cz:8080/odcleanstore/), localRDF store, I got: 

2013-12-25 13:27:29,222 [dpu: RDF Data Validator] WARN  exec:23228 dpu:504 c.c.m.x.o.backend.facade.DatabaseReconnectAspect - Database is down after 26802 attempts.
2013-12-25 13:27:33,006 [dpu: RDF Data Validator] WARN  exec:23228 dpu:504 c.c.m.x.o.backend.facade.DatabaseReconnectAspect - Database is down after 26803 attempts.
2013-12-25 13:27:36,242 [dpu: RDF Data Validator] WARN  exec:23228 dpu:504 c.c.m.x.o.backend.facade.DatabaseReconnectAspect - Database is down after 26804 attempts.
2013-12-25 13:27:39,415 [dpu: RDF Data Validator] WARN  exec:23228 dpu:504 c.c.m.x.o.backend.facade.DatabaseReconnectAspect - Database is down after 26805 attempts.
2013-12-25 13:27:43,765 [dpu: RDF Data Validator] WARN  exec:23228 dpu:504 c.c.m.x.o.backend.facade.DatabaseReconnectAspect - Database is down after 26806 attempts.
2013-12-25 13:27:47,990 [dpu: RDF Data Validator] WARN  exec:23228 dpu:504 c.c.m.x.o.backend.facade.DatabaseReconnectAspect - Database is down after 26807 attempts.

So the RDF data validatior has problem reconnecting to db. But that is strange, @tomesj  please explain. RDF data validator was using localRDF store, so how it could happen that it cannot connect?

**Comment by tomas-knap** [comment]
See pipeline exec 23228 there

**Comment by tomesj** [comment]
Když jsem si najel zmíněnou pipelinu a nahlédl do posledního logu, zjistil jsem, že validace celá doběhla v pořádku s výsledkem
TOTAL VALIDATED:7451361 triples (viz screen) 

Proč pipeline nepokračuje dále a konec události validace se neukazuje,to netuším. Možná se mezitím vykonává něco jiného. 

![image](https://f.cloud.github.com/assets/3481055/1808877/0e7d2868-6d87-11e3-9b6b-1246efa62c4b.png)

Jinak když jsem Tvůj log bude z jiné pipeliny, protože když jsem dal třídění na úrovni warning, nic se mi neukázalo a poslední log v této pipeline je z Dec 24, 2013 9:09:31 AM

**Comment by skodapetr** [comment]
And is the used virtuoso alive? Based on the log the class DatabaseReconnectAspect take care about SQL problems, unfortunately .. it somehow can hide problems with database other than connections problems.

**Comment by tomas-knap** [comment]
Koukam ted jeste do logu a objevuje se tam:

2013-12-26 11:20:52,507 [dpu: RDF Data Validator] WARN  exec:23228 dpu:504 org.eclipse.persistence.logging.Slf4jSessionLogger - Unknown category 'null', the default is used.
2013-12-26 11:20:52,507 [dpu: RDF Data Validator] WARN  exec:23228 dpu:504 org.eclipse.persistence.logging.Slf4jSessionLogger - Unknown category 'null', the default is used.
2013-12-26 11:20:52,507 [dpu: RDF Data Validator] WARN  exec:23228 dpu:504 org.eclipse.persistence.logging.Slf4jSessionLogger - Unknown category 'null', the default is used.
2013-12-26 11:20:52,507 [dpu: RDF Data Validator] WARN  exec:23228 dpu:504 org.eclipse.persistence.logging.Slf4jSessionLogger - Unknown category 'null', the default is used.
2013-12-26 11:20:52,507 [dpu: RDF Data Validator] WARN  exec:23228 dpu:504 org.eclipse.persistence.logging.default - 2013-12-26 11:20:52.507--ClientSession(1588114335)--Thread(Thread[dpu: RDF Data Validator,5,main])--
2013-12-26 11:20:53,016 [taskExecutor-8] DEBUG exec: dpu: c.c.mff.xrg.odcs.backend.logback.SqlAppenderImpl - flush() : get connection
2013-12-26 11:20:53,017 [taskExecutor-8] DEBUG exec: dpu: c.c.mff.xrg.odcs.backend.logback.SqlAppenderImpl - flush() : flushIntoDatabase
2013-12-26 11:20:54,155 [taskScheduler-3] TRACE exec: dpu: cz.cuni.mff.xrg.odcs.backend.execution.Engine - Checking for new executions.
2013-12-26 11:20:54,391 [dpu: RDF Data Validator] WARN  exec:23228 dpu:504 c.c.m.x.o.backend.facade.DatabaseReconnectAspect - Database is down after 46540 attempts.
2013-12-26 11:20:54,392 [taskExecutor-8] ERROR exec: dpu: c.c.mff.xrg.odcs.backend.logback.SqlAppenderImpl - Can't save logs into database.
java.sql.BatchUpdateException: Problem during serialization : Broken pipe
    at virtuoso.jdbc4.VirtuosoPreparedStatement.throwBatchUpdateException(Unknown Source) ~[jdbc-driver-4.jar:na]
    at virtuoso.jdbc4.VirtuosoPreparedStatement.executeBatchUpdate(Unknown Source) ~[jdbc-driver-4.jar:na]
    at virtuoso.jdbc4.VirtuosoPreparedStatement.executeBatch(Unknown Source) ~[jdbc-driver-4.jar:na]
    at org.apache.commons.dbcp.DelegatingStatement.executeBatch(DelegatingStatement.java:297) ~[commons-dbcp-1.4.jar:1.4]
    at org.apache.commons.dbcp.DelegatingStatement.executeBatch(DelegatingStatement.java:297) ~[commons-dbcp-1.4.jar:1.4]
    at cz.cuni.mff.xrg.odcs.backend.logback.SqlAppenderImpl.flushIntoDatabase(SqlAppenderImpl.java:116) [backend-1.0.0.jar:na]
    at cz.cuni.mff.xrg.odcs.backend.logback.SqlAppenderImpl.flush(SqlAppenderImpl.java:174) [backend-1.0.0.jar:na]
    at sun.reflect.GeneratedMethodAccessor45.invoke(Unknown Source) ~[na:na]
    at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43) ~[na:1.7.0_40]
    at java.lang.reflect.Method.invoke(Method.java:606) ~[na:1.7.0_40]
    at org.springframework.aop.support.AopUtils.invokeJoinpointUsingReflection(AopUtils.java:319) [spring-aop-3.1.2.RELEASE.jar:3.1.2.RELEASE]
    at org.springframework.aop.framework.ReflectiveMethodInvocation.invokeJoinpoint(ReflectiveMethodInvocation.java:183) [spring-aop-3.1.2.RELEASE.jar:3.1.2.RELEASE]
    at org.springframework.aop.framework.ReflectiveMethodInvocation.proceed(ReflectiveMethodInvocation.java:150) [spring-aop-3.1.2.RELEASE.jar:3.1.2.RELEASE]
    at org.springframework.aop.interceptor.AsyncExecutionInterceptor$1.call(AsyncExecutionInterceptor.java:83) [spring-aop-3.1.2.RELEASE.jar:3.1.2.RELEASE]
    at java.util.concurrent.FutureTask.run(FutureTask.java:262) [na:1.7.0_40]
    at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1145) [na:1.7.0_40]
    at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:615) [na:1.7.0_40]
    at java.lang.Thread.run(Thread.java:724) [na:1.7.0_40]

@skodape  Please check how resistant is log sql appender if connection is down and again up

**Comment by ghost** [comment]
wontfix
