### ISSUE TITLE
Problem when creating pipeline on ODCS

### ISSUE THREAD

**Issue by tomesj** [mff-uk/odcs#988]
I tried create new pipeline on http://odcs.xrg.cz:8080/odcleanstore 
and I got this:

![image](https://f.cloud.github.com/assets/3481055/1816029/9f7743b0-6f2d-11e3-8c4b-61ee6864e632.png)

**Comment by skodapetr** [comment]
I can try to look on this but more info (like stack trace) would be nice ... from the exception not much can be seen imho. Also the name is missing, you tried to save empty pipeline? or .. how does this happen?

**Comment by tomesj** [comment]
I click on button "create new pipeline", nothing else and I got this. 

Try it on http://odcs.xrg.cz:8080/odcleanstore. You probably get the same result.

**Comment by tomas-knap** [comment]
```
013-12-28 11:37:56,990 [http-bio-8080-exec-381] ERROR cz.cuni.mff.xrg.odcs.frontend.AppEntry - Uncaught exception
java.lang.IllegalStateException: During synchronization a new object was found through a relationship that was not marked cascade PERSIST: cz.cuni.mff.xrg.odcs.commons.app.pipeline.Pipeline@5cc09121.
    at org.eclipse.persistence.internal.sessions.RepeatableWriteUnitOfWork.discoverUnregisteredNewObjects(RepeatableWriteUnitOfWork.java:310) ~[eclipselink-2.5.1.jar:2.5.1.v20130918-f2b9fc5]
    at org.eclipse.persistence.internal.sessions.UnitOfWorkImpl.calculateChanges(UnitOfWorkImpl.java:723) ~[eclipselink-2.5.1.jar:2.5.1.v20130918-f2b9fc5]
    at org.eclipse.persistence.internal.sessions.UnitOfWorkImpl.commitToDatabaseWithChangeSet(UnitOfWorkImpl.java:1516) ~[eclipselink-2.5.1.jar:2.5.1.v20130918-f2b9fc5]
    at org.eclipse.persistence.internal.sessions.RepeatableWriteUnitOfWork.commitRootUnitOfWork(RepeatableWriteUnitOfWork.java:277) ~[eclipselink-2.5.1.jar:2.5.1.v20130918-f2b9fc5]
    at org.eclipse.persistence.internal.sessions.UnitOfWorkImpl.commitAndResume(UnitOfWorkImpl.java:1169) ~[eclipselink-2.5.1.jar:2.5.1.v20130918-f2b9fc5]
    at org.eclipse.persistence.internal.jpa.transaction.EntityTransactionImpl.commit(EntityTransactionImpl.java:132) ~[eclipselink-2.5.1.jar:2.5.1.v20130918-f2b9fc5]
    at org.springframework.orm.jpa.JpaTransactionManager.doCommit(JpaTransactionManager.java:512) ~[spring-orm-3.1.2.RELEASE.jar:3.1.2.RELEASE]
    at org.springframework.transaction.support.AbstractPlatformTransactionManager.processCommit(AbstractPlatformTransactionManager.java:754) ~[spring-tx-3.1.2.RELEASE.jar:3.1.2.RELEASE]
    at org.springframework.transaction.support.AbstractPlatformTransactionManager.commit(AbstractPlatformTransactionManager.java:723) ~[spring-tx-3.1.2.RELEASE.jar:3.1.2.RELEASE]
    at org.springframework.transaction.interceptor.TransactionAspectSupport.commitTransactionAfterReturning(TransactionAspectSupport.java:394) ~[spring-tx-3.1.2.RELEASE.jar:3.1.2.RELEASE]
    at org.springframework.transaction.interceptor.TransactionInterceptor.invoke(TransactionInterceptor.java:120) ~[spring-tx-3.1.2.RELEASE.jar:3.1.2.RELEASE]
    at org.springframework.aop.framework.ReflectiveMethodInvocation.proceed(ReflectiveMethodInvocation.java:172) ~[spring-aop-3.0.7.RELEASE.jar:3.0.7.RELEASE]
    at org.springframework.aop.framework.Cglib2AopProxy$DynamicAdvisedInterceptor.intercept(Cglib2AopProxy.java:621) ~[spring-aop-3.0.7.RELEASE.jar:3.0.7.RELEASE]
    at cz.cuni.mff.xrg.odcs.commons.app.facade.PipelineFacade$$EnhancerByCGLIB$$df3a691b.createOpenEvent(<generated>) ~[cglib-3.0.jar:na]
    at cz.cuni.mff.xrg.odcs.frontend.gui.views.PipelineEdit$1.refresh(PipelineEdit.java:148) ~[PipelineEdit$1.class:na]
    at com.github.wolfie.refresher.Refresher.fireRefreshEvents(Refresher.java:72) ~[refresher-1.2.1.7.jar:1.2.1.7]
    at com.github.wolfie.refresher.Refresher.access$1(Refresher.java:70) ~[refresher-1.2.1.7.jar:1.2.1.7]
    at com.github.wolfie.refresher.Refresher$1.refresh(Refresher.java:35) ~[refresher-1.2.1.7.jar:1.2.1.7]
    at sun.reflect.GeneratedMethodAccessor940.invoke(Unknown Source) ~[na:na]
    at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43) ~[na:1.7.0_40]
    at java.lang.reflect.Method.invoke(Method.java:606) ~[na:1.7.0_40]
    at com.vaadin.server.ServerRpcManager.applyInvocation(ServerRpcManager.java:168) ~[vaadin-server-7.1.8.jar:7.1.8]
    at com.vaadin.server.ServerRpcManager.applyInvocation(ServerRpcManager.java:118) ~[vaadin-server-7.1.8.jar:7.1.8]
    at com.vaadin.server.communication.ServerRpcHandler.handleBurst(ServerRpcHandler.java:207) [vaadin-server-7.1.8.jar:7.1.8]
    at com.vaadin.server.communication.ServerRpcHandler.handleRpc(ServerRpcHandler.java:111) [vaadin-server-7.1.8.jar:7.1.8]
    at com.vaadin.server.communication.UidlRequestHandler.synchronizedHandleRequest(UidlRequestHandler.java:91) [vaadin-server-7.1.8.jar:7.1.8]
    at com.vaadin.server.SynchronizedRequestHandler.handleRequest(SynchronizedRequestHandler.java:37) [vaadin-server-7.1.8.jar:7.1.8]
    at com.vaadin.server.VaadinService.handleRequest(VaadinService.java:1371) [vaadin-server-7.1.8.jar:7.1.8]
    at com.vaadin.server.VaadinServlet.service(VaadinServlet.java:238) [vaadin-server-7.1.8.jar:7.1.8]
    at cz.cuni.mff.xrg.odcs.frontend.IntlibApplicationServlet.service(IntlibApplicationServlet.java:67) [IntlibApplicationServlet.class:na]
    at javax.servlet.http.HttpServlet.service(HttpServlet.java:728) [servlet-api.jar:na]
    at org.apache.catalina.core.ApplicationFilterChain.internalDoFilter(ApplicationFilterChain.java:305) [catalina.jar:7.0.33]
    at org.apache.catalina.core.ApplicationFilterChain.doFilter(ApplicationFilterChain.java:210) [catalina.jar:7.0.33]
    at org.apache.catalina.core.StandardWrapperValve.invoke(StandardWrapperValve.java:222) [catalina.jar:7.0.33]
    at org.apache.catalina.core.StandardContextValve.invoke(StandardContextValve.java:123) [catalina.jar:7.0.33]
    at org.apache.catalina.authenticator.AuthenticatorBase.invoke(AuthenticatorBase.java:472) [catalina.jar:7.0.33]
    at org.apache.catalina.core.StandardHostValve.invoke(StandardHostValve.java:171) [catalina.jar:7.0.33]
    at org.apache.catalina.valves.ErrorReportValve.invoke(ErrorReportValve.java:99) [catalina.jar:7.0.33]
    at org.apache.catalina.valves.AccessLogValve.invoke(AccessLogValve.java:931) [catalina.jar:7.0.33]
    at org.apache.catalina.core.StandardEngineValve.invoke(StandardEngineValve.java:118) [catalina.jar:7.0.33]
    at org.apache.catalina.connector.CoyoteAdapter.service(CoyoteAdapter.java:407) [catalina.jar:7.0.33]
    at org.apache.coyote.http11.AbstractHttp11Processor.process(AbstractHttp11Processor.java:1004) [tomcat-coyote.jar:7.0.33]
    at org.apache.coyote.AbstractProtocol$AbstractConnectionHandler.process(AbstractProtocol.java:589) [tomcat-coyote.jar:7.0.33]
    at org.apache.tomcat.util.net.JIoEndpoint$SocketProcessor.run(JIoEndpoint.java:312) [tomcat-coyote.jar:7.0.33]
    at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1145) [na:1.7.0_40]
    at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:615) [na:1.7.0_40]
    at java.lang.Thread.run(Thread.java:724) [na:1.7.0_40]
```

**Comment by tomas-knap** [comment]
@janvojt Please explain

**Comment by skodapetr** [comment]
imho: Do you have the "last" version?  I think that we had met similar problem already .. it tries to save open event for non-saved pipeline.
But this has been solved already by @janvojt I think.

**Comment by tomas-knap** [comment]
No, there is version from 22.12. on ODCS, ODCS-test is more up to date

**Comment by janvojt** [comment]
This was solved in #934 by commit 8ae7beb7e13321bde1828d1d9019a41002c1b8f3. @tomas-knap are you sure this commit is deployed on ODCS? I cannot reproduce this on current version.

**Comment by skodapetr** [comment]
just to give an idea .. what we can try .. (sorry Jan) use in-memory storage for that .. just store pipeline.id and user.name in HashMap<Long, List<String> >.. there for sure will be no persistence problems, thanks to good design it can be implemented easily in PipelineFacade .. and it can be faster then trying to replicate this .. as Jan is right .. this should not happen

(as it appears also on experimental branch I will try to add some logs there ... which I hope may help use to localize the problem and fix it rather then reimplement it]

**Comment by tomas-knap** [comment]
Also cannot reproduce right now
