### ISSUE TITLE
Problems when saving DPU conf as a new DPU template

### ISSUE THREAD

**Issue by tomas-knap** [mff-uk/odcs#991]
To reproduce, use experimental branch: 

I created new pipeline, SPARQL extractor, open DPU conf, adjusted, saved as new template than:

![screen shot 2013-12-30 at 9 18 53 am](https://f.cloud.github.com/assets/3014917/1821326/5562ffda-712b-11e3-999c-86defae696ea.png)

2013-12-30 09:19:01,653 [http-bio-8080-exec-14] ERROR cz.cuni.mff.xrg.odcs.frontend.AppEntry - Uncaught exception
virtuoso.jdbc4.VirtuosoException: SQL Type -9 not defined.
    at virtuoso.jdbc4.VirtuosoNullParameter.fromSQLType(Unknown Source) ~[virtjdbc-4.1.jar:na]
    at virtuoso.jdbc4.VirtuosoNullParameter.<init>(Unknown Source) ~[virtjdbc-4.1.jar:na]
    at virtuoso.jdbc4.VirtuosoPreparedStatement.setNull(Unknown Source) ~[virtjdbc-4.1.jar:na]
    at org.apache.commons.dbcp.DelegatingPreparedStatement.setNull(DelegatingPreparedStatement.java:108) ~[commons-dbcp-1.4.jar:1.4]
    at org.apache.commons.dbcp.DelegatingPreparedStatement.setNull(DelegatingPreparedStatement.java:108) ~[commons-dbcp-1.4.jar:1.4]
    at org.eclipse.persistence.internal.databaseaccess.DatabasePlatform.setNullFromDatabaseField(DatabasePlatform.java:2455) ~[eclipselink-2.5.1.jar:2.5.1.v20130918-f2b9fc5]
    at org.eclipse.persistence.internal.databaseaccess.DatabasePlatform.setParameterValueInDatabaseCall(DatabasePlatform.java:2412) ~[eclipselink-2.5.1.jar:2.5.1.v20130918-f2b9fc5]
    at org.eclipse.persistence.internal.databaseaccess.DatabaseCall.prepareStatement(DatabaseCall.java:797) ~[eclipselink-2.5.1.jar:2.5.1.v20130918-f2b9fc5]
    at org.eclipse.persistence.internal.databaseaccess.DatabaseAccessor.basicExecuteCall(DatabaseAccessor.java:619) ~[eclipselink-2.5.1.jar:2.5.1.v20130918-f2b9fc5]
    at org.eclipse.persistence.internal.databaseaccess.DatabaseAccessor.executeCall(DatabaseAccessor.java:558) ~[eclipselink-2.5.1.jar:2.5.1.v20130918-f2b9fc5]
    at org.eclipse.persistence.internal.sessions.AbstractSession.basicExecuteCall(AbstractSession.java:1991) ~[eclipselink-2.5.1.jar:2.5.1.v20130918-f2b9fc5]
    at org.eclipse.persistence.sessions.server.ClientSession.executeCall(ClientSession.java:298) ~[eclipselink-2.5.1.jar:2.5.1.v20130918-f2b9fc5]
    at org.eclipse.persistence.internal.queries.DatasourceCallQueryMechanism.executeCall(DatasourceCallQueryMechanism.java:242) ~[eclipselink-2.5.1.jar:2.5.1.v20130918-f2b9fc5]
    at org.eclipse.persistence.internal.queries.DatasourceCallQueryMechanism.executeCall(DatasourceCallQueryMechanism.java:228) ~[eclipselink-2.5.1.jar:2.5.1.v20130918-f2b9fc5]
    at org.eclipse.persistence.internal.queries.DatasourceCallQueryMechanism.insertObject(DatasourceCallQueryMechanism.java:377) ~[eclipselink-2.5.1.jar:2.5.1.v20130918-f2b9fc5]
    at org.eclipse.persistence.internal.queries.StatementQueryMechanism.insertObject(StatementQueryMechanism.java:165) ~[eclipselink-2.5.1.jar:2.5.1.v20130918-f2b9fc5]
    at org.eclipse.persistence.internal.queries.StatementQueryMechanism.insertObject(StatementQueryMechanism.java:180) ~[eclipselink-2.5.1.jar:2.5.1.v20130918-f2b9fc5]
    at org.eclipse.persistence.internal.queries.DatabaseQueryMechanism.insertObjectForWrite(DatabaseQueryMechanism.java:489) ~[eclipselink-2.5.1.jar:2.5.1.v20130918-f2b9fc5]
    at org.eclipse.persistence.queries.InsertObjectQuery.executeCommit(InsertObjectQuery.java:80) ~[eclipselink-2.5.1.jar:2.5.1.v20130918-f2b9fc5]
    at org.eclipse.persistence.queries.InsertObjectQuery.executeCommitWithChangeSet(InsertObjectQuery.java:90) ~[eclipselink-2.5.1.jar:2.5.1.v20130918-f2b9fc5]
    at org.eclipse.persistence.internal.queries.DatabaseQueryMechanism.executeWriteWithChangeSet(DatabaseQueryMechanism.java:301) ~[eclipselink-2.5.1.jar:2.5.1.v20130918-f2b9fc5]
    at org.eclipse.persistence.queries.WriteObjectQuery.executeDatabaseQuery(WriteObjectQuery.java:58) ~[eclipselink-2.5.1.jar:2.5.1.v20130918-f2b9fc5]
    at org.eclipse.persistence.queries.DatabaseQuery.execute(DatabaseQuery.java:899) ~[eclipselink-2.5.1.jar:2.5.1.v20130918-f2b9fc5]
    at org.eclipse.persistence.queries.DatabaseQuery.executeInUnitOfWork(DatabaseQuery.java:798) ~[eclipselink-2.5.1.jar:2.5.1.v20130918-f2b9fc5]
    at org.eclipse.persistence.queries.ObjectLevelModifyQuery.executeInUnitOfWorkObjectLevelModifyQuery(ObjectLevelModifyQuery.java:108) ~[eclipselink-2.5.1.jar:2.5.1.v20130918-f2b9fc5]
    at org.eclipse.persistence.queries.ObjectLevelModifyQuery.executeInUnitOfWork(ObjectLevelModifyQuery.java:85) ~[eclipselink-2.5.1.jar:2.5.1.v20130918-f2b9fc5]
    at org.eclipse.persistence.internal.sessions.UnitOfWorkImpl.internalExecuteQuery(UnitOfWorkImpl.java:2896) ~[eclipselink-2.5.1.jar:2.5.1.v20130918-f2b9fc5]
    at org.eclipse.persistence.internal.sessions.AbstractSession.executeQuery(AbstractSession.java:1793) ~[eclipselink-2.5.1.jar:2.5.1.v20130918-f2b9fc5]
    at org.eclipse.persistence.internal.sessions.AbstractSession.executeQuery(AbstractSession.java:1775) ~[eclipselink-2.5.1.jar:2.5.1.v20130918-f2b9fc5]
    at org.eclipse.persistence.internal.sessions.AbstractSession.executeQuery(AbstractSession.java:1726) ~[eclipselink-2.5.1.jar:2.5.1.v20130918-f2b9fc5]
    at org.eclipse.persistence.internal.sessions.CommitManager.commitNewObjectsForClassWithChangeSet(CommitManager.java:226) ~[eclipselink-2.5.1.jar:2.5.1.v20130918-f2b9fc5]
    at org.eclipse.persistence.internal.sessions.CommitManager.commitAllObjectsWithChangeSet(CommitManager.java:125) ~[eclipselink-2.5.1.jar:2.5.1.v20130918-f2b9fc5]
    at org.eclipse.persistence.internal.sessions.AbstractSession.writeAllObjectsWithChangeSet(AbstractSession.java:4196) ~[eclipselink-2.5.1.jar:2.5.1.v20130918-f2b9fc5]
    at org.eclipse.persistence.internal.sessions.UnitOfWorkImpl.commitToDatabase(UnitOfWorkImpl.java:1441) ~[eclipselink-2.5.1.jar:2.5.1.v20130918-f2b9fc5]
    at org.eclipse.persistence.internal.sessions.UnitOfWorkImpl.commitToDatabaseWithChangeSet(UnitOfWorkImpl.java:1531) ~[eclipselink-2.5.1.jar:2.5.1.v20130918-f2b9fc5]
    at org.eclipse.persistence.internal.sessions.RepeatableWriteUnitOfWork.commitRootUnitOfWork(RepeatableWriteUnitOfWork.java:277) ~[eclipselink-2.5.1.jar:2.5.1.v20130918-f2b9fc5]
    at org.eclipse.persistence.internal.sessions.UnitOfWorkImpl.commitAndResume(UnitOfWorkImpl.java:1169) ~[eclipselink-2.5.1.jar:2.5.1.v20130918-f2b9fc5]
    at org.eclipse.persistence.internal.jpa.transaction.EntityTransactionImpl.commit(EntityTransactionImpl.java:132) ~[eclipselink-2.5.1.jar:2.5.1.v20130918-f2b9fc5]
    at org.springframework.orm.jpa.JpaTransactionManager.doCommit(JpaTransactionManager.java:512) ~[spring-orm-3.1.2.RELEASE.jar:3.1.2.RELEASE]
    at org.springframework.transaction.support.AbstractPlatformTransactionManager.processCommit(AbstractPlatformTransactionManager.java:754) ~[spring-tx-3.1.2.RELEASE.jar:3.1.2.RELEASE]
    at org.springframework.transaction.support.AbstractPlatformTransactionManager.commit(AbstractPlatformTransactionManager.java:723) ~[spring-tx-3.1.2.RELEASE.jar:3.1.2.RELEASE]
    at org.springframework.transaction.interceptor.TransactionAspectSupport.commitTransactionAfterReturning(TransactionAspectSupport.java:394) ~[spring-tx-3.1.2.RELEASE.jar:3.1.2.RELEASE]
    at org.springframework.transaction.interceptor.TransactionInterceptor.invoke(TransactionInterceptor.java:120) ~[spring-tx-3.1.2.RELEASE.jar:3.1.2.RELEASE]
    at org.springframework.aop.framework.ReflectiveMethodInvocation.proceed(ReflectiveMethodInvocation.java:172) ~[spring-aop-3.0.7.RELEASE.jar:3.0.7.RELEASE]
    at org.springframework.aop.framework.JdkDynamicAopProxy.invoke(JdkDynamicAopProxy.java:202) ~[spring-aop-3.0.7.RELEASE.jar:3.0.7.RELEASE]
    at com.sun.proxy.$Proxy107.save(Unknown Source) ~[na:na]
    at cz.cuni.mff.xrg.odcs.frontend.gui.components.DPUDetail.saveDpuAsNew(DPUDetail.java:277) ~[DPUDetail.class:na]
    at cz.cuni.mff.xrg.odcs.frontend.gui.components.DPUDetail$4$1.onClose(DPUDetail.java:195) ~[DPUDetail$4$1.class:na]
    at org.vaadin.dialogs.DefaultConfirmDialogFactory$2.buttonClick(DefaultConfirmDialogFactory.java:145) ~[confirmdialog-2.0.4.jar:2.0.4]
    at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method) ~[na:1.7.0_40]
    at sun.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:57) ~[na:1.7.0_40]
    at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43) ~[na:1.7.0_40]
    at java.lang.reflect.Method.invoke(Method.java:606) ~[na:1.7.0_40]
    at com.vaadin.event.ListenerMethod.receiveEvent(ListenerMethod.java:508) ~[vaadin-server-7.1.8.jar:7.1.8]
    at com.vaadin.event.EventRouter.fireEvent(EventRouter.java:167) ~[vaadin-server-7.1.8.jar:7.1.8]
    at com.vaadin.server.AbstractClientConnector.fireEvent(AbstractClientConnector.java:969) ~[vaadin-server-7.1.8.jar:7.1.8]
    at com.vaadin.ui.Button.fireClick(Button.java:368) ~[vaadin-server-7.1.8.jar:7.1.8]
    at com.vaadin.ui.Button$1.click(Button.java:57) ~[vaadin-server-7.1.8.jar:7.1.8]
    at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method) ~[na:1.7.0_40]
    at sun.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:57) ~[na:1.7.0_40]
    at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43) ~[na:1.7.0_40]
    at java.lang.reflect.Method.invoke(Method.java:606) ~[na:1.7.0_40]
    at com.vaadin.server.ServerRpcManager.applyInvocation(ServerRpcManager.java:168) ~[vaadin-server-7.1.8.jar:7.1.8]
    at com.vaadin.server.ServerRpcManager.applyInvocation(ServerRpcManager.java:118) ~[vaadin-server-7.1.8.jar:7.1.8]
    at com.vaadin.server.communication.ServerRpcHandler.handleBurst(ServerRpcHandler.java:207) [vaadin-server-7.1.8.jar:7.1.8]
    at com.vaadin.server.communication.ServerRpcHandler.handleRpc(ServerRpcHandler.java:111) [vaadin-server-7.1.8.jar:7.1.8]
    at com.vaadin.server.communication.UidlRequestHandler.synchronizedHandleRequest(UidlRequestHandler.java:91) [vaadin-server-7.1.8.jar:7.1.8]
    at com.vaadin.server.SynchronizedRequestHandler.handleRequest(SynchronizedRequestHandler.java:37) [vaadin-server-7.1.8.jar:7.1.8]
    at com.vaadin.server.VaadinService.handleRequest(VaadinService.java:1371) [vaadin-server-7.1.8.jar:7.1.8]
    at com.vaadin.server.VaadinServlet.service(VaadinServlet.java:238) [vaadin-server-7.1.8.jar:7.1.8]
    at cz.cuni.mff.xrg.odcs.frontend.IntlibApplicationServlet.service(IntlibApplicationServlet.java:67) [IntlibApplicationServlet.class:na]
    at javax.servlet.http.HttpServlet.service(HttpServlet.java:728) [servlet-api.jar:na]
    at org.apache.catalina.core.ApplicationFilterChain.internalDoFilter(ApplicationFilterChain.java:305) [catalina.jar:7.0.33]
    at org.apache.catalina.core.ApplicationFilterChain.doFilter(ApplicationFilterChain.java:210) [catalina.jar:7.0.33]
    at org.apache.catalina.core.StandardWrapperValve.invoke(StandardWrapperValve.java:222) [catalina.jar:7.0.33]
    at org.apache.catalina.core.StandardContextValve.invoke(StandardContextValve.java:123) [catalina.jar:7.0.33]
    at org.apache.catalina.authenticator.AuthenticatorBase.invoke(AuthenticatorBase.java:472) [catalina.jar:7.0.33]
    at org.apache.catalina.core.StandardHostValve.invoke(StandardHostValve.java:171) [catalina.jar:7.0.33]
    at org.apache.catalina.valves.ErrorReportValve.invoke(ErrorReportValve.java:99) [catalina.jar:7.0.33]
    at org.apache.catalina.valves.AccessLogValve.invoke(AccessLogValve.java:931) [catalina.jar:7.0.33]
    at org.apache.catalina.core.StandardEngineValve.invoke(StandardEngineValve.java:118) [catalina.jar:7.0.33]
    at org.apache.catalina.connector.CoyoteAdapter.service(CoyoteAdapter.java:407) [catalina.jar:7.0.33]
    at org.apache.coyote.http11.AbstractHttp11Processor.process(AbstractHttp11Processor.java:1004) [tomcat-coyote.jar:7.0.33]
    at org.apache.coyote.AbstractProtocol$AbstractConnectionHandler.process(AbstractProtocol.java:589) [tomcat-coyote.jar:7.0.33]
    at org.apache.tomcat.util.net.JIoEndpoint$SocketProcessor.run(JIoEndpoint.java:312) [tomcat-coyote.jar:7.0.33]
    at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1145) [na:1.7.0_40]
    at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:615) [na:1.7.0_40]
    at java.lang.Thread.run(Thread.java:724) [na:1.7.0_40]

**Comment by tomas-knap** [comment]
When saving DPU configuration, it works well, but save as DPU template does not work

**Comment by skodapetr** [comment]
The bad news is .. that we can not probably fix it as .. the jdc https://github.com/openlink/virtuoso-opensource/blob/stable/6/libsrc/JDBCDriverType4/virtuoso/jdbc2/VirtuosoNullParameter.java?source=cc 
does not support standart java.sql.Types.NVARCHAR = -9 .. so we can read null from database but we can not save it .. imho: they are actually missing support for more null-values from JDBC 4.0 types

We have two-three options:
1) use byte[] and conversion .. 
2) never store null value .. is use some dummy "string"
3) ask openlink to add those constant into their driver .. (long term solution)

I will chose 2 as there are already some "guard" methods .. about values that binds to LONG VARCHAR ..

**Comment by skodapetr** [comment]
Nicméně ten problém je koukám větší .. neb ono to neumí NULL ani pro klasické NVARCHAR .. s pevnou délkou, na což třeba dost spoléháme u DPU .. tedy tam bude třeba použít zase klasické VARCHAR .. ať žije virtuoso jdbc ..

**Comment by tomas-knap** [comment]
Tedy ty sloupce, ktere maji omezenou delku a kde nebyl problem s narodnimi znaky jsi vratil na VARCHARY?

**Comment by skodapetr** [comment]
Ano. Dlouhé řětezce jsou LONG NVARCHAR a neměli by být nikdy null (jinak to skončí exception), to že nejsou null hlídá setter-getter v jednotlivých dao objektech. (místo null a "" , se používá "--null--" string ..

**Comment by tomas-knap** [comment]
Jinak k tomu "místo null a "" , se používá "--null--" string", neni to moc hezke a verim, ze s pouzitim mysql se toho zbavime. Mas to tam na jednoum miste, abychom mohli to tvoje doplnovatko pripadne disablovat kdyz budem pracovat s normalni db?

**Comment by skodapetr** [comment]
Ano, je na to pomocná třída a vní 2 metody, jenž toto zařizují, tedy odstranění je otázkou chvilky. 
Ono by stačilo, kdyby upravili ten jdbc driver .. ale to možná bude dříve to mysql pravda.

**Comment by tomas-knap** [comment]
Solved on odcs experimental branch
