### ISSUE TITLE
Problems when logging the pipeline run

### ISSUE THREAD

**Issue by tomas-knap** [mff-uk/odcs#994]
[12/31/13 11:45:00 AM] Tomas "nappy" Knap: Mno, db se tvari ze bezi
[12/31/13 11:45:13 AM] Tomas "nappy" Knap: ale v logu je kopec hlasek :
[12/31/13 11:45:14 AM] Tomas "nappy" Knap: sudo /etc/init.d/virtuoso-opensourceETL-TEST start
[12/31/13 11:45:30 AM] Tomas "nappy" Knap: teda: 11:43:32 Malformed data received from IP [127.0.0.1] : Box length too large. Disconnecting the client
[12/31/13 11:45:49 AM] Tomas "nappy" Knap: tedy zda se ze to nezapisovalo logy od backendu
[12/31/13 11:46:41 AM] Tomas "nappy" Knap: jo a v backendu jsou hlasky:
[12/31/13 11:46:43 AM] Tomas "nappy" Knap: 2013-12-31 11:46:20,914 [taskExecutor-1] ERROR exec: dpu: c.c.mff.xrg.odcs.backend.logback.SqlAppenderImpl - Can't save logs into database.
java.sql.BatchUpdateException: Problem during serialization : Broken pipe
    at virtuoso.jdbc4.VirtuosoPreparedStatement.throwBatchUpdateException(Unknown Source) ~[jdbc-driver-4.jar:na]
    at virtuoso.jdbc4.VirtuosoPreparedStatement.executeBatchUpdate(Unknown Source) ~[jdbc-driver-4.jar:na]
    at virtuoso.jdbc4.VirtuosoPreparedStatement.executeBatch(Unknown Source) ~[jdbc-driver-4.jar:na]
    at org.apache.commons.dbcp.DelegatingStatement.executeBatch(DelegatingStatement.java:297) ~[commons-dbcp-1.4.jar:1.4]
    at org.apache.commons.dbcp.DelegatingStatement.executeBatch(DelegatingStatement.java:297) ~[commons-dbcp-1.4.jar:1.4]
    at cz.cuni.mff.xrg.odcs.backend.logback.SqlAppenderImpl.flushIntoDatabase(SqlAppenderImpl.java:116) [backend-1.0.0.jar:na]
    at cz.cuni.mff.xrg.odcs.backend.logback.SqlAppenderImpl.flush(SqlAppenderImpl.java:174) [backend-1.0.0.jar:na]
    at sun.reflect.GeneratedMethodAccessor56.invoke(Unknown Source) ~[na:na]
    at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43) ~[na:1.7.0_40]
    at java.lang.reflect.Method.invoke(Method.java:606) ~[na:1.7.0_40]
    at org.springframework.aop.support.AopUtils.invokeJoinpointUsingReflection(AopUtils.java:319) [spring-aop-3.1.2.RELEASE.jar:3.1.2.RELEASE]
    at org.springframework.aop.framework.ReflectiveMethodInvocation.invokeJoinpoint(ReflectiveMethodInvocation.java:183) [spring-aop-3.1.2.RELEASE.jar:3.1.2.RELEASE]
    at org.springframework.aop.framework.ReflectiveMethodInvocation.proceed(ReflectiveMethodInvocation.java:150) [spring-aop-3.1.2.RELEASE.jar:3.1.2.RELEASE]
    at org.springframework.aop.interceptor.AsyncExecutionInterceptor$1.call(AsyncExecutionInterceptor.java:83) [spring-aop-3.1.2.RELEASE.jar:3.1.2.RELEASE]
    at java.util.concurrent.FutureTask.run(FutureTask.java:262) [na:1.7.0_40]
    at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1145) [na:1.7.0_40]
    at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:615) [na:1.7.0_40]
    at java.lang.Thread.run(Thread.java:724) [na:1.7.0_40]

**Comment by tomas-knap** [comment]
So it should be solved by that?

**Comment by skodapetr** [comment]
I hope yes .. the problem imho was .. that the database was offline .. backend store logs (as they have been generated by application) and then try to store more than the connection can handle. 
(cite: Malformed data received from IP [127.0.0.1] : Box length too large. Disconnecting the client )

Now backend store at most 50 logs in one query, if he has more of them .. then he split them and save one part after another .. in different queries (same connection).

What we can .. consider is .. that when backend failed to save logs, it keeps trying again and again .. no give up. The problem is that the exception is only one type .. so he does not recognized if there is problem with logs, or just the DB is down.
But we can try to use some "string-base approach" and in case of other then NoConnection problem .. just drop some logs .. similar issue is in backend's aspect that takes care about "reconnection".

. as future work for let's say .. one week? As apart from this issue we have here, so far we does not meet problems with logs (best to my knowledge) so they do not looks like the source of all evil and failures.

**Comment by tomas-knap** [comment]
Now it happens again, I created a pipeline with one SPARQL extractor, run in debug mode and when opening exec record detail, there were events but no logs. 

![screen shot 2013-12-31 at 2 46 58 pm](https://f.cloud.github.com/assets/3014917/1827083/39051966-7222-11e3-81b5-e37cb6bfd127.png)

![screen shot 2013-12-31 at 2 47 12 pm](https://f.cloud.github.com/assets/3014917/1827084/3bf05294-7222-11e3-950e-92c879eca0fd.png)

**Comment by tomas-knap** [comment]
solved in exp branch
