### ISSUE TITLE
When browsing execution record and switching to pipeline list - javax.persistence.NonUniqueResultException 

### ISSUE THREAD

**Issue by tomas-knap** [mff-uk/odcs#997]
When I was browse/query the execution record and then I tried to switch to pipeline view, I got: 

![screen shot 2013-12-31 at 2 04 09 pm](https://f.cloud.github.com/assets/3014917/1826991/12262d36-721c-11e3-964b-6dd33f9bf61a.png)

Petre, if you do not know, please reassing on @janvojt 

2013-12-31 14:03:01,537 [http-bio-8080-exec-37] ERROR cz.cuni.mff.xrg.odcs.frontend.AppEntry - Uncaught exception
javax.persistence.NonUniqueResultException: More than one result was returned from Query.getSingleResult()
    at org.eclipse.persistence.internal.jpa.QueryImpl.throwNonUniqueResultException(QueryImpl.java:976) ~[eclipselink-2.5.1.jar:2.5.1.v20130918-f2b9fc5]
    at org.eclipse.persistence.internal.jpa.QueryImpl.getSingleResult(QueryImpl.java:525) ~[eclipselink-2.5.1.jar:2.5.1.v20130918-f2b9fc5]
    at org.eclipse.persistence.internal.jpa.EJBQueryImpl.getSingleResult(EJBQueryImpl.java:400) ~[eclipselink-2.5.1.jar:2.5.1.v20130918-f2b9fc5]
    at cz.cuni.mff.xrg.odcs.commons.app.dao.db.DbAccessReadBase.execute(DbAccessReadBase.java:113) ~[commons-app-1.0.0.jar:na]
    at cz.cuni.mff.xrg.odcs.commons.app.pipeline.DbExecutionImpl.getLastExecution(DbExecutionImpl.java:69) ~[commons-app-1.0.0.jar:na]
    at sun.reflect.GeneratedMethodAccessor192.invoke(Unknown Source) ~[na:na]
    at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43) ~[na:1.7.0_40]
    at java.lang.reflect.Method.invoke(Method.java:606) ~[na:1.7.0_40]
    at org.springframework.aop.support.AopUtils.invokeJoinpointUsingReflection(AopUtils.java:309) ~[spring-aop-3.0.7.RELEASE.jar:3.0.7.RELEASE]
    at org.springframework.aop.framework.ReflectiveMethodInvocation.invokeJoinpoint(ReflectiveMethodInvocation.java:183) ~[spring-aop-3.0.7.RELEASE.jar:3.0.7.RELEASE]
    at org.springframework.aop.framework.ReflectiveMethodInvocation.proceed(ReflectiveMethodInvocation.java:150) ~[spring-aop-3.0.7.RELEASE.jar:3.0.7.RELEASE]
    at org.springframework.transaction.interceptor.TransactionInterceptor.invoke(TransactionInterceptor.java:110) ~[spring-tx-3.1.2.RELEASE.jar:3.1.2.RELEASE]
    at org.springframework.aop.framework.ReflectiveMethodInvocation.proceed(ReflectiveMethodInvocation.java:172) ~[spring-aop-3.0.7.RELEASE.jar:3.0.7.RELEASE]
    at org.springframework.aop.framework.JdkDynamicAopProxy.invoke(JdkDynamicAopProxy.java:202) ~[spring-aop-3.0.7.RELEASE.jar:3.0.7.RELEASE]
    at com.sun.proxy.$Proxy156.getLastExecution(Unknown Source) ~[na:na]
    at cz.cuni.mff.xrg.odcs.commons.app.facade.PipelineFacadeImpl.getLastExec(PipelineFacadeImpl.java:416) ~[commons-app-1.0.0.jar:na]
    at sun.reflect.GeneratedMethodAccessor210.invoke(Unknown Source) ~[na:na]
    at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43) ~[na:1.7.0_40]
    at java.lang.reflect.Method.invoke(Method.java:606) ~[na:1.7.0_40]
    at org.springframework.aop.support.AopUtils.invokeJoinpointUsingReflection(AopUtils.java:309) ~[spring-aop-3.0.7.RELEASE.jar:3.0.7.RELEASE]
    at org.springframework.aop.framework.ReflectiveMethodInvocation.invokeJoinpoint(ReflectiveMethodInvocation.java:183) ~[spring-aop-3.0.7.RELEASE.jar:3.0.7.RELEASE]
    at org.springframework.aop.framework.ReflectiveMethodInvocation.proceed(ReflectiveMethodInvocation.java:150) ~[spring-aop-3.0.7.RELEASE.jar:3.0.7.RELEASE]
    at org.springframework.transaction.interceptor.TransactionInterceptor.invoke(TransactionInterceptor.java:110) ~[spring-tx-3.1.2.RELEASE.jar:3.1.2.RELEASE]
    at org.springframework.aop.framework.ReflectiveMethodInvocation.proceed(ReflectiveMethodInvocation.java:172) ~[spring-aop-3.0.7.RELEASE.jar:3.0.7.RELEASE]
    at org.springframework.aop.framework.JdkDynamicAopProxy.invoke(JdkDynamicAopProxy.java:202) ~[spring-aop-3.0.7.RELEASE.jar:3.0.7.RELEASE]
    at com.sun.proxy.$Proxy161.getLastExec(Unknown Source) ~[na:na]
    at cz.cuni.mff.xrg.odcs.frontend.container.accessor.PipelineAccessor.getValue(PipelineAccessor.java:112) ~[PipelineAccessor.class:na]
    at cz.cuni.mff.xrg.odcs.frontend.container.accessor.PipelineAccessor.getValue(PipelineAccessor.java:22) ~[PipelineAccessor.class:na]
    at cz.cuni.mff.xrg.odcs.frontend.container.GeneralProperty.getValueForObject(GeneralProperty.java:41) ~[GeneralProperty.class:na]
    at cz.cuni.mff.xrg.odcs.frontend.container.ValueProperty.getValue(ValueProperty.java:30) ~[ValueProperty.class:na]
    at com.vaadin.ui.CustomTable.formatPropertyValue(CustomTable.java:4016) ~[filteringtable-0.9.0.v7.jar:7.1.8]
    at com.vaadin.ui.CustomTable.getPropertyValue(CustomTable.java:3960) ~[filteringtable-0.9.0.v7.jar:7.1.8]
    at com.vaadin.ui.CustomTable.parseItemIdToCells(CustomTable.java:2310) ~[filteringtable-0.9.0.v7.jar:7.1.8]
    at com.vaadin.ui.CustomTable.getVisibleCellsNoCache(CustomTable.java:2149) ~[filteringtable-0.9.0.v7.jar:7.1.8]
    at com.vaadin.ui.CustomTable.refreshRenderedCells(CustomTable.java:1670) ~[filteringtable-0.9.0.v7.jar:7.1.8]
    at com.vaadin.ui.CustomTable.enableContentRefreshing(CustomTable.java:3147) ~[filteringtable-0.9.0.v7.jar:7.1.8]
    at com.vaadin.ui.CustomTable.setContainerDataSource(CustomTable.java:2715) ~[filteringtable-0.9.0.v7.jar:7.1.8]
    at com.vaadin.ui.CustomTable.setContainerDataSource(CustomTable.java:2656) ~[filteringtable-0.9.0.v7.jar:7.1.8]
    at org.tepi.filtertable.FilterTable.setContainerDataSource(FilterTable.java:119) ~[filteringtable-0.9.0.v7.jar:0.9.0.v7]
    at org.tepi.filtertable.paged.PagedFilterTable.setContainerDataSource(PagedFilterTable.java:235) ~[filteringtable-0.9.0.v7.jar:0.9.0.v7]
    at cz.cuni.mff.xrg.odcs.frontend.gui.tables.IntlibPagedTable.setContainerDataSource(IntlibPagedTable.java:210) ~[IntlibPagedTable.class:na]
    at cz.cuni.mff.xrg.odcs.frontend.gui.views.pipelinelist.PipelineListViewImpl.setDisplay(PipelineListViewImpl.java:197) ~[PipelineListViewImpl.class:na]
    at cz.cuni.mff.xrg.odcs.frontend.gui.views.pipelinelist.PipelineListPresenterImpl.enter(PipelineListPresenterImpl.java:107) ~[PipelineListPresenterImpl.class:na]
    at cz.cuni.mff.xrg.odcs.frontend.navigation.PresenterWrap.enterPresenter(PresenterWrap.java:41) ~[PresenterWrap.class:na]
    at cz.cuni.mff.xrg.odcs.frontend.navigation.PresenterViewDisplay.showView(PresenterViewDisplay.java:41) ~[PresenterViewDisplay.class:na]
    at com.vaadin.navigator.Navigator.navigateTo(Navigator.java:568) ~[vaadin-server-7.1.8.jar:7.1.8]
    at com.vaadin.navigator.Navigator.navigateTo(Navigator.java:526) ~[vaadin-server-7.1.8.jar:7.1.8]
    at cz.cuni.mff.xrg.odcs.frontend.navigation.ClassNavigatorImpl.navigateTo(ClassNavigatorImpl.java:49) ~[ClassNavigatorImpl.class:na]
    at cz.cuni.mff.xrg.odcs.frontend.navigation.ClassNavigatorHolder.navigateTo(ClassNavigatorHolder.java:24) ~[ClassNavigatorHolder.class:na]
    at cz.cuni.mff.xrg.odcs.frontend.gui.MenuLayout$NavigateToCommand.menuSelected(MenuLayout.java:204) ~[MenuLayout$NavigateToCommand.class:na]
    at com.vaadin.ui.MenuBar.changeVariables(MenuBar.java:186) ~[vaadin-server-7.1.8.jar:7.1.8]
    at com.vaadin.server.communication.ServerRpcHandler.changeVariables(ServerRpcHandler.java:396) [vaadin-server-7.1.8.jar:7.1.8]
    at com.vaadin.server.communication.ServerRpcHandler.handleBurst(ServerRpcHandler.java:221) [vaadin-server-7.1.8.jar:7.1.8]
    at com.vaadin.server.communication.ServerRpcHandler.handleRpc(ServerRpcHandler.java:111) [vaadin-server-7.1.8.jar:7.1.8]
    at com.vaadin.server.communication.UidlRequestHandler.synchronizedHandleRequest(UidlRequestHandler.java:91) [vaadin-server-7.1.8.jar:7.1.8]
    at com.vaadin.server.SynchronizedRequestHandler.handleRequest(SynchronizedRequestHandler.java:37) [vaadin-server-7.1.8.jar:7.1.8]
    at com.vaadin.server.VaadinService.handleRequest(VaadinService.java:1371) [vaadin-server-7.1.8.jar:7.1.8]
    at com.vaadin.server.VaadinServlet.service(VaadinServlet.java:238) [vaadin-server-7.1.8.jar:7.1.8]
    at cz.cuni.mff.xrg.odcs.frontend.IntlibApplicationServlet.service(IntlibApplicationServlet.java:67) [IntlibApplicationServlet.class:na]
    at javax.servlet.http.HttpServlet.service(HttpServlet.java:728) [servlet-api.jar:na]
    at org.apache.catalina.core.ApplicationFilterChain.internalDoFilter(ApplicationFilterChain.java:305) [catalina.jar:7.0.33]
    at org.apache.catalina.core.ApplicationFilterChain.doFilter(ApplicationFilterChain.java:210) [catalina.jar:7.0.33]
    at org.apache.catalina.core.StandardWrapperValve.invoke(StandardWrapperValve.java:222) [catalina.jar:7.0.33]
    at org.apache.catalina.core.StandardContextValve.invoke(StandardContextValve.java:123) [catalina.jar:7.0.33]
    at org.apache.catalina.authenticator.AuthenticatorBase.invoke(AuthenticatorBase.java:472) [catalina.jar:7.0.33]
    at org.apache.catalina.core.StandardHostValve.invoke(StandardHostValve.java:171) [catalina.jar:7.0.33]
    at org.apache.catalina.valves.ErrorReportValve.invoke(ErrorReportValve.java:99) [catalina.jar:7.0.33]
    at org.apache.catalina.valves.AccessLogValve.invoke(AccessLogValve.java:931) [catalina.jar:7.0.33]
    at org.apache.catalina.core.StandardEngineValve.invoke(StandardEngineValve.java:118) [catalina.jar:7.0.33]
    at org.apache.catalina.connector.CoyoteAdapter.service(CoyoteAdapter.java:407) [catalina.jar:7.0.33]
    at org.apache.coyote.http11.AbstractHttp11Processor.process(AbstractHttp11Processor.java:1004) [tomcat-coyote.jar:7.0.33]
    at org.apache.coyote.AbstractProtocol$AbstractConnectionHandler.process(AbstractProtocol.java:589) [tomcat-coyote.jar:7.0.33]
    at org.apache.tomcat.util.net.JIoEndpoint$SocketProcessor.run(JIoEndpoint.java:312) [tomcat-coyote.jar:7.0.33]
    at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1145) [na:1.7.0_40]
    at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:615) [na:1.7.0_40]
    at java.lang.Thread.run(Thread.java:724) [na:1.7.0_40]
2013-12-31 14:03:03,171 [http-bio-8080-exec-37] DEBUG org.eclipse.p

**Comment by tomas-knap** [comment]
It happens even when reloading the app, so I cannot work with the app. Appears in experimental branch

**Comment by skodapetr** [comment]
Seems like problem with data in database .. I take a immediate look on this.

**Comment by tomas-knap** [comment]
solved in exp.branch
